### ISSUE TITLE
Query polling

### ISSUE THREAD

**Issue by gedw99** [zino-app/graphql-flutter#10]
Is this instead of subscriptions ?
Like a pull instead of push ?

**Comment by HofmannZ** [comment]
Query poling will live alongside subscriptions. The [Apollo docs](https://www.apollographql.com/docs/react/advanced/subscriptions.html#when-to-use) explained it really nicely.

**Comment by gedw99** [comment]
@HofmannZ thanks for link. Makes sense. They designed for KISS.

It will never scale. Polling in once a second over JSON will kill scaling once you have 10000 concurrent users. 10000 users hitting system every second. 

Another way to do it without killing scaling.
If you have a local Cache DB it can cache the data.
If that local Cache also has a DB that uses GRPC underneath to the server for push updates its can do very low latency updates, and put it into the local DB. The data is now there waiting for the Flutter client to poll in. 

here is a simple golang flutter plugin that would allow you to run a full cache and Db on flutter.

https://github.com/adieu/flutter_go
Its just JSONRPC which is perfect for grapql.
Its also bidirectional so both sides can push.

Behind the JSON RPC layer you can put anything easily.
A Full graphql server if you want. 
Under that a bucket based versions DB is easy. Say BadgerDB
Even DGraph can be compiled to mobile with a few changes.

**Comment by gedw99** [comment]
Here is how you do push based subscriptions. Just saying.. This will scale to millions of concurrent users easily. Its designed to be clustered. I use NATS alot.

https://github.com/cdmbase/graphql-nats-subscriptions

I have not run it yet but its easy to try.

**Comment by gedw99** [comment]
Actually this is even better

https://outcrawl.com/go-graphql-realtime-chat/
