### ISSUE TITLE
socketClient is always null

### ISSUE THREAD

**Issue by jpJuni0r** [zino-app/graphql-flutter#102]
**Description of the bug**
`socketClient` is initialized but never set to the actual connection ([reference](https://github.com/zino-app/graphql-flutter/blob/a34fea21830b56b4feb37a19c46b08d1873544c2/lib/src/socket_client.dart#L8)). 
This also results in an error when using the subscription-Widget, because [`socketClient.connect()`](https://github.com/zino-app/graphql-flutter/blob/a34fea21830b56b4feb37a19c46b08d1873544c2/lib/src/widgets/subscription.dart#L49) is called on null.

**Reproduction**
n/a

**Expected behavior**
There should be a way to set the [`SocketClient`](https://github.com/zino-app/graphql-flutter/blob/a34fea21830b56b4feb37a19c46b08d1873544c2/lib/src/socket_client.dart#L8) to the websocket connection reference.

**Additional info**
It would also be a good idea to update the readme file.

Assuming I didn't miss a thing are the proposals for an alternative implementation?

**Comment by HofmannZ** [comment]
Please provide some more info.

**Comment by micimize** [comment]
I believe this is resolved in other PRs, given it's age. Feel free to reopen if it's still an issue
