### ISSUE TITLE
QueryState.didChangeDependencies not being called when variables change

### ISSUE THREAD

**Issue by HelveticaScenario** [zino-app/graphql-flutter#103]
**Describe the bug**
When I pass in a new QueryOptions object with different variables to a Query widget it sends a query with the variables from the previous build, not the new variables. I have traced the bug to the didChangeDependencies of QueryState not being called when the variables in the QueryOptions change (I haven't tested to see if its the same for other properties of the Query widget or QueryOptions object)

**To Reproduce**
create a widget that builds a Query widget that takes a QueryOptions that take in a variable map that has a single entry which is a string to another string which is a prop. render that widget multiple times in a row with different values for the prop that is being used as a variable to the Query. set a breakpoint on the first line of didChangeDependencies in the QueryState widget. It will run on the first mount but not on subsequent changes.

**Expected behavior**
When I pass in new variables to a Query widget it should send a query with the new variables, not the ones from the previous build

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 
 - Version 10.13.6

**Smartphone (please complete the following information):**
 - Device: Pixel XL (original)
 - OS: Android 9
 - Version Security Patch september 5, 2018

**Comment by micimize** [comment]
this is with `^1.0.0-alpha`. Downgrading to `^0.9.4` works fine

**Comment by HofmannZ** [comment]
@HelveticaScenario Thanks for reporting the issue, I'll look into the issue and try to push a fix ASAP.

**Comment by HofmannZ** [comment]
@HelveticaScenario Hmm, apparently I got something wrong. When updating the `StatefulWidget` the  `didChangeDependencies` method on it's `State` class does not trigger.

I could just drop in another `InheritedWidget` but still looking for a more elegant solution.

**Comment by HofmannZ** [comment]
Fixed with 1.0.0-alpha.10
