### ISSUE TITLE
Allow async / Future in the GraphQLConsumer builder

### ISSUE THREAD

**Issue by sjmcdowall** [zino-app/graphql-flutter#104]
**Is your feature request related to a problem? Please describe.**

Yes -- I am using the GraphQLConsumer .. but the builder code won't let me use async so
when I try to await in the code... 

Here is a code snippet : 

       child: ScopedModelDescendant<MainModel>(
            builder: (BuildContext context, Widget child, MainModel model) {
          return GraphQLConsumer(builder: (GraphQLClient client) **async** {
            tasks = await _getTasks(model, client);
              return ColumnBuilder(
                itemCount: tasks.length,
                itemBuilder: (context, index) {
..

Throws an error : 

[dart] The argument type '(BuildContext, Widget, MainModel) → Future<GraphQLConsumer>' can't be assigned to the parameter type '(BuildContext, Widget, MainModel) → Widget'.

**Describe the solution you'd like**

Allow for a Future return so I can use async in my builder method?

I really have no idea...

**Comment by HofmannZ** [comment]
@sjmcdowall not sure if you can use async build functions in Flutter at all. Anyway, have a look at the [FutureBuilder class](https://docs.flutter.io/flutter/widgets/FutureBuilder-class.html) I think it might does what you want.

**Comment by sjmcdowall** [comment]
@HofmannZ -- Yep, that is exactly what I would up using and it worked pretty well too!  Thank you!
