### ISSUE TITLE
InMemoryCache() TTL?

### ISSUE THREAD

**Issue by sjmcdowall** [zino-app/graphql-flutter#106]
**Is your feature request related to a problem? Please describe.**
Our backend data can be mutated from many sources -- Our data gets stale "forever" until we do a hard refresh on the app .. before it will show new data..

**Describe the solution you'd like**
Ability to set a TTL on the cache items and mark them as dirty if expired to force a new query() to happen..

**Describe alternatives you've considered**
Not sure I have any ideas on this one.

**Comment by HofmannZ** [comment]
Have a look at the `fetchPolicy` option in the query option class.

**Comment by sjmcdowall** [comment]
Yes -- ok I see that and it's a nice improvement for sure.  However, I am not positive it alleviates the need or desire to have a TTL on cache entries to auto-expire cache elements .. but .. maybe that is more complex than is needed (well, ok -- its simple if its a global TTL) .. ANyway -- since fetchPolicy works for what I need .. I can pass but if you want/desire to have a TTL type cahce let me know.. I write about one of those a year :)
