### ISSUE TITLE
Optimistic results PR

### ISSUE THREAD

**Issue by jinxac** [zino-app/graphql-flutter#11]
@HofmannZ is anyone working on the optimistic results PR or can I take it up? 

Also, would like to know the requirements/guidelines before getting starting on it  :)

**Comment by HofmannZ** [comment]
@jinxac have not found any time for that yet, so you can take it up for sure. I will try to get some commits in myself as well, but you can lead the charge here.
 
As far as guidelines are concerned, we don't have any yet. I will go ahead and draft some this coming week. 

Here are some general pointers:
* Comments in the code are encouraged for technical complex pieces of code.
* We prefer longer but descriptive variable names over short but vague ones.
* Keep commits small and singular.
* Provide descriptive commit messages.

**Comment by jinxac** [comment]
I am working on this currently.  Would create a PR in few days.

**Comment by HofmannZ** [comment]
@jinxac Any updates?

**Comment by jinxac** [comment]
@HofmannZ sorry I have moved to another project so was not able to focus on this. I can take a look at this week for sure. Will that work?

**Comment by HofmannZ** [comment]
Closing the issue due to inactivity.
