### ISSUE TITLE
how to add fragments ???

### ISSUE THREAD

**Issue by kunaldodiya** [zino-app/graphql-flutter#113]
```
String userDetail = '''
  fragment userDetail on users {
    id
    name
  }
  '''
    .replaceAll('\n', ' ');

String register = '''
  mutation(
    \$uid: String!
    \$pin: String!
  ) {
    user: createUser(
      data: {
        uid: \$uid
        pin: \$pin
      }
    ) {
      ...userDetail
    }
  }
 '''
    .replaceAll('\n', ' ');
```

this does not work :) please let me know how can i add fragments ???

**Comment by HofmannZ** [comment]
Currently this package does not support fragments. Feel free to open a PR for it.

**Comment by comerc** [comment]
```dart
import 'package:gql/ast.dart';
import 'package:gql/language.dart';

DocumentNode gql(String query) => parseString(query);

class Queries {
  static final itemFields = gql(r'''
    fragment itemFields on item {
      id
      text
    }
  ''');

  static final getItems = gql('''
    query getItems {
      items {
        ...itemFields
      }
    }
  ''');
}
```

```dart
import 'package:graphql_flutter/graphql_flutter.dart';
// ...
    final documentNode = Queries.getItems;
    final fragment = Queries.itemFields;
    documentNode.definitions.addAll(fragment.definitions);
// ...
        Query(
          options: QueryOptions(
            documentNode: documentNode,
          ),
          builder:
// ...
```

**Comment by D4G4** [comment]
> ```dart
> import 'package:graphql_flutter/graphql_flutter.dart';
> 
> class Fragments {
>   static final itemFields = gql(r'''
>     fragment itemFields on item {
>       id
>       text
>     }
> 
>     fragment memberFields on member {
>       id
>       nickname
>     }
>   ''');
> }
> 
> class Queries {
>   static final getItems = gql('''
>     query getItems {
>       items {
>         ...itemFields
>         member {
>           ...memberFields
>         }
>       }
>     }
>   ''')..definitions.addAll(Fragments.itemFields.definitions);
> }
> 
> // ...
> 
>         Query(
>           options: QueryOptions(
>             documentNode: Queries.getItems,
>           ),
>           builder:
> 
> // ...
> ```

Ummm..
I'm getting this error in   `graphql: ^4.0.1`

`Unsupported operation: Cannot add to a fixed-length list`

**Comment by MbeleLebohang-uct** [comment]
@D4G4 I have been struggling with that for the past 2 weeks now. I was previously using the solution by @comerc and it worked nicely. After I upgraded the grapqhl, I started getting the same issue as you. I tried using Artemis library to autogenerate documents, but that seems to also be a pain.

**Comment by ekoto4** [comment]
Running into the same issue as @D4G4 . Any guidance? @micimize

**Comment by micimize** [comment]
Cause: https://github.com/gql-dart/gql/issues/185
A type generator would probably be a good way to do this https://github.com/gql-dart/gql/tree/master/gql#packagegqlastdart

```dart
class AddFragments extends ast.TransformingVisitor {
  @override
  ast.DocumentNode visitDocumentNode(ast.DocumentNode node) =>
    DocumentNode(definitions: [...node.definitions, ...fragmentDefinitons], span: node.span);
}
```

We should add this as an optional argument `gql`. I'm guessing this was done because `gql` aims to be completely immutable

**Comment by ekoto4** [comment]
Ahh thats the problem! To make sure - you plan on doing something like this?
```DocumentNode gql(String document, {List<TransformingVisitor> visitors}) => transform(
      parseString(document),
      [AddTypenameVisitor(), ...visitors],
    );
```

Then we can pass in the AddFragments transforming visitor?

**Comment by micimize** [comment]
@ekoto4 no the fragment visitor should prob take the fragments as an argument and the fragments params for `gql`. I think for custom `gql` implementations people should just use the original library and define a userland function

**Comment by ekoto4** [comment]
@micimize Ahh Im following you now. So Something like this

```class AddFragmentsVisitor extends TransformingVisitor {
  final List<DefinitionNode> fragmentDefinitions;

  AddFragmentsVisitor({
    @required this.fragmentDefinitions,
  });

  @override
  DocumentNode visitDocumentNode(
    DocumentNode node,
  ) =>
      DocumentNode(
        definitions: [
          ...node.definitions,
          ...fragmentDefinitions,
        ],
        span: node.span,
      );
}
```

coupled with

```
gql(''''[Your Document]''')..accept(AddFragmentsVisitor(fragmentDefinitions: [...fragmentDefinitions]))
````

**Comment by ekoto4** [comment]
@micimize Ahh I think Im following you now. It would be what you put coupled with the following?

```
  static final DocumentNode query = AddFragmentsVisitor(
    fragments: [...fragments],
  ).visitDocumentNode(
    gql(r'''[Your Document]'''),
  );
 ```

**Comment by micimize** [comment]
Or just a custom version of `gql`:
```dart
/// Parse a GraphQL [document] into a [DocumentNode],
/// automatically adding `__typename`s
///
/// If you want to provide your own document parser or builder,
/// keep in mind that default cache normalization depends heavily on `__typename`s,
/// So you should probably include an [AddTypenameVistor] [transform]
DocumentNode gql(String document, {List<FragmentDefinition> fragments}) => transform(
      parseString(document),
      [AddTypenameVisitor(), AddFragmentsVisitor(fragments)],
    );
```

I believe `gql` also has support for `#import` directives – I don't remember if that's just the ast builder though

**Comment by ekoto4** [comment]
> Or just a custom version of `gql`:
> 
> ```dart
> /// Parse a GraphQL [document] into a [DocumentNode],
> /// automatically adding `__typename`s
> ///
> /// If you want to provide your own document parser or builder,
> /// keep in mind that default cache normalization depends heavily on `__typename`s,
> /// So you should probably include an [AddTypenameVistor] [transform]
> DocumentNode gql(String document, {List<FragmentDefinition> fragments}) => transform(
>       parseString(document),
>       [AddTypenameVisitor(), AddFragmentsVisitor(fragments)],
>     );
> ```
> 
> I believe `gql` also has support for `#import` directives – I don't remember if that's just the ast builder though

Thank you for the help

**Comment by reilem** [comment]
This is probably not the best solution but here is what I'm doing now. I define this util function:
```dart
DocumentNode addFragments(DocumentNode doc, List<DocumentNode> fragments) {
  final newDefinitions = {for (final def in List<DefinitionNode>.from(doc.definitions)) def.name: def};
  for (final frag in fragments) {
    for (final def in frag.definitions) {
      // Check ensures no duplicate fragments
      if (!newDefinitions.containsKey(def.name)) {
        newDefinitions[def.name] = def;
      }
    }
  }
  return DocumentNode(definitions: newDefinitions.values.toList(), span: doc.span);
}
```
And then whenever I need fragments I do:
```dart
final fooDetail = gql('''
  fragment FooDetail on Foo {
    x y z
  }
''');

final getFoo = addFragments(gql(r'''
  query GetFoo {
    foo {   
      ...FooDetail
    }
  }
'''), [fooDetail]);
```

**Comment by D4G4** [comment]
> This is probably not the best solution but here is what I'm doing now. I define this util function:
> 
> ```dart
> DocumentNode addFragments(DocumentNode doc, List<DocumentNode> fragments) {
>   final newDefinitions = {for (final def in List<DefinitionNode>.from(doc.definitions)) def.name: def};
>   for (final frag in fragments) {
>     for (final def in frag.definitions) {
>       // Check ensures no duplicate fragments
>       if (!newDefinitions.containsKey(def.name)) {
>         newDefinitions[def.name] = def;
>       }
>     }
>   }
>   return DocumentNode(definitions: newDefinitions.values.toList(), span: doc.span);
> }
> ```
> 
> And then whenever I need fragments I do:
> 
> ```dart
> final fooDetail = gql('''
>   fragment FooDetail on Foo {
>     x y z
>   }
> ''');
> 
> final getFoo = addFragments(gql(r'''
>   query GetFoo {
>     foo {   
>       ...FooDetail
>     }
>   }
> '''), [fooDetail]);
> ```

Yeah, did the same thing
Did it a bit differently

`static String create(String queryStr, List<String> fragments) {
    String str = "";
    fragments.forEach((element) {
      str += element + "\n";
    });
    str += queryStr;
    return str;
  }`

```
static String initialFeedQuery() {
    return GService.create(GQueries.kAStringQuery, [
      GFragments.kSomeFragment,
      GFragments.kSomeAnotherFragment,
    ]);
  }
```

And then pass it as a raw string to graphql function.

**Comment by reilem** [comment]
> 
> Yeah, did the same thing, but a bit differently:
> 
> ...
> To prevent duplicates, you can always use Set instead of List

Using Sets is actually a good tip, I didn't realise that `Node` implements `==` . My code also does not work on latest version (5.0.0-nullsafety.2) because the `name` field has been removed from definitions. So for those looking for a solution similar to mine that is working on 5.0.0 and using Sets here it is:
```dart
DocumentNode addFragments(DocumentNode doc, List<DocumentNode> fragments) {
  final newDefinitions = Set<DefinitionNode>.from(doc.definitions);
  for (final frag in fragments) {
    newDefinitions.addAll(frag.definitions);
  }
  return DocumentNode(definitions: newDefinitions.toList(), span: doc.span);
}
```

**Comment by SalahAdDin** [comment]
> This is probably not the best solution but here is what I'm doing now. I define this util function:
> 
> ```dart
> DocumentNode addFragments(DocumentNode doc, List<DocumentNode> fragments) {
>   final newDefinitions = {for (final def in List<DefinitionNode>.from(doc.definitions)) def.name: def};
>   for (final frag in fragments) {
>     for (final def in frag.definitions) {
>       // Check ensures no duplicate fragments
>       if (!newDefinitions.containsKey(def.name)) {
>         newDefinitions[def.name] = def;
>       }
>     }
>   }
>   return DocumentNode(definitions: newDefinitions.values.toList(), span: doc.span);
> }
> ```
> 
> And then whenever I need fragments I do:
> 
> ```dart
> final fooDetail = gql('''
>   fragment FooDetail on Foo {
>     x y z
>   }
> ''');
> 
> final getFoo = addFragments(gql(r'''
>   query GetFoo {
>     foo {   
>       ...FooDetail
>     }
>   }
> '''), [fooDetail]);
> ```

so, it is not need to pass raw strings to the queries, right?

So we could do it as in `JavaScript`:
```dart
const String graphQLFragmentBody =
    r'''fragment AuthFields on UsersPermissionsLoginPayload {
    jwt
    user{
      username
      email
      confirmed
    }
}
''';

const String graphQLDocumentRegisterUser = '''
    $graphQLFragmentBody
    mutation RegisterUser(
        \$username: String!,
        \$email: String!,
        \$password: String!
    ){
  register(input: { username: \$username, email: \$email, password: \$password }) {
    ...UsersPermissionsLoginPayload
  }
}
''';
```

Could it be?

**Comment by reilem** [comment]
@SalahAdDin I think the risk you run with this is that you might have the same fragment in your query multiple times. If I recall correctly, duplicate fragments will result in an error. Most JS clients like apollo parse & filter out duplicate fragments automatically but this one doesn't do that.

For example:
```dart
final fragmentFoo = '''
  fragment FooDetail on Foo {
    a
    b
  }
''';

final fragmentBar = '''
  fragment BarDetail on Bar {
    c
    foo {
      ...FooDetail
    }
  }
  $fragmentFoo
''';

final query = '''
  query GetFoosAndBars {
    foosAndBars {
      foos {
        ...FooDetail
      }
      bars {
        ...BarDetail
      }
    }
  }
  $fragmentFoo
  $fragmentBar
''';
```
If you now try to use the `GetFoosAndBars` query, you might get some error like `There can be only one fragment named "FooDetail"` or something.

**Comment by wackyapps** [comment]
@SalahAdDin did you find a working solution to this..?
I am in need to apply fragments with a working way...

**Comment by SalahAdDin** [comment]
> @SalahAdDin did you find a working solution to this..? I am in need to apply fragments in a working way...

I used fragments but i am not sure if i got duplicated fragments.
