### ISSUE TITLE
graphql_flutter.dart not exporting useGraphQLClient hook?

### ISSUE THREAD

**Issue by robertoestivill** [zino-app/graphql-flutter#1146]
According to [Other hooks](https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql_flutter/README.md#other-hooks) section of the README.md, it seems that a consumer should be able to use the `useGraphQLClient` hook.

However, after trying it myself, I could not make it work. 

You can reproduce it by 

1. Add graphql_flutter package import to your `HookWidget`

`import 'package:graphql_flutter/graphql_flutter.dart';`

2. In your widget's build method, try retrieving a reference to the GraphQL client by using the mentioned hook 
 
```dart
@override
Widget build(BuildContext context) {
   final graphQLClient = useGraphQLClient();
   ...
}
```

3. Expected behavior is for this to actually worked as documented. Actual behavior is this not compiling. 

Digging a bit on the source code, It looks like the only missing bit to export it as part of the [graphql_flutter.dart](https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql_flutter/lib/graphql_flutter.dart) barrel file.

Is this an intended behavior and the documentation went out-of-date? or should we consider this a bug?   

Cheers

**Comment by budde377** [comment]
This is definitely a bug. We should be exporting this. A PR is very welcome!
