### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by donglua** [zino-app/graphql-flutter#115]
```
Because every version of flutter_test from sdk depends on http 0.12.0 and my_proj depends on http ^0.11.3+17, flutter_test from sdk is forbidden.
So, because my_proj depends on flutter_test any from sdk, version solving failed.

pub get failed (1)
Process finished with exit code 1
```

**Comment by donglua** [comment]
```
Because omni_github_client depends on graphql_flutter ^0.9.4 which depends on http ^0.11.3, http ^0.11.3 is required.
So, because omni_github_client depends on http ^0.12.0, version solving failed.

pub get failed (1)
```

I use Flutter 0.9.6 (channel dev) , it still failed. graphql_flutter depends on http ^0.11.3, and sdk depends on http 0.12.0

**Comment by d-silveira** [comment]
@HofmannZ is the solution to change to alpha channel?
I don't see any alpha channel when I run flutter channel
Im on dev channel also, and being plagued by this issue, stopping me from doing anything

**Comment by HofmannZ** [comment]
@d-silveira Tested with the latest version on the Flutter beta channel, should work just fine with `1.0.0-alpha.11`

**Comment by HofmannZ** [comment]
@d-silveira I'm not sure if we can support both channels at the same time. Upgrading our dependencies to versions that support the `dev` channel will break support for the `beta` channel. Since `beta` is the default channel and the recommended channel for production, we can't drop it's support. 😕

If you know a way to support both channels, feel free to open a PR 🚀

**Comment by cfjohan** [comment]
@HofmannZ I'm on the flutter beta channel and I get this when I upgrade:
```
Because every version of flutter_test from sdk depends on http 0.11.3+17 and graphql_flutter >=1.0.0-alpha.11 depends on http ^0.12.0, flutter_test from sdk is incompatible with graphql_flutter >=1.0.0-alpha.11.
So, because app depends on both graphql_flutter ^1.0.0-alpha.11 and flutter_test any from sdk, version solving failed.
```

**Comment by HofmannZ** [comment]
@cfjohan Try `flutter update-packages --force-upgrade`, it seems like your flutter packages are still referencing to an older version.

**Comment by cfjohan** [comment]
@HofmannZ that seems to have done the trick, thank you!
