### ISSUE TITLE
Can't find out `debug` parameter

### ISSUE THREAD

**Issue by yohom** [zino-app/graphql-flutter#116]
I found that the `debug` parameter was added to PR #54 to achieve log printing, but I couldn't find out where the parameter was set in the latest version 1.0.0-alpha10.

**Comment by HofmannZ** [comment]
@yohom This parameter has been removed, instead you can add your own link, allowing you to gain full control over debug logging.

**Comment by gabsbelini** [comment]
@HofmannZ Can you elaborate a bit more on how do I add my own link to help me logging my api calls? thanks!

**Comment by Nazacheres** [comment]
@HofmannZ Greetings, there is no documentation about how it can be used. Being able to read the logs is one of the most important features for the development. Please, could you add to documentation at least some small example?
