### ISSUE TITLE
please help how can i write logic for caching (refetching updated data)

### ISSUE THREAD

**Issue by kunaldodiya** [zino-app/graphql-flutter#118]
hello,

the scenario is on main page i show list of posts, and then it automatically cache but the problem is if i try to refetch data it does not show latest updated but only cached data :) i tried calling client.cache.reset() but then it remove all cached data. show app start loading each and every pages again.. 

in apollo there is a function called refetchQuery so only particular query can be updated and other query has no impact of cache..

how can do something like this. ???

**Comment by knewter** [comment]
I'm passing an extra fake variable into a query to force this. I call it `_counter` and I increment it each time I want to refetch. Seems to work fine, and as hacks go it doesn't feel bad at all. The more idiomatic way to do it is probably to pass a `QueryController` into the query and call `controller.refresh` or something to make it query again.

**Comment by kunaldodiya** [comment]
Thanks buddy, would help a lot

**Comment by venkatd** [comment]
I wasn't able to find any reference to `QueryController` but passing a dummy variable worked for me.
