### ISSUE TITLE
Decouple operation apis from flutter widgets

### ISSUE THREAD

**Issue by dopecoder** [zino-app/graphql-flutter#125]
**Describe the bug**
When using scoped_model in flutter, i'm unable to return subscriptions as streams as the subscriptions are implemented as widgets.

**Expected behavior**
Being able to subscribe without the use of flutter widgets.

Is there a way to just use pure dart for performing operations such as querying, subscribing and mutating as its not possible to subscribe date in scoped_model using widgets.

**Comment by arnold-parge** [comment]
Check the code in my issue: [https://github.com/zino-app/graphql-flutter/issues/126](https://github.com/zino-app/graphql-flutter/issues/126)

I am subscribing without Subscription widget.

**Comment by micimize** [comment]
@truongsinh [is working on this](https://github.com/zino-app/graphql-flutter/issues/196#issuecomment-476709199), and it is critical for #72.
Also from @feinstein:
> if I want to make a Query on my BLoC or Reducer or ViewModel or any form of code that's not presentation, I can't
>
> If this library can be used in a Model class, please also provide its use on the Readme. This is very helpful for unit testing and DI, where we can just simulate a query on a model class and serve it to a Presentation Widget.
 
For now I encourage anyone with urgent need to look into the widget implementations - you might be able to fit the client interaction points to whatever alternative pattern you're using. For instance, for basic `Query` and `Mutation` integration, the main things you'll have to port would be:
* `QueryOptions`, `MutationOptions`, and `WatchQueryOptions` 
* `observableQuery` management (`observableQuery = client.watchQuery(_options);`)
* collecting the `observableQuery.stream` for usage as in the `StreamBuilder`

**Comment by truongsinh** [comment]
Separation MR at #203

**Comment by micimize** [comment]
@truongsinh contributed a [bloc implementation example](https://github.com/zino-app/graphql-flutter/blob/next/example/lib/graphql_bloc/bloc.dart). This is similar enough to #72 that I'm going to close it in favor of there, as #203 will solve both at once
