### ISSUE TITLE
Optimistic mutation results

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#127]
This depends on #114 - a naive implementation shouldn't be too difficult.
Steps for optimistic results would be:
* Add an [list of optimistic result patches](https://github.com/apollographql/apollo-client/blob/c3561e73957799bbf0d7f87c4a3ebcfee6f40e3a/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L80-L103) to the cache
* associate them with mutations and [invalidate them appropriately](https://github.com/apollographql/apollo-client/blob/c3561e73957799bbf0d7f87c4a3ebcfee6f40e3a/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L150)  

Offline queue moved to #201:  

@HofmannZ if #114 makes sense to you I'd like to start working on it in preparation to implement this

**Comment by HofmannZ** [comment]
@micimize Yeah sounds good to me, need any help?

**Comment by micimize** [comment]
@HofmannZ possibly! I think I've just about completed the [optimism](https://github.com/micimize/graphql-flutter/tree/optimism) chunk of this, continuing from #130 (although they're less entangled than I expected).

Here's a brain dump on the **query rebroadcast logic**, for posterity:
The solution I implemented is to just [rebroadcast all safe queries](https://github.com/micimize/graphql-flutter/blob/optimism/lib/src/core/query_manager.dart#L177-L191) from the cache on every optimistic update, [preserving previous `QueryResult` state](https://github.com/micimize/graphql-flutter/blob/optimism/lib/src/core/observable_query.dart#L89-L99) where it makes sense.

**Apollo's solution**, which may be more robust:
* call a protected [`broadcastWatches`](https://github.com/apollographql/apollo-client/blob/48a224d504487ea480bce95685402d40c4a90eea/packages/apollo-cache-inmemory/src/inMemoryCache.ts#L323-L349) method on the cache when optimistic updates are made
* this calls a [`callback`](https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/QueryManager.ts#L755-L757) supplied in the query manager with the change diff,
marking the query `invalidated`
* [`invalidated` queries](https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/QueryManager.ts#L180) are then broadcast when [broadcastQueries is called](https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/QueryManager.ts#L180) immediately after optimistic results are recorded.
* they are then [marked valid](https://github.com/apollographql/apollo-client/blob/905001e40cfadf841aa5a78aa428ab09f8cdf108/packages/apollo-client/src/core/QueryManager.ts#L727) again in listeners (which there is always one of)

**Comment by eusdima** [comment]
Fixed by #130

**Comment by micimize** [comment]
this was not actually resolved - #114 was resolved, which was a dependency.

Here's [a diff of the most recent work I've done on this](https://github.com/zino-app/graphql-flutter/compare/next...micimize:lazy_dereference?expand=1)

**Comment by micimize** [comment]
closed by #199
