### ISSUE TITLE
Error reading: I am getting the following error on deployment:

### ISSUE THREAD

**Issue by theabhayprajapati** [zino-app/graphql-flutter#1272]
This issue is occurring during the continuous integration and deployment (CI/CD) process, and the file is present in my local setup.

**Steps to reproduce**

1. Add the `graphql_flutter` package to the dependencies in the `pubspec.yaml` file.
2. Import the package in the main Dart file: `import 'package:graphql_flutter/graphql_flutter.dart';`
3. Attempt to deploy the application with GitHub actions.

**Expected behavior**

The application should build and deploy successfully.

**Actual behaviour**

The application fails to build and deploy due to the error described above.

**Environment**

- Flutter version: [
- Operating system: windows.
- graphql_flutter: ^5.0.0

**Additional context**

 It works fine on the local setups also local build works fine however when i deploy the application with github actions it gives me this error.
`
lib/main.dart:6:8:
Error: Error when reading '../.pub-cache/hosted/pub.dev/graphql_flutter-5.1.0/lib/graphql_flutter.dart%20': Error reading '../.pub-cache/hosted/pub.dev/graphql_flutter-5.1.0/lib/graphql_flutter.dart%20'  (No such file or directory)
import 'package:graphql_flutter/graphql_flutter.dart ';
       ^
lib/main.dart:11:9:
Error: Method is not found: 'initHiveForFlutter'.
  await initHiveForFlutter();
`

**Comment by vincenzopalazzo** [comment]
There is a couple of tests that you can do before you upgrate to the last beta version and then rerun the CI, if the error persist reproduce the issue and report it, without the an example I can not help you

**Comment by vincenzopalazzo** [comment]
closing this due the lack of response, feel free to reopen if you had a reproducible example
