### ISSUE TITLE
Can you keep to "beta" flutter version?

### ISSUE THREAD

**Issue by sjmcdowall** [zino-app/graphql-flutter#132]
Unless there is a giant need to use "dev" level Flutter channel, can this stick to beta channel packages, etc?

I just tried using alpha.11 and that demanded http 0.12 .. which in turned failed because the beta test package demands http 0.11.XXXXXX 

Now, if there is a critical bug / reason to use "dev" .. maybe document that so "we" have ammunition as to why we need to use the "dev" channel and not "beta" for our managers, other co-workers? 

Keep up the awesome work!!

Cheers!

**Comment by HofmannZ** [comment]
Fair point, our development in the package has been a bit jumpy, will be picking it up in the coming week.
