### ISSUE TITLE
How to create infinite listview - graphql pagination

### ISSUE THREAD

**Issue by patelmanjeet** [zino-app/graphql-flutter#135]
How we can implement infinite listview something like FutureBuilder/StreamBuilder with ListView, so when user scroll down to list it will call graphql pagination query to load more data.

**Comment by jxltom** [comment]
My way is using listview with scrollcontroller. When the listview is scrolled to the bottom, the notification of the controller would call a async function which will loading more data with graphql client and save to a variable. The listview will build from this variable.

**Comment by eusdima** [comment]
@jxltom Would be awesome if you could provide an example of that so we can extend the documentation.

**Comment by jxltom** [comment]
I will try to make a PR for that, updating a example under ```example``` directory.

**Comment by juanpablocs** [comment]
what is status for this issue?

**Comment by eusdima** [comment]
I will close this issue since there was no example provided and the original question got an answer.
