### ISSUE TITLE
Rename field `document` in POST requests to `query` according to the graphql specification

### ISSUE THREAD

**Issue by ArneSchulze** [zino-app/graphql-flutter#138]
It would be nice to align the POST request body to the official [graphql specification](https://graphql.org/learn/serving-over-http/#post-request). Meaning:

Instead of sending  
```json
{
    "document": "$query",
    "variables": "$variables",
    "operationName": "$operation"
}
```  
send  
```json
{
    "query": "$query",
    "variables": "$variables",
    "operationName": "$operation"
}
```

**Comment by HofmannZ** [comment]
We send `query` instead of `document` see [HttpLink](https://github.com/zino-app/graphql-flutter/blob/8b01b4467bea7a4b527d0b61562e9dc49a82f93e/lib/src/link/http/link_http.dart#L170-L188)
