### ISSUE TITLE
server-sent events (SSE) support in GraphQLSubscriptions

### ISSUE THREAD

**Issue by ArneSchulze** [zino-app/graphql-flutter#139]
Is there any existing solution or a plan to support server-sent events in graphql subscriptions yet? If not, I think it would be worth considering

**Comment by eusdima** [comment]
We currently don't have any plans to support that. But feel free to open a PR.

**Comment by micimize** [comment]
Related info:
* https://github.com/apollographql/graphql-subscriptions/issues/204
* https://developers.facebook.com/docs/graph-api/server-sent-events/

With `v4` we use [`gql_link`](https://pub.dev/packages/gql_link) so if someone wants this I'd say just make a 3rd party library or maybe PR a new link to https://github.com/gql-dart/gql
