### ISSUE TITLE
Ignore IntelliJ config files and lock files

### ISSUE THREAD

**Issue by camuthig** [zino-app/graphql-flutter#14]
Are there any thoughts on ignoring the .idea directory (and some of the config files, like `.flutter-plugins` and `graphql.iml`) as well as both the main pubspec.lock and the example's pubspec.lock? The [Dart guides](https://www.dartlang.org/guides/libraries/private-files#pubspeclock) suggest not including the pubspec.lock on libraries, and the .idea and IntelliJ config files create large diffs when working on small pieces of the project.

**Comment by HofmannZ** [comment]
@camuthig yeah should be ignored, will add it to the `.gitignore`
