### ISSUE TITLE
Exception swallow

### ISSUE THREAD

**Issue by guitcastro** [zino-app/graphql-flutter#140]
**Describe the bug**
My client is failing with NoConnectionException, I expect to see an error but instead it silence fail, debugging the code I notice that the conditional `if (data == {})` fails for the `_internalLinkedHashMap` with size 0.
 
**To Reproduce**
1. Try to query with a bad connection
2. See error

**Expected behavior**
Emit the exception

**Screenshots**
![error image](https://i.imgur.com/x8tIGey.png)

**Comment by HofmannZ** [comment]
Fixed with #162
