### ISSUE TITLE
Expose bodyBytes from http.response in client.dart

### ISSUE THREAD

**Issue by ifndefdeadmau5** [zino-app/graphql-flutter#141]
**Is your feature request related to a problem? Please describe.**

> It seems response from server sometimes(in my case, request to `apollo-server`) isn't decoded properly by http package. So I want to manually decode raw `bodyBytes` by myself with my own decoding method. Currently client.query only expose that already decoded result as far as I know.

**Describe the solution you'd like**

> Expose `bodyBytes` to user.

**Describe alternatives you've considered**

> Couldn't come up with any, yet.

**Additional context**

> Below is just motivation of this feature request, which is unexpected decoding when requesting with `'content-type': 'application/json, charset=utf-8;'` from client, `'Content-Type': 'application/json'` from server.

![image](https://user-images.githubusercontent.com/8914311/49848991-fe120a00-fe1a-11e8-9106-2476abd016c0.png)

and guess this is a related issue https://github.com/dart-lang/http/issues/175

**Comment by dennisschneider** [comment]
I have exactly the same issue (in my case request to apollo-server-micro), being able to access `bodyBytes` would be nice.

**Comment by ifndefdeadmau5** [comment]
@dennisschneider Glad to found another victim here. Are you still having that issue? 
I resolved that by setting response header as `'Content-Type': 'application/json; charset=utf-8'` so that `dart/http` can choose the right encoding

**Comment by dennisschneider** [comment]
@ifndefdeadmau5 how did you set the server response header for apollo-server & which implementation are you using ? Tried it with apollo-server-micro & apollo-server-express but apollo seems to override it ... I tried this: 
`app.use((req, res, next) => {
  res.append("Content-Type", "application/json; charset=utf-8");
  next();
});`

**Comment by dennisschneider** [comment]
@ifndefdeadmau5 finally found a workaround ... I use http-proxy to override the header ... only drawback is that it breaks graphql-playground (but you still can connect with a standalone graphql-playground so not a real issue)

`
const httpProxy = require("http-proxy");
const proxy = httpProxy
  .createProxyServer({ target: "http://localhost:3000", changeOrigin: true })
  .listen(8000);
proxy.on("proxyRes", function(proxyRes, req, res, options) {
  proxyRes.headers["Content-Type"] = "application/json; charset=UTF-8";
});
`

**Comment by ifndefdeadmau5** [comment]
Thank you @dennisschneider, it works like a charm 👍 
Hope `apollo-server` provide built-in way to do it soon, tho  :)

**Comment by micimize** [comment]
This seems outdated - I think today this could be resolved with a custom http link, which I think is fine given the niche nature of it
