### ISSUE TITLE
Implement ErrorPolicy

### ISSUE THREAD

**Issue by shrugs** [zino-app/graphql-flutter#143]
**Is your feature request related to a problem? Please describe.**
ErrorPolicy allows your code to tell the client how it should surface graphql errors.

https://www.apollographql.com/docs/react/features/error-handling.html

Currently, ErrorPolicy is mocked but not implemented in #next; it'd be awesome if a 1.0 supported ErrorPolicies. the behavior at the moment is closes to `ErrorPolicy.all`, but is implicit.

Also of note, it seems like in apollo network errors are handled differently (always thrown?) than graphql errors; the `ErrorPolicy` property only affects graphql errors and how they're surfaced to consumers.

**Comment by HofmannZ** [comment]
This a good addition to the library, feel free to open a PR.

**Comment by mainawycliffe** [comment]
Closed by https://github.com/zino-app/graphql-flutter/pull/248
