### ISSUE TITLE
Non widget queries

### ISSUE THREAD

**Issue by liepaja** [zino-app/graphql-flutter#145]
At the moment the only way to query/mutate is to do that from widgets, yet if models are used, its better to do that not from widgets. Is there a way to do so?

**Comment by liepaja** [comment]
Found the solution:
```
var graphQLClient = GraphQLClient(
      cache: InMemoryCache(),
      link: link,
 );

 var result =
        await client.query(QueryOptions(
                document: query.me,
              ));
```

**Comment by mkhennoussi** [comment]
@liepaja Thanks for the solution, but it seems to work only for simple queries. When I try for a mutation with variables, I have the following error : [Network Error: 400 Bad Request: Undefind location]

Do you have the same issue or is it working fine for you (with mutations) ?

Thanks !

**Comment by liepaja** [comment]
@mkhennoussi can you try with some existing graphql backend? To validate that error is not from server?

**Comment by mkhennoussi** [comment]
I'm using Hasura.io as a backend. I just discovered that when I remove the "variables" field in the MutationOptions, it is working fine. So I can run static mutation but when I add variables, it fails. I'm not really sure (I'm not a GraphQL expert) if it comes from the flutter package or from the backend (which doesn't understand how the package send variables). 

Any ideas ? Thanks !

**Comment by liepaja** [comment]
@mkhennoussi  can you post your mutation string as well as the client.mutate line

**Comment by mkhennoussi** [comment]
Sorry it was my fault. I don't really understand, maybe an indentation issue or a typo, I tried to code all my queries in Insomnia.rest then just copy/paste the query in my dart code, and it worked. 

Sorry again, for me it's fixed, thanks again for your solution !
