### ISSUE TITLE
[Feature Request] Accept future as context

### ISSUE THREAD

**Issue by degroote22** [zino-app/graphql-flutter#148]
I'm using Firebase Auth to get the credentials for my server.
Their SDK provides me with an async function which will give me the token.

I'd like if I could pass a future as the context (so that I can provide the Authorization header)
When the future is loading graphql-flutter would say to the query/mutation that the state is loading and if this future errors graphql-flutter would pass this as an error to the component.

Right now there is a lot of boilerplate code necessary to run this setup:
```dart
body: FutureBuilder<Map<String, Map<String, String>>>(
        future: getGqlContextFromBuildContext(context),
        builder: (
          BuildContext context,
          AsyncSnapshot<Map<String, Map<String, String>>> snapshot,
        ) {
          switch (snapshot.connectionState) {
            case ConnectionState.none:
            case ConnectionState.active:
            case ConnectionState.waiting:
              return LoadingIndicator();
            case ConnectionState.done:
              if (snapshot.hasError) {
                return Text('Error: ${snapshot.error}');
              }

              return Query(
                options: QueryOptions(
                  document: meDetailsQuery,
                  context: snapshot.data,
                ),
                builder: (r) => _builder(r, context),
              );
          }
          return null; // unreachable
        },
```

I'd love if the API let me write like this:
```dart
body: Query(
        options: QueryOptions(
            document: meDetailsQuery,
            context: getGqlContextFromBuildContext(context),
        ),
        builder: (r) => _builder(r, context),
    );
```

And also sometimes while this is resolving I'd like to have the cached query show up.

I'd like to hear your opinion on this before submitting a PR.

Thanks 👍

**Comment by HofmannZ** [comment]
The new AuthLink would some this
