### ISSUE TITLE
HTTP Errors not reported because of invalid comparision

### ISSUE THREAD

**Issue by lenaschimmel** [zino-app/graphql-flutter#149]
**Describe the bug**
When the GraphQL Server responds with an HTTP error code, in some cases, the state is not updated with the error object.

**To Reproduce**
1. Make a request to a server that reqires JWT auth, but provide no auth, like `https://fakerql.com/graphql/`
2. Create a `Query` widget
3. Write a `builder`function which would show if the query is loading and/or received an error

**Expected behavior**
The widget should show the `loading` state, and after a short while, should be updated with the `error`state, possibly showing `Network Error: 401 Unauthorized` as the cause.

**Actual behavior**
The widget remains in the `loading` state forever. No error is shown on the UI or in the log.

**Possible reason and fix**
In the following line, data is checked for emptyness using an indentity check:
https://github.com/zino-app/graphql-flutter/blob/ad4c2417677e5879e7846f8c26bb96f49152eee5/lib/src/widgets/query.dart#L108
I checked that `data` actually is an empty map, but the check returns false, thus the following `setState` will never be called. Changing the check to `if (data.isEmpty) {` fixed it for me.

**System**
This bug was encountered on the following system:
* Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale de-DE)
* iOS toolchain - develop for iOS devices (Xcode 10.1)
* iOS 12.1.1 on physical device iPhone 8
* graphql_flutter 0.9.5
* debug mode

**Comment by Jetsly** [comment]
as same too

**Comment by HofmannZ** [comment]
Fixes by #162
