### ISSUE TITLE
Don't hide loading state

### ISSUE THREAD

**Issue by lucasavila00** [zino-app/graphql-flutter#153]
If a query is loading but was found from cache the current implementation tells us that the loading is false.

I'd like if this app would report errors, loading and data independently because there may be a case where a query has data from cache and is loading and I'd like to display a loading indicator alongside the data to show that it is loading and if this query errors I'd like to show the error but not stop showing the cached data.

What's your take on this API change? I'm using a fork that does this and if you agree on this change of the API I could submit a PR with it.

**Comment by degroote22** [comment]
I'll try to show in code what I mean. [Currently if the data is cached then it won't pass the loading state.](https://github.com/zino-app/graphql-flutter/blob/6a4c18d9141b4112f2f369cb613818e526447e66/lib/src/core/query_manager.dart#L95)

But we could say that it is loading AND give the result, so we may show the old data and show an icon that tells the user new data is being fetched.
[Like here.](https://github.com/degroote22/graphql-flutter/blob/e0117d6cfb9f8aa20c31fb018d58187c4194a0b1/lib/src/core/query_manager.dart#L136)

**Comment by HofmannZ** [comment]
@degroote22 Nice idea!

**Comment by micimize** [comment]
#199 adds an `optimistic` field to results, which I think we could extend to queries here to indicate an optimistic cache response

**Comment by micimize** [comment]
We should really just add a `responseType` enum or something, as there are so many aspects to this basic problem.

A result can be some vector of loading, eagerly returned from cache,  optimistic only, optimistic with partially normalized results from cache, eager with the previous call to the query, etc, etc.

Will take more consideration

**Comment by mbellezi** [comment]
Maybe change QueryResult introducing fields like networkLoading and fromCache. This way is possible to know if a result is coming from the cache while waiting for a Network updated response.

**Comment by micimize** [comment]
Closed with a `source` attribute on `QueryResult`:
```data
/// The source of the result data contained
///
/// Loading: No data has been specified from any source
/// Cache: A result has been eagerly resolved from the cache
/// OptimisticResults: An optimistic result has been specified
///   (may include eager results from the cache)
/// Network: The query has been resolved on the network
///
/// Both Optimistic and Cache sources are considered "Eager" results
enum QueryResultSource {
  Loading,
  Cache,
  OptimisticResult,
  Network,
}
```
