### ISSUE TITLE
[Feature] Add new methods of authentification

### ISSUE THREAD

**Issue by IhorPatychenko** [zino-app/graphql-flutter#154]
In a current version of plugin we can access to endpoint using an **apiToken**.
It would be great to can use other authentication methods like **Basic Authentication**, **OAuth2**, etc.

**Comment by degroote22** [comment]
How would this be done?
Could you provide a clearer example of what do you mean?
Could you show another lib which does it (for instance, react-apollo or relay, if that's the case)

Thanks

**Comment by IhorPatychenko** [comment]
The context of this feature is in to allow to user to authenticate due **Basic Authentication**.
For example:
I'm creating an Github client using Github API. My app allows to authenticate providing login and password. App saves this credentials to use them after in all http requests to get information from Github API. The purpose is to avoid the need to create api tokens and use existent methods of authentication.

Posible solution:
* Add new optional parameter that allows to create a client with basic authentication.
Example:
`Client(
      endPoint: 'https://api.github.com/graphql',
      cache: InMemoryCache(),
      basicAuth: {'login': '<YOUR_LOGIN>', 'password': '<YOUR_PASSWORD>'}
    ),`
* In case if _apiToken_ parameter isn't set then check if parameter that could contain login and password is valid.
* Depending on which parameter is set do an http request with one auth type or another.

Sorry for my english. :)

**Comment by HofmannZ** [comment]
Hi @IhorPatychenko Take a look at our new AuthLink, you can use it as an example to setup your own basic auth link.
