### ISSUE TITLE
[Bug] Avoid overriding a query with a subset of it

### ISSUE THREAD

**Issue by degroote22** [zino-app/graphql-flutter#155]
When using the normalized cache the updates are made through [this piece of code](https://github.com/zino-app/graphql-flutter/blob/next/lib/src/cache/in_memory.dart#L26) which replaces bigger types with smaller types.

For istance, if I have a list of posts where I get their titles
```graphql
searchPosts(search: String!){
  post {
    title
  }
}
```
this would replace a bigger type, let's say a detail page which has this query
```graphql
postById(id: ID!) {
  post {
    title
    subtitle
  }
}
```

and the subtitle field would be deleted.

The correct way would be to [addAll](https://docs.flutter.io/flutter/dart-core/Map/addAll.html) the new object to the old object (if the old one exists).

**Comment by eusdima** [comment]
Closed because of #156
