### ISSUE TITLE
Is this library still under active development?

### ISSUE THREAD

**Issue by dbanck** [zino-app/graphql-flutter#157]
Hi 👋 

I really like GraphQL and want to keep using it for many coming Flutter projects. I’ve seen the great work you did on the `next` branch and I’m wondering why the development suddenly stopped?

What are the next steps to get to `1.0`? Can I help you reaching it? I'm eager to contribute 🙂

**Comment by sjmcdowall** [comment]
Great question @dbanck -- We are using this quite a bit and it's "ok" -- but man -- this seems to have been slightly abandoned by the original authors ... I wish they would open it up to a few other of the people submitting PR's to keep the traction going . :(

**Comment by juicycleff** [comment]
I am wondering too. I've been thinking if I should move my project to React Native or just fork this repo and start playing around to see what I can start fixing

**Comment by olup** [comment]
@juicycleff You would help a lot of people by forking and offering your work to the community, if you have a bit of time to spare (If you don't have it and your project needs to move along, react native is a safer bet). 

This is actually an essential piece into any app/front-end language or framework. It is unbelievable that this repository is the only option developers have when speaking of graphql on Flutter, when javascript has already many of them. Kudos to the first devs, they done quite a lot already, but the community cannot depend on a non maintained and partly implemented graphql client.

This shows on one side the limited Flutter adoption by the community. On the other side, Flutter use will not increase without this absolutely critical piece of the puzzle. Graphql is the ~~future~~ present of front-end oriented api. Without it, Flutter and the many advantages it has over react-native stays a no-go.

**Comment by juicycleff** [comment]
@olup thanks for the feedback. I already did fork it and fixed a bug that makes test fail and breaks release build. I plan on taking the library ahead and improving especially caching and persistence. I would love the final 1.0.0 release before messing around, but it won't hurt to continue. I just started out in the next branch. As for penetration, it hasn't gained more ground, but it's a better piece of software compared to React Native

**Comment by sjmcdowall** [comment]
I’m not sure the next branch is the right one?? 

The last pub version is alpha.11 and I think next is .8 or .7?.  

Then again I can’t find .11 .. sigh

**Comment by sjmcdowall** [comment]
@juicycleff -- Rex, can you post the git url for your branch?  And yes, "next" is the appropriate branch to start with.  Personally in your branch I would merge that to master as 1.0.0 and go from there... and .. maybe change the name to flutter_graphql and publish it on dart pub on that and just basically take it over and open it up to others so we're not in this position again.. :(

**Comment by juicycleff** [comment]
@sjmcdowall I'm thinking of doing the same. I will do some cleanup with all those complicated branches and tags that this library does not need right now. merge it into the master and create a dev branch for any current issues. I will notify you later today, after work. Here is the link you requested https://github.com/juicycleff/graphql-flutter.git

**Comment by eusdima** [comment]
Sorry for the lack of feedback from me and @HofmannZ 
We are currently doing some maintenance and we are going to be more active from now on.
