### ISSUE TITLE
DateTime format

### ISSUE THREAD

**Issue by netwrkx** [zino-app/graphql-flutter#160]
hello, thanks for the hardwork in developing this plugin..

```
in my mongodb, createdat and updatedat are store in this format
    "createdAt" : ISODate("2018-09-19T11:01:23.700Z"),
    "updatedAt" : ISODate("2018-12-26T19:28:30.412Z"),
```

```
but when i use this plugin, it returns as 
Wed Sep 19 2018 12:01:23 GMT+0100 (W. Central Africa Standard Time)
```

is this a flutter issue or how do i get the DateTime format
anybody pls help

**Comment by juicycleff** [comment]
That is neither flutter or graphql issue. Create an iso firmated DateTime object in flutter

**Comment by netwrkx** [comment]
Do you mean I should add Iso8601DateTimeSerializer to my serializers or how do I "Create an iso firmated DateTime object in flutter"

**Comment by juicycleff** [comment]
@netwrkx if I get you correctly, you are sending data from your server to flutter and the format changes once it gets to flutter right?

**Comment by netwrkx** [comment]
Yes, it does.. Any reason why?

**Comment by juicycleff** [comment]
But what's the point if you need ISO string then use a String for the graphql type or convert your existing date time to ISO format in Flutter. What difference does it make? A Date is a date. I think you should close this as it's not an issue

**Comment by netwrkx** [comment]
You don't still get me
Http call returns my date in iso format but when I use this graphql plugin it returns as "Wed Sep 19 2018 12:01:23 GMT+0100 (W. Central Africa Standard Time)" 

How do I parse date "Wed Sep 19 2018 12:01:23 GMT+0100 (W. Central Africa Standard Time)" to ago format..

**Comment by netwrkx** [comment]
@HofmannZ any help with this

**Comment by HofmannZ** [comment]
@netwrkx Have a look at https://docs.flutter.io/flutter/dart-core/DateTime-class.html.

It looks like there's something going wrong with the ISO convention as @juicycleff has pointed out.

Closing the issue right now, it seems unrelated to this project.

**Comment by fluttercorner** [comment]
[How to Display Current DateTime in Flutter](https://fluttercorner.com/how-to-display-current-datetime-in-flutter/)
