### ISSUE TITLE
HttpLink doesn't call NextLink

### ISSUE THREAD

**Issue by michael-golfi** [zino-app/graphql-flutter#165]
**Describe the bug**

I'm working on creating an AuthLink to fetch a token before calling HttpLink. I was using HttpLink as a model for the new link and noticed that HttpLink doesn't call NextLink. Is it supposed to call next link if a link is concatenated to it?

For completeness I got my Link working by doing the following:

```dart
class AuthLink extends Link {
  AuthLink()
      : super(
          request: (Operation operation, [NextLink forward]) {
            StreamController<FetchResult> controller;

            Future<void> onListen() async {
              try {
                var session = await UserService.getSession();
                var token = session.getToken();
                operation.setContext(<String, Map<String, String>>{
                  'headers': <String, String>{'Authorization': token}
                });
              } catch (error) {
                controller.addError(error);
              }

              await controller.addStream(forward(operation));
              await controller.close();
            }

            controller = StreamController<FetchResult>(onListen: onListen);

            return controller.stream;
          },
        );
}
```

Here's the corresponding code from HttpLink@1.0.0-alpha.11

```dart
StreamController<FetchResult> controller;
Future<void> onListen() async {
  Response response;

  try {
    // TODO: support multiple http methods
    response = await fetcher.post(
      uri,
      headers: httpHeaders,
      body: httpOptionsAndBody.body,
    );

    operation.setContext(<String, Response>{
      'response': response,
    });

    final FetchResult parsedResponse = _parseResponse(response);

    controller.add(parsedResponse);
  } catch (error) {
    controller.addError(error);
  }

  await controller.close();
}

controller = StreamController<FetchResult>(onListen: onListen);

return controller.stream;
```

and using concat:
```dart
    var authLink = AuthLink()
        .concat(HttpLink(uri: ''));
    ValueNotifier<GraphQLClient> client = ValueNotifier(
      GraphQLClient(
        cache: InMemoryCache(),
        link: authLink,
      ),
    );
```

**Expected behavior**
- NextLink executed if a link is appended to HttpLink.

**Smartphone (please complete the following information):**
 - Device: IPhone XR

**Additional context**

**Comment by HofmannZ** [comment]
@michael-golfi Just added an official AuthLink based on your idea, it does call the link, see #171

**Comment by michael-golfi** [comment]
This is awesome, thanks for including this!

**Comment by mjheilmann** [comment]
HttpLink really doesn't call next link.  In my Graphql Server, authorization is performed in the resolvers, so I detect a revoked authorization token in the GraphQL errors.  I handle this in Apollo by having a link after the http call that can do this high-level logic, but in this library any link after Http Link is never called.  I copied HttpLink into my project to try to modify it, but the operation class is not capable of holding a graphql or network error result, so the HttpLink cannot call next link.  I am brand new to Dart/Flutter, so I didn't go further.

I am currently evaluating having a custom HttpLink so I can action on the HttpResult before it gets to Flutter, or having a Query and Mutation wrapper to handle this logic on every Query or Mutation invocation, but neither feel like good or maintainable options.

Are there any plans (or documentation I haven't discovered) for an ErrorLink, or RetryLink, or similar where I can take action outside of the Flutter update cycle, but after the network call?

**Comment by mjheilmann** [comment]
In the meantime, I subclassed HttpLink, and I proxy the request call so I can inspect and process the result transparently to the other links.
