### ISSUE TITLE
Update dependencies and cleanup project

### ISSUE THREAD

**Issue by sjmcdowall** [zino-app/graphql-flutter#166]
**Describe the bug**

Getting package conflicts with the latest versions of various packages.. Lots have changed since this was last pushed. 

Also -- this repo needs some TLC.  There are many old / dead branches still -- and we're at 1.0.0+alpha.11 yet there is no Tag for that ...

Is there anyone actually reading these and maintaining this? There are 12 PR's .. and 35 open issues..

**Comment by eusdima** [comment]
Closed because of #168
