### ISSUE TITLE
Proper documentation for subscriptions (both in flutter and standalone)

### ISSUE THREAD

**Issue by hardikmodi1** [zino-app/graphql-flutter#169]
I would like to use this library for my ongoing project. I want to consume graphql subscriptions but unable to find how to do the same. Can someone please share the proper documentation for the same like where to initialize the socketClient and how to use subscription widget.  As when I am using it as described in docs, it throws the error.

**Comment by HofmannZ** [comment]
We're planning to do a load of work on the documentation starting next weekend. We'll include some examples for subscriptions as well

**Comment by juicycleff** [comment]
I think we should set up a static paged website for this @HofmannZ. I will create a repository setup minimal docs then move it here

**Comment by hardiked** [comment]
If someone can post the working subscription example that will also help me for now.

**Comment by gabrieltong** [comment]
+1

**Comment by ArpanKIIT2017** [comment]
Its very frustrating trying to use Subscriptions here. Although I got an idea by going through your code, its still hard to make it work. Websocket also connected but there are errors. So need a thorough documentation. I planned to use subscription in my app but had to stick with polling.

**Comment by micimize** [comment]
The `starwars` example [fully functioning subscription example](https://github.com/zino-app/graphql-flutter/blob/master/examples/starwars/lib/reviews/review_subscription.dart). I'm leaving this open until we have more rigorous docs, which would be a welcome contribution (and I think is a doable first issue going off of the example)

**Comment by ArpanKIIT2017** [comment]
I shall try my best setting up a documentation for the Subscription API. It took me days to figure out. @micimize 's starwars example helped. I had to fix another bug in local in your codebase to get things woking (now under another issue). For people not being able to set up subscriptions kindly follow the startwars example for the time being.

**Comment by dmh2000** [comment]
I ginned up some reasonably simple working examples of using this package in a standalone Dart program and a Flutter app. Its located in my repo at https://github.com/dmh2000/Flutter-GraphqlX.  The examples show how to make simple query, mutation and subscription requests. It includes a simple node.js graphql server to test against.

**Comment by micimize** [comment]
`v4`'s READMEs combined with the starwars examples make the subscription docs up to snuff with the rest of the api
