### ISSUE TITLE
The following StateError was thrown while handling a gesture:Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by OOMROO** [zino-app/graphql-flutter#170]
Click the button mutation request data, enter the next page, return to the previous page, and click the button to report an error

**Describe the bug**
The following StateError was thrown while handling a gesture:
I/flutter (14239): Bad state: Cannot add new events after calling close
I/flutter (14239): 
I/flutter (14239): When the exception was thrown, this was the stack:
I/flutter (14239): #1 MutationState.runMutation (package:graphql_flutter/src/widgets/mutation.dart:56:32)
I/flutter (14239): #2 _LoginPageState.sendCodeButton.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:antu_flutter/page/LoginPage.dart:175:28)
I/flutter (14239): #3 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
I/flutter (14239): #4 _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
I/flutter (14239): #5 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (14239): #6 TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (14239): #7 TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
I/flutter (14239): #8 GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (14239): #9 _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:184:20)
I/flutter (14239): #10 _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (14239): #11 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (14239): #12 _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (14239): #13 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (14239): #14 _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter (14239): #15 _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter (14239): (elided one frame from package dart:async)

**Comment by HofmannZ** [comment]
Can you provide some more context?

**Comment by budde377** [comment]
I'm seeing this when calling a mutation on one route, then navigating to another route and calling another mutation. I'm on version `1.0.0-alpha-11`.

**Comment by Goolpe** [comment]
> I'm seeing this when calling a mutation on one route, then navigating to another route and calling another mutation. I'm on version `1.0.0-alpha-11`.
I also had this error, but after switching to version '^1.0.0-beta.1+1' the error disappeared

**Comment by budde377** [comment]
Upgrading to `1.0.0-beta.1+1` fixed it for me aswell.
