### ISSUE TITLE
Need more headers in AuthLink

### ISSUE THREAD

**Issue by endigo** [zino-app/graphql-flutter#173]
Our API service uses access-token and refresh token.

Here just one header: 'Authorization'
https://github.com/zino-app/graphql-flutter/blob/next/lib/src/link/auth/link_auth.dart#L21

We need 3 custom named headers.
for example:
```dart
HttpLink(uri: global.graphqlEndpoint, headers: {
  'x-token': state.user.accessToken,
  'x-refresh-token': state.user.refreshToken,
  'accept-language': locale.toString()
}),
```

Thanks.

**Comment by HofmannZ** [comment]
You can write your own Link:

```dart
typedef GetHeaders = Future<Map<String, String>> Function();

class CustomAuthLink extends Link {
  CustomAuthLink({
    this.getHeaders,
  }) : super(
          request: (Operation operation, [NextLink forward]) {
            StreamController<FetchResult> controller;

            Future<void> onListen() async {
              try {
                final Map<String, String> headers = await getHeaders();

                operation.setContext(<String, Map<String, String>>{
                  'headers': headers
                });
              } catch (error) {
                controller.addError(error);
              }

              await controller.addStream(forward(operation));
              await controller.close();
            }

            controller = StreamController<FetchResult>(onListen: onListen);

            return controller.stream;
          },
        );

  GetHeaders getHeaders;
}
```

And then you can implement it just as you would with the `AuthLink`.

Hope that helps!

**Comment by HofmannZ** [comment]
Closing, seems revolved.

**Comment by 5hanth** [comment]
@HofmannZ need to reopen this as the above CustomAuthLink's parameter signatures fails for 4.0.0

**Comment by HofmannZ** [comment]
@5hanth we moved to a new link system, see https://github.com/zino-app/graphql-flutter/blob/beta/changelog-v3-v4.md#we-now-use-the-gql_link-system

**Comment by MSRPRO** [comment]
You can create your own link (updated answer 2021) :

    import 'dart:async';
    
    import 'package:graphql/client.dart';
    
    typedef _RequestTransformer = FutureOr<Request> Function(Request request);
    
    class CustomAuthLink extends _AsyncReqTransformLink {
      CustomAuthLink({
        required this.getHeaders,
      }) : super(requestTransformer: transform(getHeaders));
    
      final FutureOr<Map<String, String>>? Function() getHeaders;
    
      static _RequestTransformer transform(
        FutureOr<Map<String, String>>? Function() getHeaders,
      ) =>
          (Request request) async {
            final Map<String, String>? headers = await getHeaders();
            return request.updateContextEntry<HttpLinkHeaders>(
              (_headers) => HttpLinkHeaders(
                headers: headers!,
              ),
            );
          };
    }
    
    class _AsyncReqTransformLink extends Link {
      final _RequestTransformer requestTransformer;
    
      _AsyncReqTransformLink({
        required this.requestTransformer,
      });
    
      @override
      Stream<Response> request(
        Request request, [
        NextLink? forward,
      ]) async* {
        final req = await requestTransformer(request);
    
        yield* forward!(req);
      }
    }
