### ISSUE TITLE
Implement apollo's direct cache access (writeQuery, readQuery)

### ISSUE THREAD

**Issue by lucasavila00** [zino-app/graphql-flutter#176]
Let's say I query a list of items and then I query just one item from this list.
I know that the query for one item has the data on the list one but I cannot tell the cache so.

Like apollo, I'd like to be able to do so, but currently the cache is keyed based on the [Operation().toKey()](https://github.com/degroote22/graphql-flutter/blob/e0117d6cfb9f8aa20c31fb018d58187c4194a0b1/lib/src/core/query_manager.dart#L129) method.

The way I thought about doing it is exposing two methods on the client (readQuery and writeQuery) that does this stuff of figuring out the key behind the scenes.

[On my fork I've done it and you can check it out.](https://github.com/degroote22/graphql-flutter/blob/e0117d6cfb9f8aa20c31fb018d58187c4194a0b1/lib/src/graphql_client.dart#L51)
[(the implementation)](https://github.com/degroote22/graphql-flutter/blob/fork/lib/src/core/query_manager.dart#L62)

My fork is not well mantained and I'm changing stuff all the time so don't assume this is how we'd implement it, I'm only showing it to discuss the surfacing API.

Anyway, having this I can write to the query to expand lists in the cache and mutate fields whenever I want.

What do you think?
Perhaps we should use names like readQueryFromCache and writeQueryToCache for clarity?

Once this is solved I can write a proper PR.

**Comment by juicycleff** [comment]
@degroote22 that's nice, I think readQueryFromCache and writeQueryToCache seem like a name for this feature. I will wait for @HofmannZ for his input, but you could send a PR so we test this out.

**Comment by juicycleff** [comment]
I just saw your PR, I will test it out

**Comment by HofmannZ** [comment]
@degroote22 I think that exposing cache to the query/mutation would be great. I think we should just expose the whole cache rather than just the read/write operations. That's also how Apollo does it. This would also allow us to update the cache after a mutation.

@degroote22 @juicycleff Do you guys agree we should keep that in line with Apollo?

**Comment by juicycleff** [comment]
@HofmannZ I totally agree to this. I have been looking at the Apollo cache implementation on Android it is the apollo way

**Comment by micimize** [comment]
I have some related [typed state management](https://gist.github.com/micimize/b47df421b0753e99447d967422584d28) work in my project that takes advantage of cache normalization to add custom transient state to entities (gist probably not particularly interpret-able out of context)

**Comment by micimize** [comment]
[These methods are exposed in Apollo](https://www.apollographql.com/docs/angular/features/caching) via the [DataProxy](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache/src/types/DataProxy.ts#L85) interface, which is implemented by the cache and exposed by the [`client`](https://github.com/apollographql/apollo-client/blob/724cda81ecad34d159615d4dda2249ba55435aa6/packages/apollo-client/src/ApolloClient.ts#L368). With [`Operation.fromOptions`](https://github.com/micimize/graphql-flutter/blob/optimisim_revived/lib/src/link/operation.dart#L15) and `operationName` as a getter in #199, the code for this will become a lot simpler.
In the cache:
```dart
void writeQuery(QueryOptions options, dynamic data) => write(
      Operation.fromOptions(options).toKey(),
      data,
);
dynamic readQuery(QueryOptions options) => read(
      Operation.fromOptions(options).toKey()
);
```
In the client:
```dart
void writeQuery(QueryOptions options, dynamic data) {
    cache.writeQuery(options, data);
   queryManager.rebroadcastQueries();
};
dynamic readQuery(QueryOptions options) => cache.readQuery(options);
```

**Comment by lucasavila00** [comment]
Is there a reason not to implement this after #199 has been merged?

**Comment by lucasavila00** [comment]
I implemented it on my fork on the query manager itself. I think the cache doesn't need to know about the Operation as how to generate a key.

Client:
```dart
  QueryResult readQuery(QueryOptions options) {
    return queryManager.readQuery(options);
  }

  void writeQuery(QueryOptions options, dynamic data) {
    queryManager.writeQuery(options, data);
  }
```

Query Manager:
```dart
  QueryResult readQuery(QueryOptions options) {
    final Operation operation = Operation.fromOptions(options);

    final QueryResult queryResult = QueryResult(
      data: cache.read(operation.toKey()),
      source: QueryResultSource.Cache,
    );

    return queryResult;
  }

  void writeQuery(QueryOptions options, dynamic data) {
    final Operation operation = Operation.fromOptions(options);

    cache.write(
      operation.toKey(),
      data,
    );
    rebroadcastQueries();
  }
```

**Comment by micimize** [comment]
@lucasavila00 yeah I was just modeling it on apollo, but I also prefer keeping the cache more generic.
Your implementation looks good to me - would be a welcome PR (on `beta`)

**Comment by lucasavila00** [comment]
I plan to submit it with tests.
I'm in a kind of busy week but soon I'll submit it.

**Comment by klavs** [comment]
As I mentioned in https://github.com/zino-app/graphql-flutter/issues/400#issuecomment-539147245, I think the cache must know about the operation and it's variables to cache the data more intelligently. It is required to understand how each parameterized field was actually queried.

**Comment by micimize** [comment]
This has been implemented on the cache in `v4`. Am consolidating the rebroadcasting client methods into #728
