### ISSUE TITLE
SQL Normalised cache on disk

### ISSUE THREAD

**Issue by juicycleff** [zino-app/graphql-flutter#179]
**Is your feature request related to a problem? Please describe.**
Seeing a lot of mobile apps require cache persistence, I think it's mandatory to have optional support for SQL storage out of the box. I have started building the API [here](https://github.com/rexraphael/graphql-flutter) following Apollo client android pattern here https://github.com/apollographql/apollo-android/blob/master/apollo-android-support/src/

**Describe the solution you'd like**
I want the cache argument to accept any class that implements Cache interface internally, with support for multiple caches or chaining such as in-memory cache and disk cache  I would like full support for iOS and Android.

I would love feedback and feature you think we should add to it

**Comment by micimize** [comment]
The `cache` argument should definitely be able to support anything that implements `Cache`. Adding an SQL cache seems fine enough. I'd note that we have a [persist-able](https://github.com/zino-app/graphql-flutter/blob/next/lib/src/cache/in_memory.dart#L47-L57), normalized cache already. But still, nothing wrong with more options

**Comment by micimize** [comment]
Closing as this is not a priority anytime soon. Would be interesting to do with angel's orm, maybe
