### ISSUE TITLE
NoSuchMethodError: The getter 'loader' was called on null.

### ISSUE THREAD

**Issue by Sndan** [zino-app/graphql-flutter#18]
**Describe the bug**
not sure what it is ... just trying to run the library

**To Reproduce**
just ruining the app with basic implantation 
this is my code 

```
          new Mutation(
            mutations.signupUserMutation,
            builder: (
              runMutation, { // you can name it whatever you like
              bool loading,
              var data,
              String error,
          }) {
            if (error != '') {
              return new Text(error);
            }
            return new RaisedButton(
              onPressed: () => runMutation({
                'name': 'ali',
                'email': 'a@w.com',
                'password': '1qaz1q',
              }),
              child: new Icon(Icons.edit),
            );
            
          },
          onCompleted: (Map<String, dynamic> data) {
                showDialog(
                context: context,
                builder: (BuildContext context) {
                  return AlertDialog(
                    title: Text('Thanks for your star!'),
                    actions: <Widget>[
                      SimpleDialogOption(
                        child: Text('Dismiss'),
                        onPressed: () {
                          Navigator.of(context).pop();
                        },
                      )
                    ],
                  );
                }
              );
            }
          ),
```

**Screenshots**
![image](https://user-images.githubusercontent.com/110978/41860975-adda09b8-78a8-11e8-9186-5bfbebcd19e9.png)

**Desktop (please complete the following information):**
 - OS: windows
 - 
 - Version 0.4.1 , 0.5

> compiler message: #54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
> TimeoutException: Request to Dart VM Service timed out: ext.flutter.debugPaint({enabled: false, isolateId: isolates/629662914})TimeoutException: Request to Dart VM Service timed out: ext.flutter.showPerformanceOverlay({enabled: false, isolateId: isolates/629662914})TimeoutException: Request to Dart VM Service timed out: ext.flutter.repaintRainbow({enabled: false, isolateId: isolates/629662914})TimeoutException: Request to Dart VM Service timed out: ext.flutter.timeDilation({timeDilation: 1, isolateId: isolates/629662914})TimeoutException: Request to Dart VM Service timed out: ext.flutter.debugAllowBanner({enabled: true, isolateId: isolates/629662914})TimeoutException: Request to Dart VM Service timed out: ext.flutter.debugPaintBaselinesEnabled({enabled: false, isolateId: isolates/629662914})

**Comment by eusdima** [comment]
We have the template for bug reporting for a reason. If you don't provide detailed information on what is going on,what versions are you running, 
etc, then I will close the issue for not being able to reproduce it.
