### ISSUE TITLE
More examples with complex object structure inside mutation or query

### ISSUE THREAD

**Issue by vvasc** [zino-app/graphql-flutter#182]
**Is your feature request related to a problem? Please describe.**
I use flutter graphql with flutter redux and my mutations and queries are inside my middlewares. My problem is in serialization of a mutation, when pass the object variables through the client.

In Insomnia I use this mutation: 

```
mutation {
 createSpot(createSpotInput: {
    nome: "Spot 1"
    descricao: "Primeiro spot criado"
    id_usuario: 1
 }) {
      code
      message
      data {
        id
        nome
        descricao
        usuario {
          nome
          email
        }
    	}
    } 
}
```

And it works perfectly, but, in flutter I try something like:

```
    mutation createSpot(\$createSpotInput: CreateSpotInput) {
      createSpot(createSpotInput: {
        nome: \$nome
        descricao: \$descricao
        id_usuario: \$id_usuario
      }) {
        code
        message
        data {
          id
          nome
          descricao
          usuario {
            nome
            email
          }
        }
      }
    }

```
And I've a parser Error

**Describe the solution you'd like**
If possible, I would like a more complex and concise example to use different object structure with your serialization.

**Describe alternatives you've considered**
For now, I pass this three keys like your documentations said

**Additional context**
My variables are something like: 
`variables: {'createSpotInput': {'nome': action.spot['nome'], 'descricao': action.spot['descricao'], 'id_usuario': store.state.loginState.id}}`
And my middleware is:

```
import 'package:redux/redux.dart';
import 'package:reduxpoc/graphql/graphql.dart';
import 'package:reduxpoc/keys.dart';
import 'package:reduxpoc/pages/home-page/spot-page/+state/spot-page-actions.dart';

class SpotPageMiddleware extends MiddlewareClass {

  String createSpotMutation =
  """
    mutation createSpot(\$createSpotInput: CreateSpotInput) {
      createSpot(createSpotInput: {
        nome: \$nome
        descricao: \$descricao
        id_usuario: \$id_usuario
      }) {
        code
        message
        data {
          id
          nome
          descricao
          usuario {
            nome
            email
          }
        }
      }
    }
  """.replaceAll('\n', ' ');


  @override
  void call(Store store, action, NextDispatcher next) {

    if (action is SpotCreate) {
      mutation(createSpotMutation, variables: {'createSpotInput': {'nome': action.spot['nome'], 'descricao': action.spot['descricao'], 'id_usuario': store.state.loginState.id}})
        .map((dynamic data) {
          store.dispatch(new SpotCreated(data));
        })
        .listen(
          print, onDone: () => print('Done!'),
        );
    }

    if (action is SpotCreated) {
      Keys.navKey.currentState.pushNamed("home-page");
    }
    next(action);
  }
}
```

**Comment by vvasc** [comment]
I solve that using
    mutation createSpot(\$createSpotInput: CreateSpotInput) {
      createSpot(createSpotInput: \$createSpotInput) {
        code
        message
        data {
          id
          nome
          descricao
          usuario {
            nome
            email
          }
        }
      }
    }

I'll close this issue, but you might consider make a better and bigger example.

**Comment by Setti7** [comment]
Hi @vvasc, how did you pass a type of `CreateSpotInput` into the mutation?
