### ISSUE TITLE
Support GraphQL Multipart Requests

### ISSUE THREAD

**Issue by yunyu** [zino-app/graphql-flutter#183]
**Is your feature request related to a problem? Please describe.**
We are currently unable to do things like upload images and large files directly using this library.

**Describe the solution you'd like**
The library should support the multipart request spec: https://github.com/jaydenseric/graphql-multipart-request-spec

**Comment by micimize** [comment]
@truongsinh you said you were working on this?

**Comment by truongsinh** [comment]
@micimize I will push the code in 4 hours

**Comment by truongsinh** [comment]
@micimize @yunyu PR at #202

**Comment by micimize** [comment]
closed by #202
