### ISSUE TITLE
Return the actual error message only

### ISSUE THREAD

**Issue by echonox** [zino-app/graphql-flutter#185]
**Is your feature request related to a problem? Please describe.**
When Catching error using `error.toString();`, graphql mutation returns this "Error returned by the server in the query: [There is already a user with that username: [{ line: 2, column: 7 }]]"

**Describe the solution you'd like**
What I would like is to be able to get just the message error that is "There is already a user with that username", as its really bad to show dev like error to the user, how can I access just this message?

**Comment by micimize** [comment]
You mean `error.message`?
