### ISSUE TITLE
How to add(enable) debug logging?

### ISSUE THREAD

**Issue by dekeract** [zino-app/graphql-flutter#188]
Hi!
In this issue I saw there is a way to add debug logging by using Link object. 
https://github.com/zino-app/graphql-flutter/issues/116
Do you have any example of how to do it on latest 1.0.0-beta?

**Comment by dekeract** [comment]
In case someone else will need to do same, this is how we enabled logging
`Link loggingLink = Link(request: (
      Operation operation, [
      NextLink forward,
    ]) {
      StreamController<FetchResult> controller;

      Future<void> onListen() async {
        await controller.addStream(forward(operation));
        for (var response in operation.getContext().values) {
          if (response is Response) {
            //TODO extended logs
            Logger.root.info("Interceptor: ${response.body}");
          } else {
            Logger.root.info("Interceptor: ${response}");
          }

        }
        await controller.close();
      }

      controller = StreamController<FetchResult>(onListen: onListen);

      return controller.stream;
    });
    Link link = loggingLink.concat(authLink)`

**Comment by micimize** [comment]
@dekeract thanks for sharing the solution! Will have to remember to `ADD_TO_DOCS` when we look at #59

**Comment by Nazacheres** [comment]
@micimize Even tho it works great with the response, I can't find a way to print the body of request, cause BaseRequest has no body :\

**Comment by micimize** [comment]
The `BaseRequest` should be either a `Request`, or a `MultipartRequest` in the event you're uploading a file. So, wherever you're trying to get the body, you should be able to do something like
```dart
String getBody(BaseRequest request) {
  if (request is Request) {
    return request.body;
  } else if (request is MultipartRequest) {
    return (<String>[
      'Fields:',
      request.fields?.toString() ?? '',
      'Files:',
    ]..addAll(request.files.map((MultipartFile f) =>
            "<File field='${f.field}', filename='${f.filename}'/>")))
        .join('\n');
  }
  return 'unrecognized request $request';
}

**Comment by amadeu01** [comment]
> In case someone else will need to do same, this is how we enabled logging
> 
> ```
> Link loggingLink = Link(request: (
>       Operation operation, [
>       NextLink forward,
>     ]) {
>       StreamController<FetchResult> controller;
> 
>       Future<void> onListen() async {
>         await controller.addStream(forward(operation));
>         for (var response in operation.getContext().values) {
>           if (response is Response) {
>             Logger.root.info("Interceptor: ${response.body}");
>           } 
> 
>         }
>         await controller.close();
>       }
> 
>       controller = StreamController<FetchResult>(onListen: onListen);
> 
>       return controller.stream;
>     });
>     Link link = loggingLink.concat(authLink)
> ```

I'm getting `StreamedResponse` instead of `Response`, so when I try to print the response body I get 

```
09:35:22.678 22 info flutter.tools [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Stream has already been listened to.

```

@micimize Do you know how I can the the response body?

**Comment by micimize** [comment]
@amadeu01 try [`await response.stream.bytesToString()`](https://stackoverflow.com/a/55521892/2234013)

**Comment by Abdelazeem777** [comment]
How can I read the HttpLink URL from the LoggerLink?
