### ISSUE TITLE
Provide methods for Dart and not only Flutter. 

### ISSUE THREAD

**Issue by feinstein** [zino-app/graphql-flutter#189]
I didn't use this library, I am just starting to look for GraphQL in Flutter, but looking at the Readme, this library seems to be really tight with Flutter Widgets, so if I want to make a Query on my BLoC or Reducer or ViewModel or any form of code that's not presentation, I can't.

If this library can be used in a Model class, please also provide its use on the Readme. This is very helpful for unit testing and DI, where we can just simulate a query on a model class and serve it to a Presentation Widget.

**Comment by micimize** [comment]
Consolidating this with #125
