### ISSUE TITLE
How to update cache after mutation without pollInterval?

### ISSUE THREAD

**Issue by Goolpe** [zino-app/graphql-flutter#190]
Hello, Query gives old data after mutation - need new, how can I do this without pollInterval (because I can't to do much requests to the server)?

**Comment by micimize** [comment]
#199 adds `rebroadcastQueries` to the manager, which should solve the problem if you're leveraging normalization

**Comment by micimize** [comment]
This should now happen automatically with #199 if you're using an `OptimisticCache`

**Comment by mohammadanton** [comment]
I already update to 1.0.0-beta.1 but after mutation, the query keep giving old data.

this is my mutation
    final QueryResult result = await client2.mutate(
      MutationOptions(
        document: mutation.addChat,
        variables: {
          'roomId': roomId,
          'content': content,
          'idUser': idUser
        }
      )
    );

and this is my client
  GraphQLClient client2 = GraphQLClient(
    link: link,
    cache: InMemoryCache(),
  );

**Comment by HofmannZ** [comment]
@mohammadanton could you try out version `1.0.1-beta.9`?
