### ISSUE TITLE
We are looking for people that can push this library to the next level.

### ISSUE THREAD

**Issue by eusdima** [zino-app/graphql-flutter#196]
### Everyone can help
We only have a few requirements regarding styling and structuring the project, but in rest, every idea is welcome. We can set up a few things:
- A communication channel like slack or discord. [Discord Invite Link](https://discord.gg/tXTtBfC)
- Periodic skype call to discuss the future of the project.
- Open scrum platform
- Weekend lunch sessions for people from **Amsterdam** and you want to share your amazing ideas or you need help with a Dart/Flutter related project.
- You decide what we can do more!!

### Storytime
This project has been going through a dry period of maintainers.

Both @HofmannZ and I don't have the time to do much work since we are not actively working with flutter anymore.
I initially started this project as an in-house prototype while working at Zino App and since it passed all the quality requirements, we used it in production. @HofmannZ decided to push it open-source to help speed up the flutter community and to gather more people that believe Flutter is the future. Sadly, we both stopped working with Flutter half a year ago and we had no time to keep this project happy.

### Future projects
I have been working on a few projects that can improve the quality of this library even more:
- Dart types generator from GraphQL schema
- HTTP scheduler that can be coupled with the GraphQL engine of this library to allow smooth package communication on slower devices and lazy loading for Queries.
- Advanced caching modules for GraphQL-Flutter that are tailored to some uses cases(low-latency applications where milliseconds matter)
If people are interested in those, then I can push more of my free time to get a working alpha version.

### Interested in helping?
You can contact me at **eusdima@gmail.com** or reply with a comment.

#### Update 1
Added discord link [Discord Invite Link](https://discord.gg/tXTtBfC)
Proposalt to integrate [graphql-to-dart](https://github.com/micimize/graphql-to-dart)

**Comment by micimize** [comment]
I vote for a discord.

How far along is your type generator? I made [graphql-to-dart](https://github.com/micimize/graphql-to-dart) for type / json serializable generation, and have done some work on integrating it with `graphql-flutter`. It's not that well integrated with the flutter ecosystem, but I feel like it gets the job done for now. Would be happy to rework the way the models /helpers work as well.

**Comment by eusdima** [comment]
@micimize That is a really nice library. 
I have written the types generator prototype in Dart [Example](https://github.com/zino-app/graphql-flutter/files/3000744/main.txt)
Created a discord server: [Discord Invite Link](https://discord.gg/tXTtBfC)

**Comment by Sach97** [comment]
Hi guys I don't if it can help but I've started working on a [graphql_cli](https://github.com/Sach97/graphql_cli.dart) which aim to write locally a remote schema.

**Comment by truongsinh** [comment]
count me in as well ( i@truongsinh.pro ) . Actually, I'm working on https://github.com/zino-app/graphql-flutter/issues/189 , and already finish GraphQL upload https://github.com/jaydenseric/graphql-multipart-request-spec , and lots of other enhanced stuff, such as unittest / codecoverage . I'm also uploader of https://pub.dartlang.org/packages/graphql_client , which can be good if we seperate this project into dart-only as a core repo, and flutter-related which imports `graphql_client`

**Comment by aaahrens** [comment]
any performance considerations with built value? (not just factory gen)

**Comment by micimize** [comment]
@aaahrens I'm not sure what you mean, but please pop into discord to discuss further
