### ISSUE TITLE
flutter and graphql-flutter  doesn't match any versions

### ISSUE THREAD

**Issue by njdmznkj** [zino-app/graphql-flutter#198]
when I import graphql-flutter:^0.9.5 in my project,But prompted me to make a mistake

[snakemobile] flutter packages get
Running "flutter packages get" in snakemobile...                
The current Flutter SDK version is 0.0.0-unknown.

Because graphql_flutter >=0.9.2 <1.0.0-beta.1 depends on path_provider >=0.4.0 which requires Flutter SDK version >=0.1.4 <2.0.0, graphql_flutter >=0.9.2 <1.0.0-beta.1 is forbidden.
So, because snakemobile depends on graphql_flutter ^0.9.5, version solving failed.
pub get failed (1)
exit code 1

**Comment by smkhalsa** [comment]
I'm also getting this error when I try to use audioplayers 0.12.0

**Comment by mainawycliffe** [comment]
You have a dependency conflict, both this package and audioplayers package are using different versions of path_provider package causing conflict. We will update to the latest version of path_provider (or if you can, you can submit a PR), in the meantime, version 0.11.0 shouldn't cause any conflicts, as a temporary work around.

**Comment by smkhalsa** [comment]
Updated dependency in #271

**Comment by mainawycliffe** [comment]
That was quick. I was about to do the same. Could you please also update any other packages, on both packages, there are several ones that needs updates.
![Annotation 2019-05-17 041644](https://user-images.githubusercontent.com/12270550/57896699-b0cb1600-785a-11e9-9ac3-67dd84592b76.png)
![Annotation 2019-05-17 041715](https://user-images.githubusercontent.com/12270550/57896702-b163ac80-785a-11e9-9690-caeb86e35e9b.png)

**Comment by smkhalsa** [comment]
@mainawycliffe #268 updates rxdart. flutter_test depends on meta 1.1.6, so upgrading it to 1.1.7 fails.

**Comment by mainawycliffe** [comment]
Yea, i see it. The only problem is that the PR is against master instead of beta. I will add a comment there.
