### ISSUE TITLE
Automated releases (CI/CD)

### ISSUE THREAD

**Issue by HofmannZ** [zino-app/graphql-flutter#204]
**Is your feature request related to a problem? Please describe.**
Releases currently require me to manually deploy them.

**Describe the solution you'd like**
I want to setup CircleCI with `semantic-release` to handle this automatically.

**Describe alternatives you've considered**
We could use other CI tools, but I have done most professional projects with CircleCI, so my preference lays there.

**Additional context**
It would require a standard for composing commit messages.

**Comment by truongsinh** [comment]
FYI I'm using CirrusCI in other MRs for unit test and coverage (#202, #203)
