### ISSUE TITLE
Calling Mutation onClick

### ISSUE THREAD

**Issue by abumoallim** [zino-app/graphql-flutter#205]
I want to call mutations onClick on the buttons.
How Can I do that?

Like simple Post and Get calls without returning as a widget.

I am unable to find any example for that.
So please help me with the examples.

Using Client Without Widget for both Query and Mutations with Headers.
I tried the one example in ReadMe but I think its older one, many things have been changed after that,

Please help me with this.

**Comment by micimize** [comment]
You can now see some direct client usage [in the bloc example](https://github.com/zino-app/graphql-flutter/blob/next/example/lib/graphql_bloc/bloc.dart#L73-L86).
Essentially you just `QueryResult result = await client.query(options)`
or `QueryResult result = await client.mutate(options)` directly on the client with their respective options objects.

Better direct client usage (and better docs in general) is on the roadmap will be more of a focus after #203 is merged
