### ISSUE TITLE
Json parse response error

### ISSUE THREAD

**Issue by fabricio-godoi** [zino-app/graphql-flutter#21]
Greetings,

Performing a simple query to get a username from my local server, I got this message on the console:
`type 'List<dynamic>' is not a subtype of type 'String'`

Performing a debug in the code, I reach this exception:
```
Map<String, dynamic> _parseResponse(http.Response response) {
...
if (jsonResponse['errors'] != null) {
   throw new Exception(
        'Error returned by the server in the query' + jsonResponse['errors'],
   );
}
```
But checking the debug information I got the response data back from the server and also got the errors tag in the Json with size 0.

The code checks only if the tag is available in the Json, not if there is any error included. So to fix this issue I propose to change the code to check if there is an error in the list:
`if (jsonResponse['errors'] != null && jsonResponse['errors'].value.size>0) {`

**Query used in the test**
```
String query = """
query user(\$userId:Long) {
  user (id: \$userId) {
    userName
  }
}
""".replaceAll('\n', ' ');
```

**Screenshot**
![image](https://user-images.githubusercontent.com/7767910/41889974-b6a7e9a8-78e3-11e8-979e-bef5f451762a.png)

Thanks,
Best regards.

**Comment by eusdima** [comment]
Do you know if `jsonResponse['errors'].value` Always returns an array?

**Comment by fabricio-godoi** [comment]
@eusdima In my simple examples it does. I could no perform any complex procedures yet.

**Comment by fabricio-godoi** [comment]
@eusdima
Using `if (jsonResponse['errors'] != null && jsonResponse['errors'].length > 0) {` seens to fix the problem.
Thanks!
