### ISSUE TITLE
Can't act on errors without Mutation widget rebuilding.

### ISSUE THREAD

**Issue by kasonde** [zino-app/graphql-flutter#216]
**Describe the bug**
Since there is no documentation on your lib I'll file this as a bug. I'm trying to run a mutation but after that mutation runs, I'm trying to show a dialog with an error message. Because your error response is within the build function, I can't act on it only once. The dialog will show as many times as the Widget rebuilds. When I change routes, it will rebuild and show a dialog if error != null. Is there any way to get around this?

**To Reproduce**
1. Create a mutation, then after a mutation has an error, try to show a dialog. Change routes and notice that the Dialog shows again.

**Expected behavior**
Dialog only shows once. Or at least a complete function for the whole operation (with errors) not just successful response.

**Additional context**
This is for a login registration flow.

**Comment by micimize** [comment]
are you on the `next`? You might try depending on the latest:
```
   git:
     url: https://github.com/zino-app/graphql-flutter.git
     ref: next
```
With the latest, using [`onCompleted`](https://github.com/zino-app/graphql-flutter/blob/next/example/lib/graphql_widget/main.dart#L223) should avoid this. Also, having your `Mutation` below your routes would as well.

If errors remain after a valid response, or if `Mutations` that should have different results share errors, that would be a bug.

**Comment by kasonde** [comment]
okay thanks. I'll give that a try. If it doesn't work, I'll reopen the issue.
