### ISSUE TITLE
Mutation is not triggered

### ISSUE THREAD

**Issue by todorstoev** [zino-app/graphql-flutter#218]
Hello guys, i have a problem with the Mutation Widget.  I attached the runMutation callback on a button pressed event but its like the function its not being executed and dont trigger the API call.

This is my code , any help would be appreciated

![Untitled](https://user-images.githubusercontent.com/24528337/56099543-199b3780-5f17-11e9-803a-622834a3f38d.png)

**Comment by mainawycliffe** [comment]
What version are you running?

**Comment by todorstoev** [comment]
Hello , the version is graphql_flutter: ^0.9.5  . This is the repo 
https://github.com/bloodrush/projectZ

**Comment by mainawycliffe** [comment]
It looks like you are relying on a different folk of this package:

```
flutter_graphql: ^1.0.0-rc.1
```
(
https://github.com/bloodrush/projectZ/blob/2c04329fa1a9316836f6e4a51657e38fa871596c/pubspec.yaml#L29)

It would be better of if you raised the issue there or switched to this package here https://pub.dartlang.org/packages/graphql_flutter/versions/1.0.0-beta.1+1

**Comment by mainawycliffe** [comment]
And from my attempt without changing anything, i tried to login and am getting a valid (error though) response from the graphql server

```
[No such user found: Undefined location]
```

So, it seems to be triggering the API Call on login.

**Comment by todorstoev** [comment]
Sorry about that , because of the error i didnt commited the code.  The whole thing is that im migrating from flutter_graphql to graphql_flutter. The flutter_graphql implementation works fine, problems came when i changed.  I commited the new code now using graphql_flutter:1.0.0-beta.1+1 as u adviced. Now im making the call but i got failed to host lookup. Any idea on this one ? Thanks a lot in advance.

**Comment by mainawycliffe** [comment]
From my own experience, that happens when you have a problem with network connectivity. On my end, everything seems in order after the update, am getting the No such user found error above, which indicates  it works as expected.

**Comment by todorstoev** [comment]
Nice yes it works as expected , thanks for the help!
