### ISSUE TITLE
raw_operation_data.dart breaks AppSync Queries

### ISSUE THREAD

**Issue by bobwiller** [zino-app/graphql-flutter#222]
I have been spiking various scenarios against a simple AWS AppSync endpoint using the 'next' branch.  I have authentication working against Cognito w/help of the amazon_cognito_identity_dart package.  Here is my extremely simple GraphQL query:

`const readPets = '''{
  listPets(limit: 5) {
    nextToken
    items {
      id
      name
      description
    }
  }
}
''';`

If I call `QueryResult data = await client.query(QueryOptions(document: readPets));` using the 
1.0.0-beta.1 release, this query works fine.  The request body looks like this:

`{"operationName":null,"variables":null,"query":"{\n  listPets(limit: 5) {\n    nextToken\n    items {\n      id\n      name\n      description\n    }\n  }\n}\n"}`

However if I get latest, this query breaks, as what is getting sent across the wire has been changed to:

`{"operationName":"UNNAMED/903347897","variables":{},"query":"{\n  listPets(limit: 5) {\n    nextToken\n    items {\n      id\n      name\n      description\n    }\n  }\n}\n"}`

 And as near as I can tell, the operation name gets forced here in raw_operation_data.dart here:
`  String get operationName {
    // XXX there is a bug in the `graphql_parser` package, where this result might be
    // null event though the operation name is present in the document
    _operationName ??= getOperationName(document);
    _operationName ??= 'UNNAMED/' + document.hashCode.toString();
    return _operationName;
  }`

So, either I am doing something wrong w/my query, or we shouldn't force an operationName?

Let me know if there is any way I can help.
Thanks,
Bob

**Comment by mainawycliffe** [comment]
There are some differences between the version on dart, master and the next branch branch. Try updating to the latest next branch, it was pushed yesterday and see if it works.

**Comment by bobwiller** [comment]
I can confirm this is still an issue w/get latest.  AppSync will fail if you send it an operationName.

**Comment by bobwiller** [comment]
Sigh, I take this back -> figured out if I change my query it works as designed....sorry.

**Comment by lenaschimmel** [comment]
So I'm running into a similar problem, using version 1.0.0+4. I'm using a backend powered by Apollo-Server 2.4.8 and it also doesn't like the generated names. The error is:

    [Unknown operation named "UNNAMED/242467548".: Undefined location]

If I comment out [Line 34](https://github.com/zino-app/graphql-flutter/blob/59c838e511e4d4c2b63d839da34492e6c4cadc34/lib/src/core/raw_operation_data.dart#L34), it works fine.

To be honest, I don't understand why this only became a problem after updating to Dart 2.3.0, because the code line is there since 6 months.

**Comment by micimize** [comment]
should be fixed by #276, along with #235
