### ISSUE TITLE
Cannot install the pub

### ISSUE THREAD

**Issue by honkevin** [zino-app/graphql-flutter#225]
When I add the pub bu typing "flutter packages get"
I got the following message.

The current Dart SDK version is 2.1.2-dev.0.0.flutter-0a7dcf17eb.

Because <App name> depends on graphql_flutter >=1.0.0 which requires SDK version >=2.2.0 <3.0.0, version solving failed.

It would be great if you can point me the right direction to solve this problem. Thanks!!!!

**Comment by mainawycliffe** [comment]
Hi, this needs dart Dart 2.2.0, which means for now until the next flutter release you need to change the channel to beta.

You can do so by running the following command:

`flutter channel beta`

**Comment by honkevin** [comment]
It works!! Thanks a lot!!
