### ISSUE TITLE
Refactoring some parts of the client to allow easier development of new features

### ISSUE THREAD

**Issue by eusdima** [zino-app/graphql-flutter#226]
I want to get myself involved more into the development of the library and push some of my ideas about how to make it speedy enough to take advantage of the low latency 5G boom that is coming. 
I have a few steps I want to follow for this:

- [ ] Commenting on the current changes and discussing about what micro tweaks can be added to improve the performance / code quality
- [ ] Accepting suggestions about what should change to get to the next level
- [ ] Drafting a TODO list followed by a PR 
- [ ] Feedback and PR is merged 

### widgets
 - [x]  /cache_provider

 It's nice to see how my initial code for saving and restoring the cache has evolved. I think it should allow the user the ability to fine-tune its behaviour. Also having a shadow cache, as react does with the DOM, should allow for quicker cache saving and maybe doing it in the background so the keys in the cache are not discarded on an accidental close of the application.

 - [x]  /graphql_consumer and /graphql_provider
 Straightforward context implementation

 - [x]  /mutation

https://github.com/zino-app/graphql-flutter/blob/e8fa8466eb621b4ed25e958805e27460ed1fa680/lib/src/widgets/mutation.dart#L15
 What if I don't want optimistic result in my RunMutation function

 The optimisticUpdate is awesome but I think it takes too much of the mutation logic and it should be decoupled from it to allow "optimism-less" mutations

 - [x]  /query

https://github.com/zino-app/graphql-flutter/blob/e8fa8466eb621b4ed25e958805e27460ed1fa680/lib/src/widgets/query.dart#L37
 Why is the cache policy overwritten?

https://github.com/zino-app/graphql-flutter/blob/e8fa8466eb621b4ed25e958805e27460ed1fa680/lib/src/widgets/query.dart#L72
 Should we allow the choice of shallow vs deep comparison ?

https://github.com/zino-app/graphql-flutter/blob/e8fa8466eb621b4ed25e958805e27460ed1fa680/lib/src/widgets/query.dart#L86
  Should the user be allowed to specify initialData value for a query?

https://github.com/zino-app/graphql-flutter/blob/e8fa8466eb621b4ed25e958805e27460ed1fa680/lib/src/widgets/query.dart#L12
 What if we don't enforce the callback as the second parameter and you have the option to only have 'result'

 - []  /subscription

**Comment by micimize** [comment]
* `/mutation` & `refetch` - The `optimisticResult` is optional, and `null`s are ignored by the manager. But yeah, I'm not sure loading so much in function signatures is good/idiomatic. maybe we should inject "controller" class instances for query and mutation for calls like
```dart
mutationController
  ..optimisticResult = expected
  ..variables = <String, Object>{}
  .run();
```
I don't think we can do something like `Union<JustResultCallback, ResultWithRefetch>` in dart.

We'll want to break these high level actionables into separate issues - same with whatever we decide from the review. I do think making the client non-flutter usage standalone (#203) will make things a lot more manageable

**Comment by truongsinh** [comment]
1 part I would definitely recommend is to have proper test coverage (unit and widget level)

**Comment by micimize** [comment]
calling this closed with v4 as this was kind of a planning issue. I think reworking some of the `scheduler` and `core` logic could still make sense and apis could always be better but would make more sense as new more focused issues
