### ISSUE TITLE
Subscription support

### ISSUE THREAD

**Issue by juicycleff** [zino-app/graphql-flutter#23]
Is there any short term plan for subscription support yet? If yes how soon else a good direction to start off in implementing the support would be awesome. I am not strong in dart yet, but I can take a plunge. Thank you guys. Graphql support for flutter was a big plus for me making my decision to use flutter

**Comment by cal-pratt** [comment]
+1 on this. I am interested in creating a front-end client for my real-time application in Flutter, however, I need the ability to manage `GraphQL` subscriptions.

Have any timelines been discussed for implementing this feature? If there is a known path forward I would also be interesting in helping out.

**Comment by HofmannZ** [comment]
It's not a very high priority item for our team, but feel free to open a PR. We will start implementing subscriptions once most of the core features are more mature.

**Comment by juicycleff** [comment]
Cool

**Comment by cal-pratt** [comment]
@juicycleff There's a basic `Subscription` `Widget` available to test out now! :)
