### ISSUE TITLE
Refetch should be optional

### ISSUE THREAD

**Issue by Kyle-Mendes** [zino-app/graphql-flutter#234]
In one of the recent releases `refetch` was added to the `builder` on `queries`.

This is a great addition, but `refetch` should definitely default to `{ VoidCallback refetch }` so that we don't need include it on every single Query.

**Comment by micimize** [comment]
Do you mean it's annoying to have to add `refetch` into your `builder` arguments? If so, I agree, I'm just not sure what the better way to do it would be.

There isn't a "union typedef" in dart, so we can't make an api that takes "either a function with a `refetch` argument, or one without".

We could maybe add multiple `builder` params, or multiple widgets, but I'm mostly inclined to wait a while and see if dart implements a discriminated union type.

I'd recommend adding a small point-free helper to your code, something like:
```dart
typedef SimpleQueryBuilder = Widget Function(QueryResult result);
QueryBuilder justResults(SimpleQueryBuilder builder) =>
  (QueryResult result, { VoidCallback refetch }) =>
      builder(result);

//...
builder: justResults((QueryResult result){})
```

**Comment by Kyle-Mendes** [comment]
Couldn't `refetch` be optional? And then , in `builder` `graphql_flutter` could check `if (refetch != null)`? Or am I misunderstanding the issue

**Comment by micimize** [comment]
fundamental limitation of `dart` – we might rethink this api in the future though
