### ISSUE TITLE
Implement 'Keep a Changelog'

### ISSUE THREAD

**Issue by HofmannZ** [zino-app/graphql-flutter#237]
When releasing a new version it's always hard to deliver a proper changelog. [Keep a changelog](https://keepachangelog.com/en/1.0.0/) is a proposal on how we can deliver a consistent and complete changelog.

I propose we implement it in this repo. I would require the following steps:
- [ ] Refactor the changelog to the [keep a changelog spec](https://keepachangelog.com/en/1.0.0/).
- [ ] Add update the [pull request template](https://github.com/zino-app/graphql-flutter/blob/master/.github/PULL_REQUEST_TEMPLATE.md) to mention the changelog requirements.

**Comment by mainawycliffe** [comment]
Is it possible to automatically parse changes from PRs, so we can have a section for change log in the PR?

**Comment by HofmannZ** [comment]
For PRs; I’m not sure, but for [branches it does work](https://github.com/semantic-release/semantic-release). It does requires better commit messages so that’s a possible bottle neck.


The flow would be:
- Merge to beta branch: create a beta Github version tag.
- Merge to master: create a stable Github version tag.

Then we can add a CI trigger on git tags to do a `pub publish`.

The only problem is that it can’t deal with the `+1` in the Dart/Flutter version tags.

So it might not be the best fit..

**Comment by micimize** [comment]
closed long ago
