### ISSUE TITLE
Unknown operation, undefined location with FutureBuilder and GraphQLClient

### ISSUE THREAD

**Issue by felixvdh** [zino-app/graphql-flutter#243]
So I Just started to set up a graphql client. For now I use a public [api](https://bahnql.herokuapp.com). I am planning on separating the api code from my views, via a bloc, so I am not using the Widgets provided by this library.

I set up the client:
```dart
final GraphQLClient _client = GraphQLClient(
    cache: InMemoryCache(),
    link: HttpLink(
      uri: 'https://bahnql.herokuapp.com/graphql',
    ) as Link,
  );
```

The query:
```dart
class Queries {
  static const String station =
      r'''{ stationWithEvaId(evaId: 8000105) { name } }''';
}
```

```dart
  Future<QueryResult> get station async =>
      await _client.query(QueryOptions(document: Queries.station));
```
And a Widget:

```dart
FutureBuilder<QueryResult>(
            future: _api.station,
            builder:
                (BuildContext context, AsyncSnapshot<QueryResult> snapshot) {
              switch (snapshot.connectionState) {
                case ConnectionState.none:
                case ConnectionState.active:
                case ConnectionState.waiting:
                  return Center(child: CircularProgressIndicator());
                case ConnectionState.done:
                  if (snapshot.hasError) {
                    return Center(child: Text('Error : ${snapshot.error}'));
                  } else {
                    return Center(child: Text(snapshot.data.data.toString()));
                  }
              }
            },
          )
```
What I get is an `Unknown operation named "UNNAMED/224188357".: Undefined location`.
![Screenshot from 2019-04-26 11-53-34](https://user-images.githubusercontent.com/16648580/56799932-27f02a00-681a-11e9-82e5-3ddcf75c13aa.png)

Can anyone help me with that?

**Comment by felixvdh** [comment]
Alright I got It, It is linked to #235. I was expecting to be able to omit the `query` keyword in my query string. Which is not the case appearantly.

**Comment by mahamedh** [comment]
Hi member's,
how can i do this with the return result of mutation. Suppose let's think  mutation returns user id and email i need a navigation if user found.how can i do they above task using future in flutter.
