### ISSUE TITLE
Error reporting in query

### ISSUE THREAD

**Issue by chenxianqi** [zino-app/graphql-flutter#249]
[No operation named "UNNAMED/123856237": Undefined location]

**Comment by eusdima** [comment]
@chenxianqi Can you use the bug report template? Otherwise it's impossible to analyse what happen and why.

**Comment by chenxianqi** [comment]
> @chenxianqi Can you use the bug report template? Otherwise it's impossible to analyse what happen and why.

Hey, I've found the problem, query {} can't be written like this.The problem is closed. 3Q
