### ISSUE TITLE
Consider sync version number from CI

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#250]
[Circle CI is going to be in charge of releases](https://github.com/zino-app/graphql-flutter/pull/247/files#r279200394), but I think it would still be good to have a proper version number in pubspec via an [automated commit](https://support.circleci.com/hc/en-us/articles/360018860473-How-to-push-a-commit-back-to-the-same-repository-as-part-of-the-CircleCI-job)

**Comment by HofmannZ** [comment]
Fixed in #247
