### ISSUE TITLE
Dart does not like when I import FetchResult and Operation from the package

### ISSUE THREAD

**Issue by xxhenglyxx** [zino-app/graphql-flutter#257]
I am trying to implement my own `CustomLink` which extends from the `Link` from this package and follow from this https://github.com/zino-app/graphql-flutter/issues/173. When I try to import `FetchResult` and `Operation` from the package, dart complaints about not to import implementation from other packages.

**Comment by mainawycliffe** [comment]
How are you importing the packages? Can you try something like:
 
```dart
import 'package:graphql/internal.dart';
```

**Comment by xxhenglyxx** [comment]
@mainawycliffe Hi, thanks for the comment. importing the `package:graphql/internal.dart` removed the dart warning. I was importing them from inside the `graphql_flutter` lib, i am sorry I forgot what was the path and my editor autocomplete does not show it this time, so weird, but it was something like inside the package `../link/operation.dart`
