### ISSUE TITLE
Create contributor guidelines

### ISSUE THREAD

**Issue by HofmannZ** [zino-app/graphql-flutter#262]
The automated CD requires us to use [Angular style](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) commit messages. This needs to be communicated to all contributors. So we should add some contributor guidelines.

**Comment by mainawycliffe** [comment]
Should we copy the one from [Angular ](https://github.com/angular/angular/blob/master/CONTRIBUTING.md)and make the necessary changes?

**Comment by HofmannZ** [comment]
@mainawycliffe Yeah, that might actually be the quickest way to do it.

**Comment by mainawycliffe** [comment]
I will create a pull request, alongside a change log for the GraphQL client package

**Comment by mainawycliffe** [comment]
I think this should be close now.

**Comment by HofmannZ** [comment]
#287
