### ISSUE TITLE
Map QueryResult to dart model object

### ISSUE THREAD

**Issue by jaumard** [zino-app/graphql-flutter#265]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to use models instead of just Map, because in big payload it become really messy ^^ 

**Describe the solution you'd like**
having some code generation "fromMap" would be nice, we can then use `client.query<MyQueryResultMapped>(...)` that will internally call fromMap 

**Describe alternatives you've considered**
Don't see any other 

It will make usage of this lib even move convenient :)

**Comment by micimize** [comment]
This is planned eventually and tracked in #26, but for now you can check out [graphql-to-dart](https://github.com/micimize/graphql-to-dart)  and the [`TypedQuery`](https://github.com/micimize/graphql-to-dart/blob/master/example/lib/episode.dart#L47) usage in the example.

Still pretty janky though, and I don't have much time to work on it.
