### ISSUE TITLE
Need of flutter?

### ISSUE THREAD

**Issue by theKAKAN** [zino-app/graphql-flutter#27]
I was trying to make a CLI client that would require the use of GraphQL. But, I don't see the need of this library to use Flutter.
Would it be possible to remove Flutter as a dependency or something is required for this library to work, which uses Flutter?

I'll try removing Flutter as a dependency, but that would take some time( _depending on how much free time I get_ ). So, any other ideas to get this working without Flutter or has anyone already done it?

P.S:- I'll soon try it with Flutter, 'cause this library seems pretty amazing 😃

**Comment by HofmannZ** [comment]
Our package provides Flutter widgets for easy interaction with the Client. We are already planning to split the package into multiple smaler ones to allow for more modular code. The core package should then be usable without Flutter.
