### ISSUE TITLE
Version conflicts with other libs, update rxdart to ^0.22.0

### ISSUE THREAD

**Issue by NhaPCS** [zino-app/graphql-flutter#270]
**Describe the bug**
I am using bloc and graphql_flutter, but bloc 0.13.0 is using rxdart ^0.22.0, graphql is using rxdart ^0.21.0.

**Additional context**
Please update rxdart to 0.22.0!

Thanks and best regards!

**Comment by dbrb** [comment]
Submitted a PR for this https://github.com/zino-app/graphql-flutter/pull/268

In the meantime, if you're in a rush you can use my fork.

**Comment by NhaPCS** [comment]
@dbrb thanks :))

**Comment by micimize** [comment]
closed by #275
