### ISSUE TITLE
Can I refetch outside of the Query() block in another part of the context?

### ISSUE THREAD

**Issue by CalebJTSmith** [zino-app/graphql-flutter#272]
I have a Query() that renders a listview of items. In the AppBar, I have an action for adding a new item that sends a mutation back to the server. Is there a way to force a refetch on the query with a mutation outside of the Query()? I didn't really want to setup a specific state for a small query.

**Comment by mainawycliffe** [comment]
There are a number of ways i can think of, one is subscriptions to push data down from the server, any changes would be picked up by the listener. The second option is to use polling, and i think the easiest option, where your query will poll the server on interval.

**Comment by CalebJTSmith** [comment]
Subscriptions was my first big stab - I was really struggling (from a server perspective) to get that all flowing right, so I wanted to explore some other ways to handle it in the meantime. I like the idea of changing the polling interval. I might try to set that number dynamically, flip it down to 1, then flip it back to a higher interval after the first refetch.

**Comment by mainawycliffe** [comment]
I still think you should try and implement a state management solution, something like inherited widget or scoped model. This would allow you to fetch the query when you need to, like on mutation, while avoiding to constantly poll the server for changes.

**Comment by CalebJTSmith** [comment]
I agree - Thanks for the tips! I wanted to make sure I wasn't missing something obvious first, so I'm glad I wasn't too far off track.
