### ISSUE TITLE
How to update client after 2-3 page??

### ISSUE THREAD

**Issue by anirudhsharma392** [zino-app/graphql-flutter#274]
I have made graphqlprovider in main but after 2-3 screen i want to change the client in graphqlprovider of main. can i do it with GraphQL consumer??
if yes, how??

return GraphQLConsumer(
                  builder: (GraphQLClient client){
                    client=GraphQLClient(cache: InMemoryCache(), link: httpLink);
                    return Season();
                  },

**Comment by micimize** [comment]
You would have to use a callback, `InheritedWidget`, or other external logic. But, from what I can understand from your code, what you really want to do authenticate below the client.

If so, I'd recommend something like:
1. saving the token in the `update` of your `AuthenticationMutation` to the cache under `"@authentication_token"`
2. where you define the cache, define `getToken` for an `AuthLink` (you may have to make a custom, optional-token link):
```dart
final cache = NormalizedInMemoryCache(
  dataIdFromObject: uuidFromObject,
);
// pass this to `AuthLink`
String getToken => cache.read("@authentication_token");
```
3. redirect to the authenticated route in `onCompleted`

Hopefully that's helpful - if you figure it out, contributing an example would be much appreciated 😄 

In the future, please use code blocks to format your snippets, and put more effort into formulating your question clearly
