### ISSUE TITLE
Consider not mutating client

### ISSUE THREAD

**Issue by abs-zero** [zino-app/graphql-flutter#28]
## Problem
I think the way client is being initialized by mutating global variable inside the library is bad and confusing, and will eventually bite someone. I recently, out of habit of making everything final, made the client final and wasted time figuring out what was wrong.

## Proposed Solution
Let users create their own client and add methods like query and mutation in it like Apollo Client does. Also let the user specify token in the constructor itself instead of setting it later.

**Comment by HofmannZ** [comment]
There is already a PR open implementing it #24, based on this issue #16.
