### ISSUE TITLE
getting error in the code given below after updating the flutter to Flutter 1.5.4-hotfix.2 .

### ISSUE THREAD

**Issue by anirudhsharma392** [zino-app/graphql-flutter#285]
can't assign httpLink to link.

static HttpLink httpLink = HttpLink(
    uri: " .."
  );
  ValueNotifier<GraphQLClient> client1 = ValueNotifier(
    GraphQLClient(cache: InMemoryCache(), link: httpLink//error is here
),
  );

error: The argument type 'HttpLink' can't be assigned to the parameter type 'Link'. (argument_type_not_assignable

**Comment by mainawycliffe** [comment]
You need to cast the error `httpLink as Link`
`
