### ISSUE TITLE
How do I find the key to write to cache on mutation?

### ISSUE THREAD

**Issue by CalebJTSmith** [zino-app/graphql-flutter#291]
I've tried a few different things.. but im stumped on how to handle this. I have a basic query that is returning a list of items and caching with NormalizedInMemoryCache. I have a mutation that adds an item to that list - the result returns back the same list of data.

```
cache: NormalizedInMemoryCache(
          dataIdFromObject: _typenameDataIdFromObject,
        ),

...
String _typenameDataIdFromObject(Object object) {
    if (object is Map<String, Object> && object.containsKey('__typename') && object.containsKey('id')) {
      return "${object['__typename']}/${object['id']}";
    }
    return null;
  }
```
```
query GroceryLists {
    groceryLists {
      id,
      name,
    }
  }
```
```
mutation DeleteGroceryList(\$id: ID!) {
    deleteGroceryList(id: \$id) {
      message
      success
      lists {
        id,
        name
      },
    }
  }
```
I am trying to find the key for the cache so I can override the current cached list of "lists" and add the new ones. Does anyone have advice on next steps here?

**Comment by CalebJTSmith** [comment]
I ended up going to route of utilizing `bloc` state instead following examples. Ended up being the smoothest route anyway so im pleased with it.

**Comment by mainawycliffe** [comment]
@CalebJTSmith Hi, its great you found a solution. Would you mind contributing an example, we are still short on those.
