### ISSUE TITLE
I want to pass authToken in header with clientSocket to make successful connection.But getting error

### ISSUE THREAD

**Issue by anirudhsharma392** [zino-app/graphql-flutter#322]
```
ValueNotifier<GraphQLClient> clientFor({
      String uri =
          "http://staginggraphql-xxxxxx/graphql",
      String subscriptionUri =
          "ws://staginggraphql-xxxxxxx/graphql",
    }) {
      Link link = HttpLink(uri: uri) as Link;
      if (subscriptionUri != null) {
        final WebSocketLink websocketLink = WebSocketLink(
          url: subscriptionUri,
          config: SocketClientConfig(
            autoReconnect: true,
            inactivityTimeout: Duration(seconds: 30),
          ),
        );

        link = link.concat(websocketLink);
      }

      return ValueNotifier<GraphQLClient>(
        GraphQLClient(
          cache: InMemoryCache(),
          link: link,
        ),
      );
    }
```
Error:
```
I/flutter (24451): data: {type: connection_error, payload: {message: Cannot read property 'authToken' of undefined}}
I/flutter (24451): done
I/flutter (24451): Disconnected from websocket.
I/flutter (24451): Scheduling to connect in 5 seconds...
```
I am making this websocket  for subscription.
Really frustrated.
please help;

**Comment by huang12zheng** [comment]
@anirudhsharma392 If it's not particularly simple,I think it provides a minimal reproducible Repositories being useful.

**Comment by truongsinh** [comment]
Please see https://stackoverflow.com/a/4361358/1326678

> only the path and protocol field can be specified (to connect to a websocket, not headers)

**Comment by anirudhsharma392** [comment]
So, do i need make connection open. I mean without any authentication for connection.

**Comment by anirudhsharma392** [comment]
Can i sending it as part of a query parameter in URL or  send the authToken within payload.

**Comment by truongsinh** [comment]
How would have you done it with a webapp/JavaScript file?

**Comment by anirudhsharma392** [comment]
i got this just need to pass in  init payload,Thanks though

final WebSocketLink socketLink = WebSocketLink(
      url:'ws://staginggraphql-xxxxxxx/graphql',
      config: SocketClientConfig(
      initPayload:{"authToken":"${centralstate.GraphQLToken}"},
      autoReconnect: true,
      inactivityTimeout: Duration(seconds: 30),
    ),
    );


    ValueNotifier<GraphQLClient> client = ValueNotifier(
      GraphQLClient(
          cache: InMemoryCache(), link: socketLink as Link),
    );
