### ISSUE TITLE
how to set timeout for graphql request

### ISSUE THREAD

**Issue by codewine** [zino-app/graphql-flutter#327]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by micimize** [comment]
There's no builtin API for this, but a link could be made similarly to [`apollo-link-timeout`](https://github.com/drcallaway/apollo-link-timeout)

**Comment by jerryzhoujw** [comment]
It seems no `TimeoutLink` here.

**Comment by canisterism** [comment]
You can set timeout on Future.timeout method.
https://api.dart.dev/stable/2.8.4/dart-async/Future/timeout.html

```
client
  .query(options)
  .timeout(
    const Duration(milliseconds: 100),
    onTimeout: () {
      throw Exception;
    }
  );
```

**Comment by jifalops** [comment]
There's no way to do this from the Query widget.

**Comment by abarrettPS** [comment]
any change on this issue? Would really like to be able to set timeouts in the Query widget.

**Comment by vincenzopalazzo** [comment]
>any change on this issue? Would really like to be able to set timeouts in the Query widget.


Too old to be in our todo list, please open a issue with all the information needed

**Comment by HarikiRito** [comment]
For anyone here looking for a solution. Here is my implementation for the custom request timeout link
https://gist.github.com/HarikiRito/7c275a6a9081fad7d75cf8ac0f47adfd

**Comment by Neelansh-ns** [comment]
https://gist.github.com/Neelansh-ns/7cfa1e3fec10682547161e234675a3ef

This is an implementation of ```HttpTimeoutLink```, it stops any further events from being emitted to the stream.

Unlike the above gist, when adding a timeout to a stream, the event to be yielded will wait for the final overridden request function to be completed with error and then yield the TimeoutException Event. The error thrown from the overridden request function would go unhandled.

**Comment by Mukul-Ronin** [comment]
why not use queryTimeout

**Comment by PhantomRay** [comment]
use `queryRequestTimeout`

```dart
GraphQLClient(
      cache: GraphQLCache(),
      link: _getLink(),
      defaultPolicies: DefaultPolicies(query: Policies(fetch: FetchPolicy.noCache)),
      queryRequestTimeout: _QUERY_REQUEST_TIMEOUT, // default to 5 sec
    );
```

**Comment by Mukul-Ronin** [comment]
> use `queryRequestTimeout`
> 
> ```dart
> GraphQLClient(
>       cache: GraphQLCache(),
>       link: _getLink(),
>       defaultPolicies: DefaultPolicies(query: Policies(fetch: FetchPolicy.noCache)),
>       queryRequestTimeout: _QUERY_REQUEST_TIMEOUT, // default to 5 sec
>     );
> ```

exactly
