### ISSUE TITLE
Ability to set default Fetch-policy for all query requests

### ISSUE THREAD

**Issue by milind-mevada-stl** [zino-app/graphql-flutter#334]
I see default fetch policy for Query is `FetchPolicy.cacheFirst`.

How we can set default `fetch-policy` for Query requests? I don't want to to change at each Query requests.

**Comment by micimize** [comment]
This feature doesn't exist but is feasible

**Comment by serendipity1004** [comment]
@micimize 
How about receiving `QueryOptions` from below

https://github.com/zino-app/graphql-flutter/blob/519381cd1c57515fd26cedb33c68a68d563a6eac/packages/graphql/lib/src/graphql_client.dart#L17-L25

and expose it as a getter. Then when setting `WatchQueryOptions` below, get the default values provided from client and apply to `_options` getter if policy had not been provided in the widget?

https://github.com/zino-app/graphql-flutter/blob/519381cd1c57515fd26cedb33c68a68d563a6eac/packages/graphql_flutter/lib/src/widgets/query.dart#L38-L63

**Comment by micimize** [comment]
`defaultPolicies` handled this in #398
