### ISSUE TITLE
Is there a way to update SocketClientConfig options?

### ISSUE THREAD

**Issue by EugenePisotsky** [zino-app/graphql-flutter#338]
Hello,

It's possible to send token to the server passing it through `initPayload`, but.. how to update it, when token is expired and I want to update it?

Maybe possible `initPayload` to be a function? Something like this:

```dart
SocketClientConfig(
    ...
    initPayload: () async => ... get token here
)
```

So I can just manually reconnect to refresh it.

**Comment by micimize** [comment]
init payload has since become a `FutureOr Function()` – I think there are other issues around that address  error handling and refresh but comment if there's still an issue/questions (or come by the discord linked in the readme)

**Comment by diegoveloper** [comment]
any way to have a `StreamController` like we have in `getToken` for `AuthLink` ?

**Comment by micimize** [comment]
@diegoveloper I don't know what you mean, but there is a `onConnectOrReconnect` option for the `SocketClientConfig` that allows one to do arbitrary things with the websocket after connections are established
