### ISSUE TITLE
graphql_flutter return LazyCacheMap, built_value deserializeWith JSON String, how to make them work together

### ISSUE THREAD

**Issue by jerryzhoujw** [zino-app/graphql-flutter#344]
`graphql_flutter` return `LazyCacheMap`, `built_value` `deserializeWith` `JSON String`,  how to make them work together.

 1. I use `graphql_flutter` to fetch data, and response give the result data as `LazyCacheMap`.
 2. And using `built_value` for data model & data serialization, but since `deserializeWith` working with `JSON String`.

What's the best way to work with them together ?

- Should I just convert `LazyCacheMap`'s data of to `String` and call  `deserializeWith` ?
- should I use other serialization pubs ?

I currently handle JSON response like this bellow:
```dart
if (result is LazyCacheMap) {
      List<dynamic> records = result['records'];

      records.forEach((record) {
        Book book = Book((b) {
          b.id = record['id'];
          b.title = record['title'];
          Author auth = Author((b) {
            b.id = record['auth']['id'];
            b.name = record['auth']['name'];
            return b;
          });
          b.auth = auth.toBuilder();
          return b;
        }
       BooklistState.main..add(book);
}
```

**Comment by micimize** [comment]
In [`graphql-to-dart`](https://github.com/micimize/graphql-to-dart/blob/master/example/lib/starwars_graphql_serializers.dart) I use `json_serializable`. I haven't used `built_value`

**Comment by micimize** [comment]
Closing this as its mostly a support question
