### ISSUE TITLE
Undefined Location null error when querying

### ISSUE THREAD

**Issue by dali546** [zino-app/graphql-flutter#345]
I've looked through other issues but can't find a solution. When I am making a query with my client, i get an error where all data is null

**To Reproduce**
```dart
// globals.dart
GraphQLClient client;
```
```dart
// main.dart
void main() async {
  ...
  HttpLink link = HttpLink(uri: "http://127.0.0.1:8000/graphql");
  client = GraphQLClient(
    cache: InMemoryCache(),
    link: link,
  );
  runApp(AppComponent(store: store));
}
```
I am using Flutter BLoC so i am calling the query in my BLoC method
```dart
loadEvents() async {
    try {
      QueryResult data = await client
          .query(QueryOptions(document: getPosts));
      print(data.data);
    } catch (e) {
      print(e);
    }
  }

const getPosts = '''
      query {
        event(id:5) {
            title
            description
            user {
              profile {
                forename
              }
            }
        }
      }
      ''';
```
I have tried both with and without ValueNotifier and with and without wrapping MaterialApp in a GraphQLProvider. same result

**Expected behavior**
I expect it to work? and produce the results from my graphql endpoint. i used PHPs GraphQL Playground with the exact same query and it pulled results... not sure what im doing wrong

**Screenshots**
![image](https://user-images.githubusercontent.com/35352237/59965987-79145580-950d-11e9-837b-43a631fd903b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Smartphone (please complete the following information):**
 - Device: OnePlus One
 - OS: Android Pie
 - Version: 9.0

**Additional context**
I am using this in conjunction with the BLoC pattern. so I dont want to make requests withing my UI widgets.

**Comment by micimize** [comment]
See if the result `hasErrors` or is `loading`

**Comment by dali546** [comment]
Never mind.
A simple fact of knowing that localhost on my Android device does not mean my PC

**Comment by dali546** [comment]
#186 is similar
