### ISSUE TITLE
Subscription does not emit after reconnect to Websocket

### ISSUE THREAD

**Issue by fdh-cap3** [zino-app/graphql-flutter#356]
The `Stream` returned by  the `GraphQLClient`'s `subscribe` method does not emit data after a successfull reconnect. 

There is neither of `onData`, `onError` ,`onCancel` nor `onDone` firing, so there is no way to manually reconnect to the stream without doing so periodically, which is frustrating.

With successfull reconnect, as stated above I mean, that the following logs are present:
```
18:22:11.237 157 info flutter.tools I/flutter (32630): Disconnected from websocket.
18:22:11.237 158 info flutter.tools I/flutter (32630): Scheduling to connect in 1 seconds...
18:22:12.241 159 info flutter.tools I/flutter (32630): Connecting to websocket: wss://[ redacted url ]
18:22:12.897 160 info flutter.tools I/flutter (32630): Connected to websocket.
```
I set the `SocketClientConfig` as follows:

```dart
SocketClientConfig(
          autoReconnect: true,
          inactivityTimeout: null,
          delayBetweenReconnectionAttempts: const Duration(seconds: 1),
        )
```

**Comment by EugenePisotsky** [comment]
I met the same issue. Also would be nice to add callback to detect that connection is lost, something like `onDisconnected`.

**Comment by micimize** [comment]
This is older than I thought. If it is still an issue on `4.0.0-beta` let me know

**Comment by temirlanalmassov** [comment]
> 

I also need it

**Comment by dehypnosis** [comment]
still having same issue

**Comment by vincenzopalazzo** [comment]
closed issue are not monitored anymore
