### ISSUE TITLE
Question: Working with NormalizedInMemoryCache

### ISSUE THREAD

**Issue by tarunt815** [zino-app/graphql-flutter#357]
I'm fairly new to Flutter and GraphQl for that matter and am struggling with working with the NormalizedInMemoryCache. I've scoured the repo issues and the internet but can't figure out how to dereference a cached mutation result. 

I have a mutation that returns a nested 'User' along with its id, name, and email, but when I access results.data['User'] I see: `[@cache/reference, User/<User ID>]`. My question is how do I access the cache so that I can gather the related information (email, name, etc), from this point in my mutation. Any direction would be greatly appreciated. 

Here is my mutation widget:

```
return Mutation(
      options: MutationOptions(document: authenticationMutation),
      builder: (RunMutation signup, QueryResult result) {
        return RaisedButton(
            color: Theme.of(context).primaryColor,
            textTheme: ButtonTextTheme.primary,
            onPressed: () => signup({
                  "email": <>,
                  "password": <>,
                  "name": <>
                }),
            child: Text('Log in'));
      },
      onCompleted: _onCompleted,
      // you can update the cache based on results
      update: (Cache cache, QueryResult result) {
        return cache;
      },
    );
```

**Comment by tarunt815** [comment]
Actually figured this out. You have to perform a cache.read() on the key passed back in the result ([@cache/reference, <Key>]).

**Comment by serendipity1004** [comment]
how did you resollve this? What should I pass into the key as cache.read()?
