### ISSUE TITLE
YOUR PUB.DEV DOCUMENTATION IS OUT OF DATE

### ISSUE THREAD

**Issue by kasonde** [zino-app/graphql-flutter#360]
**Describe the bug**
Hi, I'm adding this here because it's rather urgent. Your documentation on pub.dev is out of date and doesn't work for version two. Things like GraphQLClient seems to have changed to Client and the like. It might be rather misleading to new users of your library as it was for me.

**To Reproduce**
1. Update flutter
2. Create a new app and add this library
3. Follow documentation as it currently is

**Expected behavior**
The code on the documentation will not match what the library actually requires in version 2

**Comment by mainawycliffe** [comment]
Can you please provide more information on what is working and what is not. The documentation may be slightly out of sync, i will create a PR later today on the same.

**Comment by kasonde** [comment]
So far HttpLink isn't what it says to be. GraphQLProvider seems to be Graphqlprovider. GraphQLClient is now Graphqlclient... That's really the only thing I've tried so far.

**Comment by kasonde** [comment]
If you need to know more about what's not working, use the steps provided in the original issue. There might be more than the few ive mentioned.

**Comment by mainawycliffe** [comment]
> So far HttpLink isn't what it says to be. GraphQLProvider seems to be Graphqlprovider. GraphQLClient is now Graphqlclient... That's really the only thing I've tried so far.

I know the docs may be slightly not up to date due to some breaking changes prior release on 2.0, but the Classes you just referenced here haven't change. You can see the example [here](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql_flutter/example/lib/graphql_widget/main.dart) using the same classes and relying on v2.0 of both `[flutter_graphql](https://pub.dartlang.org/packages/graphql)` and `[graphql](https://pub.dev/packages/graphql_flutter)` client.

Can you share the docs you using on pub.dev and try and run the example [here](https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter/example) and see if it works for you.

**Comment by kasonde** [comment]
Let me try them and give you the feedback

**Comment by kasonde** [comment]
@mainawycliffe I'm still experiencing the same issue. Have you tried the steps defined in the original issue?

**Comment by mainawycliffe** [comment]
Did everything and it works as expected, [here](https://github.com/mainawycliffe/flutter_graphql_quick_demo)is the repo i just created. You can test it out and see if it works locally for you. Have you installed the pub packages for your application?

**Comment by kasonde** [comment]
I'm using VSCode as my editor/IDE and that's it. Yes I do have the package installed. I don't know....
When I install flutter_graphql instead, I get compilation errors with information on programming practices and how wrong variable types were used. No intellisense errors, just a whole lot of compilation errors.

**Comment by mainawycliffe** [comment]
This is strange. What about version of Dart, Flutter? Does the example i created work and are you using `flutter_graphql` or `graphql_flutter`? And can you also please share the compilation errors you are getting and if possible the content of you pubspec file. This are the things that will help us nail down the problem.

**Comment by kasonde** [comment]
So here's a log of me using flutter_graphql
```
Launching lib/main.dart on iPhone X in debug mode...

Compiler message:
file:///Users/Richard/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_graphql-1.0.0-alpha.12/lib/src/widgets/subscription.dart:11:3: Error: Function-typed parameters can't specify 'const', 'final' or 'var' in place of a return type.
Try replacing the keyword with a return type.
  final bool loading,
  ^^^^^
file:///Users/Richard/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_graphql-1.0.0-alpha.12/lib/src/widgets/subscription.dart:12:3: Error: Function-typed parameters can't specify 'const', 'final' or 'var' in place of a return type.
Try replacing the keyword with a return type.
  final dynamic payload,
  ^^^^^
file:///Users/Richard/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_graphql-1.0.0-alpha.12/lib/src/widgets/subscription.dart:13:3: Error: Function-typed parameters can't specify 'const', 'final' or 'var' in place of a return type.
Try replacing the keyword with a return type.
  final dynamic error,
  ^^^^^
file:///Users/Richard/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.6.0-alpha.2/lib/cached_network_image.dart:203:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/Richard/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/Richard/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
file:///Users/Richard/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.6.0-alpha.2/lib/cached_network_image.dart:204:32: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/Richard/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/Richard/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      _imageStream.addListener(_handleImageChanged);
                               ^
file:///Users/Richard/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.6.0-alpha.2/lib/cached_network_image.dart:214:34: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/Richard/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Users/Richard/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
file:///Users/Richard/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.6.0-alpha.2/lib/cached_network_image.dart:474:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/Richard/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /Users/richard/work/flutter-apps/zingati/lib/main.dart
Error launching application on iPhone X.
Exited (sigterm)
```
On my machine with your project, the intellisense doesn't seem to be interfering with anything. 

Does it matter if I specify the version number? I always prefer to be on the latest stable version regardless of the refactoring responsibilities that may arise.

**Comment by kasonde** [comment]
Pardon me; here's ```flutter doctor``` output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale en-ZM)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by mainawycliffe** [comment]
I see you using an early version of the extension `flutter_graphql-1.0.0-alpha.12` in your log, please check your `pubspec.lock` file to check version ^2.0 you have, also do a spot check on your lockfile for the versions inside it. If still are prior to 2, try running `flutter pub upgrade` to try and upgrade the dependencies.

**Comment by mainawycliffe** [comment]
> Does it matter if I specify the version number? I always prefer to be on the latest stable version regardless of the refactoring responsibilities that may arise.

Dart uses version constraint to create a dependency graph, this determines which dependencies are installed. But the basic thumb of the rule is that, the latest version that is compatible with other dependencies is installed. I wrote a [post](https://codinglatte.com/posts/flutter/flutter-a-closer-look-at-how-pub-handles-dependency-versions/) on that last week.

**Comment by kasonde** [comment]
After running ```flutter pub upgrade``` all seems well. My mistake was assuming that running ```flutter pub get``` will update all my dependencies for me even when the project has been newly cloned from github. I thought it was a system wide packages update. Thanks for the tip @mainawycliffe.

**Comment by kasonde** [comment]
@mainawycliffe I've just spotted another issue where onComplete in the mutation widget doesn't return a query result. Instead it returns the response data only. This kind of gets rid of the other useful reason to use the onComplete function which is error handling. The return value of the onComplete function is dynamic. Which when an error is deliberately thrown from the server only returns ```null```. Is there a work around aside from using the client in a separate function outside the widget.build function?
