### ISSUE TITLE
Loop WebSocket reconnect

### ISSUE THREAD

**Issue by MarceloRab** [zino-app/graphql-flutter#361]
Why reconnect in looping?

`final HttpLink httpLink = HttpLink(
    uri: "http://10.0.2.2:4000/graphql");  

  final AuthLink authLink = AuthLink(
      getToken: () async =>
          "Bearer --token");

  ValueNotifier<GraphQLClient> client;

     Link link = httpLink as Link;  
      final WebSocketLink websocketLink = WebSocketLink(
        url: subscriptionEndpoint,
        config: SocketClientConfig(
          autoReconnect: true,
          inactivityTimeout: Duration(seconds: 30),    
        ),
      );
      link = authLink.concat(httpLink as Link);
      link = link.concat(websocketLink);

    client = ValueNotifier(
      GraphQLClient(
        cache: InMemoryCache(),
        link: link,
      ),
    );
`

I/flutter ( 4395): Connected to websocket.
I/flutter ( 4395): Disconnected from websocket.
I/flutter ( 4395): Scheduling to connect in 5 seconds...
I/flutter ( 4395): Connecting to websocket: ws://10.0.2.2:4000/graphql...
I/flutter ( 4395): Connected to websocket.
**...**

**Apollo Server** 

const { split } = require('apollo-link');
const { HttpLink } = require('apollo-link-http');
const { WebSocketLink } = require('apollo-link-ws');
const { getMainDefinition } = require('apollo-utilities');
const { SubscriptionClient } = require('subscriptions-transport-ws');
const fetch = require('node-fetch');
const ws = require('ws');

//const uri = "https://node-app-lab-1-js.herokuapp.com/graphql";
//const subscriptionsURI = "ws://node-app-lab-1-js.herokuapp.com/graphql";
const uri = 'http://localhost:4000/graphql';
const subscriptionsURI = "ws://localhost:4000/graphql";
// Create an http link:
const httpLink = new HttpLink({
  uri: uri,
  fetch,
});

const wsForNode = typeof window === "undefined" ? ws : null

const wsClient = new SubscriptionClient(
  subscriptionsURI,
  {
    reconnect: true
  },
  wsForNode
)

const wsLink = new WebSocketLink(wsClient)

// using the ability to split links, you can send data to each link
// depending on what kind of operation is being sent
const link = split(
  // split based on operation type
  ({ query }) => {
    const definition = getMainDefinition(query);
    return (
      definition.kind === 'OperationDefinition' &&
      definition.operation === 'subscription'
    );
  },
  wsLink,
  httpLink,
);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
});

module.exports = client; 

**LOG**

Websocket CONNECTED
Websocket DISCONNECTED
Websocket CONNECTED
Websocket DISCONNECTED
Websocket CONNECTED
Websocket DISCONNECTED

**...**

**Comment by MarceloRab** [comment]
Resolution 

...

`const wsClient = new SubscriptionClient(
  subscriptionsURI,
  {
    reconnect: true,
    reconnectionAttempts: 50,
    lazy: true,
    timeout: 20000,
  },
  wsForNode
);`

AND

...

`const wsLink = new WebSocketLink({
  uri: wsClient,
  webSocketImpl: wsForNode,
  options: {
    lazy: true,
    reconnect: true,
    connectionParams: () => {
      const token = "<token>";
      return {
        headers: {
          Authorization: token ? `Bearer ${token}` : "",
        },
      }
    },
  },
});`

I do not know exactly what it solved: lazy, timeout or reconnectionAttempts?

If anyone knows the answer, please clarify.

**Comment by EugenePisotsky** [comment]
do you use Apollo Server? I had the same problem. Solved it by adding keepAlive:

```javascript
new ApolloServer({
    ...
    subscriptions: {
        path: "/subscriptions",
        keepAlive: 10,
    ...
});
```

**Comment by razorabhu1995** [comment]
@MarceloRab did you manage to solve this issue?

**Comment by micimize** [comment]
the websocket link automatically disconnects on inactivity timeout, and reconnects if the autoreconnect config is set. See discussion in #653 for more info
```dart
SocketClientConfig(
  autoReconnect: true, // false to disable reconnect
  inactivityTimeout: Duration(seconds: 30), // set to 0 to disable timeout
)
```
