### ISSUE TITLE
Subscriptions Reconnect solution

### ISSUE THREAD

**Issue by rullyalves** [zino-app/graphql-flutter#364]
I noticed that graphql_flutter does not have a functional reconnection of subscriptions when the internet connection is interrupted, I created an implementation to take care of that and would like to integrate with the current package, my implementation has already been tested and is fully functional

**Comment by mainawycliffe** [comment]
Fee free to create a PR against beta, follow contributions guidelines [here](https://github.com/zino-app/graphql-flutter/blob/master/CONTRIBUTING.md). Make sure to include tests and if possible update documentation where necessary.

**Comment by bsr203** [comment]
@rullyalves would like to see your implementation. Thanks.

**Comment by kdkul** [comment]
@mainawycliffe @rullyalves any idea when this solution will be available? I am looking for this solution to implement in one of my project. @rullyalves thanks for valuable solution.

**Comment by mainawycliffe** [comment]
@rullyalves are you able to create a PR for this?
