### ISSUE TITLE
Support FetchPolicy.cacheFirst on Query widget

### ISSUE THREAD

**Issue by lucasavila00** [zino-app/graphql-flutter#366]
I'm trying to use the Query widget to query something only if it is not cached but I can't.

If I set the Fetch Policy to cacheFirst I'd like it to be the fetch policy, but since the Query widget [replaces the fetch policy ](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql_flutter/lib/src/widgets/query.dart#L37) to cacheAndNetwork I can't do this.

I don't know why the widget does this but a fix would be to simply remove the code that replaces the fetchPolicy.

**Comment by mainawycliffe** [comment]
Yea, that line does look unnecessary, not sure why it is there.

**Comment by lucasavila00** [comment]
Yes, that's the same as I thought.
I was looking at [git blame and the commit that introduced it has no fixed issue](https://github.com/zino-app/graphql-flutter/commit/ce338ddb86c82c32902522da41d5c726f5afce1a).
I have been using a forked version without this overriding and I haven't found any issues yet.

Maybe @HofmannZ could shed some light on the problem as this commit was his :)

**Comment by mainawycliffe** [comment]
@lucasavila00 can you PR this?

**Comment by prajwalmr62** [comment]
@mainawycliffe I've raised a PR removing the changes.

[PR 396](https://github.com/zino-app/graphql-flutter/pull/396)

**Comment by mainawycliffe** [comment]
This should be closed by this [PR](https://github.com/zino-app/graphql-flutter/pull/398) from @micimize
