### ISSUE TITLE
upload mutiple asset image

### ISSUE THREAD

**Issue by dsourav** [zino-app/graphql-flutter#368]
hello i want to upload images, which i am getting as assets. But i don't know how to upload it. Any code or example would be preferable.

**Comment by mainawycliffe** [comment]
Hi, here is an upload example https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter#graphql-upload

**Comment by dsourav** [comment]
i am using multiple image picker library it accept asset not file how can i upload the assets.
here is the library link:
https://github.com/Sh1d0w/multi_image_picker

**Comment by mainawycliffe** [comment]
All you need is to convert whatever file you are uploading to dart.io File class type and it will work. It doesn't matter if its an asset or a file picker, if you manage that, it will work.

**Comment by dsourav** [comment]
can you give me some code it will help me a lot

**Comment by mainawycliffe** [comment]
Hi, i have gone through the API for the package you are using. Basically, what you need to do is use the steps here to convert your asset to https://sh1d0w.github.io/multi_image_picker/#/upload?id=server-api to multipart file, as shown below:


```dart
ByteData byteData = await asset.requestOriginal();
List<int> imageData = byteData.buffer.asUint8List();

MultipartFile multipartFile = MultipartFile.fromBytes(
  'photo',
  imageData,
  filename: 'some-file-name.jpg',
  contentType: MediaType("image", "jpg"),
);
```

You can now pass the multipart variable above as a variable for your mutation.

```dart
MultipartFile multipartFile = MultipartFile.fromBytes(
  'photo',
  byteData,
  filename: 'some-file-name.jpg',
  contentType: MediaType("image", "jpg"),
);

MutationOptions opts = MutationOptions(
  document: uploadImage,
  variables: {
    "file": multipartFile,
  },
);

var results = await client.mutate(opts);
```

I have tested the multipart upload, and that should work well. Hope this helps.

**Comment by dsourav** [comment]
Thanks a lot but i need multiple images then how can I work with assets of array.

**Comment by mainawycliffe** [comment]
Its an array, you can loop over it and create an array of multipart files.

**Comment by dsourav** [comment]
I got it I am closing the issue...

**Comment by chuongdevJC** [comment]
Hi @dsourav ! 
```dart 
var multipartFile = MultipartFile.fromFileSync(sendMessageRequest.attachmentInputs[0].file.path,
        filename: '${DateTime.now()}.jpg');
    return _apolloService.mutate(
      MessageApi.sendMessage,
      variables: {
        'groupID': sendMessageRequest.groupId,
        'content': sendMessageRequest.content,
        'clientTimestamp': sendMessageRequest.clientTimestamp,
        'isNeedConfirm': sendMessageRequest.isNeedConfirm,
        'attachment': multipartFile,
      },
    );
```
i tried put multipartFile into mutation but i still get error ```DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile'  ```
pls help!

**Comment by longth97** [comment]
> Hi @dsourav !
> 
> ```dart
> var multipartFile = MultipartFile.fromFileSync(sendMessageRequest.attachmentInputs[0].file.path,
>         filename: '${DateTime.now()}.jpg');
>     return _apolloService.mutate(
>       MessageApi.sendMessage,
>       variables: {
>         'groupID': sendMessageRequest.groupId,
>         'content': sendMessageRequest.content,
>         'clientTimestamp': sendMessageRequest.clientTimestamp,
>         'isNeedConfirm': sendMessageRequest.isNeedConfirm,
>         'attachment': multipartFile,
>       },
>     );
> ```
> 
> i tried put multipartFile into mutation but i still get error `DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile' `
> pls help!

Bạn dùng của http thay vì dio xem :v

**Comment by chuongdevJC** [comment]
> > Hi @dsourav !
> > ```dart
> > var multipartFile = MultipartFile.fromFileSync(sendMessageRequest.attachmentInputs[0].file.path,
> >         filename: '${DateTime.now()}.jpg');
> >     return _apolloService.mutate(
> >       MessageApi.sendMessage,
> >       variables: {
> >         'groupID': sendMessageRequest.groupId,
> >         'content': sendMessageRequest.content,
> >         'clientTimestamp': sendMessageRequest.clientTimestamp,
> >         'isNeedConfirm': sendMessageRequest.isNeedConfirm,
> >         'attachment': multipartFile,
> >       },
> >     );
> > ```
> > 
> > 
> > i tried put multipartFile into mutation but i still get error `DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile' `
> > pls help!
> 
> Bạn dùng của http thay vì dio xem :v

mình thử đổi MultipartFile của dio sang http r mà vẫn bị lỗi như trên bác ơi. :(

**Comment by longth97** [comment]
> > > Hi @dsourav !
> > > ```dart
> > > var multipartFile = MultipartFile.fromFileSync(sendMessageRequest.attachmentInputs[0].file.path,
> > >         filename: '${DateTime.now()}.jpg');
> > >     return _apolloService.mutate(
> > >       MessageApi.sendMessage,
> > >       variables: {
> > >         'groupID': sendMessageRequest.groupId,
> > >         'content': sendMessageRequest.content,
> > >         'clientTimestamp': sendMessageRequest.clientTimestamp,
> > >         'isNeedConfirm': sendMessageRequest.isNeedConfirm,
> > >         'attachment': multipartFile,
> > >       },
> > >     );
> > > ```
> > > 
> > > 
> > > i tried put multipartFile into mutation but i still get error `DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile' `
> > > pls help!
> > 
> > 
> > Bạn dùng của http thay vì dio xem :v
> 
> mình thử đổi MultipartFile của dio sang http r mà vẫn bị lỗi như trên bác ơi. :(

![image](https://user-images.githubusercontent.com/48413548/102862069-277ebb00-4463-11eb-9490-f1b509591fef.png)
Thử cách này xem. vẫn dùng của http nhé

**Comment by chuongdevJC** [comment]
@longth97 
```dart
final images = await Future.wait(
      sendMessageRequest.attachmentInputs
          .map(
            (e) async => MultipartFile.fromBytes(
              'Photo',
              e.file.readAsBytesSync(),
              filename: '${DateTime.now()}.jpg',
              contentType: parser.MediaType("image", "jpg"),
            ),
          )
          .toList(),
    );
    return _apolloService.mutate(
      MessageApi.sendMessage,
      variables: {
        'groupID': sendMessageRequest.groupId,
        'content': sendMessageRequest.content,
        'clientTimestamp': sendMessageRequest.clientTimestamp,
        'isNeedConfirm': sendMessageRequest.isNeedConfirm,
        'attachment': images[0],
      },
      mapper: (json) => Message.fromRemote(MessageRemoteEntity.fromJson(json['addMessage'])),
    );
```
vẫn toang bác ạ :(

**Comment by longth97** [comment]
> @longth97
> 
> ```dart
> final images = await Future.wait(
>       sendMessageRequest.attachmentInputs
>           .map(
>             (e) async => MultipartFile.fromBytes(
>               'Photo',
>               e.file.readAsBytesSync(),
>               filename: '${DateTime.now()}.jpg',
>               contentType: parser.MediaType("image", "jpg"),
>             ),
>           )
>           .toList(),
>     );
>     return _apolloService.mutate(
>       MessageApi.sendMessage,
>       variables: {
>         'groupID': sendMessageRequest.groupId,
>         'content': sendMessageRequest.content,
>         'clientTimestamp': sendMessageRequest.clientTimestamp,
>         'isNeedConfirm': sendMessageRequest.isNeedConfirm,
>         'attachment': images[0],
>       },
>       mapper: (json) => Message.fromRemote(MessageRemoteEntity.fromJson(json['addMessage'])),
>     );
> ```
> 
> vẫn toang bác ạ :(

teamview bác ơi.

**Comment by chuongdevJC** [comment]
@longth97 k đc bác ạ. đang project cty :D

**Comment by longth97** [comment]
> @longth97 k đc bác ạ. đang project cty :D

thế chịu thôi bác ơi. debug mới biết đc lõi từ đâu, mình cũng vừa dùng cái này xong chạy bth

**Comment by chuongdevJC** [comment]
> > @longth97 k đc bác ạ. đang project cty :D
> 
> thế chịu thôi bác ơi. debug mới biết đc lõi từ đâu, mình cũng vừa dùng cái này xong chạy bth
trong chỗ config graphql bác có dio k? 
của mình hiện tại có nhét thêm thằng dio như này. k biết phải do thế mà ảnh hưởng k
```dart
GraphQLClient _initClient() {
    final normalLink = Link.from([_dioLink, _httpLink]);
    final link = Link.split((request) => request.isSubscription, _webSocketLink, normalLink);
    return GraphQLClient(cache: _cache, link: link);
  }
```
