### ISSUE TITLE
Mutation return null

### ISSUE THREAD

**Issue by a-aslani-dev** [zino-app/graphql-flutter#369]
**Describe the bug**
my query working and data from back-end changed but resultData in onComplete and result.errors in update return null! also result.hasError is true however i have not any error in server log 

**Screenshots**
[Query Screenshot](http://up.iranblog.com/files/1564639540.png)

[Mutation Screenshot](http://up.iranblog.com/files/1564602414.png)

[Logs Screenshot](http://up.iranblog.com/files/1564618000.png)

**version of package:**
 - graphql_flutter: 2.0.0
 - graphql: 2.0.0

**Comment by mainawycliffe** [comment]
Have you tried logging errors object or inspect it to see if ts an empty object?

**Comment by micimize** [comment]
The error is that your client is misconfigured, and thus is failing to reach the the server: #212

This should have it's own, intelligible error - sorry for the confusion
