### ISSUE TITLE
Making a dart implimentation of apollo client

### ISSUE THREAD

**Issue by HugoReeves** [zino-app/graphql-flutter#37]
**Is your feature request related to a problem? Please describe.**
No. My feature request is a question/recommendation about the direction of this project.

**Describe the solution you'd like**
Dart has the ability to be converted to javascript, but has the advantage of types. Considering apollo-client is a javascript/typescript library, in theory it should be possible to implement a version of apollo-client with very similar usage in dart. Considering this, it might be worth directing this project with the goal of having the same usage, project structure and plugable nature as the official apollo-client implementation. This might make it easier for react-js/native flutter converts to pick up this project and use it as their own graphql solution. The apollo team has created a well liked, powerful set of clients for react, android, ios and more, but a flutter solution is needed.

**Describe alternatives you've considered**
Alternatively this project could continue as is. This feature request is less of a strict request as it is a question about the direction of the project and a proposal as to what direction that could be.

**Additional context**
[Apollo Client issue requesting flutter support](https://github.com/apollographql/apollo-client/issues/2756)
[Apollo Client](https://github.com/apollographql/apollo-client/)
[React Apollo](https://github.com/apollographql/react-apollo)
[Apollo Android](https://github.com/apollographql/apollo-android)

**Comment by HofmannZ** [comment]
This is exactly what we're trying to do, I've just updated the readme to reflect our mission.

**Comment by bricekams** [comment]
How far?

**Comment by vincenzopalazzo** [comment]
already implemented :) @bricekams 

Happy coding!

**Comment by bricekams** [comment]
@vincenzopalazzo ref?
