### ISSUE TITLE
Crash serializing json_serializable objects

### ISSUE THREAD

**Issue by lookfirst** [zino-app/graphql-flutter#374]
Included package: graphql client V2.0.1

I'm using one of my model objects as variables for a mutation. I am passing in List of these objects as a graphql variable. For some reason, in `raw_operation_data.dart:toKey()`, `json.encoder()` is crashing with this error:

![image](https://user-images.githubusercontent.com/85355/62525566-d831ed80-b861-11e9-82a8-f94c40259f8b.png)

As you can see, if I remove the `toEncodable`, things work just fine:

![image](https://user-images.githubusercontent.com/85355/62525698-0e6f6d00-b862-11e9-839f-99a8513aaa5e.png)

Any ideas?

I do have toJson and fromJson methods in the object, which are just proxies for the stuff generated by `json_serializable`.

**Comment by lookfirst** [comment]
I just worked around this issue by pre .toJson()'ing my json_serializable model classes first...

```
final gpus = rig.gpus.map((gpu) => gpu.toJson()).toList();
    QueryResult result = await _client
        .mutate(MutationOptions(document: mutation, variables: {"id": rig.id, "gpus": gpus, "psu": rig.psu.toJson()}));
```

**Comment by micimize** [comment]
https://api.dartlang.org/stable/2.4.0/dart-convert/jsonEncode.html
> If `toEncodable` is omitted, it defaults to a function that returns the result of calling `.toJson()` on the unencodable object.

So we shoud add the default behavior to our encoder

**Comment by lookfirst** [comment]
I should add, this method potentially generates an absurdly long key. What you should be doing is taking a hash of the string and using that as the key.

**Comment by micimize** [comment]
@lookfirst I think we could even just use `object.hashCode`. PRs welcome, naturally

**Comment by micimize** [comment]
Please try `2.1.1-beta.1` and comment if this is still an issue (didn't thoroughly test myself)

**Comment by lookfirst** [comment]
@micimize Confirmed! Thanks for the hard work. One question, why not also fix the code that builds the key to be a shorter string (ie: hash)?

**Comment by micimize** [comment]
@lookfirst want to do it carefully - made an issue though #400. For instance, I realized I was misunderstanding `hashCode` recently, so if I had used it collisions would have been possible (Objects that are not equal are allowed to have the same hash code)

Would also be good to see exactly how apollo implements it, although it might be irrelevant because they do client-side query-resolution.

**Comment by lookfirst** [comment]
https://pchalin.blogspot.com/2014/04/defining-equality-and-hashcode-for-dart.html

apparently quiver has hash functions.

**Comment by lookfirst** [comment]
Oh man, this sent me down a rabbit hole: https://medium.com/booking-com-development/hardening-perls-hash-function-d642601f4e54

I wonder if there are any potential attacks against software as a result of using the quiver hash functions.

**Comment by lookfirst** [comment]
Oh, it just keeps going... https://github.com/dart-lang/sdk/issues/11617
