### ISSUE TITLE
SocketException is crashing application

### ISSUE THREAD

**Issue by ryankauk** [zino-app/graphql-flutter#380]
**Describe the bug**
I cannot handle the SocketException error.

**To Reproduce**
1. Go to https://github.com/ryankauk/graphqlFlutterSocketException
2. Install and run flutter application. (I'm using VsCode Start Debugging using Flutter extension)
3. You'll see the error thrown

**Expected behavior**
The error should be at the minimum be able to handled in try catch statement. Stated by the package it should be added to graphql errors.

**Screenshots**
When using try catch
<img width="1062" alt="Screen Shot 2019-08-13 at 2 30 48 PM" src="https://user-images.githubusercontent.com/11300593/62967538-25b8d800-bdd7-11e9-82ea-97249c1385b6.png">

Full error without try catch
<img width="1061" alt="Screen Shot 2019-08-13 at 2 30 17 PM" src="https://user-images.githubusercontent.com/11300593/62967489-0b7efa00-bdd7-11e9-9fd8-47f60a9f5b00.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 
 - Version 10.14.4

**Comment by micimize** [comment]
Seems to me that this is likely related to [breaking the async awareness bridge](https://github.com/dart-lang/http/issues/160#issuecomment-390403747) within the library. As in, we connect "in the background", and that isn't linked to the rest of the api entrypoints.
