### ISSUE TITLE
No deepmerge when writing queryresults to cache

### ISSUE THREAD

**Issue by Sewdn** [zino-app/graphql-flutter#381]
**Describe the bug**
Multiple queries of same documents are conflicting. Only the result of the lastly executed query is in cache. It seems that no deepmerge is executed with the existing cache, when writing a new document to cache

**To Reproduce**
- setup a query to list a set of documents, only resolving a few fields.
- setup a detail query to fetch a document detail, resolving the same but also additional fields
- fetch the listQuery with cacheAndNetwork fetchPolicy
- fetch the detailQuery with cacheAndNetwork fetchpolicy
- (re)fetch the listQuery with CacheAndNetwork fetchPolicy

**Expected behavior**
additional fields resolved with de detailquery are still present in cache.

**Comment by micimize** [comment]
[cache entities should be deeply merged](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/cache/normalized_in_memory.dart#L127), but if a field is returned as `null` explicitly it will overwrite the previous value. Can you add some examples of the data, and your `dataIdFromObject`?

**Comment by Sewdn** [comment]
@micimize sorry for this very late follow up. We found out that it was not because of the documents not being deeply merged, but because cache restoration is restoring an incomplete cache.

This is the case when the cache provider is not awaiting a full save when the app is being suspended (closed, moved to background). We'll open a separate issue for this.
