### ISSUE TITLE
Union types query

### ISSUE THREAD

**Issue by javi11** [zino-app/graphql-flutter#385]
Hi, first of all thanks for this amazing library.

I don't know if this is the correct place to put this but here i go:

I just started to creating an app consuming a third party graphQL API and now i'm facing the issue that i have to do the following query:

```graphql
query Following(
  $isFollowing: Boolean = true
  $hasReplies: Boolean = false
  $activityType: ActivityType
  $page: Int
) {
  Page(page: $page, perPage: 10) {
    pageInfo {
      total
      perPage
      currentPage
      lastPage
      hasNextPage
    }
    activities(
      isFollowing: $isFollowing
      type: $activityType
      hasRepliesOrTypeText: $hasReplies
      type_in: [TEXT, ANIME_LIST, MANGA_LIST]
      sort: ID_DESC
    ) {
      ... on TextActivity {
        id
        userId
        type
        replyCount
        text
        createdAt
      }
      ... on ListActivity {
        id
        userId
        type
        status
        progress
        replyCount
        createdAt
        media {
          id
          type
          status
          isAdult
          title {
            userPreferred
          }
          coverImage {
            large
          }
        }
      }
    }
  }
}
```

I know that this library do not support fragments but still you know if there is another way to do this query with this library? I'm always receiving totalItems but an empty array of activities

Regards ;)

**Comment by bsr203** [comment]
Hi. I am just a user of this lib. Where does it say fragments are not supported. I do use fragments and it works fine. I also see them used in the [example](https://github.com/zino-app/graphql-flutter/blob/master/examples/starwars/lib/episode/hero_query.dart)

**Comment by javi11** [comment]
:O then my bad i didn't found that example. I just searched fragments on issues and i got this issue https://github.com/zino-app/graphql-flutter/issues/113 so i thought it was not implemented since i didn't found any other related issue.

Okey then i close it, then for sure my error is because i did something wrong ;)

Thanks :)

**Comment by bsr203** [comment]
@javi11 no problem. we are all learning through struggling :-)
