### ISSUE TITLE
didUpdateWidget causing issues

### ISSUE THREAD

**Issue by ryankauk** [zino-app/graphql-flutter#388]
**Describe the bug**
I'm using the Mutation widget for running the graphql
It took me some time to hunt this down. Seems like a few things.

1. Initial cause is when setState is ran along side with runMutation(). As well as requestFocus(), it seems this in turn causes the Mutation widget to call didUpdateWidget. Now at this point it does a check against initiated options variables to the old widget variables. If you don't set any variables in the options and then runMutation(fields), then this will always be false based on the variables check for length. Once this runs is where it starts causing the issues.

2. When didUpdateWidget is ran during a query, the observableQuery is reinitialized and assigned to the class. The build method uses this reassigned variable for it's stream but the result for the previous  observableQuery is now lost. 

**To Reproduce**
I created a [repo](https://github.com/ryankauk/graphqlFlutterMutationIssue) that shows this with a custom class mimicking the Mutation widget to display the results. It has some print statements so you can see the sequence when using the custom widget it gets reinitialized before the query finishes.

**Expected behavior**
I think if the didUpdateWidget check for equality of options is used it should cache the previously used options (variables) to prevent the observableQuery from being reinitialized indefinitely if the runMutation variables are different than the widgets initiated ones. Lastly if the observable is reinitialized it should wait for the previous one. Maybe instead of reinitializing, the streams just get merged together?

Made a possible implementation in the repo at dart/test_stream.dart. Not extremely knowledgable about streams with dart yet. Not sure if there's a better way to manage the streams.

**Comment by ryankauk** [comment]
I just updated the github at lib/new_mutation.dart, you can see the new implementation fully in use.

**Comment by micimize** [comment]
So, you're saying you're 
* triggering a call to `didUpdateWidget` during the call to `runMutation`, 
* which incorrectly resolves `(!observableQuery.options.areEqualTo(_options))` to `true` due to empty variables (`null`?)
* which discards the old mutation widget, then re-renders?

Sounds to me like the only problem is the incorrect `areEqualTo` result. We actually want to discard the old `ObservableQuery` if the options change because it's no longer the same

**Comment by mainawycliffe** [comment]
I am thinking that the only way this is false is if the client changes, otherwise it will always be true. Maybe we should compare if the variables have changed or QueryOptions or something like that.

**Comment by mainawycliffe** [comment]
The error seems to be here, on the comparison for policies:

```dart
if (a.policies != b.policies) {
  return true;
}
```

And it is related to [this issue](https://github.com/zino-app/graphql-flutter/issues/351).

**Comment by mainawycliffe** [comment]
This can be solve by adding an `areEqual` method to the policies and compare both `ErrorPolicy` and `FetchPolicy` independently.

**Comment by micimize** [comment]
This was closed by #504
