### ISSUE TITLE
Can we access the status code from query result?

### ISSUE THREAD

**Issue by KingWu** [zino-app/graphql-flutter#390]
I wanna to access status code. But, it is encapsulated into FetchResult

**Comment by mainawycliffe** [comment]
We are considering exposing low-level information such as status code, headers, etc, which is being tracked by this [issue](https://github.com/zino-app/graphql-flutter/issues/371).

That being said, if you follow GraphQL conventions [here](https://graphql.github.io/graphql-spec/June2018/#sec-Errors), all the error data you need should be returned as an error field, with additional information such as code being added under extensions.

**Comment by kateile** [comment]
I want the same thing
