### ISSUE TITLE
 GET requests possible?

### ISSUE THREAD

**Issue by w0nderb0y** [zino-app/graphql-flutter#391]
This might be a really silly question but I'm new to GraphQL.

Is every Query a POST request? Or is it somehow possible to change it?

**Comment by mainawycliffe** [comment]
Why GET? Currently, I don't think it is possible. But I don't understand why you want to use GET instead of POST.

**Comment by w0nderb0y** [comment]
As I said. I'm very new to GraphQL and don't completely understand the concept yet. 

I want to use the Facebook GraphAPI and not my own backend. 
https://developers.facebook.com/docs/instagram-api

And in some tutorials, also in the Facebook documentation they use GraphQL clients and specify GET as request method. 

That's the reason I asked if it possible to query with GET.

**Comment by mainawycliffe** [comment]
Okay, I was going over the [GraphQL Spec Sheet](https://graphql.org/learn/serving-over-http/#get-request), and you are right, we should support GET request if we don't already do. Maybe this should be an option when initializing an HTTP_LINK with post Request as the default for backward compatibility. What do you think @micimize and @HofmannZ?

**Comment by micimize** [comment]
@w0nderb0y I wouldn't worry about this as a beginner. It is only an optimization - all of the examples should work the same with `POST`. Think of HTTP as a protocol under GraphQL - you don't need to worry about it at all, except when doing something like performance tuning.

@mainawycliffe Yeah, [`apollo-link` has a `useGETForQueries ` option](https://www.apollographql.com/docs/link/links/http/). One of the default [`HttpConfig.options`](https://github.com/zino-app/graphql-flutter/blob/ced45b5b06bae3a43c2646d682f8b289675adc9e/packages/graphql/lib/src/link/http/fallback_http_config.dart#L9) fields specifies `method`, but it doesn't appear to influence behavior. I'd say this is a low priority though.

**Comment by w0nderb0y** [comment]
@micimize the requests fails with the grapql client against the Facebook Graph API. So I need to worry about it. It works with a REST client though.

I didn't try it with a different graphql client though. In the Facebook documentation there is a Swift snippet where they use a Graph QL client with GET

**Comment by micimize** [comment]
@w0nderb0y are you sure the facebook graph api has a GraphQL api? Can you post a link?
You can test whether a graphql endpoint accepts post with curl:
```bash
curl \
  -H "Content-Type: application/json" \
  -d '{ "query": "{ me { name } }" }'` \
  -X POST \
  http://some-graphql-api.com/data
```

**Comment by eusdima** [comment]
@w0nderb0y I don't think GET will add any performance benefits  for Graphql. Only if you spend the time to do specific endpoint for a certain mutation, thus diverging back to REST, which I myself consider a contradiction of the entire GQL.

**Comment by eusdima** [comment]
@w0nderb0y if you are at the beginning, then I would suggest you focusing more on learning the basics than carrying about complex things like GET that only bring you so little for GQL

**Comment by Codebear98** [comment]
Hi, just came across this topic.

The benefit of having Get method is performance gain from supporting Cloudflare or other CDN.
To use Get request, you also need to implement `Auto persisted queries` (APQ) due to the uri length limitation of cloudflare

it's covered in ApolloSDK doc, currently web, apollo-android and apollo-ios are supporting APQ+get method.

https://www.apollographql.com/docs/apollo-server/features/apq/

**Comment by micimize** [comment]
made a specific issue for #397 for get support so the thread is more focused on the issue
