### ISSUE TITLE
Cannot query field "X" on type "Y".: Undefined location

### ISSUE THREAD

**Issue by michalsuryntequiqo** [zino-app/graphql-flutter#395]
Hello there,
I'm experiencing the error with getting data from graphQL API (the real one, not hosted locally).
When quering for some data, the error appears:
`Cannot query field "X" on type "Y".: Undefined location
`
The query used:
```
 String productQuery = r'''
  query Prods {
    products(skus:["111111"], locale:"en_EN") {
     id
     name
     variants { name }
  }
  }
''';
```

With the property `variants { name }` the result shows error:
`Cannot query field "variants" on type "Product".: Undefined location
`
Without it, the result **contains proper data.**

When tested using graphQL playground or Postman, using the same query, everything works fine (received data contains queried `variants`).

Am I doing something wrong, the plugin contains a bug, or it looks like the server issue?
The thing is, that everything works fine when using graphQL playground or Postman.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone XR Simulator
 - OS: iOS 12.4

**flutter doctor output**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.1-pre.90, on Mac OS X 10.14.6 18G87, locale
    pl-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
[✓] VS Code (version 1.35.0)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by MelonWXD** [comment]
same issue here
works fine when using graphQL playground
have you solved the problem ?
