### ISSUE TITLE
Add HTTP GET Query Support

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#397]
Broken off from #391

[`apollo-link` has a `useGETForQueries ` option](https://www.apollographql.com/docs/link/links/http/).

One of the default [`HttpConfig.options`](https://github.com/zino-app/graphql-flutter/blob/ced45b5b06bae3a43c2646d682f8b289675adc9e/packages/graphql/lib/src/link/http/fallback_http_config.dart#L9) fields specifies `method`, but it doesn't influence behavior. I'd say this is a low priority though.

As @Codebear98 says: 
> The benefit of having Get method is performance gain from supporting Cloudflare or other CDN.
> To use Get request, you also need to implement `Auto persisted queries` (APQ) due to the uri length limitation of cloudflare
> 
> it's covered in ApolloSDK doc, currently web, apollo-android and apollo-ios are supporting APQ+get method.
> 
> It's essential if
> 
>     1. your app is production and have large user base
> 
>     2. your user will access to the app at the same time suddenly (eg, responds to push notification)
> 
> 
> Otherwise your server may experience temporary downtime due to high demand of request without CDN.
> 
> https://www.apollographql.com/docs/apollo-server/features/apq/

**Comment by micimize** [comment]
If anyone has an app in production with these kinds of load-based demands, they can start contributing themselves IMO.

I can only dream my app gets to the point where this is a concern 😅

**Comment by Codebear98** [comment]
Yes we do have production apps were encountering that issues but they are native apps.

We wanna implement another app with flutter, it’ll be the issue we need to go through again.

FYI: https://link.medium.com/H0LVnHvayZ

**Comment by mainawycliffe** [comment]
I have an idea on this feature, I am thinking it is not as hard as it seems at first (Could be wrong though). I will try it out and see if it works.

**Comment by mainawycliffe** [comment]
@micimize I have a rough implementation of this using GET on Queries only similar to apollo in my own folk [here](https://github.com/mainawycliffe/graphql-flutter/tree/add-httpget-support), still needs testing and I can't find a graphql endpoint that supports GET. Fortunately, it is a minor change, so completely backward compatible.

**Comment by Codebear98** [comment]
U can build a local server with star ‘wars-server’
It’s also the server used in unit test of Apollo-iOS 

https://github.com/apollographql/starwars-server

**Comment by mainawycliffe** [comment]
It turns out using GET is not supported out of the box by apollo and also [gqlgen](https://gqlgen.com/) for Go. I am working on enabling [Automatic persisted queries](https://www.apollographql.com/docs/apollo-server/performance/apq/) on one of my Go GraphQL Servers and see if GET requests work.

**Comment by micimize** [comment]
Closed by #585
