### ISSUE TITLE
Run query in a MV* pattern

### ISSUE THREAD

**Issue by NeoDigi** [zino-app/graphql-flutter#4]
Right now, if I understand correctly the query is a widget so it's building the UI with the result of the query.

Is it possible to run a query outside of a widget and just fet the result ?

**Comment by eusdima** [comment]
For now, you can import the client.dart and call the method execute(). 
`client.execute(
        query: '<YOUR_QUERY_STRING>',
        variables: variables,
      );` which returns `Future<Map<String, dynamic>>`
We will try to add a more elegant solution in the near future.

**Comment by NeoDigi** [comment]
Thank you for the quick respond, it's working perfectly!
