### ISSUE TITLE
Add support for https  connection w/ self-signed certificate

### ISSUE THREAD

**Issue by pepie** [zino-app/graphql-flutter#40]
Hello.
A 'CERTIFICATE_VERIFY_FAILED' exception is thrown, when connect to a server with a self-signed certificate.

Consider switching to [HttpClient](https://docs.flutter.io/flutter/dart-io/HttpClient-class.html) 
and supporting '[BadCertificateCallback](https://docs.flutter.io/flutter/dart-io/BadCertificateCallback.html)'.

**Comment by HofmannZ** [comment]
Thanks for using our library. We do not plan to support self signed certificates in our package, because It’s encryption is less secure, due to the lack a certificate authority.

We are currently implementing a modular approach for transport layers. Giving you the option to implement your own transport links.

If you plan to use self-signed certificates, I suggest you wait until we finish up that pull request. And if you want to speed up things, you could write some commits and push them to the PR. 

Hope that helped!

**Comment by pepie** [comment]
Thanks for the feedback.

Re: "Thanks for using our library. We do not plan to support self signed certificates in our package, because It’s encryption is less secure, due to the lack a certificate authority."

Using a self-signed certificate is common in development environments, so having that flexibility would make it easier to implement/test while with https. Many developers don't use 3rd-Party certificate authorities.

**Comment by gedw99** [comment]
i agree

this tool does it easily for you
github.com/FiloSottile/mkcert

**Comment by HofmannZ** [comment]
@pepie Thanks for pointing that out. 

We probably won't be working on this feature ourselves, because our team uses a wildcard certs on the staging domains. Since this might be useful for a few developers, we would be happy to merge a good PR. If you need some help we're happy to give some pointers.

**Comment by evarzot** [comment]
Hello, all! I'm sorry if I'm resurrecting a 'zombie thread' here but I just wanted to add how to work around this in case anyone is having trouble with this:

From the client class in examples:

GraphQLClient client() {
  // Workaround for self-signed certificate execption (to be used in dev mode only)
  HttpClient _httpClient = new HttpClient()
  _httpClient.badCertificateCallback = (X509Certificate cert, String host, int port) => true;
  IOClient _ioClient = new IOClient(_httpClient);

  // Link to the GraphQL Endpoint
  final HttpLink _httpLink = HttpLink(
    uri: 'https://api.github.com/graphql',
    httpClient: _ioClient
  );

  // Authentication header (if needed)
  final AuthLink _authLink = AuthLink(
    getToken: () async => 'Basic $PERSONAL_ACCESS_TOKEN',
  );

  final Link _link = _authLink.concat(_httpLink as Link);

  return GraphQLClient(
    cache: InMemoryCache(storageProvider: () {}),
    link: _link,
  );
}

That's it! Worked for me :)

**Comment by simplenotezy** [comment]
> Hello, all! I'm sorry if I'm resurrecting a 'zombie thread' here but I just wanted to add how to work around this in case anyone is having trouble with this:
> 
> From the client class in examples:
> 
> ```
> GraphQLClient client() {
>   // Workaround for self-signed certificate execption (to be used in dev mode only)
>   HttpClient _httpClient = new HttpClient()
>   _httpClient.badCertificateCallback = (X509Certificate cert, String host, int port) => true;
>   IOClient _ioClient = new IOClient(_httpClient);
> 
>   // Link to the GraphQL Endpoint
>   final HttpLink _httpLink = HttpLink(
>     uri: 'https://api.github.com/graphql',
>     httpClient: _ioClient
>   );
> 
>   // Authentication header (if needed)
>   final AuthLink _authLink = AuthLink(
>     getToken: () async => 'Basic $PERSONAL_ACCESS_TOKEN',
>   );
> 
>   final Link _link = _authLink.concat(_httpLink as Link);
> 
>   return GraphQLClient(
>     cache: InMemoryCache(storageProvider: () {}),
>     link: _link,
>   );
> }
> ```
> 
> That's it! Worked for me :)
> 
> P.S.: If there's a better/more optimal way of doing this, feel free to edit my comment or remove it if it shouldn't be here!

This no longer works unfortunately. `HttpLink` gives error:

```
1 positional argument(s) expected, but 0 found.
Try adding the missing arguments.dart[not_enough_positional_arguments](https://dart.dev/diagnostics/not_enough_positional_arguments)
```

**Comment by vincenzopalazzo** [comment]
@simplenotezy can you open a new issue with all the details about the last version that you are running, and other useful info?

Thanks!

P.S: also the link to this issue is helpful

**Comment by simplenotezy** [comment]
Hey @vincenzopalazzo thanks for chipping in! Actually I don't have an issue currently, simply wanted to share how to do it in the latest version :)

It would be cool with an easier way to do this though, eg with an environment variable.

Anyhow, no issues for now! :)

**Comment by vincenzopalazzo** [comment]
>Anyhow, no issues for now! :)

Just a feature request it is fine too, we can put it in the TODO list and maybe make a doc example for it if needed!

The issue of 2018 changed 4 maintainers, and this mean that it is out of every context :)

**Comment by diegonc** [comment]
> ```dart
> GraphQLClient client() {
>   // Workaround for self-signed certificate execption (to be used in dev mode only)
>  HttpClient _httpClient = new HttpClient()
>  _httpClient.badCertificateCallback = (X509Certificate cert, String host, int port) => true;
>   IOClient _ioClient = new IOClient(_httpClient);
> ```

Sorry to "necro-bump", but what is IOClient here?
