### ISSUE TITLE
The caching is not controlled by ErrorPolicy

### ISSUE THREAD

**Issue by nekocode** [zino-app/graphql-flutter#405]
Why the caching is not controlled by `ErrorPolicy` ?

See here:
https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/core/query_manager.dart#L115-L121

Is this to be expected?

**Comment by micimize** [comment]
I guess according to the [apollo docs](https://www.apollographql.com/docs/react/features/error-handling/#error-policies) it is not expected. In fact, this is probably a fairly critical issue
> By default, the error policy treats any GraphQL Errors as network errors and ends the request chain. It doesn't save any data in the cache, and renders your UI with the error prop to be an ApolloError

**Comment by micimize** [comment]
Fixed by #754
