### ISSUE TITLE
 subscriptions through SSL (https)

### ISSUE THREAD

**Issue by bsr203** [zino-app/graphql-flutter#406]
Hi. I updated my server to a secure endpoint. I changed the HttpLink uri from `http://localhost:8080/graphql` -> `https://localhost:443/graphql`. All graphql query seems to work fine.

Now, changed the subscription uri from `ws://localhost:8080/subscriptions` to `ws://localhost:443/subscriptions`. But I see these error

```
flutter: Disconnected from websocket.
flutter: Scheduling to connect in 5 seconds...
flutter: Connecting to websocket: ws://localhost:443/subscriptions...
flutter: There was an error causing connection lost: HttpException: Invalid request method, uri = http://localhost:443/subscriptions
```

this may work if uri is `https://localhost:443/subscriptions`, but this created somewhere by the framework. Is there a configuration I can change so subscription work through `https` . Any pointers appreciated.

thanks.

**Comment by micimize** [comment]
`wss://localhost:443/subscriptions` should work, though there are a [couple](https://github.com/dart-lang/sdk/issues/34284) [issues](https://stackoverflow.com/questions/14496496/using-dartio-websocket-with-wss-protocol-ssl) with dart sockets. I'm pretty sure the `url` for the socket client gets passed through unchanged though

**Comment by bsr203** [comment]
@micimize thank you so much for the help. I will test it at the earliest and get back with you. Have a great weekend.
