### ISSUE TITLE
GraphQLClient subscription will lost when re-connected to server

### ISSUE THREAD

**Issue by ryanz1219** [zino-app/graphql-flutter#407]
**What Happened**
In some reasons, I required to write my script through GraphQLClient and develop using Query, Mutation, Subscription. When I developing the subscription I found that when every connection closed and after re-connect, it didn't pass any query operation(StartOperation) to the server. Therefore, everything will no longer be received from the server.

**Expected behavior**
On re-connected will also able to receive the message from the server.

**Version**
- graphql v2.0.1

**Additional context**
I also checked the source code and found the reason happened in this line.
https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/socket_client.dart#L254
If this line has gone, everything's works fine.

**Comment by mainawycliffe** [comment]
@ryanz1219 can you try and the beta version and see if you still experience the issue

**Comment by gepd** [comment]
I've tried the `2.1.1-beta.2 ` and I got the same behavior.
I'm checking this printing something in the `onConnect` callback. The first time I see how the it's called, but if I make the device lost connection and then connect it again, `onConnect` is never called

**Comment by gepd** [comment]
I've found it's the same issue as https://github.com/zino-app/graphql-flutter/issues/356

**Comment by sharad-paghadal** [comment]
@gepd have you found solution?

**Comment by gepd** [comment]
I've not found a solution yet, I'm looking for something though

**Comment by mainawycliffe** [comment]
I have been away for the last week, I will look into this sometime over the weekend or next week. I am open for any suggestions.

**Comment by gepd** [comment]
cannot the streamController in the `subscribe` method ([#L238](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/socket_client.dart#L238)) to reconnect too instead of only close the connection?

**Comment by ryanz1219** [comment]
I don't know is it have other effects that will cause by removing line 254 in the before I said, but I am trying to remove this line because SocketClient._connect() called at the beginning and _connect() will auto re-connect the server according to the same file at line 140.

However, the connection is reconnected by line 140 but It didn't resend the previous GraphQL operation to the server so the WebSocket is connected, graphql operation isn't started in server cause by request isn't sent.

I hope this information will helpful for this problem.

**Comment by ryanz1219** [comment]
> cannot the streamController in the `subscribe` method ([#L238](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/socket_client.dart#L238)) to reconnect too instead of only close the connection?

I think it can't because the subscribe method is directly called by the user so if reconnect it, then the user will be required to reload their subscription callback also.
In addition, the streamController doesn't know any network status of the connection at now. streamController depends on _connectionStateController to receive a new message for itself. 
As my knowledge :)

**Comment by gepd** [comment]
Hey @mainawycliffe have you been able to check this? If so, what are your thought about it? It seems like it isn't an easy fix without breaking the current functioning

**Comment by mainawycliffe** [comment]
I am sorry, this is another that slipped my radar. I am thinking we could probably have a queue for all Subscription operations and upon reconnection, retry them again. When the connection fails, does it send an error and close the subscription? I currently don't have any way of testing this, so I will have to create a demo to see this behavior my self.

**Comment by EugenePisotsky** [comment]
I tweaked it for my project a few months ago until waiting for this to be fixed. Not perfect solution, but may be helpful
https://github.com/EugenePisotsky/graphql-flutter/commit/57f64c37fdc895d822d0c713b3c7d21630613498

Idea is to create map of subscriptions, and callbacks that call `response.onListen` each time after websocket connection is restored

**Comment by mainawycliffe** [comment]
@EugenePisotsky If it's already working for you, can you PR the change and we will review and merge it. Here are our [contributing guidelines](https://github.com/zino-app/graphql-flutter/blob/master/CONTRIBUTING.md).

**Comment by EugenePisotsky** [comment]
@mainawycliffe Ok, I'll try to find time within the next few days

**Comment by kulture-rob** [comment]
@EugenePisotsky did you get a chance to get a PR in for this? Subscriptions are pointless without it.

**Comment by EugenePisotsky** [comment]
@kulture-rob 
done. if someone has a better solution it would be awesome :)

**Comment by mainawycliffe** [comment]
I am closing this issue, the PR has been released to the latest beta.
