### ISSUE TITLE
Is there a reason to force set `fetchPolicy = FetchPolicy.cacheAndNetwork` in query options?

### ISSUE THREAD

**Issue by j-deng** [zino-app/graphql-flutter#412]
**Describe the bug**
https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql_flutter/lib/src/widgets/query.dart#L41 
It will cause the unnecessary query to the backend if forced to update from the network and make this option setting confusing.  [related ask](https://stackoverflow.com/questions/57891193/how-to-disable-graphql-flutter-query-backend-every-time-build-query) / [related flutter behavior](https://github.com/flutter/flutter/issues/11655)

**Expected behavior**
Is it good to make the user control the action and without forcing `cacheAndNetwork`?

**Comment by j-deng** [comment]
And if it's an issue, then the fetchMore cache also has no effect on caching the whole list, will still causing fetching a small list without fetchMoreData

**Comment by mainawycliffe** [comment]
Can you try the beta version, I think the issue was resolved a while back.

**Comment by j-deng** [comment]
> Can you try the beta version, I think the issue was resolved a while back.

Thanks, man, my bad, it's resolved. 👍
