### ISSUE TITLE
Add middleware

### ISSUE THREAD

**Issue by tamdesktop** [zino-app/graphql-flutter#413]
Thanks for your hard work on this project.

Can you plan to add something like middleware? I want to add my custom encrypt and decrypt data before send and receive data.

**Comment by klavs** [comment]
@tamdesktop `Link` is a middleware.

https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql/lib/src/link

**Comment by mainawycliffe** [comment]
I am going to add this to the backlog and hopefully implement it in the future, @tamdesktop if you want, you can take up this issue and we will review it and merge it.

**Comment by micimize** [comment]
> Link is a middleware.
