### ISSUE TITLE
Query result.loading is always false when used in statefulwidget

### ISSUE THREAD

**Issue by serendipity1004** [zino-app/graphql-flutter#416]
When `Query` is inside a statefulwidget and if the statefulwidget is re-rendered due to change of state in its parent stateful widget, result.loading is always false even when new query is being fired to take account of state change in parent widget that propagates down to the child widget.

I will try to provide a minimal working example ASAP this week. I can't do it right now because I've got too much work to do. However, I think it will be quite easy to reproduce based on above explanation.

**Comment by mainawycliffe** [comment]
Can you try the better version, I think this issue was resolved sometime back.

**Comment by serendipity1004** [comment]
@mainawycliffe I was using 2.1.0 and now switched to 2.1.0-beta.2 to test but result.loading is always false. Anyway it's besides the point but what have you done to the library? It's got considerably faster after upgrading. (from 2.1.0 to 2.1.0-beta.2)
