### ISSUE TITLE
Global Catch/Parse Error

### ISSUE THREAD

**Issue by serendipity1004** [zino-app/graphql-flutter#419]
**Is your feature request related to a problem? Please describe.**
Sometimes it is very useful to be able to catch specific error globally. For example, when you are using JWT auth and if JWT has expired or invalidated, user should be redirected to the login page. In current version of the package, we have to specify error handling method for each Query.

**Describe the solution you'd like**
https://www.apollographql.com/docs/react/features/error-handling/#network-errors I think implementation of something similar to apollo would suffice.

**Comment by mainawycliffe** [comment]
I will look into this and see if such a feature exists, the docs are lacking for this package. If it doesn't, I agree, it is an important feature to have.

**Comment by mainawycliffe** [comment]
Now that #445 has been merged, we can close this issue.
