### ISSUE TITLE
Add a new document to cache and get it reflected on a List type UI

### ISSUE THREAD

**Issue by serendipity1004** [zino-app/graphql-flutter#437]
Say I have mutation `CreateNewPost` and an UI listening to `PaginatePosts`, currently there seems to be no way to have the new post created in `CreateNewPost` to be reflected with cache update on `PaginatePosts`.

I have cacheKeyBuilder like below

```
String cacheKeyBuilder(Object object) {

  if(object is Map<String, Object>){
    if(object.containsKey('__typename') && object.containsKey('id')) {
      return "${object['__typename']}/${object['id']}";
    }
  }
  return null;
}
```

So on `PaginatePosts` will listen to list of posts something like `Post/1` `Post/2`...

If I had `Post/3` in another screen and update cache with key `Post/3` and returned new post result, it is not shown on `PaginatePost` UI.

**Comment by micimize** [comment]
you need to use an `update` callback to do something like 
```dart
result = cache.read(paginatePostsKey);
result['posts'].add(newPost.toJson());
cache.write(paginatePostsKey, result);
```

More complete usage can be seen in the example, :
https://github.com/zino-app/graphql-flutter/blob/519381cd1c57515fd26cedb33c68a68d563a6eac/packages/graphql_flutter/example/lib/graphql_widget/main.dart#L211-L220

**Comment by micimize** [comment]
Feel free to add more comments here or drop into [the discord](https://discord.gg/tXTtBfC) if you're still having issues
