### ISSUE TITLE
Integration tests with flutter_test

### ISSUE THREAD

**Issue by lassesteffen** [zino-app/graphql-flutter#439]
**Is your feature request related to a problem? Please describe.**
I am not sure if there is currently a way to mock graphQL related queries and mutations currently. If yes please point me to the right direction if no, can we get it?

**Comment by mainawycliffe** [comment]
For now, I think Mockito is your best bet, Maybe we could build on it and make it easier to test GraphQL, but you could definitely use it to test GraphQL Client.

**Comment by lassesteffen** [comment]
Okey thank you! Would be cool if building on top of it would be done at some point!
