### ISSUE TITLE
Add ErrorLink

### ISSUE THREAD

**Issue by smkhalsa** [zino-app/graphql-flutter#440]
Something comparable to Apollo's ErrorLink

**Comment by bsr203** [comment]
Similar request https://github.com/zino-app/graphql-flutter/issues/419

I too really like to have this feature to catch Network error and to handle appropriately outside components. I see an approach in this repo https://github.com/ygmpkk/flutter_graphql_backenderrorlink 
but, as far as I see, ClientExceptions from http package is not able to capture by this package and may need to implement at core.

**Comment by jayjun** [comment]
@smkhalsa @bsr203 I sent a pull request (#445) to add `ErrorLink`.

**Comment by bsr203** [comment]
@jayjun thank you so much for your work on it. This was much needed feature for me. I didn't test it, but there has been lot changes around splitting network error etc. In the stable branch  I couldn't handle http error (status code 401 etc) through a custom link. It may all solved now with the changes in beta branch. But please confirm your changes make it possible to catch errors at network level. thanks again. bsr

**Comment by mainawycliffe** [comment]
Now that #445 has been merged, we can close this issue.
