### ISSUE TITLE
Add method to print contents of cache

### ISSUE THREAD

**Issue by serendipity1004** [zino-app/graphql-flutter#448]
currently when we print default message which is instance of w/e.

I think it would be great to use the code provided by @micimize below and override toString method so that we don't have to import toJson function every time we would like to visualize cache. I can work on this if you approve.

```
import 'package:flutter/material.dart' show debugPrint;
import 'package:graphql/src/utilities/traverse.dart';
import 'dart:convert';

import 'package:graphql_flutter/graphql_flutter.dart' show LazyCacheMap;

final JsonEncoder encoder = const JsonEncoder.withIndent('  ');

class LazyCacheMapTraversal extends Traversal {
  LazyCacheMapTraversal() : super((Object n) => null);

  Object traverse(Object node) {
    final seen = alreadySeen(node);
    if (node is LazyCacheMap) {
      if (seen) {
        return '...';
      }
      node = Map<String, dynamic>.fromEntries((node as LazyCacheMap).entries);
    }
    if (seen) {
      return node;
    }
    if (node is List<Object>) {
      return node.map<Object>((Object node) => traverse(node)).toList();
    }
    if (node is Map<String, Object>) {
      return traverseValues(node);
    }
    return node;
  }
}

dynamic getJson(LazyCacheMap cacheMap) {
  return LazyCacheMapTraversal().traverse(cacheMap);
}

void pprint(dynamic json) {
  if (json is LazyCacheMap) {
    json = getJson(json);
  }
  debugPrint(encoder.convert(json));
}
```

**Comment by micimize** [comment]
So, I don't think we should print the entire contents on `print(cache)`, but we could add that as a `toString()` for `LazyCacheMap`. I remember I ran into some issues when writing [the above](https://github.com/zino-app/graphql-flutter/issues/383#issuecomment-526439093), but I can't remember what they were.

Also, `debugPrint` is a flutter utility so we can't include it in core. but, I think we could add `pprint` as a top-level utility in `graphql_flutter`, and figure out a good api for getting the raw denormalized cache data.

**Comment by micimize** [comment]
Closing this in favor of #606 and #471 (which removes the need for dealing with LazyCacheMaps)
