### ISSUE TITLE
Does "rethrow" really need in in_memory_io.dart?

### ISSUE THREAD

**Issue by heyask** [zino-app/graphql-flutter#450]
**Describe the bug**

```
Unhandled Exception: FileSystemException: Cannot open file, path = 'cache.txt' (OS Error: Read-only file system, errno = 30)
```

**To Reproduce**
1. launch iOS simulator
2. flutter run or VSCode debug start
3. when app is running, click home button for app being background.
4. re-open app
5. app is freezing because vscode debug catched exception.

error log in console.
```
[VERBOSE-2:ui_dart_state.cc(144)] Unhandled Exception: FileSystemException: Cannot open file, path = 'cache.txt' (OS Error: Read-only file system, errno = 30)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop <…>
```

https://github.com/zino-app/graphql-flutter/blob/519381cd1c57515fd26cedb33c68a68d563a6eac/packages/graphql/lib/src/cache/in_memory_io.dart#L88-L105

**Expected behavior**
when I run app through ```flutter run```, not vscode debug, and when app is in background, 
it just shows verbose exception error. error doesn't affect app's running.
but, I wonder it is okay to ignore.

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Smartphone (please complete the following information):**
 - Device: iOS Simulator - iphone 8
 - OS: iOS
 - Version: 8

**Comment by micimize** [comment]
outdated / solved implicitly by `4.0.0-beta.1` as we've decoupled persistence from the cache and `HiveStore` does not have this problem
