### ISSUE TITLE
Session and Shared preferences (use session data next time)

### ISSUE THREAD

**Issue by Hellomik2002** [zino-app/graphql-flutter#460]
I want to use session credentials when the app restarts. However, I cannot take out cookies and save them with the current implementation. Maybe you can create SessionLink or something like that. It would make using this package easier for beginners like me.

**Comment by Hellomik2002** [comment]
and it would be cool to save session data with package "Shared Preferences"

**Comment by cutzmf** [comment]
You can do any perverted auth with little help of

```HttpLink(uri: _baseUri, httpClient: CookiesCatcherClient());```

```import 'package:http/io_client.dart';
import 'package:http/src/base_request.dart';
import 'package:http/src/streamed_response.dart';

class CookiesCatcherClient extends IOClient {
  @override
  Future<StreamedResponse> send(BaseRequest request) async {
    print('###>>> ${request.headers}');
    return super.send(request).then((response) {
      print('###<<< ${response.headers}');
      return response;
    });
  }
}```

**Comment by mainawycliffe** [comment]
@Hellomik2002 was your problem solved by @cutzmf solution?

**Comment by Hellomik2002** [comment]
> @Hellomik2002 was your problem solved by @cutzmf solution?

Yes, you need just add some features
