### ISSUE TITLE
Migration guide?

### ISSUE THREAD

**Issue by serendipity1004** [zino-app/graphql-flutter#470]
A lot of changes have been made in beta3 it seems. I have upgraded and `result.error` has changed to `result.exception`, `update`s are not found in mutations, `onCompleted` is also not found. A migration guide to try out beta3 would be helpful. Or will the guide be available only for stable releases?

**Comment by mainawycliffe** [comment]
There are so many changes, I have lost count, I will write a migration guide over the weekend.

On top of that, we need to jump to version 3, to allow people not ready for the upgrade to stay safely in version 2 since flutter follows semantic versioning. So, I think this we should be having a version 3.0.0.beta.1 instead. @micimize any ideas of how to bump the major version up?

**Comment by micimize** [comment]
`update` and `onCompleted` moved to `MutationOptions`. The [changelog](https://github.com/zino-app/graphql-flutter/releases) will be useful for a migration guide

As for a new release - @HofmannZ correct me if I'm wrong, but I think we need to add the `BREAKING CHANGE:` footer to a commit,  which we've been neglecting 😬

**Comment by HofmannZ** [comment]
@micimize yes, unfortunately you’re correct on that one.

**Comment by mainawycliffe** [comment]
@HofmannZ can we force it?

**Comment by HofmannZ** [comment]
It seems a bit weird to do a bump from beta 2.0.0 to beta 3.0.0 without releasing 2.0.0.

Looking at the release notes, promoting the current version to stable would already do a major version bump because `v2.1.1-beta.3` includes breaking changes.

**Comment by mainawycliffe** [comment]
I don't understand, we already released versions 2.0.0 and 2.1.0, so since we are introducing breaking changes, we have to bump major versions.

v2.1.0 - https://github.com/zino-app/graphql-flutter/compare/v2.0.1...v2.1.0
v2.0.0 - https://github.com/zino-app/graphql-flutter/compare/v1.1.0...v2.0.0

**Comment by HofmannZ** [comment]
Sorry for the comment earlier, we of course already have version 2.

Just reading through the [semantic release docs](https://semantic-release.gitbook.io/semantic-release/v/beta/usage/workflow-configuration#pre-release-branches) again. It looks like we should have merged features and fixes into master. And only push breaking changes to the beta branch.

**Comment by mainawycliffe** [comment]
I think from v3, we should follow those guidelines. Bug fixes and patches go to master branch, while major features go to beta, then we can merge master into beta automatically daily just like we do.

**Comment by HofmannZ** [comment]
@mainawycliffe Agreed

**Comment by mainawycliffe** [comment]
I have added a migration guide #486, hope I didn't miss anything. This should clear for release to stable.
