### ISSUE TITLE
Getter not found: 'suspending'.

### ISSUE THREAD

**Issue by puruzio** [zino-app/graphql-flutter#472]
**Describe the bug**
My app using graphql_flutter started to error out once flutter is upgraded 

**To Reproduce**
1. Upgrade Flutter as of Nov 14, 2019
2. Run `flutter build web`
3. See error

**Expected behavior**
My app was working fine using graphql_flutter until it started to fail compiling after flutter upgrade on 11/14/2019.

**Desktop (please complete the following information):**
 - OS: macOs Catalina version 10.15.1

Error message
#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:156:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:222:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:41:50)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:57:11)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:607:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

Exception: ../../../flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30:
Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:
                             ^^^^^^^^^^
Error: Compilation failed.

Compiling lib/main.dart for the Web...                             11.6s
Exception: Failed to compile application for the Web.

**Comment by mainawycliffe** [comment]
Hi, your information is missing a few important things like flutter version and package version. That said, I am guessing this is because flutter introduced a breaking change by removing `AppLifecycleState.suspending`, this is going to be addressed by the following PR (#465).

**Comment by mainawycliffe** [comment]
This has been closed by #473
