### ISSUE TITLE
How to define new input types?

### ISSUE THREAD

**Issue by FedericoMatera** [zino-app/graphql-flutter#479]
I have a model like this:
```
{
  a: String,
  ...,
  objects: [{
    c: String,
    d: String,
    ...
  }],
  otherObject: {
    e: String,
    f: String,
    ...
  }
}
```
and I have to pass it as a mutation's input. 
I'm not able to find documentation about this case. How can I do?
Thanks in advance

**Comment by FedericoMatera** [comment]
resolved

**Comment by Setti7** [comment]
@FedericoMatera How did you solve it?
