### ISSUE TITLE
WebSocketException: Connection not upgraded to websocket

### ISSUE THREAD

**Issue by netwrkx** [zino-app/graphql-flutter#480]
Good day, please any idea on how to resolve this

```
/flutter (31920): Connecting to websocket: ws://192.168.43.95:8080/graphql...
I/flutter (31920): There was an error causing connection lost: WebSocketException: Connection to 'http://192.168.43.95:8080/graphql#' was not upgraded to websocket
I/flutter (31920): Disconnected from websocket.
I/flutter (31920): Scheduling to connect in 5 seconds...
I/flutter (31920): Connecting to websocket: ws://192.168.43.95:8080/graphql...
I/flutter (31920): There was an error causing connection lost: WebSocketException: Connection to 'http://192.168.43.95:8080/graphql#' was not upgraded to websocket
I/flutter (31920): Disconnected from websocket.
```
Tested on
^2.1.1-beta.4
^2.1.0
^2.0.1

http request work flawless but websocket is giving me headache. any one pls.
here is my code

```
const String YOUR_PERSONAL_ACCESS_TOKEN =
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

const bool ENABLE_WEBSOCKETS = true;

class Principal extends StatelessWidget {
  const Principal() : super();
  
  @override
  Widget build(BuildContext context) {
    final HttpLink httpLink = HttpLink(
      uri: 'http://192.168.43.95:3030/graphql',
    );

    final AuthLink authLink = AuthLink(
      getToken: () async => 'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
    );

    Link link = authLink.concat(httpLink);
    if (ENABLE_WEBSOCKETS) {
      final WebSocketLink websocketLink = WebSocketLink(
        url: 'ws://192.168.43.95:3030/graphql',
        config: SocketClientConfig(
            autoReconnect: true, inactivityTimeout: Duration(seconds: 15),
            initPayload: {}  
          ),
      );

      link = link.concat(websocketLink);
    }

    final ValueNotifier<GraphQLClient> client = ValueNotifier<GraphQLClient>(
      GraphQLClient(
        cache: OptimisticCache(
          dataIdFromObject: typenameDataIdFromObject,
        ),
        link: link,
      ),
    );


    return GraphQLProvider(
      client: client,
      child: const CacheProvider(
        child: MyHomePage(title: 'GraphQL Widget'),
      ),
    );

  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    Key key,
    this.title,
  }) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Person> listPerson = List<Person>();
  QueryMutation queryMutation = QueryMutation();



  @override
  void initState() {
    super.initState();
    //fillList();
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Example"),
      ),
      body: Stack(
        children: <Widget>[
          Container(
            width: MediaQuery.of(context).size.width,
            child: Text(
              "Person",
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 30.0),
            ),
          ),
          Query(
            options: QueryOptions(
              document: queryMutation.getAll(),
            ), builder: (QueryResult result, {refetch, fetchMore}) {

                if (result.loading) {
                  return const Center(
                    child: CircularProgressIndicator(),
                  );
                }

                if (result.hasErrors) {
                  return Text('\nErrors: \n  ' + result.errors.join(',\n  '));
                }

                if (result.data == null && result.errors == null) {
                  return const Text(
                      'Both data and errors are null, this is a known bug after refactoring, you might forget to set Github token');
                }

                // result.data can be either a [List<dynamic>] or a [Map<String, dynamic>]
                final List<LazyCacheMap> repositories = (result.data['Persons'] as List<dynamic>).cast<LazyCacheMap>();

                return  ListView.builder(
                    itemCount: repositories.length,
                    itemBuilder: (BuildContext context, int index) {
                      return ListTile(
                        selected: repositories == null ? false : true,
                        title: Text(
                          repositories[index]['firsName'],
                        ),
                        onTap: () => {},
                      );
                    },
                  );
                
            },
          ),
            ENABLE_WEBSOCKETS
              ? Subscription<Map<String, dynamic>>(
                    'PERSON_ADDED', queryMutation.testSubscription(), builder: ({
                    bool loading,
                    Map<String, dynamic> payload,
                    dynamic error,
                  }) {
                    if (error != null) {
                      return Text('\nErrors: \n  ' + error.join(',\n  '));
                    }

                    return loading ? const Text('Loading...') : Text(payload.toString());
                  })
              : const Text(''),
        ],
      ),
    );
  }
}


```

**Comment by mainawycliffe** [comment]
I am not sure about this, but a WebSocket is upgraded by the server and not the client. It is initialized just like a normal HTTP request and upgraded to WebSocket after the handshake. This seems like an error on the backend and I would suggest trying the to use GraphiQL and see if it works and then report back.

**Comment by netwrkx** [comment]
@mainawycliffe Graphql works, tested with postman and my web browser. Its more flutter issue
[flutter issue](https://github.com/flutter/flutter/issues/11444)
[Another flutter issue](https://github.com/flutter/flutter/issues/42210).

I can upload my server code on github if you don't mind

**Comment by mainawycliffe** [comment]
If I read the issues correctly this could be an issue with the emulator and device settings. It would be helpful if you could upload your server code and when I get some time I will try and test it.

**Comment by netwrkx** [comment]
@mainawycliffe here is my server code 
[FeatherjsGraphql](https://github.com/netwrkx/FeatherjsGraphql).

thanks

**Comment by netwrkx** [comment]
@mainawycliffe any luck with this

**Comment by agilob** [comment]
Why is `#` appended to the URI?

My host is `ws://192.168.1.159:8080/echo` but flutter is failing with `WebSocketException: Connection to 'http://192.168.1.159:8080/echo#' was not upgraded` where is the `#` from?

**Comment by micimize** [comment]
This is likely resolved on `4.0.0-beta`. If someone still has this issue there please comment and I'll reopen

**Comment by Pinteezy** [comment]
Yes I still have an issue with this

**Comment by Zony-Zhao** [comment]
![image](https://user-images.githubusercontent.com/50739849/102492925-584ea100-40ad-11eb-8554-d5bd9ae00ed4.png)

**Comment by Zony-Zhao** [comment]
All right, I found that the issue is my Nginx proxy server making this error. No wonder ws protocol is changing to http.
![image](https://user-images.githubusercontent.com/50739849/102493701-85e81a00-40ae-11eb-8fbc-3e34c129aec2.png)
https://www.nginx.com/blog/websocket-nginx/

**Comment by Pinteezy** [comment]
Yes we added a condition on the api to check for gql flutter protocol.

**Comment by micimize** [comment]
@Pinteezy and that solved your issue? So it looks to me like this was both:
* an issue with flutter that has since been resolved
* a tricky server-side configuration that can result in a similar error

Is my read correct, or is there something we should be doing differently here? I have not  looked deeply

**Comment by Pouya69** [comment]
Did anyone come with an idea for this? I am stuck on this for 2 days now. In HTML it works great but in APIs and Flutter it does not. I tried everything and it is still converting my "ws://<my_ip>/groups" to "http://<my_ip>/groups#"

**Comment by Hasilt** [comment]
Getting the same error on plugin version `graphql_flutter: ^5.0.0`

![image](https://user-images.githubusercontent.com/9217770/128950920-1aebc181-d7ff-4515-b860-e072e9a19119.png)

**Comment by Exeteres** [comment]
It looks like the problem still exists in the latest versions of the package.
I have exactly the same problem as the two commenters above.

**Comment by mrhaydari** [comment]
Correct NGINX config

listen on port 80, u can use any port
//sites-available
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name socket.chargoshe.com;
    location / {
        proxy_pass http://websocket; // upstream name lookup upstream method 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;     // headers key and handle method name
        proxy_set_header Connection $connection_upgrade; // headers key and handle method name // header most be contains key Connection 
        proxy_set_header Host $host;
    }
}
```
// nginx.conf
```
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }  // connection header must be contains Connection and here Connection value is updarade
      // u can add any authorization, authenticated or any u wanted
   upstream websocket {
        server 127.0.0.1:27015; // backend websocket app running IP and port // here I running my app with port 27015
    }

```
now you can connect to wabsocket like

```
final channel = IOWebSocketChannel.connect('ws://yourhost:LISTENPORT
        headers: {'Connection': 'upgrade', 'Upgrade': 'websocket'}); // headers 
    channel.stream.listen((message) {
      print("message $message");
    });

```

**Comment by Djihanegh** [comment]
I have the same problem i have tried socket io client version 1.0.1 in flutter with the socket io in nodejs version 2.4.1 , and tried to upgrade flutter socket io to the 2.0.0-beta.4-nullsafety.0 version with the node js socket io 2.3 version , it didn't worked

here's my code :
```
  static Socket? socket;

  socket = io("wss://url:443", OptionBuilder()
         .setTransports(["polling","websocket"]) 
          .disableAutoConnect()  
          .setExtraHeaders({'authentication':token ,  'Connection': 'upgrade', 'Upgrade': 'websocket'}) 
          .build() );

      // Connect to websocket
      socket?.connect();

```

**Comment by jesseburstrom** [comment]
> I have the same problem i have tried socket io client version 1.0.1 in flutter with the socket io in nodejs version 2.4.1 , and tried to upgrade flutter socket io to the 2.0.0-beta.4-nullsafety.0 version with the node js socket io 2.3 version , it didn't worked
> 
> here's my code :
> 
> ```
>   static Socket? socket;
> 
>   socket = io("wss://url:443", OptionBuilder()
>          .setTransports(["polling","websocket"]) 
>           .disableAutoConnect()  
>           .setExtraHeaders({'authentication':token ,  'Connection': 'upgrade', 'Upgrade': 'websocket'}) 
>           .build() );
> 
>       // Connect to websocket
>       socket?.connect();
> ```

you need to use socket_io_client 2 or higher scroll down list to see beta versions. 
also i dont think using wss with socket.io works since socket.io and websocket are not compatible. 
I use socket_io_clientlike : socket_io_client: ^2.0.0-beta.4-nullsafety.0 and works fine with node.js
like:

late Socket socketConnection;

// Configure socket, transports must be sepecified
        socketConnection = io(localhostIO, <String, dynamic>{
          "transports": ["websocket"],
        });
        socketConnectionId = socketConnection.id!;
        socketConnection.on("onClientMsg", onClientMsg);
        socketConnection.on("onServerMsg", onServerMsg);

**Comment by okan-oz** [comment]
I have the same problem. My problem started after deploy my app to Azure.

**Comment by vincenzopalazzo** [comment]
@okan-oz Nov 30, 2019 is too late in the past, maybe can you open an issue with more details and we can help you!

**Comment by david-macharia** [comment]
am still getting this error 0/socket.io/?EIO=4&transport=websocket#' where does this leading zero come from ??
