### ISSUE TITLE
How can I handle the connection errors ?

### ISSUE THREAD

**Issue by chicrock** [zino-app/graphql-flutter#482]
**Describe the bug**
I'm not sure if this bug or not.
I want to handle the exception when the server is down.
But, I can't catch the connection error.

How can I handle this ?

**To Reproduce**
1. Wrap Mutation with try-catch block.
2. Turn off the server.
3. Request to the server with Mutation.

```dart
try {
  mutation({
    'accessToken': 'my_tokens',
  });
} catch (error) {
  print("Error: Error occurred!!");
}
```

OR

```dart
Mutation(
    options: MutationOptions(
      document: qSocialLogin,
    ),
    builder: (
      RunMutation mutation,
      QueryResult result,
    ) {
      if (!result.loading && result.hasErrors) {
        print("Error: Error occurred!!");
      }
  }
)
```

**Expected behavior**
Print "Error: Error occurred!!" in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/1574553/70034447-8a04df00-15f4-11ea-9582-d22efa8c7860.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.6

**Smartphone (please complete the following information):**
 - Device: iPhone8 Plus(Simulator)
 - OS: iOS 12.1

**Comment by mainawycliffe** [comment]
Can you try the beta version of the package, I think this may have been resolved a while back

**Comment by chicrock** [comment]
@mainawycliffe Thanks~ 👍
I found the update for exception handling in `v2.1.1-beta.3@beta` after saw your word.
When is this feature release in a stable version ?

**Comment by mainawycliffe** [comment]
I am not sure, been caught up lately, but I will find some time and update the changelog and see if we can push the next version to stable over the week.
