### ISSUE TITLE
When mutation fails, loading state never changes back to false

### ISSUE THREAD

**Issue by serendipity1004** [zino-app/graphql-flutter#484]
I am unsure if this is intended but currently, when mutation query fails, loading state is never returned to false.

So currently, we need to have `bool _loading` in statefulwidget and change the loading state manually when onCompleted is called. However, ideally we would want to just listen to result.loading and change button state or w/e.

**Comment by mainawycliffe** [comment]
@serendipity1004 I am unable to replicate this using the example on this repo, can you provide more info.

**Comment by SanjiKir** [comment]
@mainawycliffe Maybe it will help, I just noticed that it goes into infinite loading in case a device doesn't have internet connection.

**Comment by SwannLV** [comment]
Same here, in case a device doesn't have internet connection.

**Comment by micimize** [comment]
I think this is likely resolved in `4.0.0-beta.4`
