### ISSUE TITLE
Export operation and fetch_result in graphql_flutter.dart

### ISSUE THREAD

**Issue by Hauglid** [zino-app/graphql-flutter#487]
I have implemented my own authlink so that I can customise the header. 
My IDE gives me a warning for the imports:
`import 'package:graphql/src/link/operation.dart';
import 'package:graphql/src/link/fetch_result.dart';`
`Don't import implementation files from another package.dart(implementation_imports)`

Please add them to graphql_flutter.dart exports.

**Comment by mainawycliffe** [comment]
Can you try and import `package:graphql/client.dart` and see if it changes anything?

**Comment by Hauglid** [comment]
Didn't work since they are not a part of the client.dart exports.

**Comment by mainawycliffe** [comment]
Okay, I will PR this today, it's a simple change, once they are exported by the `client.dart`, then graphql flutter will pick them up automatically.

**Comment by mainawycliffe** [comment]
@Hauglid since #492 has been merged, you can try the next beta and check if this issue has been resolved. It is not released yet but will be automatically released in the next few of hours.

**Comment by micimize** [comment]
Outdated / Solved implicitly by core rework in `4.0.0-beta.1` #648
