### ISSUE TITLE
Compile error in Flutter v1.12.13+hotfix.5

### ISSUE THREAD

**Issue by mateusfsilva** [zino-app/graphql-flutter#489]
**Describe the bug**
Compile error after update to Flutter v1.12.13+hotfix.5.

**To Reproduce**
Update the Flutter version to the [last stable release](https://flutter.dev/docs/development/tools/sdk/releases) and compile a project with graphql_flutter.

**Expected behavior**
Compile without errors.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version 10.15.2

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10
 - Version QP1A.191105.003

**Additional context**
The error is in class `CacheProvider` the enum `AppLifecycleState` don't have the option `suspending`.

**Comment by mainawycliffe** [comment]
This has been fixed in the latest beta

**Comment by reeichert** [comment]
HI guys, any update on this?

**Comment by mainawycliffe** [comment]
@reeichert use the latest beta, we have a pipeline error issue that is preventing this being released to stable.

**Comment by HofmannZ** [comment]
@mainawycliffe Seems like coverage is failing, any ideas, and therefore the pipeline fails. Any ideas for fixing the coverage?

**Comment by HofmannZ** [comment]
#514 might be related

**Comment by mainawycliffe** [comment]
@HofmannZ I think this has just been documented by #525 not sure what happened and the tests started to fail. I will work on a solution tomorrow evening.
