### ISSUE TITLE
Implement `gql` in Extension method on String

### ISSUE THREAD

**Issue by HofmannZ** [zino-app/graphql-flutter#491]
With the release of Dart 2.7 we can now use extension methods. I would be slick if we could create an extension method on the `String` type to run the `gql`.

**Comment by mainawycliffe** [comment]
Wow, that's cool and would make it easier to parse `documents` to `document nodes`.

**Comment by micimize** [comment]
neat idea but I feel like `'longquery'.gql` would be less legible than `gql('longquery')`. Maybe a builder api for options could be cool though.

```dart
class extension GqlAble on String {
  get gql => _gql(this);
}
```

idk I think we should close this and leave it in "userland"
