### ISSUE TITLE
Not compatible with last stable flutter version

### ISSUE THREAD

**Issue by rolurq** [zino-app/graphql-flutter#495]
**Describe the bug**
When using this plugin the cache provider fails with the following error:
```
../../../.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:
                             ^^^^^^^^^^
```

**Expected behavior**
Using the last stable version of flutter and this plugin the app doesn't compile.

**Comment by marciocesarcorrea** [comment]
Duplicate #475. Use the latest beta version.
