### ISSUE TITLE
AppLifecycleState ENUN

### ISSUE THREAD

**Issue by KaiserGid** [zino-app/graphql-flutter#496]
**Describe the bug**
Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:

**To Reproduce**
error debugging flutter project.

**Expected behavior**
Compiler message:
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] linux ubuntu
 - Version [e.g. 22] 20.04

**Smartphone (please complete the following information):**
 - Device:  avd emualator
 - OS: android
 - Version 10

**Additional context**
AppLifecycleState.suspended has changed to AppLifecycleState.detached.
must make the change in package

**Comment by bsr203** [comment]
hi. you will see previous report of this error in this repo. See one at https://github.com/zino-app/graphql-flutter/issues/472

You may have to use beta version (2.1.1-beta.5)
