### ISSUE TITLE
Support for new version of rxdart

### ISSUE THREAD

**Issue by luizjunior05** [zino-app/graphql-flutter#497]
When do you intend to support rxdart version 0.23?

**Comment by luizjunior05** [comment]
> When do you intend to support rxdart version 0.23?

Sorry, just now I looked at issue #420

**Comment by 5hanth** [comment]
**graphql**: ^2.0.0 started getting rxdart version conflicts with **flutter_bloc**: ^3.1.0

> flutter packages get
> Running "flutter pub get" in flutter_app...                       
> Because no versions of flutter_bloc match >3.1.0 <4.0.0 and flutter_bloc 3.1.0 depends on bloc ^3.0.0, flutter_bloc ^3.1.0 requires bloc ^3.0.0.
> 
> And because no versions of bloc match >3.0.0 <4.0.0, flutter_bloc ^3.1.0 requires bloc 3.0.0.
> And because bloc 3.0.0 depends on rxdart ^0.23.0 and graphql >=1.0.1-beta.8 depends on rxdart ^0.22.0, flutter_bloc ^3.1.0 is incompatible with graphql >=1.0.1-beta.8.
> 
> 
> So, because flutter_app depends on both flutter_bloc ^3.1.0 and graphql ^2.0.0, version solving failed.
> pub get failed (1; So, because flutter_app depends on both flutter_bloc ^3.1.0 and graphql ^2.0.0, version solving failed.)
> exit code 1
>

**Comment by mainawycliffe** [comment]
The fix for this issue has already been merged. There is an issue with the deployment pipeline and tests are failing hence hasn't been released to beta or stable.

**Comment by mainawycliffe** [comment]
I will have a look and see if we can fix the pipeline and release the existing deployments.

**Comment by OTDE** [comment]
Looking forward to seeing this deployed -- I have the exact same use case as @5hanth here.

**Comment by 2ZeroSix** [comment]
@mainawycliffe it's unrelated to this issue, but I think it could be much easier to maintain pipelines and deployments with distinct repositories for graphql and graphql_flutter. I mentioned one issue with version inconsistency I didn't sure how to solve in my PR.
Do you have any discussions or thoughts on this topic between core contributors?
