### ISSUE TITLE
How Can I check network error when mutation failed or something errors when mutation failed

### ISSUE THREAD

**Issue by quochuynh67** [zino-app/graphql-flutter#506]
How Can I check network error when mutation failed or something errors when mutation failed

**Comment by Goolpe** [comment]
Try this
```
final QueryResult result = await GraphQLProvider.of(context).value.mutate(MutationOptions());
if(result.hasException){
    print(result.exceptions);
}
```

**Comment by Hellomik2002** [comment]
you can also use ``` try {} catch(e){}``` with previous code to be sure

**Comment by micimize** [comment]
https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#exceptions
