### ISSUE TITLE
Error: Getter not found: 'suspending'.

### ISSUE THREAD

**Issue by kpguru20001** [zino-app/graphql-flutter#508]
Compiler message:                                                       
../../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:                                
                             ^^^^^^^^^^  
I m doing a simple query but seems to me like its the flutter versioning issue
Please
HELP
Thanks in Advance

**Comment by rakafajar** [comment]
how solved this problem ??

**Comment by kpguru20001** [comment]
Hey @rakafajar can u elaborate what exactly is the problem

**Comment by mainawycliffe** [comment]
@rakafajar Use the latest beta.

**Comment by silkyland** [comment]
Use 3.0.0-beta.3

**Comment by mainawycliffe** [comment]
@HofmannZ the stable version is not getting deployed either, since the current beta is already getting deployed successfully, we should promote it to stable and see if that works.
