### ISSUE TITLE
graphql_flutter-2.1.0 - Error: Getter not found: 'suspending'

### ISSUE THREAD

**Issue by andriy-gulak-ew** [zino-app/graphql-flutter#509]
**Describe the bug**
Error after upgrading to graphql_flutter-2.1.0

**To Reproduce**
Just update the lib to the latest version

**Expected behavior**
Everything should be working fine

**Error**
`Compiler message:
../../flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:
                             ^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.`
 

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

**Comment by bsr203** [comment]
Please search in this repo before raising an issue. If you look up "suspending" you will see recent issues and resolution.

**Comment by andriy-gulak-ew** [comment]
@bsr203 the only thing I've found is this:
https://github.com/zino-app/graphql-flutter/releases/tag/v3.0.0-beta.1
So, you suggest me to update to the version in beta that has been released only 2 days ago, right?  
The other solutions are just to remove the library...

**Comment by saber93** [comment]
I have the same message:


Compiler message:
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:
                             ^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.13.2, on Mac OS X 10.14.6 18G1012, locale en-EG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (3 available)

**Comment by mainawycliffe** [comment]
This is a duplicate issue #489 among others, try the latest beta. It was fixed over a month ago. A major release should be ready soon.
