### ISSUE TITLE
Multipart Upload Test Failing Beta

### ISSUE THREAD

**Issue by kulture-rob** [zino-app/graphql-flutter#514]
**Describe the bug**
test\multipart_upload_test.dart is failing on the beta branch.

**To Reproduce**
1. Clone repo
2. Checkout beta
3. Run `pub get`
4. Run `pub run test`

**Expected behavior**
Test passes

**Desktop (please complete the following information):**
Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17134.950], locale en-US)

**Comment by Waitak** [comment]
I've further described the issue in #525. That issue and this one should probably be merged.

**Comment by kulture-rob** [comment]
Tracked by #525
