### ISSUE TITLE
How to pass Enum to the query

### ISSUE THREAD

**Issue by thphuc** [zino-app/graphql-flutter#515]
Below is the GraphQL doc, it requires to pass [PostOrder!] and PostOrder is an enum.

![image](https://user-images.githubusercontent.com/4323410/71554359-a3147a80-2a50-11ea-8255-dbb0a6c274e1.png)

I created the query:
```
const String getPostsQuery = r'''
  query getPosts($limit: Int, $skip: Int, $order: [PostOrder!]) {
    posts(limit: $limit, skip: $skip, order: $order) {
      results {
        id
        content
        likeCount
        title
        referenceUrl
        postType {
          name
          description
        }
      }
      count
    }
  }
''';
```

I created an enum:
```
enum PostOrder {
  createdAt_ASC,
  createdAt_DESC,
  updatedAt_ASC,
  updatedAt_DESC,
  ACL_ASC,
  ACL_DESC,
  content_ASC,
  content_DESC,
  likeCount_ASC,
  likeCount_DESC,
  title_ASC,
  title_DESC,
  referenceUrl_ASC,
  referenceUrl_DESC,
  postType_ASC,
  postType_DESC,
  id_ASC,
  id_DESC,
}
```

And created the query options like below:
```
final QueryOptions queryOptions = QueryOptions(
      document: getPostsQuery,
      variables: <String, dynamic>{
        'limit': limit,
        'skip': skip,
        'order': [PostOrder.likeCount_DESC]
      });
```

It throw the exception: 

## Converting object to an encodable object failed: Instance of 'PostOrder'

How to pass the order to the query?

**Comment by klavs** [comment]
GraphQL-over-JSON uses string literals as enum values. Dart enums do not behave as strings.

https://graphql.github.io/graphql-spec/June2018/#sec-JSON-Serialization

**Comment by bsr203** [comment]
enum PostOrder {
  @JsonValue('createdAt_ASC')
  createdAt_ASC,
  @JsonValue('createdAt_DESC')
  createdAt_DESC,
  ...
}

then use `json_serializable` to generate the encode/decode code. You may have to use whatever value your server accepts as string value instead of `createdAt_ASC` ...

I guess you already do this for other graphql types.

**Comment by phuc-koli** [comment]
Thanks @klavs and @bsr203 

I tried to add. @JsonValue to my enum:

```
enum PostOrder {
  @JsonValue('createdAt_ASC')
  createdAt_ASC,
  @JsonValue('createdAt_DESC')
  createdAt_DESC,
  @JsonValue('updatedAt_ASC')
  updatedAt_ASC,
  @JsonValue('updatedAt_DESC')
  updatedAt_DESC,
  @JsonValue('ACL_ASC')
  ACL_ASC,
  @JsonValue('ACL_DESC')
  ACL_DESC,
  @JsonValue('content_ASC')
  content_ASC,
  @JsonValue('content_DESC')
  content_DESC,
  @JsonValue('likeCount_ASC')
  likeCount_ASC,
  @JsonValue('likeCount_DESC')
  likeCount_DESC,
  @JsonValue('title_ASC')
  title_ASC,
  @JsonValue('title_DESC')
  title_DESC,
  @JsonValue('referenceUrl_ASC')
  referenceUrl_ASC,
  @JsonValue('createdAt_ASC')
  referenceUrl_DESC,
  @JsonValue('postType_ASC')
  postType_ASC,
  @JsonValue('postType_DESC')
  postType_DESC,
  @JsonValue('id_ASC')
  id_ASC,
  @JsonValue('id_DESC')
  id_DESC,
}
```

Then call the api:

```
...
final QueryOptions queryOptions =
      QueryOptions(document: getPostsQuery, variables: <String, dynamic>{
    'limit': limit,
    'skip': skip,
    'order': [PostOrder.likeCount_DESC]
  });

  final GraphQL graphQL = GraphQL();
  final QueryResult result = await graphQL.graphQLClient.query(queryOptions);
...
```

But I got below exception: **Converting object to an encodable object failed: Instance of 'PostOrder'**

<img width="847" alt="image" src="https://user-images.githubusercontent.com/55618058/71568637-77020380-2afb-11ea-95f4-6f31a1021227.png">

**Comment by bsr203** [comment]
I use Input Object and use like
```
  final result = await client.query(QueryOptions(
      documentNode:  queryDocument,
      variables: MyQueryVariables(abc: xyz).toJson(),
    ));
```
the variable has to be json encodable.

your error indicated that `PostOrder` not  encodable. Try make `json.encode` work on this type? .

**Comment by phuc-koli** [comment]
Thanks @bsr203 again.

Due to the limit time, I decide to apply a work around first by putting the string directly

```
final QueryOptions queryOptions =
      QueryOptions(document: getPostsQuery, variables: <String, dynamic>{
    'limit': limit,
    'skip': skip,
    'order': ['likeCount_DESC']
  });

  final GraphQL graphQL = GraphQL();
  final QueryResult result = await graphQL.graphQLClient.query(queryOptions);
```

It works now. I will come back later to find a better approach.

**Comment by bsr203** [comment]
may be this will work
```
var order = PostOrder.likeCount_DESC;
....

'order': [order.toJson()]
```
this may keep the type safety without using string.

**Comment by MattisBrizard** [comment]
I would use the flutter describeEnum() method.

https://api.flutter.dev/flutter/foundation/describeEnum.html

```
...
final PostOrder order = PostOrder.likeCount_DESC;
final QueryOptions queryOptions =
      QueryOptions(
document: getPostsQuery,
variables: <String, dynamic>{
    'limit': limit,
    'skip': skip,
    'order': [describeEnum(order)]
  },
);
...
```

**Comment by micimize** [comment]
As `graphql-flutter` doesn't currently do any serialization, This is a more general question about enum-to-json serialization.

When I was still using `graphql-to-dart`, `json_serializable` accepted [regular enums](https://github.com/micimize/graphql-to-dart/blob/bee58790f36c708fbb674d6cd09ef4794abc4438/example/lib/graphql/schema.dart#L12-L16) and generated [enum mappings](https://github.com/micimize/graphql-to-dart/blob/bee58790f36c708fbb674d6cd09ef4794abc4438/example/lib/graphql/hero_for_episode.gql.g.dart#L64-L68)

In `major_graphql` I'm using `built_value`'s `EnumClass`

Anyhow, closing as typing/serialization is currently out-of-scope
