### ISSUE TITLE
Passing on variables unsuccessful 

### ISSUE THREAD

**Issue by raxosiris** [zino-app/graphql-flutter#52]
Trying to pass on a variable results in a bad request.

I am making the following query, which is successful:

`String singleFile = """
  query {file(id: "cji4rpaw702zu07920hjzseq4"){
    url
  }}
""";`

but querying for id in a variable format does not work. Perhaps it is an issue with my code, but I have tried several measures and feel hopeless now. 

Here is my code for constructing the query:
`
String singleFile = """
  query {file(id: \$someID){
    url
  }}
""";
`
and here it is inside the component:

`Query(singleFile, 
        variables: {
      'someID' : "cji4rpaw702zu07920hjzseq4"
        },`

I would really appreciate the help.

**Comment by HofmannZ** [comment]
Hmm can't tell if this is an issue with our library or your setup.
Happy to help, so could provide some more details please?

**Comment by raxosiris** [comment]
Certainly. So, what I am trying to do essentially is to query for a file by its id. I have spun up a sample backend using graphql boilerplate (graphQL yoga, Nodejs, Express, Prisma). 

In the schema, we have a files query that fetches the list of all files (what I am interested in is their url). Second is a single file query, that takes id as parameter and fetches an individual file.

I am moving from react native to flutter and my objective is to run a single file query (passing on id dynamically).

The issue I am facing is that while hard-coding the id string works fine, I am not able to pass it on as a variable as you have shown in the example. 

You may also explore the demo endpoint from this file to look at the schema: https://gist.github.com/raxosiris/f3b3b9ce6276c331878645f723e4daab

Here is how I am running the query - one of them works fine, the other one results in a 400 bad request: https://gist.github.com/raxosiris/2b48a051ef3f389b8da75683b180c9b8 

Again, would really appreciate the help.

**Comment by HofmannZ** [comment]
@raxosiris Your GraphQl syntax does not seem to be correct. You always need to declare the variables you use.

So this:
```dart
String singleFileID = """
query {
  file(id: \$someID){
    url
  }
}
""";
```

Should be: 
```dart
String singleFileID = """
query GetFile(\$someID: ID!) {
  file(id: \$someID) {
    url
  }
}
"""";
```

Hope that helps 😉
