### ISSUE TITLE
OptimisticCache fails in constructor

### ISSUE THREAD

**Issue by Waitak** [zino-app/graphql-flutter#520]
**Describe the bug**
Instantiating an OptimisticCache instance fails with the following error when running Web:

    Expected a value of type 'String', but got one of type '_Future<String>'

**To Reproduce**
1. cd .../graphql_flutter-2.1.1-beta.5/example
2. Create lib/local.dart with Git token.
3. flutter channel beta
4. flutter create .
5. flutter run -d chrome

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: v2.1.5-beta.5

**Additional context**
- [Error output](https://github.com/zino-app/graphql-flutter/files/4022072/dump.txt)
- [pubspec.lock](https://github.com/zino-app/graphql-flutter/files/4022416/pubspec.txt) (Saved as pubspec.txt so that Github will allow the upload.)

**Comment by Waitak** [comment]
Further to the above, the problem appears to be the `storagePrefix` in `in_memory_html.dart`. In contrast to the same declaration in `in_memory_io.dart`, it is declared as `String`. Passing in as `FutureOr<String>` causes a runtime error.

**Comment by micimize** [comment]
closed by #524
