### ISSUE TITLE
Set bearer token after create client

### ISSUE THREAD

**Issue by wiktoriasobczyk** [zino-app/graphql-flutter#521]
In the root of application I create a provider with define a GraphQLClient:
**My grapql configuration**
```
class GraphQLConfiguration {
  static HttpLink httpLink = HttpLink(
    uri: "https://randomdata.herokuapp.com/graphql",
  );
  
  ValueNotifier<GraphQLClient> client = ValueNotifier(
    GraphQLClient(
      link: httpLink,
      cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
    ),
  );
  GraphQLClient clientToQuery() {
    return GraphQLClient(
      cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
      link: httpLink,
    );
  }
}
```
**Root of my application**
```class MyApp extends StatelessWidget {
  GraphQLConfiguration graphQLConfig = new GraphQLConfiguration();
  @override
  Widget build(BuildContext context) {
    return GraphQLProvider(
      client: graphQLConfig.client,
      child: MaterialApp(
        title: 'Temp App',
        theme: ThemeData(
          primarySwatch: Colors.green,
        ),
        home: LoginScreen(),
      ),
    );
  }
}
```
After my first register mutation in my child LoginScreen I receive Bearer token in response. 
**How can I modify my graphql client after get the bearer token and add  to headers for later requests??**

**Comment by mainawycliffe** [comment]
You can watch the authentication state and then once it changes to authenticated, change the value of the client accordingly. Once you do this, your app will rebuild automatically with the new client containing the authentication link.

**Comment by wiktoriasobczyk** [comment]
@mainawycliffe really thank you for reponse :) How can I change the value of the client accordingly after authentication?

**Comment by KammererTob** [comment]
You can use an `AuthLink` for that:

```
    final AuthLink authLink = AuthLink(
      getToken: () async { return 'Bearer ' +  await _authTokenRepository.getJWT(); }
    );
```

**Comment by lennartschoch** [comment]
Is there any specific reason for making the clients properties immutable?
Me (and I guess a lot of other devs) would highly appreciate an option to set headers for each individual request instead of having to replace the whole client every time.
Apart from that, replacing the client also makes it quite hard to test and to mock.
When my client wrapper is able to interchange the whole client at any time, it seems uncertain to me whether I am working with a mock client still.

**Comment by abdulwahid24** [comment]
@wiktoriasobczyk I am on the same issue, Would you please help me out this by sharing how did you resolve the problem?

**Comment by brokercl** [comment]
same issue

**Comment by wiktoriasobczyk** [comment]
@abdulwahid24 , @brokercl sorry for my late response, it was my first project in flutter, but I've that configuration of GraphQLClient
https://github.com/wiktoriasobczyk/Planner/blob/master/lib/src/graphql/graphql-config.dart
```
class GraphQLConfiguration {
  static Link link = null;
  static HttpLink httpLink = HttpLink(
    uri: "http://10.0.2.2:3001/graphql",
  );

  static void setToken(String token) {
    AuthLink alink = AuthLink(getToken: () async => 'Bearer ' + token);
    GraphQLConfiguration.link = alink.concat(GraphQLConfiguration.httpLink);
  }

  static void removeToken() {
    GraphQLConfiguration.link = null;
  }

  static Link getLink() {
    return GraphQLConfiguration.link != null
        ? GraphQLConfiguration.link
        : GraphQLConfiguration.httpLink;
  }

  ValueNotifier<GraphQLClient> client = ValueNotifier(
    GraphQLClient(
      link: getLink(),
      cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
    ),
  );

  GraphQLClient clientToQuery() {
    return GraphQLClient(
      cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
      link: getLink(),
    );
  }
}
```

**Comment by abdulwahid24** [comment]
@wiktoriasobczyk Thank you very much, I was waiting for your response and till then I continued with anonymous users. :)

**Comment by micimize** [comment]
Seems like this is resolved, but if any of y'all need more help troubleshooting, come to the `support` channel in the [discord](https://discord.gg/tXTtBfC)

**Comment by brokercl** [comment]
hello there
when I run 
  static void setToken(String token) {
    print('token ' + token);
    AuthLink alink = AuthLink(getToken: () => 'Bearer ' + token);
    GraphQLConfiguration.link = alink.concat(GraphQLConfiguration.httpLink);
  }

the flutter SDK response :
  String operator +(String other) native "String_concat";
Exception has occurred.
ArgumentError (Invalid argument(s))
I printed the token and looks fine
what could be the issue ?
greetings

**Comment by micimize** [comment]
@brokercl looks like that is an issue with `'token ' + token`, like maybe `token` is `null` or something.
