### ISSUE TITLE
Flutter web fails running because of cache property in GraphQLClient

### ISSUE THREAD

**Issue by chynamyerz** [zino-app/graphql-flutter#522]
**Describe the bug**
Failed to load resource: the server responded with a status of 404 (Not Found)
js_primitives.dart:32 ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
js_primitives.dart:32 The following assertion was thrown building KeTaxiApp(dirty):
js_primitives.dart:32 Expected a value of type 'String', but got one of type '_Future<String>'
js_primitives.dart:32 
js_primitives.dart:32 Either the assertion indicates an error in the framework itself, or we should provide substantially
js_primitives.dart:32 more information in this error message to help you determine and fix the underlying cause.
js_primitives.dart:32 In either case, please report this assertion by filing a bug on GitHub:
js_primitives.dart:32   https://github.com/flutter/flutter/issues/new?template=BUG.md
js_primitives.dart:32 
js_primitives.dart:32 The relevant error-causing widget was:
js_primitives.dart:32   KeTaxiApp org-dartlang-app:///packages/ke_taxi/main.dart:14:10
js_primitives.dart:32 
js_primitives.dart:32 When the exception was thrown, this was the stack:
js_primitives.dart:32 package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49      throw_
js_primitives.dart:32 package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 45:3        castError
js_primitives.dart:32 package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:10  cast
js_primitives.dart:32 package:dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 661:12                _check
js_primitives.dart:32 package:graphql_flutter/src/caches.dart 15:8                                              new
js_primitives.dart:32 package:ke_taxi/main.dart 26:17                                                           build
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 4364:28                                        build
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 4296:15                                        performRebuild
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 4020:5                                         rebuild
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 4279:5                                         [_firstBuild]
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 4274:5                                         mount
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 3269:13                                        inflateWidget
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 3063:12                                        updateChild
js_primitives.dart:32 package:flutter/src/widgets/binding.dart 1054:16                                          [_rebuild]
js_primitives.dart:32 package:flutter/src/widgets/binding.dart 1025:5                                           mount
js_primitives.dart:32 package:flutter/src/widgets/binding.dart 968:16                                           <fn>
js_primitives.dart:32 package:flutter/src/widgets/framework.dart 2487:19                                        buildScope
js_primitives.dart:32 package:flutter/src/widgets/binding.dart 967:12                                           attachToRenderTree
js_primitives.dart:32 package:flutter/src/widgets/binding.dart 847:24                                           attachRootWidget
js_primitives.dart:32 package:flutter/src/widgets/binding.dart 830:7                                            <fn>
js_primitives.dart:32 package:dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 50:19           internalCallback
js_primitives.dart:32 
js_primitives.dart:32 ════════════════════════════════════════════════════════════════════════════════════════════════════

**To Reproduce**
final ValueNotifier<GraphQLClient> client = ValueNotifier(
      GraphQLClient(
        cache:  InMemoryCache(),
        link: httpLink,
      ),
    );

**Expected behavior**
Should execute in all device platforms with cache included in the GraphQLClient

**Desktop (please complete the following information):**
 - OS: [e.g. Linux desktop]
 - Version [e.g. 18.04]

**Additional context**
It works on mobile devices

**Comment by Waitak** [comment]
This is the same issue as #520 and is fixed in pull request #524.

**Comment by micimize** [comment]
probably closed by #524 but confirmed to not be an issue in #590, so was at least included in `3.1.0-beta.1`
