### ISSUE TITLE
How can I do server-side rendering using graphql-flutter?

### ISSUE THREAD

**Issue by zwl1619** [zino-app/graphql-flutter#527]
Can I use  `zino-app/graphql-flutter`  for   `flutter-web` ?
And if I can, how can I do server-side rendering using `zino-app/graphql-flutter`?

**Comment by jamiejackherer** [comment]
What would you be "rendering" on the server.

**Comment by zwl1619** [comment]
I want to try replacing `apollo+Next.js+react` with `zino-app/graphql-flutter + flutter-web`, and it need server side rendering.

**Comment by mainawycliffe** [comment]
flutter for web is still young and some features such as SSR might not be as good as compared to their counterparts - React, Angular, Vue. It is improving by the day though.
