### ISSUE TITLE
Enable subsequent requests through managing cookies

### ISSUE THREAD

**Issue by chynamyerz** [zino-app/graphql-flutter#531]
**Is your feature request related to a problem? Please describe.**
It is daunting to manage cookies manually especially when you want to do subsequent requests to make sure a user is authentic and authorized.

**Describe the solution you'd like**
final HttpLink httpLink = HttpLink(
    uri: 'https://api.github.com/graphql',
    credentials: 'include' // As it's seen from the apollo-link-http package in React.
  );

**Describe alternatives you've considered**
I am manually managing the taken created from the server using the JWT instead of using cookies

**Additional context**

**Comment by mainawycliffe** [comment]
Have you tried the `AuthLink` which provides authentication to a GraphQL Link?

**Comment by micimize** [comment]
Closing in favor of #592 because the thread is more active there
