### ISSUE TITLE
Graphql is not working in unit tests

### ISSUE THREAD

**Issue by andriy-gulak-ew** [zino-app/graphql-flutter#532]
**Describe the bug**
In unit tests, I'm testing some of the queries and mutations to my graphql api. I'm running my tests using `flutter test` command in terminal and everything was working before updating to 3.0.0-beta.3. 

After updating to I've faced the following problem:
```dart
Failed to load "/home/myuser.name/AndroidStudioProjects/myapp/test/api_test.dart": MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
  package:flutter/src/services/platform_channel.dart 319:7  MethodChannel.invokeMethod
  ===== asynchronous gap ===========================
  package:path_provider/path_provider.dart 92:22            getApplicationDocumentsDirectory
  package:graphql_flutter/src/caches.dart 10:25             flutterStoragePrefix.<fn>
  package:graphql_flutter/src/caches.dart 10:66             flutterStoragePrefix
  package:graphql_flutter/src/caches.dart 9:24              flutterStoragePrefix
  package:graphql_flutter/src/caches.dart 15:46             new InMemoryCache
  package:myapppackage/network/api/client.dart 31:14            API.initGraphQLClient
  api_test.dart 80:9                                        main
```
I've found the following workaround. I've added this code to the main() function of my unit test before initializing the graphql client:
```dart
  const MethodChannel channel = MethodChannel('plugins.flutter.io/path_provider');
  channel.setMockMethodCallHandler((MethodCall methodCall) async {
    return ".";
  });
``` 
I run my tests once again and the error disappeared, but I've faced another problem.

Every query/mutation fails with the following exception:
```dart
ClientException: Unhandled Failure FormatException: Unexpected end of input (at character 1)

^


```

**If I run my code not in unit tests, but as part of the app (on a device), everything works as expected.**

**To Reproduce**
1. Just try to run any query/mutation in a unit test using graphql 3.0.0-beta.3

**Expected behavior**
The same as in the previous versions of the graphql package

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

**Comment by andriy-gulak-ew** [comment]
@eusdima @HofmannZ what do you think? What should I do in this case? This is still an issue

**Comment by skol101** [comment]
@HofmannZ please, take a look.

**Comment by shkim** [comment]
I have exactly same problem, too.
Query always fails with FormatException in unit test.

**Comment by dar-mehta** [comment]
i had the same issue when i was trying to connect to a graphql endpoint that required different headers than the default one in AuthLink (`"Authorization": token`)

**Comment by micimize** [comment]
in `4.0.0-beta` the `InMemoryStore` is actually a purely in-memory store, so it doesn't depend on `path_provider`, so this shouldn't be an issue when using it anymore. If this is still an issue for anyone comment and I'll leave it open

**Comment by ldemyanenko** [comment]
Same issue here. From unit tests Im getting 
``` OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected end of input (at character 1)

^
), graphqlErrors: [])
```

**Comment by ldemyanenko** [comment]
We are using flutter tests to check that API has correct set of endpoints needed for the app. So app makes real calls from test.
What we currently experiencing is that 5.0.0 version of this lib works when app is launched, but when calling endpoints from tests it results with error 

```
QueryResult(source: QueryResultSource.network, data: null, context: Context({}), exception: OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected end of input (at character 1)

^
), graphqlErrors: []), timestamp: 2021-08-29 15:07:00.968544)
```
Workaround doesn't work for me

**Comment by DholaSain** [comment]
> We are using flutter tests to check that API has correct set of endpoints needed for the app. So app makes real calls from test.
> What we currently experiencing is that 5.0.0 version of this lib works when app is launched, but when calling endpoints from tests it results with error
> 
> ```
> QueryResult(source: QueryResultSource.network, data: null, context: Context({}), exception: OperationException(linkException: ResponseFormatException(originalException: FormatException: Unexpected end of input (at character 1)
> 
> ^
> ), graphqlErrors: []), timestamp: 2021-08-29 15:07:00.968544)
> ```
> 
> Workaround doesn't work for me

have you fixed it yet or not?

**Comment by komalkhatri08** [comment]
any update on this issue ?
