### ISSUE TITLE
Error: Getter not found: 'suspending'.    case AppLifecycleState.suspending:             

### ISSUE THREAD

**Issue by Flutter-Stack** [zino-app/graphql-flutter#535]
Compiler message:                                                       
../../mobile-applications/flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/graphql_flutter-2.1.0/lib/src/widgets/cache_provider.dart:64:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:                                
                             ^^^^^^^^^^                                 
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
      
                                                                  
* Where:                                                                
Script '/home/suresh-kumara/projects/mobile-applications/flutter-sdk/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
                      
                                                  
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/home/suresh-kumara/projects/mobile-applications/flutter-sdk/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

$ flutter doctor -v 

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/suresh-kumara/projects/mobile-applications/flutter-sdk/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/suresh-kumara/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Redmi Note 7 Pro • 6be66815 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by ankur014** [comment]
Looks like there was a [PR](https://github.com/flutter/engine/pull/11913) in flutter master channel that updated the enum AppLifecycleState.suspending to AppLifecycleState.detached.

**Comment by Flutter-Stack** [comment]
thank you @ankur014
