### ISSUE TITLE
GraphQLError Undefined location on exception

### ISSUE THREAD

**Issue by keletsomolefe** [zino-app/graphql-flutter#537]
**Describe the bug**
On a query with an exception, locations is set to null on 3.0.0-beta.3 this is because raw['locations'] gives Map of type Map<String, dynamic> while the code is checking for Map<String, int>

https://github.com/zino-app/graphql-flutter/blob/d17b57b52d3cb985a8c8d7025a242bbcddecabfb/packages/graphql/lib/src/exceptions/graphql_error.dart#L33

**To Reproduce**
1. Create a query that will return you errors which have locations
2. Check the query result's exception
3. e.g. result.exception.graphqlErrors[0].locations, result is an instance of 'QueryResult'

**Comment by micimize** [comment]
This is outdated / likely solved by using `gql_links` in `4.0.0-beta.1` (#648)
