### ISSUE TITLE
Change Link in Client Graphql provider

### ISSUE THREAD

**Issue by AhmedAlaa96** [zino-app/graphql-flutter#539]
Hi, everyone

I want to change link in client in value Notifier:

` client = ValueNotifier(`
 `             GraphQLClient(`
 `                   cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),`
`                     link: link,`
` ),`
 ` );`

to add access token after **signin**

**Comment by micimize** [comment]
Not sure what you mean here, but please come by the `#support` channel in [discord](https://discord.gg/tXTtBfC) for usage questions
