### ISSUE TITLE
`Refetch` should not use cache

### ISSUE THREAD

**Issue by j-deng** [zino-app/graphql-flutter#541]
**Is your feature request related to a problem? Please describe.**
I have a long query list, want to use `cacheFirst` policy in case of refreshing every time when pushing or pop routes. But also want to use `refetch` in `RefreshIndicator`, for now it will use query options' fetch policy and will enable cache by default. refs: https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/core/query_manager.dart#L222

**Describe the solution you'd like**
So I think we can copy and update options' fetch policy, it will not affect other functions.

**Comment by j-deng** [comment]
Here is a possible fix https://github.com/zino-app/graphql-flutter/pull/542

**Comment by Sh1d0w** [comment]
+1 about this feature. Currently `refetch` is useless if your fetch policy involves caching as it never retrieves the data from the server.

**Comment by micimize** [comment]
Good point. I don't think there's any situation where you would want to `refetch` from the cache because [you've already got a stream of updates implicitly](https://github.com/apollographql/apollo-client/issues/5515#issuecomment-586382671)

**Comment by prinze77** [comment]
+1 about this feature.
