### ISSUE TITLE
Improve documentation. Don't rely on Apollo.

### ISSUE THREAD

**Issue by ph55** [zino-app/graphql-flutter#544]
Even if this project took inspiration from the Apollo GraphQL client.
It should have it's own documentation and explanation of how things work.

From https://pub.dev/packages/graphql_flutter:

> dataIdFromObject is required and has no defaults. Our implementation is similar to Apollo's, requiring a function to return a universally unique string or null. The predefined typenameDataIdFromObject we provide is similar to apollo's default:

> However, note that graphql-flutter does not inject __typename into operations the way Apollo does, so if you aren't careful to request them in your query, this normalization scheme is not possible

And there is more.
So as user who using GraphQL for first time - I need to go to Apollo documentation and find these things.

Feels weird to learn how library works by another's library documentation.

**Comment by mainawycliffe** [comment]
I have to agree with you. We need to rebuild our docs from the grounds up, with minimal apollo references to make it easier to use for everyone.

**Comment by micimize** [comment]
merging into #741 – v4 improves docs a lot but there is much that could still be done
