### ISSUE TITLE
cache doesn't work

### ISSUE THREAD

**Issue by awaik** [zino-app/graphql-flutter#545]
Thank you for such a cool package!

**Describe the bug**
When I use cache from an official example it doesn't work. The same in my app.

**To Reproduce**
Please look here, I made a post with screencast 
https://stackoverflow.com/questions/59526017/cache-in-grapghql-flutter-package-settings-and-how-to-check-it-works

**Comment by jifalops** [comment]
The cache doesn't write until the app loses focus essentially. See https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql_flutter/lib/src/widgets/cache_provider.dart#L49.

**Comment by awaik** [comment]
Hello,
I tried close and open the example app - the result is the same.
I think I do something wrong, but it was quicker and easier to make my own cache with BLoC pattern and Shared preferences package :)
So, now work package for GraphQl and separate logic for caching.
<img src="https://habrastorage.org/webt/mp/wm/so/mpwmsofwytpp02e_qgmlalv-p0m.gif" />

**Comment by micimize** [comment]
The examples are meant to be standalone - as such they use separate clients and caches. The consequence of this is that it is [re-instantiated every mount](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql_flutter/example/lib/graphql_widget/main.dart#L38). In other words, every time you navigates to the example's route, you get a new cache, so you can't see the caching effects. For a more substantial example where you can see if the cache is working, see [the starwars example](https://github.com/zino-app/graphql-flutter/blob/master/examples/starwars/lib/main.dart)

If it still seems broken, comment and I'll investigate more
