### ISSUE TITLE
Can't handle exception when server unreacheble.

### ISSUE THREAD

**Issue by braindamagedman** [zino-app/graphql-flutter#548]
**Describe the bug**
When Query executes and server unavailable i got error in log:

E/flutter ( 1567): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.
E/flutter ( 1567): Receiver: null
E/flutter ( 1567): Tried calling: host
E/flutter ( 1567): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 1567): #1      translateNetworkFailure (package:graphql/src/exceptions/io_network_exception.dart:14:31)
E/flutter ( 1567): #2      translateFailure (package:graphql/src/exceptions/exceptions.dart:13:10)
E/flutter ( 1567): #3      new HttpLink.<anonymous closure>.onListen (package:graphql/src/link/http/link_http.dart:104:38)
E/flutter ( 1567): <asynchronous suspension>
E/flutter ( 1567): #4      _runGuarded (dart:async/stream_controller.dart:807:24)
E/flutter ( 1567): #5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:686:7)
E/flutter ( 1567): #6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:416:13)
E/flutter ( 1567): #7      _StreamController._subscribe (dart:async/stream_controller.dart:685:18)
E/flutter ( 1567): #8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)
E/flutter ( 1567): #9      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)
E/flutter ( 1567): #10     Stream.first (dart:async/stream.dart:1251:25)
E/flutter ( 1567): #11     QueryManager._resolveQueryOnNetwork (package:graphql/src/core/query_manager.dart:119:9)
E/flutter ( 1567): #12     QueryManager.fetchQueryAsMultiSourceResult (package:graphql/src/core/query_manager.dart:97:17)
E/flutter ( 1567): #13     QueryManager.fetchQuery (package:graphql/src/core/query_manager.dart:75:9)
E/flutter ( 1567): #14     QueryManager.query (package:graphql/src/core/query_manager.dart:46:12)
E/flutter ( 1567): #15     GraphQLClient.query (package:graphql/src/graphql_client.dart:106:25)
E/flutter ( 1567): #16     ScheduleApi.queryLessons (package:brics_app/backend/schedule_api.dart:23:43)

```
try {
      final QueryResult data = await client.query(
        QueryOptions(
          documentNode: gql("""
        query ReadLessons(...) { 
          lessons(
           ...
          ) {
           ...
          }
        }
        """),
          variables: {
          ...
          },
        ),
      );

      final List<Map<String, dynamic>> lessons = data.data['lessons'].cast<Map<String, dynamic>>();
      return lessons;
    } catch (e) {
      // This does not executed!
      print (e);
    }
```

Problem is - i don't get error in catch block!

In io_network_exception.dart `host: failure.address.host,` failure.address is null. But even if i replace this line by `host: failure.address?.host,` i still can't catch exception. I that case i only receive null data from Query.

I think this issue related to  #543

**To Reproduce**
1. Ensure that your host unreacheble
2. Run query
3. Try to catch error

**Expected behavior**
Error can be handled in catch block.

**Comment by braindamagedman** [comment]
I just found, that in case i fix NoSuchMethodError i receive connection exception in QueryResult.

I also see that you use same fix (`host: failure.address?.host,`) in beta branch.

So this bug can be closed, i think.

**Comment by ant-ds** [comment]
I have the same error, still unable to catch it. Did you manage to catch this NoSuchMethodError?
