### ISSUE TITLE
Regression: flutter web no longer works

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#549]
Hi! Recently I've upgraded to the latest version of graphql.

I think the import of **"io_network_exception.dart"** on **"package:graphql/src/exceptions/exceptions.dart"** makes the package incompatible with web projects.

See the related [line](https://github.com/zino-app/graphql-flutter/blob/d71b553fe96231d14aa0dde905afca5e2d592866/packages/graphql/lib/src/exceptions/exceptions.dart#L2)

_Originally posted by @marcgraub in https://github.com/zino-app/graphql-flutter/issues/295#issuecomment-577743510_

**Comment by micimize** [comment]
was a stupid mistake - should be an easy fix... at least for that line

**Comment by binarypie** [comment]
This also broke dart web in general as it is we can't adopt the 3.x releases.

**Comment by micimize** [comment]
closed by #590 and released in `3.1.0-beta.1`
