### ISSUE TITLE
Test Server

### ISSUE THREAD

**Issue by gedw99** [zino-app/graphql-flutter#55]
It would be nice if a basic test server in whatever language could be added to the repo.

It would help me with seeing what the Dart code expects to get from the server and also see patterns of usage.

**Comment by thosakwe** [comment]
You can implement a GraphQL server in Dart with: https://github.com/angel-dart/graphql/tree/master/graphql_parser

The documentation is lacking, to be honest, but there's a directory with an example app + GraphiQL.

**Comment by micimize** [comment]
I made an npm package [starwars-test-graphql-server](https://www.npmjs.com/package/starwars-test-graphql-server) for this, and want to use it for bootstrapping the example into some kind of starwars-schema-based TODOMVP equivalent for graphql clients

It would naturally be best to have an actual dart server that fits more naturally with the workflow, but function first IMO

**Comment by thosakwe** [comment]
There's https://github.com/angel-dart/graphql (Dart server), but it's not yet complete (will be by the release of Angel 2.0).

**Comment by micimize** [comment]
@thosakwe congrats on reaching 2.0! A self-contained / runnable example server built with Angel and backed with static data would definitely be the ideal solution here. If you don't end up publishing one yourself I'll probably figure out how to bundle your [starwars example](https://github.com/angel-dart/graphql/blob/master/example_star_wars/lib/star_wars.dart) (basically what I did with `starwars-test-graphql-server`)

**Comment by thosakwe** [comment]
Yes, the Star Wars example is the example server you’re looking for. I will
officially release Angel 2 this weekend, and by then, I’ll be sure to
finish the documentation, and make a tutorial video.

**Comment by micimize** [comment]
closed with #286
