### ISSUE TITLE
Unhandled exception on queries when there is no internet

### ISSUE THREAD

**Issue by talesbarretoss** [zino-app/graphql-flutter#555]
I wrote a query and it works fine when the device is connected but it throws an exception when there is no internet, right here: https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/exceptions/io_network_exception.dart#L14.
 
<img width="919" alt="Screen Shot 2020-02-05 at 11 03 24" src="https://user-images.githubusercontent.com/44670896/73849331-8403c800-4808-11ea-8d4f-50c36380c30c.png">

**Failure.address** is **null** so this exception is thrown:
```
NoSuchMethodError: The getter 'host' was called on null.
Receiver: null
Tried calling: host
```
The builder is not being called after the exception so my widget remains in loading state.

**Smartphone**
 - Galaxy S8
 - Android 9

**Comment by KammererTob** [comment]
This PR has been merged and has landed in 3.0.1-beta.1: https://github.com/zino-app/graphql-flutter/pull/528
