### ISSUE TITLE
How to update cache after editing data ??? 

### ISSUE THREAD

**Issue by kunaldodiya** [zino-app/graphql-flutter#56]
I have a UpdateProfileScreen which is populated from graphql backend and when I update data.. inside graphql database it is updating.. but when I go back and come again to profile page, the value is older, I have to force close app and reopen.. then only i can see the changes :)

**Comment by KammererTob** [comment]
For `InMemoryCache` you can currently only reset the whole cache.

`client.cache.reset();`

**Comment by kunaldodiya** [comment]
that did worked for now.. but an approach to making it more usable like updating cache would be rather nice feature to implement, it must be in roadmap :)
