### ISSUE TITLE
How to clear cache of existing data

### ISSUE THREAD

**Issue by bamoha** [zino-app/graphql-flutter#560]
Hello, When I log into another account with my app, data from the old account are shown for the new one. I have tried using `fetchPolicy: FetchPolicy.noCache,` but to no avail. I also tried using a reset on the NormalisedInMemoryCache on user login. But I dont think I am doing it right. I need help please.

**Comment by micimize** [comment]
Quoting https://github.com/zino-app/graphql-flutter/issues/354#issuecomment-585860138:

```dart
client.cache.reset(); // empty the hash map
await client.cache.save(); // persist empty map to storage
```
if you're doing so and the cache still isn't clearing, or if `fetchPolicy: FetchPolicy.noCache` is incorrectly reading from the cache, please open new issue with code demonstrating the issue
