### ISSUE TITLE
Upload MultiPartFile

### ISSUE THREAD

**Issue by Hellomik2002** [zino-app/graphql-flutter#561]
I have after upgrading mu packages. Can you give some advice and help with uploading
My error 
```
I/flutter (12390): GraphQL Errors:
I/flutter (12390): Variable "$uploadPhoto" got invalid value {}; 
Expected type Upload. Upload value invalid.: Undefined location 
```
Me code 
![image](https://user-images.githubusercontent.com/30003495/74448375-0a717700-4ea5-11ea-91e2-09365fccf7a5.png)
Maybe an error is connected with the back end, I write it on Node js
![image](https://user-images.githubusercontent.com/30003495/74448438-270daf00-4ea5-11ea-97a0-92bf3b497d33.png)

**Comment by micimize** [comment]
yeah I have no idea, but my guess is that your backend expects a `GraphQLUpload` which doesn't conform to the multipart file upload spec or something like that.

**Comment by micimize** [comment]
I'm going to say this is better triaged in the `#support` channel on [discord](https://discord.gg/tXTtBfC)
