### ISSUE TITLE
Support for Absinthe Phoenix?

### ISSUE THREAD

**Issue by edisonywh** [zino-app/graphql-flutter#562]
**Describe the bug**
Right now the websocket connection does not work with Absinthe servers (which uses Phoenix protocols). This is because Phoenix's websocket handshake is a little different.

Here's an example implementation of the protocol: https://www.npmjs.com/package/phoenix-socket

Someone also ported over to Dart, over here: https://pub.dev/packages/absinthe_socket, but that library uses observer, whereas I'm hoping to just keep to one single GraphQL client if possible.

**Expected behavior**
Able to establish subscription to Absinthe (Phoenix server)

**Comment by edisonywh** [comment]
Any update on this? I understand if support for Phoneix is way too specific, but perhaps if someone can tell me if there are possibility to swap out the WebSocket negotiation protocol, then I could maybe try my hand at writing an adapter for Phoenix?

**Comment by klavs** [comment]
@edisonywh, instead of adjusting the existing WebSocket implementation, you might be able to implement a custom Link which uses `package:absinthe_socket` internally, but translates the results back to a format this client expects.

**Comment by edisonywh** [comment]
Thanks for the pointers! I am going to try it out and will report back if I can get it to work!

**Comment by edisonywh** [comment]
How would I go about disposing the listeners? So for example I want to dispose all current listeners to the Observer, and also disconnect from the socket if something happens, how would I do that?

**Comment by edisonywh** [comment]
Hey so I gave this some try and I still couldn't figure this out, do you have a little more pointers? Where should I do my setup code? (inside or outside the link), and how do I "translate" the result?

Another main problem is that the library uses Notifier/Observer, I am able to listen to the values by printing it with my observer, but how do I convert that value to something that this library can consume?

**Comment by matthewford** [comment]
@edisonywh did you manage to get anywhere with that?

**Comment by edisonywh** [comment]
@matthewford no I wasn't able to, but I only needed subscription for that one particular screen so I just used it directly there. Would've loved to use just a single GraphQL interface but I didn't want to spend too long on it.

**Comment by knaeckeKami** [comment]
i wrote a very basic gql link for that, see https://github.com/knaeckeKami/gql_phoenix_link
it's not production ready and not very well tested, but it works
