### ISSUE TITLE
Update GraphQL Upload docs.

### ISSUE THREAD

**Issue by jghyllebert** [zino-app/graphql-flutter#568]
Currently the docs show an outdated example of the upload functionality.

When following the example loosely I get a deprecation warning.

>I/flutter (16806): ⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️ DEPRECATION WARNING ⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️
I/flutter (16806): 
I/flutter (16806): Please do not use `File` direcly anymore. Instead, use
I/flutter (16806): `MultipartFile`. There's also a utitlity method to help you
I/flutter (16806): `import 'package:graphql/utilities.dart' show multipartFileFrom;`
I/flutter (16806): 
I/flutter (16806): ⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️⚠️️️️️️️️ DEPRECA

**Comment by micimize** [comment]
closed in `4.0.0-beta.1` #648 in migration to `gql_http_link`
