### ISSUE TITLE
¿Is there any way to read the request headers?

### ISSUE THREAD

**Issue by Batres35** [zino-app/graphql-flutter#569]
I need to receive and read a token from a GraphQL server through the response headers, i can send the token from the server through the headers but I don't know how to read it.
How can i do that with this plugin?

**Comment by klavs** [comment]
@Batres35 you might want to look into how Links work here. Link is the network interface so anything related to transport goes there. You might be able to solve your problem either by using the AuthLink or implementing a custom stateful Link

**Comment by Batres35** [comment]
I did it, i had to modify the class "link_http.dart" of GraphQL after this line:
`response = await fetcher.send(request);`
Where "rensponse" has the response header, thanks a lot!

**Comment by MT-BlueGo** [comment]
What do you exactly mean with modify a class outside your project? I'm currently having the same issue as I need information from the response headers but could not find a way to access them for right now. 

I' appreciate any assistance!
