### ISSUE TITLE
No way to call a function after a mutation finishes

### ISSUE THREAD

**Issue by ZM123** [zino-app/graphql-flutter#570]
When using a `NormalizedInMemoryCache`, I would like to refetch a certain query after a mutation has completed. If I use the Mutation widget, and call the runMutation function to run the mutation, it returns immediately and so I cannot await the result before calling the refetch function. Thus, the refetch occurs too early and the data that is refetched isn't the data that exists after the mutation.

Alternatively, I found that it's possible to use the `mutate` function on the client directly - like so:
```dart
final MutationOptions options = MutationOptions(
  documentNode: gql(r'''
      mutation PerformMutation($id: ID!) {
        performMutation(id: $id) {
          __typename
          id
          value
        }
      }
    '''),
  variables: <String, String>{
    'id': this.id,
  },
);

// get the ValueNotifier<GraphQLClient> that is passed into the root GraphQLProvider
final client = GraphQLConfiguration.getClient();
await client.value.mutate(options);
```
this doesn't update the cache/rebroadcast the queries - and so the rest of the data (e.g. the value field for the object with the mutated id) is stale. Is there any way to fix either of the above issues?

Happy to provide any more information if needed!

edit: after looking through the source code, this may be related to #566 : it looks like runMutation does in fact return an object that allows for accessing the networkResult, but since the return type of that function is void dart doesn't let me access that variable. Changing the typing may be all that is needed

**Comment by micimize** [comment]
(at least now) `mutate` returns a  `MultiSourceResult` and the return type is now correct, so yes this should be closed by #567. Please come by the `#support` channel in [discord](https://discord.gg/tXTtBfC) if you have any questions
