### ISSUE TITLE
String with line break get error: Syntax Error: Unterminated string.: Undefined location

### ISSUE THREAD

**Issue by steve28100** [zino-app/graphql-flutter#579]
Hello I am trying to enter the String with line break the value from String is like this:

Example:
`String value = "Hello\nHow are you\n";`

```
String mutation = 
return """
        mutation{
        submitForm(input: {
            content: "$value"
        }) {
            success
        }
      }
    """;
```
However after I insert String that contain '\n' the GraphQL call is error and I got:

> GraphQL Errors:
> Syntax Error: Unterminated string.: Undefined location

Is there any way to enter string with line break? Thanks

**Comment by klavs** [comment]
Nothing special in this implementation.

Escape `\n` -> `\\n` or use multiline string enclosed in `"""`

**Comment by steve28100** [comment]
> Nothing special in this implementation.
> 
> Escape `\n` -> `\\n` or use multiline string enclosed in `"""`

I have tried them nothings work.

Using function to replace the `\n` -> `\\n` like this:
`query.replaceAll("\n", '\\n');`

Also try wrap the String using `"""` or  `'''`

Is there any other solution or can you give the example?

**Comment by micimize** [comment]
@steve28100 You should pass variables [as a map in `QueryOptions`](https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter#queries)
```dart
Query(
  options: QueryOptions(
    documentNode: gql(readRepositories), // this is the query string you just created
    variables: {
      'value': "Hello\nHow are you\n",
    }, // ...
```
