### ISSUE TITLE
What makes this package better than any other package?

### ISSUE THREAD

**Issue by alqinae** [zino-app/graphql-flutter#58]
Hello,

What makes this package better than any other package?
In other words, why shall I consider using your package over any other package?

I am confused as I found 3 or more packages for GraphQL and Flutter, and I don't know which package to start with.

**Comment by eusdima** [comment]
If you have found 3 more libraries and you don't provide the links to any of them then we can't provide a proper comparison.

**Comment by alqinae** [comment]
The first one is yours. The second one is: https://pub.dartlang.org/packages/graphql_client, and the third one is: https://pub.dartlang.org/packages/graphql. I think that the third one is not ready yet.

**Comment by alqinae** [comment]
I am totally new to Dart and Flutter, I found out that there is a rating system for packages and your package rating is 95%. The other packages are outdated and premature. Thank you for your time and sorry for wasting it.

Danke 🌹😉

**Comment by HofmannZ** [comment]
@alqinae No worries 😉
