### ISSUE TITLE
Managed State Ideas

### ISSUE THREAD

**Issue by fredgrott** [zino-app/graphql-flutter#581]
Just a thought, if you use stateful widget as di and service locator patterns you get state management without forcing devs into that singleton mess that inherited does..

I use flutter modular see https://github.com/Flutterando/modular

Not the only stateful widget solution out there but one of the better ones, my own internal one had sucked :)

**Comment by micimize** [comment]
Seems like an interesting project but integration with it would make more sense as a 3rd party library
