### ISSUE TITLE
Feature Request: set type QueryOptions and MutationOptions like Apollo

### ISSUE THREAD

**Issue by isaiahtaylorhh** [zino-app/graphql-flutter#583]
**Is your feature request related to a problem? Please describe.**
In Apollo, you can specify `mutate(MutationOptions<CreateTestInput>{variables: {...}})`. This is very powerful because it enforces the schema's requirements for a query or mutation. This is especially powerful when used in conjunction with automatic type generation like this: https://github.com/micimize/graphql-to-dart .

**Describe the solution you'd like**
```dart
class MutationOptions<T> extends BaseOptions {
  MutationOptions({
    // ...
    Map<String, T> variables, // used to be <String, dynamic>
    // ...
  }) : super(
    // ...
  );
}
```

Same for query.

**Additional context**
I've got this running locally and it works great. If I get some extra time I'll put it up in a PR but that is unlikely.

**Usage**:

```dart
await client.mutate(
  MutationOptions<CreateTestInput>(
    documentNode: gql(myMutation),
    variables: {
      "input": myTestInput, // myTestInput is CreateTestInput
    })
);
```

**Comment by isaiahtaylor** [comment]
This could also be extended to the QueryResult so that `QueryResult.data is MySchemaType`.

**Comment by micimize** [comment]
We wouldn't be able to do `Map<String, T>`, but we can use the generated variable type as well.

**Comment by micimize** [comment]
Merging in to #636 and continuing convo there
