### ISSUE TITLE
Cache: nodes sometimes appear as LazyCacheMap and sometimes as an array

### ISSUE THREAD

**Issue by gunnardag** [zino-app/graphql-flutter#584]
**Describe the bug**
When not using cache, this is not a problem, the nodes all give a correct data.
When using cache, the nodes sometimes appear as LazyCacheMap and sometimes as an array
version: 3.0.1-beta.2

**To Reproduce**
Not sure how to create this from scratch

**Expected behavior**
When fetching nodes I expect each node to be a LazyCacheMap

**Screenshots**
Top is the code
middle is the printed messages
bottom is the content of the array "wat"
![image](https://user-images.githubusercontent.com/1760192/76706782-1047bb80-66e2-11ea-89be-8cd71aa2e427.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10

**Comment by micimize** [comment]
Hmm - the array is a cache reference, so my guess is that the entity is not being found in the cache, which could be due to some known issues in the cache.

Is this happening while trying to load from a persisted cache at app start?

**Comment by gunnardag** [comment]
Yes this is on app start

**Comment by gilmarsquinelato** [comment]
Any update on this issue?
I'm having the same problem, and this only happens when using `CacheProvider`, without it the app starts normally.

**Comment by micimize** [comment]
the v4 alpha has a reworked caching layer that solves this issue by doing away with `LazyCacheMap` (#648)

**Comment by micimize** [comment]
solved in `4.0.0-beta`
