### ISSUE TITLE
Query widget should rebuild if cache changes from other Query

### ISSUE THREAD

**Issue by christian-muertz** [zino-app/graphql-flutter#587]
**Is your feature request related to a problem? Please describe.**
If i have two different widgets showing the same query or a slightly different one, i want to keep them in sync showing the same information. When one query for example refreshes I want the second one to show the new information as well.

**Describe the solution you'd like**
I would like the Query widget to rebuild when new information represented by this query is available in the cache. 

**Additional context**
First of all i am quite new to graphql clients and for sure i am just implementing something wrong. 
I understand the concept of normalization and for me it would make sense if a normalized entity in the cache changes that all queries that contain that entity rebuild their subtree with the new information available in the cache?! 

[This apollo page](https://www.apollographql.com/docs/angular/basics/queries/#what-is-queryref) states the following: 
> The GraphQL query itself is still only sent once, but the watchQuery observable can also update if, for example, another query causes the object to be updated within Apollo Client's global cache.

**Comment by christian-muertz** [comment]
Ok I found out that QueryManager has a function called `rebroadcastQueries` which updates all query streams with data from the cache. This function is only called after mutations but should be called whenever a query result from the network comes in!

**Comment by micimize** [comment]
Using `rxdart` like [ferry](https://github.com/gql-dart/ferry/) does to create true observables might fix this

**Comment by micimize** [comment]
Consolidating into #728
