### ISSUE TITLE
A static website for documentation

### ISSUE THREAD

**Issue by juicycleff** [zino-app/graphql-flutter#59]
I think this project deserves some static website for documentation and showcase some use case at the current state. I could volunteer to this at the moment.

**Comment by HofmannZ** [comment]
Yes definitely something we need in the future. I’m re writing most of the internals, and made a load of breaking changes, so it might be best to start on the documentation once the api is more solid. What do you think?

**Comment by HofmannZ** [comment]
@juicycleff Just finished the major API changes. We can start working on some docs.

To try it out use version `1.0.0-alpha.3` of this package.

**Comment by juicycleff** [comment]
@HofmannZ Sorry I was away and busy. I want to start the docs now. Btw I noticed development has been halted, is this permanent or temporary?

**Comment by eusdima** [comment]
@juicycleff Feel free to start working on the docs.

**Comment by micimize** [comment]
The idiomatic thing to do here is probably to use [`dartdoc`](https://pub.dartlang.org/packages/dartdoc). I think this is especially important as the contributor pool expands and we need to communicate the intent of code internals more robustly

**Comment by mainawycliffe** [comment]
@micimize i like the concept by the dartdoc tool, it will make it easier to keep the docs is up to to date. I will start exploring this over the weekend. May be soon we can have a docs site.

**Comment by mainawycliffe** [comment]
@HofmannZ I see you are assigned this issues, any progress?

**Comment by truongsinh** [comment]
Can't we use https://pub.dev/documentation/graphql/latest/graphql/graphql-library.html ? Inline doc generated by pub.dev is also widely used by Flutter 1st party plugin.

Otherwise, we can make use of Flutter web, github and netlify for a static website.

**Comment by mainawycliffe** [comment]
The `dartdoc` tool suggested above does the same thing, but allows you to add extra markdown documentation. But to be honest, this kind of documentation are good for advanced users but not beginners. 

Flutter for web would be a mess, it would be the same using Angular or React to create a docs site, its possible it just not suitable. What we need is a Static Site Generator like Hugo or Gatsby which allows for easy content management using Markdown, easy themming and generates a static site that can be hosted anywhere like GitHub Pages or Netlify. Most open source project i have come across use a variation of this.

**Comment by truongsinh** [comment]
I believe inline doc /  https://pub.dev/documentation can also have markdown, even code snippet.

**Comment by mainawycliffe** [comment]
I would much prefer this style of docs https://felangel.github.io/bloc/#/, with recipes and clear cut documentation that is easy to read for all developers. Then we can link to the API Reference for someone interested in digging into the APIs - and this already exist on pub.dev, just a simple link to the API reference.

**Comment by micimize** [comment]
merging into #741
