### ISSUE TITLE
UnhandledFailureWrapper (Unhandled Failure FormatException: Unexpected character (at line 2, character 1)

### ISSUE THREAD

**Issue by MbeleLebohang-uct** [zino-app/graphql-flutter#591]
I have been struggling with the the following client exception

`UnhandledFailureWrapper (Unhandled Failure FormatException: Unexpected character (at line 2, character 1)`

I have the following query

```
"""query {
  allAccounts{
    name
    balance
    active
  }
}"""
```

My Query options object is as follow

```
...
QueryOptions _options = QueryOptions(
   documentNode: gql(HomeDataQueries.userBudgetForAMonthQuery)
);
    
QueryResult result = await _graphQLConfiguration.getGraphQLClient().query(_options);

if(result.hasException){
     throw Exception("Error: ${result.exception.toString()}");
}
...
```

The client is obtained from the following class

```
class GraphQLConfiguration{
  // GraphqL API base url
  final HttpLink _httpLink;
  static final apiUrl = "https://***************************.com/graphql/";

  GraphQLClient _client;

  GraphQLConfiguration() 
    : _httpLink = HttpLink(uri: GraphQLConfiguration.apiUrl, headers: {"Content-Type": "application/json"});

  GraphQLClient getGraphQLClient(){
    _client ??= GraphQLClient(
      link: _httpLink,
      cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
    );
    return _client;
  }
}
```
Inspection of the results and the options variables looks as follows:

![image](https://user-images.githubusercontent.com/34369240/78017690-f1396280-734c-11ea-9b89-cb938be8b635.png)

**Comment by saarikivit** [comment]
Hey man, me too!
I was wondering, does this ever happen if you run the graphQL server locally?
When does this happen? Always or randomly? What server do you use?

I have deployed my backend to zeit.now I think behind the scenes they use lambda functions for the server.

I get the errors randomly. Every tester that has tested my app also gets them.
The weird thing to me is that all places do not fail simultaneously. One query done approx at the same time can succeed while the other one fails. This rarely happens when starting the app. Coming back to it yields these for some reason more often but not always. ⚠️ 

I think I never saw this exception running graphql locally though 🤔 

I wonder..

**Comment by micimize** [comment]
Does this happen when not using the client, i.e. with graphiql? What about with named queries?

**Comment by saarikivit** [comment]
Well for me it's a ClientError. What do you think could cause this if it was not? 🤔 I'd like to investigate.

The only thing I can think of would ne the 'now' servers as they are lambda functions and come and go. But why would it have effect tho.. 😁

**Comment by MbeleLebohang-uct** [comment]
I managed to work around this using [this](https://docs.graphene-python.org/projects/django/en/latest/installation/#csrf-exempt)

The issue was that the django application had  **CSRF protection** which prevented my API clients from POSTing to the /graphql endpoint. By wrapping the /graphql endpoint with ```django.views.decorators.csrf import csrf_exempt``` solved the problem for me. 

@saarikivit I dont know which framework you used to implement your graphql server, maybe you should look into this CSRF protection, to see if it is not the one causing this issue for you.

**Comment by micimize** [comment]
@saarikivit a `ClientError` just wraps non-graphql errors, so it doesn't necessarily mean there was an error within the client.

If you can test with graphiql you should be able to determine whether it's client-dependent

**Comment by saarikivit** [comment]
Ok, thanks! Good to know 👍

**Comment by varundroid** [comment]
> I managed to work around this using [this](https://docs.graphene-python.org/projects/django/en/latest/installation/#csrf-exempt)
> 
> The issue was that the django application had **CSRF protection** which prevented my API clients from POSTing to the /graphql endpoint. By wrapping the /graphql endpoint with `django.views.decorators.csrf import csrf_exempt` solved the problem for me.
> 
> @saarikivit I dont know which framework you used to implement your graphql server, maybe you should look into this CSRF protection, to see if it is not the one causing this issue for you.

Hi, I am struggling with the exact same issue, seems like you finally managed to resolve the issue. I would appreciate if you can demonstrate the solution using flutter code. Thanks

**Comment by mugadza** [comment]
@varundroid are you calling a third party api, or you implemented your own api? If you implemented your own api, what framework did you use?

**Comment by varundroid** [comment]
> @varundroid are you calling a third party api, or you implemented your own api? If you implemented your own api, what framework did you use?

Hi, thanks for you reply @mugadza, but I eventually managed to resolve the issue. It was my mistake, I was using `graphiql` rather than `graphql`. It was such a tiny mistake, took me ages to notice.

**Comment by saarikivit** [comment]
This issue is solved for me. Only thing that changed was my server; Vercel cloud function changed to GC App Engine. I also dockerized the service.
