### ISSUE TITLE
http2 support ?

### ISSUE THREAD

**Issue by saahithyan** [zino-app/graphql-flutter#593]
Does this support http 2 ?
What is this using internally, http 2 or 1.1 ? 
How to find out ?

**Comment by vasilich6107** [comment]
Hi. Just look into sources.
https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/link/http/link_http.dart#L7

There is another package for http2 implementation https://pub.dev/packages/http2

**Comment by KingWu** [comment]
official support http2Link?

**Comment by micimize** [comment]
Now that we've migrated to using `gql_links` in `4.0.0-beta.1` (#648) there is a `dio` link, which apparently supports `http2`. I'm not sure how well it works with `graphql/client.dart` yet, but this is maybe another reason to consider dio (#712)

> You thought what you needed what http2 support, but it was me, Dio!
