### ISSUE TITLE
Subscribe not constantly pulling data

### ISSUE THREAD

**Issue by MasulukeI** [zino-app/graphql-flutter#594]
Subscription doesnt update when changes are made 
here is my code:

```
return Subscription<Map<String, dynamic>>(
      'MyQuery',
      r'''
        query MyQuery {
          teams {
              id
              name
            }
          }
      ''',
      builder: ({dynamic loading, dynamic payload, dynamic error}) {
        if (error != null) {
          return Text(error.toString());
        }

        if (loading == true) {
          return Center(
            child: const CircularProgressIndicator(),
          );
        }
        return Text(payload.toString());
      },
    );`
```

**Comment by micimize** [comment]
The subscription widget only works with with graphql subscriptions such as you can use [with apollo](https://www.apollographql.com/docs/react/data/subscriptions/#overview), which have a special schema type:
https://github.com/zino-app/graphql-flutter/blob/dd7e6bf3cc689d59a24b8171225433ec97ab1f18/examples/starwars/lib/reviews/review_subscription.dart#L12-L16
