### ISSUE TITLE
The getter 'value' was called on null on Mutation Widget

### ISSUE THREAD

**Issue by evertonfoz** [zino-app/graphql-flutter#595]
Hello. I have a Mutation Widget on a login page that works perfectly.

When I access a page after login and return to the login page, I get the error

`The getter 'value' was called on null.`

This error occurs in

`void _initQuery () {
    client = GraphQLProvider.of (context) .value;`

**Comment by Chromicle** [comment]
hello, @evertonfoz I also getting the same error did you solved this?

**Comment by evertonfoz** [comment]
Hi @Chromicle . 
No. I ended up generating the code for the mutation and stopped using the Widget Mutation.

**Comment by micimize** [comment]
Sounds like the page you navigated to doesn't have a `GraphQLProvider` to grab the `client` from

**Comment by ValentinVignalNovade** [comment]
Just put a `GraphqlProvider` on above of your `Mutation` widget in the widget tree
