### ISSUE TITLE
Client and stateful widget 

### ISSUE THREAD

**Issue by AhmedAlaa96** [zino-app/graphql-flutter#596]
**Hi, everyone**
I'm using `GraphQLProvider` in a `StatfulWidget`  but it's always give me this error then run after `initState` because client is null 
```
The method 'addListener' was called on null.
Receiver: null
Tried calling: addListener(Closure: () => void from Function 'didValueChange':.)
```
I tested my application using debug mode and some break points to see what happening and it's happening  and this always happening because of `CreateState` in flutter cycle make `client` in `GraphQLProvider` **null** and I cannot control it 
Can anyone tell me how can I handle client to be not null in `CreateState` ? 

Thank you

**Comment by micimize** [comment]
Hi - some code would be helpful here. Do you pass a `ValueNotifier<GraphQLClient>` to the provider? 

https://github.com/zino-app/graphql-flutter/blob/4b71898dcbef28f8b3949312ee52c418d9cded79/packages/graphql_flutter/example/lib/graphql_widget/main.dart#L38-L52

**Comment by AhmedAlaa96** [comment]
Hi, @micimize  
Yes I do pass a `ValueNotifier<GraphQLClient>` to the provider but still the same issue 
I totally forgot to mention that I'm using `graphql_flutter: 2.1.0`

**Comment by micimize** [comment]
@AhmedAlaa96 ok, still need some actual code to go off of though. Ideally a minimal reproduction with the example above as a starting point

**Comment by AhmedAlaa96** [comment]
**ChatScreen.dart**
```

class ChatScreen extends StatefulWidget {
  
  @override
  _ChatScreenState createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> with WidgetsBindingObserver {
 
  ValueNotifier<GraphQLClient> client;
 
  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    
    AuthQueries.initClient().then((_client){
      client = _client;
      setState(() {
      });
    });
    super.initState();
  }

  

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    client.dispose();
    super.dispose();
  }
  
  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      body: GraphQLProvider(
        client: client,
        child: ...
    );
  }


}

```
**AuthQuries.dart**

```
Class AuthQuries {
static Future<ValueNotifier<GraphQLClient>> initClient() async{
    String _token = await getToken(); // token from shared prefrence 
    AuthLink authLink;
    HttpLink httpLink;
    Link link;
    ValueNotifier<GraphQLClient> client;

      authLink = AuthLink(
        getToken: () => "Bearer $_token",
      );
      httpLink = HttpLink(
        uri: graphqlURL,
      );
      link = _token == null ? httpLink : authLink.concat(httpLink);
      client = ValueNotifier(
        GraphQLClient(
          cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
          link: link,
        ),
      );

      return client;

  }
}
```

**Comment by micimize** [comment]
oook, this we can work with. The issue isn't something specific to `graphql_flutter` - state set asynchronously (with futures) won't be available on the first render.

Instead, what I'd suggest is constraining the async stuff to the link, like this approach I [used for google sign in](https://gist.github.com/micimize/062c0288a492c14d60936adc4a07b7a7#file-graphql_flutter_google_sign_in-dart-L19-L29). So something like:
```dart
class AuthQuries {
  static FutureOr<String> Function() get _getToken {
    String _token;
    return () async {
      if (_token == null){
        _token = await getToken(); // token from shared prefrence
      }
      return _token;
    };
  }

  static ValueNotifier<GraphQLClient> initClient() {
    AuthLink authLink;
    HttpLink httpLink;
    Link link;
    ValueNotifier<GraphQLClient> client;

    authLink = AuthLink(
      getToken: _getToken,
    );
    httpLink = HttpLink(
      uri: graphqlURL,
    );
    link = _token == null ? httpLink : authLink.concat(httpLink);
    client = ValueNotifier(
      GraphQLClient(
        cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
        link: link,
      ),
    );

    return client;
  }
}
```
With `client = AuthQueries.initClient();` in `setState`. Probably better to use an actual class rather than a closure for the token, but this should work

**Comment by AhmedAlaa96** [comment]
@micimize Thanks a lot that's work for me very well :smiley:

**Comment by AhmedAlaa96** [comment]
@micimize Thanks a lot that's work for me very well :smiley:
