### ISSUE TITLE
Instance of CacheMissException

### ISSUE THREAD

**Issue by Faiyyaz** [zino-app/graphql-flutter#597]
**Describe the bug**

If i enable cache and i switch off the network after fetching the data and try to fetch the data again i get CacheMissException instead of the cached response

**To Reproduce**
1. Set  ```fetchPolicy: FetchPolicy.cacheAndNetwork,```
2. Call a graphql Query
3. After that change the fetch policy to ```fetchPolicy: FetchPolicy.cacheOnly,```
4. You will see the error

**Expected behavior**
The response cached should come and its fine that we are getting error for no network

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: iOS
 - Version 13.3

**Comment by freewebwithme** [comment]
Same happens to me in Android(graphql-flutter 3.0.0)

**Comment by SwannLV** [comment]
Same here! 🙏

**Comment by micimize** [comment]
This is likely solved by the cache rework in `4.0.0-beta.1` (#648). Please try and repro there, and if there's still an issue:
* a reproduction or test case will help a lot
* we can maybe troubleshoot in the [discord](https://discord.gg/tXTtBfC)
