### ISSUE TITLE
Query renders two times with loading state

### ISSUE THREAD

**Issue by vasilich6107** [zino-app/graphql-flutter#598]
**Describe the bug**
When I'm making a query it fires `builder` function two times with `loading` state.

```
I/flutter ( 6703): rh report build # build method level
I/flutter ( 6703): b6f4e5db-3765-4b3c-abf0-e68818630412
I/flutter ( 6703): QueryResultSource.Loading
I/flutter ( 6703): QueryResultSource.Loading
I/flutter ( 6703): QueryResultSource.Network
```

**To Reproduce**
Create random query and `print(result.source.toString());` inside `builder` function.

**Expected behavior**
Should execute `builder` only once per state change

```
I/flutter ( 6703): rh report build # build method level
I/flutter ( 6703): b6f4e5db-3765-4b3c-abf0-e68818630412
I/flutter ( 6703): QueryResultSource.Loading
I/flutter ( 6703): QueryResultSource.Network
```

**Screenshots**
The state of connection changes from `waiting` to `active` both of this changes executes `builder` with `loading` state.

`waiting` - https://tppr.me/Zl0jj
`active` - https://tppr.me/T2Pv5
then comes the actual data with the same `active` state - https://tppr.me/lZU98
**Desktop (please complete the following information):**
 - OS: both iOs/Android emulators

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S5e SM-T720
 - OS: Android
 - Version 9

**Comment by vasilich6107** [comment]
@micimize @isaiahtaylor @wexder @mainawycliffe @lookfirst @HofmannZ 

Any thoughts, comments?

**Comment by nampdn** [comment]
I'm facing this everytime a Widget state is updated as #627 describe, is there any workaround to prevent refetch when State is updated?

**Comment by micimize** [comment]
believe this is the same as #725 – is due to `StreamBuilder` behavior
