### ISSUE TITLE
How to persist cookies?

### ISSUE THREAD

**Issue by teknolojia** [zino-app/graphql-flutter#599]
**Is your feature request related to a problem? Please describe.**
My server uses session based authentication and it seems this lib doesn't persist cookies so user can't login. 

**Describe the solution you'd like**
Just using session based authentication. Where cookies are sent with every request.

**Describe alternatives you've considered**
Using CookieJar like this [cookie_jar](https://pub.dev/packages/cookie_jar) or [Requests](https://github.com/jossef/requests). Problem is I don't know how.

**Additional context**
None.

**Comment by rajihawa** [comment]
I suggested a workaround #592 
but still we need a better solution providing by the library

**Comment by micimize** [comment]
Closing this in favor of #592
