### ISSUE TITLE
refetch() does not trigger state change to 'loading: true'

### ISSUE THREAD

**Issue by vasilich6107** [zino-app/graphql-flutter#602]
**Describe the bug**
When I'm call `refetch()` method there is no 'loading: true' state. In the same time `fetchMore(...)` works as expected.

I'm using the watch query directly.

```
result = client.watchQuery(options)

// later on I call 
result.refetch();
```

Here is how state evolves inside `result.stream.listen(() { ... })`

REFERCH CASE
```
flutter: ==========================
flutter: state - GraphqlRefetchState<ReportList$Query>
flutter: loading - false
flutter: source - QueryResultSource.Cache
flutter: items count - 25
flutter: ==========================
flutter: ==========================
flutter: state - GraphqlLoaded<ReportList$Query>
flutter: loading - false
flutter: source - QueryResultSource.Network
flutter: items count - 25
flutter: ==========================
```

FETCH MORE CASE(just for comparison)
```
flutter: ==========================
flutter: state - GraphqlFetchMoreState<ReportList$Query>
flutter: loading - true
flutter: source - QueryResultSource.Loading
flutter: items count - 25
flutter: ==========================
flutter: ==========================
flutter: state - GraphqlFetchMoreState<ReportList$Query>
flutter: loading - false
flutter: source - QueryResultSource.Network
flutter: items count - 50
flutter: ==========================
```

Code that prints this
```
result.stream.listen((QueryResult result) {
      print('==========================');
      print('state - ${state.runtimeType.toString()}');
      print('loading - ${result.loading}');
      print('source - ${result.source}');
      if (result.data != null) {
        print('items count - ${result.data['reports'].length}');
        print('==========================');
      }
    });
```

I double checked this behavior in regular query(to avoid the possible my bloc implementation bugs)
It is just the same
```
flutter: ==========================
flutter: loading - false
flutter: source - QueryResultSource.Cache
flutter: ==========================
flutter: ==========================
flutter: loading - false
flutter: source - QueryResultSource.Network
flutter: ==========================
```

I did not specify any `fetchPolicy` in `WatchQueryOptions`
 

**To Reproduce**
Create random query and run `refetch()` method.

**Expected behavior**
The state should updated to `loading: true` in the same way as in case of `fetchMore()`

**Desktop (please complete the following information):**
 - OS: both iOs/Android emulators

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S5e SM-T720
 - OS: Android
 - Version 9

**Comment by bagindo** [comment]
@vasilich6107 is there any follow-up or workaround on this?

**Comment by vasilich6107** [comment]
Look at the extended bloc sample
https://github.com/zino-app/graphql-flutter/tree/master/examples/flutter_bloc/lib

**Comment by lazylazyllama** [comment]
I have the same issue...
This is really frustrating :(

**Comment by SanjiKir** [comment]
Yeah BTW same here. I got rid of refetch for now, however, I was also surprised there is no loading state.
