### ISSUE TITLE
Query and Mutation in the same Widget

### ISSUE THREAD

**Issue by folivi** [zino-app/graphql-flutter#609]
Hi,
is it possible to have a sample or a short description of how to use a mutation and a query together?
I'm creating a widget where there is a form with a dropdown and the users can save the data.
Thank you

**Comment by vasilich6107** [comment]
Check https://github.com/zino-app/graphql-flutter/blob/master/examples/flutter_bloc/lib/bloc.dart

It uses query for repositories and mutation to star the repo.

Clone this repo, launch the flutter_bloc example in simulator and check with debugger if you need to.

**Comment by folivi** [comment]
Thank you @vasilich6107 
I'll try to adapt it to use Provider instead

**Comment by vasilich6107** [comment]
@folivi do not forget to close the issue if it helped ;-)

**Comment by folivi** [comment]
hi @vasilich6107 
Closing it now :)
I'm pretty new to flutter so I'm struggling it a bit with implementation with Provider instead of the Bloc.
If you have same example code with Provider sleeping somewhere on your computer, I'm interested :)
Cheers
