### ISSUE TITLE
WPGraphQL Pagination

### ISSUE THREAD

**Issue by imarindam** [zino-app/graphql-flutter#610]
I am developing an app using flutter where Wordpress Posts are fetched. I use Wordpress [GraphQL API plugin][1] for WP.
I am new to flutter and GraphQL concept. So far I can fetch the first 10 (or first any number of) posts using PODO. But I can't implement pagination. 
I want user to see first 10 posts, then tap on a raised button to load next page posts and show previous pages as well as new pages when tap "Load more".
But how can I get next page posts where `"hasNextPage": true`?

My Code to Query Wordpress Posts in flutter is as follows:

    options: QueryOptions(
        documentNode: gql(getpost),
        variables: {
          'nParentCatID': parentCatIDofPosts,
          'nFirst': nFirst,
          'nBefore': nBefore,
          'nAfter': nAfter,
        },
        pollInterval: 10,
      )

Query String:

        String getpost = """
    query MyQuery(\$nParentCatID: Int!, \$nFirst: Int!, \$nAfter: String!, \$nBefore: String!) {
      posts(where: {categoryId: \$nParentCatID, orderby: {field: MENU_ORDER, order: ASC}}, first: \$nFirst, after: \$nAfter, before: \$nBefore) {
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        edges {
          cursor
          node {
            categories(where: {shouldOutputInFlatList: true}) {
              nodes {
                id
                categoryId
                name
              }
            }
            id
            title
            excerpt
            date
            content
          }
        }
      }
    }
    
    """;

Output of the Query is as follows:

    {
      "data": {
        "posts": {
          "pageInfo": {
            "hasNextPage": true,
            "hasPreviousPage": false,
            "startCursor": "YXJyYXljb25uZWN0aW9uOjIxNzk1",
            "endCursor": "YXJyYXljb25uZWN0aW9uOjIxNzc3"
          },
          "edges": [
            {
              "cursor": "YXJyYXljb25uZWN0aW9uOjIxNzk1",
              "node": {
                "categories": {
                  "nodes": [
                    {
                      "id": "Y2F0ZWdvcnk6Mg==",
                      "categoryId": 2,
                      "name": "#Category1"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6NA==",
                      "categoryId": 4,
                      "name": "#Category2"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6MTE2",
                      "categoryId": 116,
                      "name": "#Category3"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6MTE4",
                      "categoryId": 118,
                      "name": "#Category4"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6MTY3",
                      "categoryId": 167,
                      "name": "#Category5"
                    }
                  ]
                },
                "id": "cG9zdDoyMTc5NQ==",
                "title": "POST 1 TITLE",
                "excerpt": "POST 1 EXCERPT",
                "date": "POST 1 DATE",
                "content": "POST 1 CONTENT"
              }
            },
            {
              "cursor": "YXJyYXljb25uZWN0aW9uOjIxNzc3",
              "node": {
                "categories": {
                  "nodes": [
                    {
                      "id": "Y2F0ZWdvcnk6Mg==",
                      "categoryId": 2,
                      "name": "#Category1"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6MTE2",
                      "categoryId": 116,
                      "name": "#Category2"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6MTY2",
                      "categoryId": 166,
                      "name": "#Category3"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6NA==",
                      "categoryId": 4,
                      "name": "#Category4"
                    },
                    {
                      "id": "Y2F0ZWdvcnk6MTE4",
                      "categoryId": 118,
                      "name": "#Category5"
                    }
                  ]
                },
                "id": "cG9zdDoyMTc3Nw==",
                "title": "POST 2 TITLE",
                "excerpt": "POST 2 EXCERPT",
                "date": "POST 2 DATE",
                "content": "POST 2 CONTENT"
              }
            },
    		...........
    		...........
    		...........
    		...........
    		...........
    		...........
    		...........
    		...........
          ]
        }
      }
    }

Now to load next page posts I need to pass the value of `nAfter` = `"YXJyYXljb25uZWN0aW9uOjIxNzc3"` which is the value of `endCursor`.

However how to implement the logic in flutter `fetchMore` and load the next posts as well as the previous posts which are already exists is not clear to me for this scenario.

My flutter list widget code where I don't know how to implement pagination on tap:

    builder: (QueryResult result,
              {VoidCallback refetch, FetchMore fetchMore}) {
            if (result.hasException) {
              return Center(child: Text(result.exception.toString()));
            }
    
            if (result.loading && result.data == null) {
              return Center(child: CircularProgressIndicator());
            }
    		
            List postsNodes = result.data['posts']['edges'];
            var pageInfo = PageInfo.fromJson(result.data['posts']['pageInfo']);
            print('Total Posts: ' + postsNodes.length.toString());
    
            bool hasNextPage = pageInfo.hasNextPage;
            bool hasPreviousPage = pageInfo.hasPreviousPage;
    
            if (hasNextPage) {
              nAfter = pageInfo.endCursor;
            }
            if (hasPreviousPage) {
              nBefore = pageInfo.startCursor;
            }
    
            List<Widget> list = List<Widget>();
    
            for (var i = 0; i < postsNodes.length; i++) {
              int qNo = i + 1;
              var data = EdgeNode.fromJson(postsNodes[i]['node']);
              String titles = data.title ?? 'Unknown';
              String exp = data.excerpt ?? '';
              print(exp);
              String id = data.id;
    
              list.add(
                  ListItems(qNo, titles, exp, id));
            }
    
            return new Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                ...list,
                Center(
                  child: RaisedButton(
                    child: Text('Load more'),
                    onPressed: () {
                      fetchMore(FetchMoreOptions(
                          variables: {
                            if (hasPreviousPage) 'startCursor': nBefore,
                            if (hasNextPage) 'endCursor': nAfter,
                          },
                          updateQuery: (existingPosts, newPosts) => {}));
                    },
                  ),
                )
              ],
            );

I would really appreciate any help.

  [1]: https://github.com/wp-graphql/wp-graphql
  [2]: https://pub.dev/packages/graphql_flutter

**Comment by vasilich6107** [comment]
See the extended example
https://github.com/zino-app/graphql-flutter/blob/master/examples/flutter_bloc/lib/extended_bloc.dart

Clone this repo, launch  the `flutter_bloc` example in simulator and check with debugger if you need to.

**Comment by imarindam** [comment]
Thank you so much for your help.
