### ISSUE TITLE
Can't send boolean values in the header

### ISSUE THREAD

**Issue by mustela** [zino-app/graphql-flutter#611]
**Describe the bug**
I can't send a custom boolean header like 
```
HttpLink(
      uri: 'https://myapi.com/query',
      headers: {"custom-header": true}
);
```

I need to convert that value into a string which is not the same, since the api is expecting a boolean not a `"true"` value.

**Comment by micimize** [comment]
This is because [`headers` can only be strings](https://pub.dev/documentation/http/latest/http/BaseRequest/headers.html), they are just plain text at the top of a request:
```
Header-Key: any value as a string
Content-Encoding: gzip
Authorization: al;sdighqop[iwrehg[oweihrga
 
<!DOCTYPE html ... my request
```
