### ISSUE TITLE
Queries do not persist on navigation

### ISSUE THREAD

**Issue by chimon2000** [zino-app/graphql-flutter#612]
**Describe the bug**
Currently when using the Query widget, if I have gotten the next page of results and navigate to another page and back, the previous results are lost.

**To Reproduce**
1. Using any common GraphQL api, implement paging (GitHub for example)
2. Page thru the query results
3. Navigate away from page
4. Navigate back to page
5. Notice results are requeried.

**Expected behavior**
The results should be cached and a query should not be re-ran unless the properties of the GraphQL query change.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by vasilich6107** [comment]
Hi. Debug inside the `typenameDataIdFromObject` function.
If it returns `null` the objects won't be cached.
I checked locally on my simple API that returns an array of objects - works fine.

**Comment by vasilich6107** [comment]
Hi)

Check this - https://tppr.me/VktpU

Move `cache` instance outside of client instantiation. Otherwise the cache resets each time the client is created.

**Comment by vasilich6107** [comment]
@chimon2000 my solution was helpful?

**Comment by chimon2000** [comment]
@vasilich6107 I actually ended up abandoning using the GraphQLQuery widget in favor of just using services.  That looks like it should work and I've stashed the original so I will give it a try.  Will reopen if still having issues.
