### ISSUE TITLE
Cache is not working on app start

### ISSUE THREAD

**Issue by lazylazyllama** [zino-app/graphql-flutter#617]
**Describe the bug**
When I use the Query() widget right at the start of the app, the cache is not working. So I get an exception if my internet is off. But after i press on a button to execute a refetch, everything works... So the cache is available, but somehow not right at the start of the app.

**Expected behavior**
The cache should be available right at the start of the app.
Maybe if there are reasons why it takes some time for the cache to come up, the Query() widget should wait for it?

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T Pro
 - OS: Android
 - Version 10

**Comment by lazylazyllama** [comment]
Actually I found out, that it is kind of working in release mode, but I am not sure if I can say that for every device.. because clearly something is off with this and its still not working perfectly..

So when I open the app without internet its working fine in release mode, but if I open it with network on I don't see any cache but a progress bar until the network request is finished..
Thats not how it should be.

**Comment by Faiyyaz** [comment]
Same issue for me. It gives host look up error rather than loading data from cache itself

**Comment by vasilich6107** [comment]
You can try to overcome this by applying the cache only fetch policy in case the internet connection is missing

https://github.com/zino-app/graphql-flutter/blob/42d010c177f7fa752b9a0b5ca57548dd1cd3ad8f/packages/graphql/lib/src/core/query_options.dart#L21

**Comment by vasilich6107** [comment]
There could also be the case when cache hydrates without awaiting to finish...
This requires additional investigation...

**Comment by Faiyyaz** [comment]
if I use cache only I get CacheMissException

**Comment by lazylazyllama** [comment]
Okay so in my case `cacheOnly` works. Thats kind of interesting 🤔 

Now the question is, why is the cache working if you use `cacheOnly`, but not if you use `cacheAndNetwork `when starting the app?

**Comment by lazylazyllama** [comment]
Actually I have to take back what I said.

So after playing around a bit more it turned out, that also cacheOnly isn't working all the time.
It's definitely better than cacheAndNetwork but its far from perfekt.

When I use a FutureBuilder to wait until getApplicationDocumentsDirectory() succeeds I get it working all the time on my device, but thats a weird hack and I have no idea if that would work on every device as this seems to be some kind of a performance thing? "If you wait long enough you might just get the cache " or something ... 

So this really still is a huge bug and the seems to be no real workaround right now.

**Comment by vasilich6107** [comment]
It seems the built in approach to launch 'getApplicationDocumentsDirectory()' is not working as expected)
If you could prepare the reproducible github repo I'll take a look and may be will be able to create PR

**Comment by lazylazyllama** [comment]
Thats very nice of you thanks.

My current project is closed source, but I will try to build a small version for demonstration purposes ASAP :)

**Comment by lazylazyllama** [comment]
Just as a small update:

Even with the FutureBuilder waiting for getApplicationDocumentsDirectory()

I get a `CacheMissException` 1 out of 10 tries or something like that.

**Comment by vasilich6107** [comment]
Thanks for your active help in investigating this issue!

**Comment by lazylazyllama** [comment]
You are welcome :) But my intentions are purely egoistic, as I need this bug to be fixed :D 

So I created a simple app that showcases my issue:
https://github.com/lazylazyllama/graphql_flutter-cache-on-start-issue

By default I configured the cache to be `cacheAndNetwork` so that you can see something by launching the app first. As the cache needs to be created anyways at some point.
You can easily change that to `cacheOnly` [here](https://github.com/lazylazyllama/graphql_flutter-cache-on-start-issue/blob/9855434e1958b0f0221a6931d441ebee22a1e8f5/lib/main.dart#L71)

**Comment by vasilich6107** [comment]
Thanks I’ll take a look!

**Comment by lazylazyllama** [comment]
That's cool thanks you a lot :)

While playing around I also noticed, that there is a similar issue that happens at runtime and it might be related. 

So what I did was:
```dart
final result = await graphql.GraphQLProvider.of(context).value.query(graphql.QueryOptions(
    documentNode: SchoolQuery().document,
));
```

And right after that I tried to read that value with a Query() Widget and cacheOnly as the FetchPolicy. But what I get is a `CacheMissException`. But after a restart its working except on those 1 out of 10 or 20 or 30 .. :D times

Context: This is part of my logging in process. I do the first fetch to put the `School` into the cache and after that I navigate to the main page, which uses cacheOnly.

**Comment by aseef17** [comment]
> You are welcome :) But my intentions are purely egoistic, as I need this bug to be fixed :D
> 
> So I created a simple app that showcases my issue:
> https://github.com/lazylazyllama/graphql_flutter-cache-on-start-issue
> 
> By default I configured the cache to be `cacheAndNetwork` so that you can see something by launching the app first. As the cache needs to be created anyways at some point.
> You can easily change that to `cacheOnly` [here](https://github.com/lazylazyllama/graphql_flutter-cache-on-start-issue/blob/9855434e1958b0f0221a6931d441ebee22a1e8f5/lib/main.dart#L71)

Tried to run your example. Seems to be throwing **CacheMissException** every single time. 
Ran the app with cacheAndNetwork policy, and then changed it to cacheOnly but no success

**Comment by lazylazyllama** [comment]
I don't get this issue anymore using Hive Storage in 4.0.0 alpha
