### ISSUE TITLE
Getting error when passing google pay token

### ISSUE THREAD

**Issue by ZhassulanUrazbayev** [zino-app/graphql-flutter#619]
I'm passing just string and all error causes in mutation 

`"""mutation {
      payOrderByToken(input: {token: "$token"}) {
        boolean
      }
    }"""..replaceAll('\n', ' ')`

this is error

`E/flutter ( 2144): #0      _Scanner.scanToken (package:gql/src/language/lexer.dart:229:5)
E/flutter ( 2144): #1      Lexer.tokenize (package:gql/src/language/lexer.dart:112:23)
E/flutter ( 2144): #2      parse (package:gql/src/language/parser.dart:14:24)
E/flutter ( 2144): #3      parseString (package:gql/src/language/parser.dart:27:5)
E/flutter ( 2144): #4      gql (package:graphql/src/core/query_options.dart:10:35)
E/flutter ( 2144): #5      GooglePayProvider.execute (package:qummy/src/datasource/google_pay_provider.dart:20:47)
E/flutter ( 2144): <asynchronous suspension>
E/flutter ( 2144): #6      BasketBloc.googlePayStatus (package:qummy/src/bloc/basket/basket_bloc.dart:189:51)
E/flutter ( 2144): <asynchronous suspension>
E/flutter ( 2144): #7      ShoppingBasketState._handleMethod (package:qummy/src/ui/basket/shopping_basket.dart:492:21)
E/flutter ( 2144): #8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter ( 2144): #9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter ( 2144): #10     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter ( 2144): #11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
E/flutter ( 2144): #12     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 2144): #13     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 2144): #14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 2144): #15     _invoke3 (dart:ui/hooks.dart:302:10)
E/flutter ( 2144): #16     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
`

**Comment by klavs** [comment]
1) It's likely a sanitisation issue and your `token` contains bad characters.
2) It's a good practice to keep your queries constant and make use of operation variables.

**Comment by micimize** [comment]
As klavs said. I recommend using `r"""` strings as well.

Please come by the `#support` channel in [discord](https://discord.gg/tXTtBfC) as this is more a usage question.
