### ISSUE TITLE
Make cache optional

### ISSUE THREAD

**Issue by insanebaba** [zino-app/graphql-flutter#621]
I'm trying to run background service to fetch results.
But I get below exception when I try without cache

```
Unhandled Failure NoSuchMethodError: The method 'write' was called on null.
```

Why is cache mandatory?
I don't want to use cache. Please make it optional. It's not wise to inject cache, even when you don't need it.

I am running service in background using workmanager.

**Comment by SanjiKir** [comment]
BTW I agree with this, I am not quite happy with current cache behaviour and I was thinking about using this library only as a network client and dumping result to my personal `cache` or `store` and I was also quite surprised about having cache as mandatory.

**Comment by micimize** [comment]
@insanebaba you can try the `defaultPolicies` api to avoid writing to the cache. Try without a cache argument and lmk if it works:

```dart
  final policies = Policies(
    fetch: FetchPolicy.networkOnly,
  );

  return ValueNotifier<GraphQLClient>(
    GraphQLClient(
      cache: null,
      link: link,
      defaultPolicies: DefaultPolicies(
        watchQuery: policies,
        query: policies,
        mutate: policies,
      ),
    ),
  );
```

**Comment by micimize** [comment]
In the future, we should possibly make cache not required and set the default policies based on it being defined

**Comment by insanebaba** [comment]
Hi @micimize , I implemented a new cache class with empty implementations. passing null doesn't work, Throws error at runtime

**Comment by klavs** [comment]
@insanebaba this library is modeled after Apollo, where client is pretty much link + cache. If you do not want to use cache, client - cache is pretty much only the link.

Did you try using your link directly?

**Comment by minhvn** [comment]
> @insanebaba this library is modeled after Apollo, where client is pretty much link + cache. If you do not want to use cache, client - cache is pretty much only the link.
> 
> Did you try using your link directly?

How to try bro? Im error when flutter pop to list, and cannot load new list after add new posts/

**Comment by micimize** [comment]
The cache calls are fairly integrated into the `QueryManager`, and making the cache itself optional makes the policy api nonsensical. Instead, I think we'll follow `apollo-client`'s lead on this and just say to [use the no fetch policy](https://github.com/apollographql/apollo-client/issues/1419#issuecomment-391035776).

Even if we tried to offer this option, a user not wanting to use (or eventually use) the cache would probably be better off with a client composed of nothing but gql links. Maybe we should make a `gql_fetch` for that use-case. Would also serve as a `gql_link` example in general
