### ISSUE TITLE
gradle error in Flutter (Channel stable, v1.17.0, on Linux)

### ISSUE THREAD

**Issue by hosseinvejdani** [zino-app/graphql-flutter#628]
Hi, i describe problem in [here](https://stackoverflow.com/questions/61674195/graphql-flutter-problem-a-problem-occurred-configuring-project-connectivity), please answer this question if you have an idea

**Comment by micimize** [comment]
Attempted to answer on the question – if you want help troubleshooting come to the `support` channel in the [discord](https://discord.gg/tXTtBfC)
