### ISSUE TITLE
Access response in custom Link

### ISSUE THREAD

**Issue by leesus** [zino-app/graphql-flutter#638]
I appreciate this may be better as a question on StackOverflow, but figured it might have more visibility here. I am trying to access the response headers in a custom link, but the FetchResult always has a null context. Am I trying to do something unsupported here? Thanks.

**Comment by leesus** [comment]
Nevermind, user error!

**Comment by micimize** [comment]
@leesus was this because you were accessing the context before waiting for a response? If you don't mind posting your solution it would be helpful for others as an example
