### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by castrors** [zino-app/graphql-flutter#639]
**Describe the bug**
I'm using AWS Appsync and then,  when I try to make a request with the same parameters via http, it goes with success.
But when I try with graphql-flutter, I'm getting this error:

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
> 
> The Canonical String for this request should have been
> 'POST
> /graphql
> 
> accept:application/json
> content-type:application/graphql; charset=utf-8
> host:www.host.com
> x-amz-date:0000000000000
> accept;content-type;host;x-amz-date
> AAAAA'
> 
> The String-to-Sign should have been
> 'AWS4-HMAC-SHA256
> 0000000000000
> 1111111/eu-west-1/appsync/aws4_request
> BBBBB'

**To Reproduce**
This is my creation of the link using graphql-flutter:
```
import 'package:amazon_cognito_identity_dart_2/sig_v4.dart';

    final awsSigV4Client = AwsSigV4Client(
        credentials.accessKeyId, credentials.secretAccessKey, endpoint,
        serviceName: 'appsync',
        sessionToken: credentials.sessionToken,
        region: 'eu-west-1');

    final signedRequest = SigV4Request(awsSigV4Client,
        method: 'POST',
        path: '/graphql',
        headers: Map<String, String>.from(
            {'Content-Type': 'application/graphql; charset=utf-8'}),
        body: Map<String, String>.from({'query': query}));

    final CustomAuthLink authLink =
        CustomAuthLink(getHeaders: () => signedRequest.headers);

    return authLink.concat(httpLink);
```

1. Just consume the AuthLink in the flutter app.

**Expected behavior**
This goes well when I'm using http.Request:
```
import 'package:amazon_cognito_identity_dart_2/sig_v4.dart';

    final awsSigV4Client = AwsSigV4Client(
        credentials.accessKeyId, credentials.secretAccessKey, endpointStaging,
        serviceName: 'appsync',
        sessionToken: credentials.sessionToken,
        region: 'eu-west-1');

    final signedRequest = SigV4Request(awsSigV4Client,
        method: 'POST',
        path: '/graphql',
        headers: Map<String, String>.from(
            {'Content-Type': 'application/graphql; charset=utf-8'}),
        body:
            Map<String, String>.from({'query': query}));

    http.Response response;
    try {
      response = await http.post(signedRequest.url,
          headers: signedRequest.headers, body: signedRequest.body);
    } catch (e) {
      print(e);
    }
    print(response.body);
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina 
 - Version 10.15.4

**Smartphone (please complete the following information):**
 - Device: android-x86 emulator
 - OS: Android
 - Version 10 (api 29)

**Comment by micimize** [comment]
Are you sure the only thing `SigV4Request` changes are the headers? Try 
```dart
      response = await http.post(endpoint,
          headers: signedRequest.headers, body: {'query': query});
```

Other than that, try using `content-type` (lowercased), since the default is lowercased: https://github.com/zino-app/graphql-flutter/blob/eec7d2c5e8d753f7d2d62b2964cb61730caeae42/packages/graphql/lib/src/link/http/fallback_http_config.dart#L14

You can try something like #88 to debug as well

**Comment by giva9712** [comment]
@castrors Did you fix that? I have faced the problem too like yours
