### ISSUE TITLE
Multiple graphQl providers and clients with different server links

### ISSUE THREAD

**Issue by sokolej79** [zino-app/graphql-flutter#641]
We have multiple modules each module on own route with different graphql server.
On each module we need to query data with different server url and Inside module  we query data from module server url and sometimes also  from other servers with each different url (need different clients in module).
We must create each client dynamicly not with hard coded urls, because we get graphql server urls in main module for other modules and only then we can create other graphql clients with new url.

How to provide different graphql clients with different urls inside modules and widgets?

Apolo client With react and angular has concept of multiple clients:
provide clients:
apollo.createDefault(options)
// and
apollo.createNamed(name, options);

use clients:
apollo.use('extra').watchQuery

In angular I provide this clients in ngModule in react with context, hooks and provider.
How can be  achieved this with graphql_flutter package with provider or hooks or built in inherited widget GraphQlProvider.
Should GraphQlProvider widget be only one in app or can we have multiple GraphQlProviders with different clients created dynamicly based on graphql server url for each module we get from server.

**Comment by sokolej79** [comment]
Will try this solutions with multi provider to pass down on each route new client:
#339
FilledStacks/flutter-tutorials#11

But this will still be nice to have:
How to provide different graphql clients with different urls inside modules and widgets?
Apolo client With react and angular has concept of multiple clients:
provide clients:
apollo.createDefault(options)
// and
apollo.createNamed(name, options);
use clients:
apollo.use('extra').watchQuery"
"

**Comment by micimize** [comment]
You could implement a version of [GraphQLProvider](https://github.com/zino-app/graphql-flutter/blob/v3.1.0-beta.6/packages/graphql_flutter/lib/src/widgets/graphql_provider.dart) with a map as state and a [GraphQLConsumer](https://github.com/zino-app/graphql-flutter/blob/v3.1.0-beta.6/packages/graphql_flutter/lib/src/widgets/graphql_consumer.dart) that selects from it based on a key would work here, or just a custom approach using https://pub.dev/packages/provider.

No intent to integrate this into core for now, but would link to a 3rd party module if you publish one
