### ISSUE TITLE
How can I pass a customised parameter in query?

### ISSUE THREAD

**Issue by zhaoyi0113** [zino-app/graphql-flutter#642]
I am using `graphql_flutter` in a flutter app. Below is my query code:

```dart
await this.gqClient.query(QueryOptions(documentNode: gql('''
    query posts(\$size: Int, \$lastEvaluatedKey: LastEvaluatedKey){
          posts(size: \$size, lastEvaluatedKey: \$lastEvaluatedKey) {
            posts {
              id
            }
            lastEvaluatedKey {
              id
              timestamp
            }
          }
        }
      '''),
       variables: {'size': this.pageSize, 'lastEvaluatedKey': this._lastEvaluatedKey}))
```

I got this error when executing above code:

```dart
OperationException (GraphQL Errors:
        Validation error of type UnknownType: Unknown type LastEvaluatedKey: Undefined location)
```

It seems that `LastEvaluatedKey` is not recognised. I have declared a dart class `LastEvaluatedKey` as below but it doesn't seem to help. Where should I put the `LastEvaluatedKey` definition in the client side?

```dart
class LastEvaluatedKey {
  final String id;
  final String timestamp;

  LastEvaluatedKey({this.id, this.timestamp});
}
```

**Comment by RanaOsamaAsif** [comment]
Hi, One possible solution is to create a toJson method in your LastEvaluatedKey class and return the fields of LastEvaluatedKey in the form of Map<String, dynamic>

**Comment by zhaoyi0113** [comment]
I have updated my class as below. But it is still not working. I still get the error `OperationException (GraphQL Errors:
        Validation error of type UnknownType: Unknown type LastEvaluatedKey: Undefined location)`.

```
class LastEvaluatedKey {
  final String id;
  final String timestamp;

  LastEvaluatedKey({this.id, this.timestamp});

  Map<String, dynamic> toJson(LastEvaluatedKey key) {
    try {
      return {
        'id': key.id,
        'timestamp': key.timestamp,
      };
    } catch (err) {
      return null;
    }
  }
}

```

**Comment by micimize** [comment]
You currently have to call `_lastEvaluatedKey.toJson()` yourself, as as [`graphql` doesn't currently do any serialization](
https://github.com/zino-app/graphql-flutter/issues/515#issuecomment-615900969)

If you're going to have a lot of input types that require serialization, you can us `json.encode` from `dart:convert`:
```dart
variables: json.encode(
  variables,
  toEncodable: (dynamic object) => object.toJson(),
)
```

**Comment by zhaoyi0113** [comment]
Thanks for your feedback. But adding `.toJson()` doesn't seem to help.

```
await this.gqClient.query(QueryOptions(documentNode: gql('''
        query posts(\$size: Int, \$lastEvaluatedKey: LastEvaluatedKey){
          posts(size: \$size, lastEvaluatedKey: \$lastEvaluatedKey) {
            posts {
              id,
              message,
              photoPaths,
              userInfo {
                username,
                picture
              }
            }
            lastEvaluatedKey {
              id
              timestamp
            }
          }
        }
      '''), variables: {
                'size': this.pageSize,
                'lastEvaluatedKey': this._lastEvaluatedKey.toJson(),
              }));
```

I updated the code above but still get the same error: 
```
OperationException (GraphQL Errors:
        Validation error of type UnknownType: Unknown type LastEvaluatedKey: Undefined location)
```

**Comment by micimize** [comment]
@zhaoyi0113 ohhh wait I think this error is that the graphql server doesn't recognize the type `LastEvaluatedKey` referenced in your query

**Comment by zhaoyi0113** [comment]
I can send query from different client so I don't think it is an issue on the server side. However, I can make it work by extracting the query parameters from LastEvlauatedKey instance like below code:

```
await this.gqClient.query(QueryOptions(documentNode: gql('''
        query posts(\$size: Int, \$lastKeyId: String!, \$lastKeyTimestamp: Long){
          posts(size: \$size, lastEvaluatedKey: {id: \$lastKeyId, timestamp: \$lastKeyTimestamp}) {
            posts {
              id,
              message,
              photoPaths,
              userInfo {
                username,
                picture
              }
            }
            lastEvaluatedKey {
              id
              timestamp
            }
          }
        }
      '''), variables: {
                'size': this.pageSize,
                'lastKeyId': this._lastEvaluatedKey.id,
                'lastKeyTimestamp': this._lastEvaluatedKey.timestamp,
              }));
```

as you can see, it takes primitive types of parameters and set them in `lastEvaluatedKey`. 
Would you consider to support passing object instance as the parameter in future release?

**Comment by micimize** [comment]
@zhaoyi0113 hmm, I'm fairly sure there must have been some difference. The error is a GraphQL validation error: `Validation error of type UnknownType: Unknown type LastEvaluatedKey`, and the only place it is referenced is
```graphql
        query posts(\$size: Int, \$lastEvaluatedKey: LastEvaluatedKey){
```
If you want to investigate it further, come to the `support` channel in the [discord](https://discord.gg/tXTtBfC)


> Would you consider to support passing object instance as the parameter in future release?
nested json Maps as variables should work just fine, but better support for `.toJson` implementing variables would be good, yes

**Comment by zhaoyi0113** [comment]
Where should I define `LastEvaluatedKey`? 
If I define it inside `gql` I will get below error:

```
input LastEvaluatedKey {
          id: String
          timestamp: Int
        }
```
```
OperationException (GraphQL Errors:
        Validation error of type NonExecutableDefinition: The LastEvaluatedKey definition is not executable.: Undefined location)
```

**Comment by micimize** [comment]
@zhaoyi0113 in graphql, inputs are defined [in the schema](https://graphql.org/learn/schema/#input-types). So, I would look at your schema and see what the method signature of `posts` is. The `lastEvaluatedKey` should have a predefined `input` type that you can reference in your query.

**Comment by zhaoyi0113** [comment]
I would say the schema is on the server side. So I don't need to define that in client side.
This is my schema:

```
type Mutation {
	sendPost(post: PostInput): Post
	savePostPhotos(id: ID!, paths: [String]): ID
}

type PaginationKey {
	id: String!
	timestamp: Long
}

input PaginationKeyInput {
	id: String!
	timestamp: Long
}

type Post {
	userId: String!
	message: String
	id: ID!
	timestamp: Long!
	userInfo: UserInfo
	photoPaths: [String]
	pstatus: Int
}

input PostInput {
	userId: String!
	message: String
}

type PostReqResponse {
	posts: [Post]
	lastEvaluatedKey: PaginationKey
}

type Query {
	presignedURL(id: ID!, count: Int!): [String]
	posts(size: Int, lastEvaluatedKey: PaginationKeyInput): PostReqResponse
	post(id: ID!): Post
}

type UserInfo {
	id: ID
	username: String
	firstName: String
	lastName: String
	name: String
	email: String
	picture: String
}

schema {
	query: Query
	mutation: Mutation
}
```

**Comment by micimize** [comment]
@zhaoyi0113 so, instead of `LastEvaluatedKey`, you want to use the input type `PaginationKeyInput`. So this should work:
```dart
await this.gqClient.query(QueryOptions(documentNode: gql('''
        query posts(\$size: Int, \$lastEvaluatedKey: PaginationKeyInput){
          posts(size: \$size, lastEvaluatedKey: \$lastEvaluatedKey) {
            posts {
              id,
              message,
              photoPaths,
              userInfo {
                username,
                picture
              }
            }
            lastEvaluatedKey {
              id
              timestamp
            }
          }
        }
      '''), variables: {
                'size': this.pageSize,
                'lastEvaluatedKey': this._lastEvaluatedKey.toJson(),
              }));
```

**Comment by zhaoyi0113** [comment]
awesome, it fixes the issue. Thanks for checking my bug.
