### ISSUE TITLE
Subscription issue: the socket keeps on connecting and disconnecting

### ISSUE THREAD

**Issue by razorabhu1995** [zino-app/graphql-flutter#653]
I think my graphql client setup is fine:

```
 final HttpLink httpLink = HttpLink(
    uri: 'http://exampleurl.com/graphql',
 );

  final WebSocketLink websocketLink =
    WebSocketLink(
    url: 'ws://exampleurl.com/graphql',
      config: SocketClientConfig(
      autoReconnect: true,
      inactivityTimeout: Duration(seconds: 30),
    ),
  );

 final Link link = authLink.concat(httpLink).concat(websocketLink);

  ValueNotifier<GraphQLClient> client = ValueNotifier(GraphQLClient(
    link: link,
    cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
  ));
```

I don't know if there is something wrong with the way by using the subscription:

```
Stream subscriptionResult;
StreamSubscription streamSubscriptionResult;

operation = Operation(documentNode: gql(messageSubscription), 
    variables : {
      'hash' : somehash
    }, operationName: 'message');

subscriptionResult = globals.client.subscribe(operation);

if(subscriptionResult != null){
  streamSubscriptionResult = subscriptionResult.listen((messages) {
    print("listening ${messages}");
  },
  onError: (e){
    print("error: $e");
  },
  cancelOnError: true);
  print("subscription result: ${streamSubscriptionResult}");
}
```

The result:
`I/flutter ( 8548): Connected to websocket. I/flutter ( 8548): Disconnected from websocket. I/flutter ( 8548): Scheduling to connect in 5 seconds...`
This happens continuously. Any solution???

**Comment by gtupak** [comment]
I am having the exact same problem

**Comment by gtupak** [comment]
Hey I ended up by fixing it! My issue was that the server expected an authentication token that I wasn't passing. I solved it by adding it to in the `initPayload` like so:

final webSocketLink = WebSocketLink(
      url: subscriptionURL,
      config: SocketClientConfig(
          autoReconnect: true,
          inactivityTimeout: Duration(seconds: 30),
          initPayload: {'api-key': _token}),
    );

**Comment by razorabhu1995** [comment]
@gtupak yah its working!! :D Thanks!!

And how to avoid the timeout!!

But do you know how to disconnect from the socket after leaving the particular view in the app??

**Comment by razorabhu1995** [comment]
Where to initialize the keepalive ?

**Comment by gtupak** [comment]
My guess is the keepalive should be done on the server-side? I am still getting the timeout, so I increased the duration to 5 minutes. I know it doesn't solve the problem but at least the user won't get disconnected continuously. If anyone has an actual fix to this I am interested.

**Comment by micimize** [comment]
I believe `keepAlive` is provided by the server, such as for [apollo server](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#apolloserver):
![image](https://user-images.githubusercontent.com/8343799/89480556-46eaa500-d75b-11ea-9d39-4350f4ae1d1c.png)

For a view-specifc subscription link, you could just make a different client for that specific view, just for subscriptions

closing this, as it seems the initial issue is resolved. If there's still an issue comment or make a new one, or come by the `#support` channel on the discord 👍

**Comment by E-A-1** [comment]
DOMException: Failed to execute 'close' on 'WebSocket': The code must be either 1000, or between 3000 and 4999. 1001 is neither.
I am facing the above issue.
