### ISSUE TITLE
clarify FetchPolicy.networkOnly docs or add more fine grained options for skipping cache entirely

### ISSUE THREAD

**Issue by troyzonzon** [zino-app/graphql-flutter#654]
**Describe the bug**
I have a listview in flutter where pulling will refresh the data. This use to work until I updated flutter and my packages. This is a pretty simple request...

Query(
                options: QueryOptions(
                   fetchPolicy: FetchPolicy.networkOnly,
                  documentNode: QueryFetch().fetchTimeline(),
                  variables: {
                    "userid": _client.id,
                    "hoa":  _client.hoa,
                    "sixtyDaysAgo": sixtyDaysAgo,
                  },
                ),

It took me a while to narrow the issue down. On initial viewing, the screen loads the data. Once I press the like button or pull to refresh the data is not updated on the screen. I have set a stop and I can see that the data is not updated once returned. I have confirmed the update call is working because I can see the updates query web tool.

I have only tested this issue on Android at the moment, I will try IOS shortly and provide more updated information.

**Comment by thanhbinh84** [comment]
I faced into the same issue, have to use 'fetchPolicy: FetchPolicy.noCache' to get new data

**Comment by micimize** [comment]
`networkOnly` skips the initial eager cache return, but still merges and re-reads results from the cache once the request completes

**Comment by micimize** [comment]
We need to either clarify FetchPolicy docs or add more fine grained options

**Comment by micimize** [comment]
The `v4` readme has a [policies section](https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#policies) now, pulled from the docs:
> * noCache: return result from network, fail if network call doesn't succeed, don't save to cache.
> * networkOnly: return result from network, fail if network call doesn't succeed, save to cache.
