### ISSUE TITLE
httpOnly cookie based authentication

### ISSUE THREAD

**Issue by ayyshim** [zino-app/graphql-flutter#661]
I am using graphql_flutter and it has good documentation on how to handle AuthLink but it doesn't fit all kinds of authentication methods. for example when using an api which store httpOnly cookie, the cookie does not get stored

I don't know if there is any other way of doing httpOnly based authentication but if there is not, then it would be nice to have that. If there is already some way around then please suggest.

**Comment by kateile** [comment]
see #592

**Comment by micimize** [comment]
closing in favor of #592
