### ISSUE TITLE
FetchMore function load only new item to current item list

### ISSUE THREAD

**Issue by freewebwithme** [zino-app/graphql-flutter#663]
I am using FetchMore in itemBuilder in ListView.builder, but after fetchmore completed, ListView widget re-rendered. I want new items added at the bottom of listview. not refreshing whole ListView.
This is because of I am doing wrong in FetchMoreOptions? This is my code.
 ```
FetchMoreOptions opts = FetchMoreOptions(
              variables: {'nextPageToken': token},
              updateQuery: (previousResultData, fetchMoreResultData) {
                var prev = previousResultData['playlistItems']['items']
                    as List<dynamic>;
                var newItems = fetchMoreResultData['playlistItems']['items']
                    as List<dynamic>;
                final List<dynamic> newMergedItems = prev + newItems;

                fetchMoreResultData['playlistItems']['items'] = newMergedItems;
                return fetchMoreResultData;
              });
```
Because of I am adding new item list like this
`fetchMoreResultData['playlistItems']['items'] = newMergedItems;`
Does this make my widget rebuild? or I can't do what I want with fetchmore function?

**Comment by vasilich6107** [comment]
Hi. Why it is the problem in the ListView re-rendering for you?
The list view renders only the on-screen visible items.

**Comment by micimize** [comment]
the widget should be rebuilt, but if the list is re-rendering (such that it jumps back to the top) then something is maybe wrong.  Try looking at the starwars review paging example code and seeing where yours differs, and maybe come to the [discord](https://discord.gg/tXTtBfC) `#support` channel.
