### ISSUE TITLE
NoSuchMethodError: Class 'Future<MultipartFile>' has no instance method 'toJson'. Receiver: Instance of 'Future<MultipartFile>'

### ISSUE THREAD

**Issue by techyrajeev** [zino-app/graphql-flutter#664]
**Describe the bug**
Getting error
`NoSuchMethodError: Class 'Future<MultipartFile>' has no instance method 'toJson'.
Receiver: Instance of 'Future<MultipartFile>'
`
While uploading the file.

As per suggestions I have used `multipartFileFrom` but still getting the error
```dart
import 'package:graphql/utilities.dart' show multipartFileFrom;

  final file = multipartFileFrom(File(videoLocalPath));

  String mutation = r'''
    mutation upload($file: Upload!, $requestId: Int!) {
      uploadFile(file: $file, requestId: $requestId) {
        id
      }
    }
  ''';

  Future<QueryResult> uploadFile(String uploadMutation, { Map<String, dynamic> variables}) {
    return _client.mutate(
        MutationOptions(
          documentNode: gql(uploadMutation),
          variables: variables,
          fetchPolicy: FetchPolicy.networkOnly
        )
    );
  }
```

If I don't use `multipartFileFrom`
  `final file = File(videoLocalPath);`
code works with a warning. But when I follow suggestions as per warning. I get error.

**Stack Trace**
```0      _JsonStringifier.writeObject (dart:convert/json.dart:659:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:740:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:695:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:650:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:846:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:831:5)
#6      JsonEncoder.convert (dart:convert/json.dart:260:30)
#7      JsonCodec.encode (dart:convert/json.dart:169:37)
#8      RawOperationData.toKey (package:graphql/src/core/raw_operation_data.dart:78:14)
#9      QueryManager._resolveQueryEagerly (package:graphql/src/core/query_manager.dart:164:37)
#10     QueryManager.fetchQueryAsMultiSourceResult (package:graphql/src/core/query_manager.dart:85:37)
#11     QueryManager.fetchQuery (package:graphql/src/core/query_manager.dart:75:9)
#12     QueryManager.query (package:graphql/src/core/query_manager.dart:46:12)
#13     GraphQLClient.query (package:graphql/src/graphql_client.dart:106:25)
```
**Expected behavior**
File should be uploaded.

When I go inside **multipartFileFrom** method it points to stub.
```import 'dart:async';

import 'package:http/http.dart';

FutureOr<MultipartFile> multipartFileFrom(/*io.File or html.File*/ f) =>
    throw UnsupportedError('io or html');
```

**Version**
  graphql_flutter: 3.0.1

**Desktop :**
flutter doctor          
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1.8)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.45.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by vasilich6107** [comment]
There is a section in the docs related to upload
https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter#graphql-upload

**Comment by micimize** [comment]
You're missing the `await` keyword
```dart
  final file = multipartFileFrom(File(videoLocalPath));
```

**Comment by micimize** [comment]
closing as I'm fairly sure the missing `await` is the issue there. Feel free to comment if I am mistaken

**Comment by mkhtradm01** [comment]
I am having the same issue even when the `await` keyword is used.

Here's my error message: `Class 'MultipartFile' has no instance method 'toJson'`

**Comment by micimize** [comment]
@mkhtradm01 I no longer maintain this project – please open a new issue. That error looks unrelated though
