### ISSUE TITLE
Add SubscriptionOptions

### ISSUE THREAD

**Issue by RodolfoSilva** [zino-app/graphql-flutter#665]
**Is your feature request related to a problem? Please describe.**
It would be really cool if we added options for registration. Thus, the mutation, query and registration widgets would be standardized.

Is there any reason today for Subscription widget to not have options like Query and Mutation widgets?

**Describe the solution you'd like**
Replace the  params operationName and query with options.

**Comment by micimize** [comment]
This is the case in `4.0.0-alpha.0` check out #648

**Comment by RodolfoSilva** [comment]
Thanks @micimize :D
