### ISSUE TITLE
How to mock an ObservableQuery

### ISSUE THREAD

**Issue by codekeyz** [zino-app/graphql-flutter#666]
**Describe the bug**
I need to write unit tests for my application. I was able to mock `mutate` & `query` methods but no success a `watchQuery`. 

I did a bit of digging into the `Query` widget and found that `watchQuery` returns an `ObservableQuery` isn't even exposed outside the package.

Any instructions on how to mock a `watchQuery`?

```dart
 /// This registers a query in the [QueryManager] and returns an [ObservableQuery]
  /// based on the provided [WatchQueryOptions].
  ObservableQuery watchQuery(WatchQueryOptions options) {
    options.policies =
        defaultPolicies.watchQuery.withOverrides(options.policies);
    return queryManager.watchQuery(options);
  }
```

**NB:** Am currently using `Mockito` library to mock the methods on the GraphQLClient.

**Comment by micimize** [comment]
[`graphql/internal.dart`](https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/internal.dart) exports `ObservableQuery`, and then figure out how to put stuff on the stream with mockito I guess. The [`v4` source](https://github.com/zino-app/graphql-flutter/blob/modularization/packages/graphql/lib/src/core/observable_query.dart) has better docstrings, and is not that different

**Comment by micimize** [comment]
in our tests we just mock a link, but yeah `ObservableQuery` is fairly entangled with the `QueryManager` so it might be hard to mock 
https://github.com/zino-app/graphql-flutter/blob/0752aa29522660746feabe07c80f8929b18ea1bf/packages/graphql/test/graphql_client_test.dart#L219-L249
