### ISSUE TITLE
Value not being returned on flutter app.

### ISSUE THREAD

**Issue by barhum** [zino-app/graphql-flutter#673]
**Describe the bug**
Query works on playground but not on Flutter.  I expected it to return an empty [ ] for the services field.  On the playground/postman the query returns the correct value.  Using the same query in flutter does not work.  The services fields are not even defined in the result when I print to console.

`    final String businessQuery = """
      query {
        businesses{
          name
          phone
          description
          pictures {
            url
          }
          employees {
            name
            avatar {
              url
            }
          }
          services {
            name
            description
            price_min
            price_max
            duration
          }
        }
      }
    """;`

**Expected behavior**
I was expecting to get the same result as the GraphQL playground/postman result.
![Screen Shot 2020-06-19 at 12 18 39 AM](https://user-images.githubusercontent.com/5341665/85102925-e6ab9e00-b1c2-11ea-87e8-894a383d2706.png)
![Screen Shot 2020-06-19 at 12 18 26 AM](https://user-images.githubusercontent.com/5341665/85102963-fb883180-b1c2-11ea-832a-6969d9100a84.png)
![Screen Shot 2020-06-19 at 12 25 41 AM](https://user-images.githubusercontent.com/5341665/85103197-72bdc580-b1c3-11ea-87ed-65a70292f6f5.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 
 -   graphql_flutter:
    dependency: "direct main"
    description:
      name: graphql_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"

**Smartphone (please complete the following information):**

**Additional context**

**Comment by micimize** [comment]
I have no idea what the issue here could be. My best guess is that `services` is an authenticated field or something. I seriously doubt we have a json parsing bug in the library or something like that

**Comment by micimize** [comment]
closing as again this doesn't look like an issue with `graphql_flutter`. I recommend coming by the [discord](https://discord.gg/tXTtBfC) `#support` channel for more help if need be
