### ISSUE TITLE
No optimisticResult in MutationOptions

### ISSUE THREAD

**Issue by Bligoubloups** [zino-app/graphql-flutter#678]
Hello !

I would like to do a mutation with optimistic result within a bloc architecture.
The thing is, there is no optimisticResult property in MutationOptions.

How can I achieve it ?

Thank You !

**Comment by micimize** [comment]
`client.watchQuery` / `ObservableQuery` also work for mutations, and is how we do reactive/observable mutations internally. You can take a look at the implementation of the `Mutation` widget for more details https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql_flutter/lib/src/widgets/mutation.dart

**Comment by Bligoubloups** [comment]
Thank you very much !
