### ISSUE TITLE
Update query on subscription

### ISSUE THREAD

**Issue by devakrishna33** [zino-app/graphql-flutter#679]
**Is your feature request related to a problem? Please describe.**
I'm currently building a chat app, the initial query will fetch the first 20 messages,  and then new messages are received in a subscription, right now there's no way to update the initial query after subscription. 

**Describe alternatives you've considered**
I have tried refetch after a payload is received in the subscription, although this works, ideally this should not be the case since it increases the number of the requests which is not necessary. It would be helpful to have a update query feature.

**Comment by micimize** [comment]
In the `v4` beta, the `Subscription` widget has an `onSubscriptionResult`, which could be used to `client.readQuery` then `client.writeQuery` ([docs]):
https://github.com/zino-app/graphql-flutter/blob/53737b5c94e365f4648ac7ccf2f47f2187419b95/packages/graphql_flutter/lib/src/widgets/subscription.dart#L10-L13

[docs]: https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#request-readquery-and-writequery
