### ISSUE TITLE
When executing a mutation, the onCompleted callback should be called AFTER the onError callback.

### ISSUE THREAD

**Issue by ronaldcurtis** [zino-app/graphql-flutter#680]
**Describe the bug**
As a developer executing a mutation request
When I receive an error from the server
Then I should be able to react to this error in the `onError` callback, before the `onCompleted` callback is run.

Example use case:
In my app, I allow the user to update his/her username. And then I `Navigator.of(context).pop` to the previous route after the mutation. But I don't want to pop the screen if there's an error. Instead I want to be able to show some kind of error message.

**To Reproduce**
1. Create a mutation using a `Mutation` widget
2. Ensure you add an `onError` and `onCompleted` params to `MutationOptions`
3. Run the mutation and receive a server error from your api.

**Expected behavior**
I expect the `onError` callback to be run first. In this callback you can save the error to the widget state.
When the `onCompleted` callback runs, it can check against this state, enabling us to run any branching logic if an error exists or not.

**Relevant code**:
https://github.com/zino-app/graphql-flutter/blob/master/packages/graphql/lib/src/core/query_options.dart#L181

**Submitted PR**:
https://github.com/zino-app/graphql-flutter/pull/681

**Comment by micimize** [comment]
consolidating into #643
