### ISSUE TITLE
pass custom channel to websocket link

### ISSUE THREAD

**Issue by yap-studios** [zino-app/graphql-flutter#684]
Hi,

Is there a way to receive and handle ping/pong messages from a server?

Rgards

**Comment by micimize** [comment]
what is a "ping/pong" message? If you mean subscription keep-alive messages, [the websocket client should handle them for you](https://github.com/zino-app/graphql-flutter/blob/1b0f7173d24a02748982e3cd1af332b36ac2c374/packages/graphql/lib/src/socket_client.dart#L114-L123)

**Comment by yap-studios** [comment]
@micimize, My question is about ping/pong frames not keepalive messages.

**Comment by yap-studios** [comment]
@micimize, when a server sends a websocket ping message I would like to receive the ping message and respond with a pong message.

So no, I don't mean keep-alive messages.

**Comment by micimize** [comment]
Hmm – well, that sounds like you'd like to access the underlying websocket for some non-graphql implementation detail. That seems like a fair ask to me, but unfortunately the [websocket is currently private](https://github.com/zino-app/graphql-flutter/blob/1b0f7173d24a02748982e3cd1af332b36ac2c374/packages/graphql/lib/src/socket_client.dart#L82). You could

**Comment by micimize** [comment]
If you use the v4 alpha, you can [pass a `channel` to `gql_websocket_link`](https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/lib/src/link.dart#L50), which means you might be able to do what you want that way

**Comment by yap-studios** [comment]
Would you consider making the websocket publicly accessible? Are there any drawbacks?  I'm working on a production app and would like to stick to a stable version if possible.

**Comment by micimize** [comment]
@yap-studios I think it should be, but it might be a minute before it gets done. In the meantime you can basically copy the websocket link and websocket client and make the vars public

**Comment by micimize** [comment]
`4.0.0-alpha.6` now has an `onConnectOrReconnect` callback. Let me know if that solves the issue:
https://github.com/zino-app/graphql-flutter/blob/7192c1669c7dbecff0bbcd0665522c5b41207ab2/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L67-L70

**Comment by micimize** [comment]
I believe this is solved by the above in (#648),– please try with `4.0.0-beta.1` and comment if it is not satisfactory.

There is also even a way to override the connect function now:
https://github.com/zino-app/graphql-flutter/blob/d81011388be3787ea1221be7342b8c3fe25ffdd4/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L116

We can't really expose the raw socket as it is recreated on reconnects
