### ISSUE TITLE
Support certificate pinning

### ISSUE THREAD

**Issue by thanhbinh84** [zino-app/graphql-flutter#685]
**Is your feature request related to a problem? Please describe.**
Cannot implement certificate pinning  

**Describe the solution you'd like**
When connecting with backend on Android using OkHttp client, it is easy to implement certificate pinning. With GraphQL, I don't know how to implement this.

**Comment by micimize** [comment]
I have no idea what this is but it sounds like an http level concern. You can pass your own `httpClient` to `HttpLink` so you should be able to do this

**Comment by thanhbinh84** [comment]
@micimize if we don't pass httpClient, what is the default httpClient library we are using?

**Comment by thanhbinh84** [comment]
If we use Android HttpURLConnection & iOS NSURLSession, the connection security such as certificate validation will be handled by the API. I am wondering which kind of http client our GraphQL flutter is using, I read the code but couldn't figure out

**Comment by micimize** [comment]
we use the default from `package:http/http.dart` – https://pub.dev/documentation/http/latest/http/http-library.html

This article seems to address using it for ssl pinning https://medium.com/surfstudio/ssl-pinning-in-flutter-apps-254e01e57965

**Comment by thanhbinh84** [comment]
@micimize Thank a lot for the link, it is very helpful. 

It looks https://api.flutter.dev/flutter/dart-io/HttpClient/badCertificateCallback.html is more secure than `package:http/http.dart`, as I don't see our default http library has any certificate validation in source code. 

But I cannot pass `dark-io:httpClient` to `HttpLink` as `The argument type 'HttpClient' can't be assigned to the parameter type 'Client'.`

```
SecurityContext context = SecurityContext();
  context.setTrustedCertificatesBytes(null);
  HttpClient http = new HttpClient(context: context);

  http.badCertificateCallback =
      (X509Certificate cert, String host, int port) {
    print("!!!!Bad certificate");
    return false;
  };

  final HttpLink link = HttpLink(uri: Env.graphQLUrl, headers: {'x-api-key': Env.graphQLApiKey}, httpClient: http);
```
