### ISSUE TITLE
getToken is not called on every Request

### ISSUE THREAD

**Issue by lazylazyllama** [zino-app/graphql-flutter#688]
If I make a graphql request and my token changed internally, graphql won't recognize it.

graphql_flutter should execute getToken() before each request to make sure that the token is current.
Only updating the token on error is no solution as on my app there are multiple tokens that can be correct and if I log out of a certain context and log in to another the old token is not invalidated straight away. So graphql just uses the old token and gets old content.

**Comment by micimize** [comment]
mm, yeah this should definitely be configurable at least

**Comment by lazylazyllama** [comment]
> mm, yeah this should definitely be configurable at least

I think calling getToken() on each request should be the standard as it shouldn't be a performance problem because it usually only is about copying a string from the Autoservice to graphql. The Autoservice should automatically update its token to be valid and so on ... So it could also be a performance benefit as we would not have to wait for a request to fail, call getToken() then and try it again as it is being done right now.

**Comment by micimize** [comment]
@lazylazyllama yeah, the api should probably allow for custom exception handling but right now it's way too presumptuous.

<details>
<summary>For now, here's a version of <code>AuthLink</code> that always calls <code>getToken</code> that probably works</summary>

```dart
import 'dart:async';
import 'package:meta/meta.dart';

import "package:gql_exec/gql_exec.dart";
import "package:gql_http_link/gql_http_link.dart";
import "package:gql_link/gql_link.dart";
import "package:gql_error_link/gql_error_link.dart";
import "package:gql_transform_link/gql_transform_link.dart";

class AuthLink extends Link {
  Link _link;
  String token;

  final FutureOr Function() getToken;

  final String headerKey;

  AuthLink({
    @required this.getToken,
    this.headerKey = 'Authorization',
  }) {
    _link = Link.concat(
      ErrorLink(onException: handleException),
      TransformLink(requestTransformer: transformRequest),
    );
  }

  Future<void> updateToken() async {
    token = await getToken();
  }

  Stream<Response> handleException(
    Request request,
    NextLink forward,
    LinkException exception,
  ) async* {
    if (exception is HttpLinkServerException &&
        exception.response.statusCode == 401) {
      await updateToken();

      yield* forward(request);

      return;
    }

    throw exception;
  }

  Request transformRequest(Request request) =>
      request.updateContextEntry<HttpLinkHeaders>(
        (headers) => HttpLinkHeaders(
          headers: <String, String>{
            ...headers?.headers ?? <String, String>{},
            headerKey: token,
          },
        ),
      );

  @override
  Stream<Response> request(Request request, [forward]) async* {
    await updateToken();

    yield* _link.request(request, forward);
  }
}
```

</details>

@britannio you could probably also use this

**Comment by lazylazyllama** [comment]
Thank you :)

**Comment by micimize** [comment]
https://pub.dev/packages/graphql/versions/4.0.0-alpha.2 is published, and the provided `AuthLink` has been simplified back to the original behavior of just calling `getToken` every request.

The exception handling stuff might make sense for some use cases but it is really easy to implement custom auth links
