### ISSUE TITLE
Give RunMutation function ability to control onCompleted callback

### ISSUE THREAD

**Issue by lfa9603** [zino-app/graphql-flutter#693]
I am trying to use the Mutation class in a Parent/Child component, where the child triggers the function where the mutation happens. My current problem is that defining onCompleted at Mutation class definition is too early as the child contains part of the information required for the onCompleted callback.

Possible solutions:
- Allow to await the RunMutation function and return the QueryResult
- Allow to specify the onCompleted callback later within RunMutation

Alternatives:
- Flatten my Parent/Child components. This would cause my class to become significantly bigger
- Add local variables at Parent level and set variables with required data before the mutation is run, this exposes a copy of the required data to the parent but it is a fairly ugly solution.

**Comment by micimize** [comment]
It might not be that well documented, but `runMutation` already returns a `MultiSourceResult`, so you should be able to do whatever you're trying to do:
https://github.com/zino-app/graphql-flutter/blob/2b6339b60c259b24990d63b5c8b7081e83a81f0c/packages/graphql_flutter/lib/src/widgets/mutation.dart#L93-L98

so you could do something like `await runMutation().networkResult`

**Comment by micimize** [comment]
Closed by the above – please come by the `#support` channel in [discord](https://discord.gg/tXTtBfC) if you have any usage questions or comment if you think this should be reopened
