### ISSUE TITLE
Graphql fragments

### ISSUE THREAD

**Issue by hadi-norouzi** [zino-app/graphql-flutter#694]
I need to use fragment in graphql for reduce response data, but i can't find any doc or method for that.

**Comment by SanjiKir** [comment]
@hadi-norouzi Hey man! Fragments don't need a special method, it's way to share graphql queries between each other. 
You should create a `item_fragment.graphql` file, fill it with your fragment, generate graphql class using `Artemis` for example and then you can reuse your fragment. 

Or simpler way just create a string. See more on fragments here https://graphql.org/learn/queries/#fragments. I would recommend you to close this issue.

**Comment by hadi-norouzi** [comment]
I have this mutation string and fragment.

```
String searchOnMapMutation = r'''
  mutation map ($data: String){
    searchOnMap(data: $data){
      # searchLocationResultFragment
    }
  }
''';

String searchLocationResultFragment = r'''
  fragment locationRes on SearchOnMapRes {
    title
    region
    province
  }
''';
```

Can you help me for add this fragment to mutation string without using ```Artemis```?

**Comment by SanjiKir** [comment]
```
String searchOnMapMutation = r'''
  mutation map ($data: String){
    searchOnMap(data: $data){
       ...searchLocationResultFragment
    }
  }

  fragment locationRes on SearchOnMapRes {
    title
    region
    province
  }
''';
```

Something like that. You can export to constant fragment.
@hadi-norouzi

**Comment by hadi-norouzi** [comment]
it's static, i want add another fragment to mutation and ignore this fragment for new events.  it's possible?
@SanjiKir

**Comment by SanjiKir** [comment]
If you want to use this fragment only once and then use other fragments with the same mutation you have to create another mutation. I am not sure it's possible to dynamically substitute fragment in the Query, you can try template literals with ternary operators, but I would seriously recommend you to ask why are you even doing such things. 

However, your questions are graphql related and not flutter related, I do recommend you to read the documentation and maybe find some playground to understand graphql itself a bit better.

**Comment by hadi-norouzi** [comment]
@SanjiKir Thanks

**Comment by SalahAdDin** [comment]
Is it possible to pass fragments as variable into string queries?

```dart
const String graphQLFragmentBody =
    r'''fragment AuthFields on UsersPermissionsLoginPayload {
    jwt
    user{
      username
      email
      confirmed
    }
}
''';

const String graphQLDocumentRegisterUser = '''
    $graphQLFragmentBody
    mutation RegisterUser(
        \$username: String!,
        \$email: String!,
        \$password: String!
    ){
  register(input: { username: \$username, email: \$email, password: \$password }) {
    ...UsersPermissionsLoginPayload
  }
}
''';
```
