### ISSUE TITLE
Incorrect pollInterval documentation

### ISSUE THREAD

**Issue by philipgiuliani** [zino-app/graphql-flutter#695]
Hi, the `pollInterval` documentation says that it has to be specificed in `milliseconds`, but it should actually be `seconds`.

What do you think about changing it from `int` to `Duration`? 

https://github.com/zino-app/graphql-flutter/blob/eec7d2c5e8d753f7d2d62b2964cb61730caeae42/packages/graphql/lib/src/core/query_options.dart#L129

**Comment by micimize** [comment]
@philipgiuliani it should really be a `Duration`

**Comment by philipgiuliani** [comment]
I also think so, especially because it gets converted to a duration anyways: https://github.com/zino-app/graphql-flutter/blob/1ef311a89acc9339da205af409934cd6b66dc1ad/packages/graphql/lib/src/scheduler/scheduler.dart#L44

**Comment by micimize** [comment]
closed by fe02bb8daed67ae635b97a8d4fe34fa015bbcdd8 on beta
