### ISSUE TITLE
Missing guide how to send auth token to subscription

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-app/graphql-flutter#701]
Hello,

i have app with apollo serrver on backend and graphql_flutter in frontend. I have implemented subscriptions and everything works fine. However i want to add authentication to subscriptions. From apollo server side it looks like:

```
...
subscriptions: {
            onConnect: async (connectionParams: any, webSocket) => {
                if (connectionParams.authToken) {
                    const isAuthorized = await authService.isTokenValid(connectionParams.authToken);
                    if (!isAuthorized) {
                        throw new AuthenticationError('Authentication token is invalid, please log in');
                    }
                }

                throw new AuthenticationError('Authentication token is invalid, please log in');
            },
        }
```

but i cannot find the way how to add auth token from your plugin side. I have this config:
```
if (subscriptionUri != null) {
    /*  final authService = GetIt.instance<AuthService>();
    var auth = new Map<String, dynamic>();
    auth.putIfAbsent('authToken', () => authService.athToken); */
    final WebSocketLink websocketLink = WebSocketLink(
        url: subscriptionUri,
        config: SocketClientConfig(
            // initPayload: auth,
            autoReconnect: true,
            inactivityTimeout: null));

    link = link.concat(websocketLink);
  }
```

as you can see i have tried via initialPaylod but it does not work.

Any help would be more than welcome.

Thanks

**Comment by micimize** [comment]
You probably want `initPayload: () => { 'authToken': authToken }` in your `SocketClientConfig`, or possibly wrapped in headers as described in https://github.com/zino-app/graphql-flutter/issues/411#issuecomment-530254321 :
```dart
initPayload: {
  "headers": {"Authorization": 'Bearer ' + token}
}
```

**Comment by vytautas-pranskunas-** [comment]
Does it fires on every reconnect? Because user might be not logged in at
first or token will change every 30 mins?

**Comment by micimize** [comment]
@vytautas-pranskunas- yes, our `SocketClient` sends the `initPayload` on instantiation, and is re-instantiated on reconnect

**Comment by vytautas-pranskunas-** [comment]
Nop it is not working...
because in your comment initPayload is not function - it is Map. So when socket gets initialized first token is not available yet and all other attempts to connect by socket leads to sending to same empty object. 
So if initPaylod would be a function it would work but now not really...

Any other ideas?

**Comment by micimize** [comment]
@vytautas-pranskunas- if you are on the most recent version it accepts a function
https://github.com/zino-app/graphql-flutter/blob/2b6339b60c259b24990d63b5c8b7081e83a81f0c/packages/graphql/lib/src/socket_client.dart#L55-L63

**Comment by vytautas-pranskunas-** [comment]
After update it is working.
Thanks :)

**Comment by vytautas-pranskunas-** [comment]
I have one more question. Maybe you have good example or reading resources
how to not loose messages while subscription is disconnected?

**Comment by micimize** [comment]
@vytautas-pranskunas- I don't – haven't actually worked with subscriptions much
