### ISSUE TITLE
Query retry

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-app/graphql-flutter#703]
Hello guys,

I would like to know is there a possibility to do query retry on error (after auth token refresh for example)?

Thanks

**Comment by vasilich6107** [comment]
Use https://pub.dev/packages/fresh_graphql package it will help you with refresh of the token and resend the query

**Comment by micimize** [comment]
yeah this is a userland problem – it might be a hassle to handle at the flutter widget level so I'd recommend a custom link like above

**Comment by iamchathu** [comment]
Is there a documentation to do this rather than using another package?
