### ISSUE TITLE
Add cache lifetime property for each request

### ISSUE THREAD

**Issue by lazylazyllama** [zino-app/graphql-flutter#705]
I am using Hive to cache all my requests. But some requests like pdf files I only want to cache for a certain amount of time and not forever to prevent my apps cache to explode.

So it would be nice if `QueryOptions` would have a property like `cacheLifetime`, which would make sure that the cache of this specific query will be deleted after the specified time has passed.

**Comment by micimize** [comment]
This is an outstanding issue (time to live) #340
