### ISSUE TITLE
Get progress while uploading files

### ISSUE THREAD

**Issue by PenF00k** [zino-app/graphql-flutter#708]
It would be great to be able to monitor progress value during file upload.
I guess, it could be some sort of a callback that brings the current progress value.
Please tell me if it is already implemented.

**Comment by PenF00k** [comment]
It will be great to be able to

**Comment by micimize** [comment]
This is not implemented and seems fairly difficult & out of scope. v4 uses [gql_http_link](https://pub.dev/packages/gql_http_link), so you could maybe PR a context-based listener for this to http://github.com/gql-dart/gql

**Comment by syssam** [comment]
@micimize Can you add a onSendProgress method, like dio
https://pub.dev/packages/dio

**Comment by micimize** [comment]
@syssam you could try using the v4 alpha with https://pub.dev/packages/gql_dio_link

**Comment by syssam** [comment]
@micimize v4 document does not clearly.
I think MutationOptions add "onSendProgress" method will be easy to use.

**Comment by micimize** [comment]
@syssam possibly, but as I said, it would be quite difficult to implement. If I had need of this functionality I would switch to v4 and PR additional context for supporting it to `gql_dio_link`, which could eventually become the default link here anyways

**Comment by syssam** [comment]
@micimize thanks, waiting for your good news. I view the gql_dio_link source code, it seems not to support file upload.
