### ISSUE TITLE
Question on GraphQLConsumer

### ISSUE THREAD

**Issue by rdamario1169** [zino-app/graphql-flutter#71]
I am new to flutter and want to use GraphQL and your package.
When I try to call GraphqlConsumer it seems that the builder never gets called.

Here is the example. Can someone help me with what I am doing wrong.

main.dart
`
    import 'package:flutter/material.dart';
    import 'package:graphql_flutter/graphql_flutter.dart';
    import './queries/query_storeship_orders.dart' as queries;

   void main() {
      runApp(TabBarDemo());
    }

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ValueNotifier<Client> client = ValueNotifier(
      Client(
        endPoint: 'http://172.16.18.12:8080/graphql',
        cache: InMemoryCache()
      ),
    );

    return GraphqlProvider(
      client: client,
      child: CacheProvider(
        child: MaterialApp(
          home: DefaultTabController(
            length: 3,
            child: Scaffold(
              appBar: AppBar(
                bottom: TabBar(
                  tabs: [
                    Tab(icon: Icon(Icons.directions_car)),
                    Tab(icon: Icon(Icons.directions_transit)),
                    Tab(icon: Icon(Icons.directions_bike)),
                  ],
                ),
                centerTitle: true,
                title: Text('Ship IT 1'),
              ),
              body: TabBarView(
                children: [
                  ListView.builder(
                    padding: new EdgeInsets.all(8.0),
                    itemExtent: 20.0,
                    itemBuilder: (BuildContext context, int index) {
                      return new Text('entry $index');
                    },
                  ),
                  Icon(Icons.directions_transit),
                   RaisedButton(
                    child: const Text('Connect with Twitter'),
                    color: Theme.of(context).accentColor,
                    elevation: 4.0,
                    splashColor: Colors.blueGrey,
                    onPressed: ()  {
                      // Perform some action
                      //Client client = GraphqlProvider.of(context).value;
                      //var hello = client.query(query: queries.query_storeship_orders);

                      return new GraphqlConsumer(
                        builder: (Client client) {
                          var result = client.query(query: queries.query_storeship_orders);
                          return new Container(
                            child: new Text('Hello widget'),
                          );
                        }
                      );

                    },
                  ),
                  //Icon(Icons.directions_bike),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
`

query_storeship_orders.dart

`String query_storeship_orders = """
query{
storeOrderStatus {
  id,
	storeno,
  storename,
  cust_name,
  cust_email,
  order_number,
  order_status
}  
}
"""
.replaceAll('\n', ' ');`

**Comment by HofmannZ** [comment]
@rdamario1169 Hi, it seems like you defined the `ValueNotifier` in the `build` method instead of the `main` function. You could fix the issue by moving the declaration of the `ValueNotifier`, but I would recommend using the `Query` widget instead.

The `Query` widget allows you to easily run queries and allow you to intuitively handle errors.

**Comment by rdamario1169** [comment]
Thanks @HofmannZ , One more question. If the endpoint is down will I get an error callback using Query it won't be able to connect.

**Comment by HofmannZ** [comment]
@rdamario1169 Right now the `Query` widget swallows errors. The `query` method on the client does throw the error. 

We are completely rewriting the transport and query logic, witch will have an option to handle errors more gracefully.

**Comment by rdamario1169** [comment]
@HofmannZ , thank You. 

You guys are going good work.
