### ISSUE TITLE
[subscriptions] confirm message received to server

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-app/graphql-flutter#711]
I am building chat. I succesfully implemented subscriptions but i cannot find a way how to send acknowledgment back to server that messages has been received.

**Comment by micimize** [comment]
@vytautas-pranskunas- I don't think we have this implemented. We could probably stand to have an api for sending subscription protocol messages directly

**Comment by vytautas-pranskunas-** [comment]
That would be awesom because now i had to create standard graphql mutation :( But subscbscriptions would be so much better

**Comment by ram231** [comment]
is this equivalent to ping pong method issued from websockets?

**Comment by vytautas-pranskunas-** [comment]
Yes that's exactly what I need. This would super helpful while building
chat like messages (while still using gql for rest of app) because then you
can send back to server different messages like - messageSeen etc with
payload

**Comment by micimize** [comment]
`4.0.0-alpha.6` now has an `onConnectOrReconnect` callback. Let me know if that solves the issue:
https://github.com/zino-app/graphql-flutter/blob/7192c1669c7dbecff0bbcd0665522c5b41207ab2/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L67-L70

**Comment by vytautas-pranskunas-** [comment]
hi, if you could add small demo on how to use it - then i can tell more about does it solves this problem or not :)

**Comment by micimize** [comment]
Something like
```dart
WebSocketLink(
  config: SocketClientConfig(
    onConnectOrReconnect: (socket) => socket.stream.listen(myOnDataReceivedCallback)
  ),
)
```

**Comment by vytautas-pranskunas-** [comment]
ok...
in case of chat...
in my case - client 1 sends message through gql server and wants to verify that client 2 has received it.
to attcheive this when message is received by client 2 i am doing http call to api with message id and server pushes data to client 1 that messages has been seen.

with this callack method how this would look like? how seerver would listen to data?

**Comment by micimize** [comment]
@vytautas-pranskunas- I'm not sure – you could define a custom "message received" type and listen to it on the server, then write a message on the socket every time you see the type of data you want to confirm. It will be kind of involved though

**Comment by vytautas-pranskunas-** [comment]
hmm need to check how to define custom message on apollo graphql server

**Comment by micimize** [comment]
closing this as `onConnectOrReconnect` in `beta` enables it, and the specific feature itself is out of scope of the client
