### ISSUE TITLE
How to close a subscription?

### ISSUE THREAD

**Issue by RobertoOrtis** [zino-app/graphql-flutter#714]
Hello,

I would like to know how to close a subscription or which would be the best way of avoiding opening a new subscription each time I enter a page in the app.

My issue: I have a subscription in my home page, and everytime I go to another page and then back to the home page, a new subscription is being made.

So, how can the close a subscription when leaving the home page, and how can I have a subscription that starts at the top of my app's hierarchy so doesn't matter how many times I leave or enter my home page, I keep the same subscription.

I am using version 4.0.0-alpha.3

**Comment by micimize** [comment]
@RobertoOrtis you're saying the `Subscription` widget isn't closing the subscription on `dispose`?

You could move the subscription code to the top in a provider or something for the other part

**Comment by RobertoOrtis** [comment]
> @RobertoOrtis you're saying the `Subscription` widget isn't closing the subscription on `dispose`?

Yes. What would be the proper way to dispose it whenever I exit the page where the subscription is on?

> You could move the subscription code to the top in a provider or something for the other part

I would like this way better but I am still learning flutter/dart... Could you please enlighten me and show me how it could be done?

**Comment by RobertoOrtis** [comment]
I managed to put the subscription on top of my tree by using BLoC patter (flutter_bloc). Thank you!

**Comment by JoshanTandukar** [comment]
As for us we cant make subscription top level due to app complexity. Now this issue is same subscription double triples every time the tabs are changed and cannot find a way to dispose the previous connection even with subscription connection id (counter).
We cant make subscription top level even if we want to using provider. Help needed.
