### ISSUE TITLE
How to mutate multiple objects?

### ISSUE THREAD

**Issue by naumansabir-wecrunch** [zino-app/graphql-flutter#716]
This is what i am trying to achieve, i have a table where i have to insert multiple rows and i know graphql supports bulk insertion but I don't know if this library supports it yet. Is it possible to do it using this library? I am using graphql-flutter version 3.1.0.

```graphql
mutation {
  insert_author(
    objects: [
      {id: 1, name: "Joe"},
      {id: 2, name: "June"},
      {id: 3, name: "John"},
      {id: 4, name: "Judy"}
    ]
  ) {
    affected_rows
  }
}
```

**Comment by micimize** [comment]
@naumansabir-wecrunch this looks like a normal mutation  to me – there's no reason why it shouldn't work

**Comment by naumansabir-wecrunch** [comment]
> @naumansabir-wecrunch this looks like a normal mutation to me – there's no reason why it shouldn't work

Is there any way i could generate types/object classes like apollo graphql does it? It would be easier to simply pass specific type of objects.

**Comment by micimize** [comment]
@naumansabir-wecrunch there are a few code generation projects, like `artemis` or my `major_graphql` https://github.com/micimize/major project, but `graphql_flutter` itself is untyped

**Comment by naumansabir-wecrunch** [comment]
> @naumansabir-wecrunch there are a few code generation projects, like `artemis` or my `major_graphql` https://github.com/micimize/major project, but `graphql_flutter` itself is untyped

@micimize Thanks!
