### ISSUE TITLE
web: in_memory_html/localstorage exception

### ISSUE THREAD

**Issue by christophemacabiau** [zino-app/graphql-flutter#717]
Seems that when initializing the cache, we try to stringify this FutureOr<String>:
https://github.com/zino-app/graphql-flutter/blob/f12aae525b1bf7fd5c3120a3a62bccd87cabad68/packages/graphql/lib/src/cache/in_memory_html.dart#L16
which produces `masterKey="Instance of '_Future<String>'"`

Later we try to find this key in localStorage:
https://github.com/zino-app/graphql-flutter/blob/f12aae525b1bf7fd5c3120a3a62bccd87cabad68/packages/graphql/lib/src/cache/in_memory_html.dart#L76
and we dont find it, but we try to `jsonDecode` it, which produces a `Invalid argument: null` exception

graphql_flutter 3.0.1
flutter 1.31.0-9.1.pre

**Comment by micimize** [comment]
This is likely solved by `HiveStore` in `4.0.0-beta.1` (#648). Please give it a try and comment if there's still an issue

**Comment by micimize** [comment]
double checked and this is solved on v4

**Comment by christophemacabiau** [comment]
@micimize thanks, it works
sorry for the late answer, I forgot this isssue...
