### ISSUE TITLE
Separate generic GraphQL client code from flutter implementation

### ISSUE THREAD

**Issue by adelcasse** [zino-app/graphql-flutter#72]
**Is your feature request related to a problem? Please describe.**
When trying to use Graphql-flutter in a framework-agnostic way, it is today possible to target directly non-Flutter specific parts (Client, ...) of this library, which is probably the best in Dart as of today.

For example, following the BLoC pattern, we use graphql-flutter inside our business logic components that (even if used today with Flutter) are intended to be framework-agnostic (and could be used with AngularDart for example ?).

The problem is that, making a separate Dart package for this business logic components, a dependency on graphql-flutter would bring a dependency on Flutter itself, even if we're not using Flutter-specific parts of the package.

**Describe the solution you'd like**
Separate this wonderfull lib in 2 packages : 1 framework-agnostic with generic GraphQL, and another one with Flutter implementation targetting the first one

**Describe alternatives you've considered**
If this is not intended, we would probably create a new library based on the "generic" GraphQL implementation from this library. This would probably bring some overhead in maintaining synchronization between the 2 projects contributions.

**Comment by adelcasse** [comment]
I've just come across the README and just saw this statement "With that being said, the project lives currently still inside one package. We plan to spilt up the project into multiple smaler packages in the near future, to follow Apollo's modules design"

So that's great, sorry I didn't read this before ;).

And, for your information, we're really interested in my company in helping for that as it matches our development needs ;)

**Comment by HofmannZ** [comment]
@adelcasse Yes will be adding that to version 1.0.0

**Comment by jeprojects** [comment]
@HofmannZ Is it possible to access the GraphQL client now for testing with 1.0.0-alpha.4?

I tried, but getting an error:

> RangeError (index): Invalid value: Valid value range is empty: 0

Here is a sample of the code, perhaps I am doing something wrong?

```
      HttpLink httpLink = HttpLink(
        uri: graphQlEndpoint + '/graphql',
      );

      GraphQLClient graphql = GraphQLClient(
        link: httpLink,
        cache: _cache,
      );

      QueryOptions q = QueryOptions()
       ..document = signedRequest.body
       ..context = <String, dynamic>{
        "headers": signedRequest.headers,
      };

      var result = await graphql.query(q);
```

**Comment by jeprojects** [comment]
@HofmannZ Thanks! Keep up the awesome work.

**Comment by dustin-graham** [comment]
Perhaps what I'll experiment with first is to use my fork to trim out Flutter pieces and make it compatible with AngularDart and see what it looks like at that point. And then try to see if I can refactor this library to depend on the trimmed-down base GraphQL library.

**Comment by HofmannZ** [comment]
@dustin-graham It's on the top of the todo list now, just having the rolling impediments:
- The subscriptions are still not merged with the new client
- No example setup to test subscriptions implementation

After those to impediments the refactoring should be minimal because I kept code splitting in mind when I did the initial refactoring.

**Comment by truongsinh** [comment]
Separation MR at #203

**Comment by micimize** [comment]
`graphql/client.dart` is now [in beta](https://pub.dartlang.org/packages/graphql/versions/1.0.1-beta), though reeeeeaaaaally lacking in docs

will leave this open until it is better documented and out of beta

**Comment by jaumard** [comment]
graphql is not yet in pub right ? Does it change a lot from the one currently bundled into this one ?

**Comment by mainawycliffe** [comment]
@jaumard It doesn't change much at all. You can find the beta on pub [here](https://pub.dev/packages/graphql/versions/1.0.1-beta.7). There are some examples too, though more docs and examples are required.

**Comment by jaumard** [comment]
Ho ok didn't pop on search ^^ thanks @mainawycliffe ! I'll try it, as I don't need the flutter part I prefer not having it in my deps :)

**Comment by klavs** [comment]
Why is it dependent on `dart:io`? As far as I know, it makes it incompatible with web platform

**Comment by kei42** [comment]
Hello,
I've been trying to use the package on web platform with graphql: ^1.0.1 for websockets and it seems that the file socket_client.dart depends on dart:io is it normal ? 
I've been trying to implement it based on this thread : https://github.com/zino-app/graphql-flutter/issues/231

Thanks.

**Comment by micimize** [comment]
@kei42 @klavs  just made #295 to track the `dart:io` issue
