### ISSUE TITLE
Subscription lost when reconnected to server

### ISSUE THREAD

**Issue by RobertoOrtis** [zino-app/graphql-flutter#721]
I know this issue was resolved for version 3 a while back, but I am experiencing it with version 4. Is there a hot fix for this? It would be greatly appreciated.

**Comment by RobertoOrtis** [comment]
At the moment, I will be implementing the reconnection myself by sending a query to the server every 30 seconds and check its status. The status will go into a bloc pattern (using flutter_bloc). Whenever, the connection is recovered after being lost, it will send a signal to all blocs that are using GraphQL subscriptions.

For example, in a messaging app, messages sent by a user, while server was down, will be sent once the connection is recovered and possible incoming messages retrieved.

Please let me know if this could be a good approach while it is implemented in v4.

**Comment by micimize** [comment]
@RobertoOrtis I released `4.0.0-alpha.4` earlier today which has a migrated/updated version of the old websocket link

**Comment by RobertoOrtis** [comment]
Good! It now reconnects fine. However, it keeps disconnecting after 30 seconds. I set `inactivityTimeout` to `null` and that fixes it. Is that good enough or should I avoid doing it that way?

**Comment by micimize** [comment]
@RobertoOrtis I'm honestly not sure. If you're not worried about having too many open connections to the server then it should be fine

**Comment by RobertoOrtis** [comment]
I am sending, every 15 seconds, a keepAlive message from the server to the client; however, the client is not receiving it somehow.
