### ISSUE TITLE
[docs] Add a note, that the order of `Link` matters

### ISSUE THREAD

**Issue by bakeyevrus** [zino-app/graphql-flutter#722]
Hello,

I had spent a couple of hours getting `access_denied` error until I found out, that the order of `Link` actually matters. 
For example, this piece of code was producing an error:
```dart
  GraphQLClient _createGraphQLClient({String token}) {
    return GraphQLClient(
      cache: InMemoryCache(),
      link: Link.from([
        HttpLink(
          uri: '<your URI>',
        ),
        if (token != null && token.isNotEmpty)
          AuthLink(
            getToken: () => 'Bearer $token',
          ),
      ]),
    );
  }
```
And this is how I've managed to get rid of the mentioned issue:
```dart
  GraphQLClient _createGraphQLClient({String token}) {
    return GraphQLClient(
      cache: InMemoryCache(),
      link: Link.from([
        if (token != null && token.isNotEmpty)
          AuthLink(
            getToken: () => 'Bearer $token',
          ),
        HttpLink(
          uri: '<your URI>',
        ),
      ]),
    );
  }
```
Adding kind of this note to the docs can save a couple of hours to less experienced people (as me :) )

**Comment by vasilich6107** [comment]
@bakeyevrus PRs are wellcome

**Comment by micimize** [comment]
I've added a more detailed section for `v4` to the README. It has a different link system but it includes the note on order https://github.com/zino-app/graphql-flutter/tree/modularization/packages/graphql#combining-multiple-links

**Comment by micimize** [comment]
we now have a whole section on link composition https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#composing-links
