### ISSUE TITLE
Query component sometimes renders x2 times from cache

### ISSUE THREAD

**Issue by vasilich6107** [zino-app/graphql-flutter#725]
**Describe the issue**
Query component sometimes renders x2 times from cache

See the attached gif
![Screen Recording 2020-09-11 at 10 35 27](https://user-images.githubusercontent.com/6721286/92887028-d94a2c80-f41c-11ea-95c8-b9f258c0b40a.gif)

**To Reproduce**
Read https://github.com/artflutter/graphql_toolchain#getting-started
Run https://github.com/artflutter/graphql_toolchain/
Navigate to simple section
https://github.com/artflutter/graphql_toolchain/blob/master/lib/simple.dart

**Expected behavior**
Should always render one time from cache.

**Comment by vasilich6107** [comment]
I figured out that this happens due to the way how `Query` widget works with initial state of `StreamBuilder`
https://github.com/zino-app/graphql-flutter/blob/modularization/packages/graphql_flutter/lib/src/widgets/query.dart#L80

**Comment by micimize** [comment]
Seems similar to #726 where the issue is [due to `StreamBuilder` fundamentals](https://stackoverflow.com/a/57562409/2234013):
> StreamBuilder makes two build calls when initialized, once for the initial data and a second time for the stream data.
> 
> Streams do not guarantee that they will send data right away so an initial data value is required. Passing `null` to `initialData` throws an InvalidArgument exception.
>
> StreamBuilders will always build twice even when the stream passed is null.

**Comment by vasilich6107** [comment]
@micimize may be it will be reasonable to make similar to the `ferry` solution and introduce the separate initial state for stream builder?
https://github.com/gql-dart/ferry/blob/master/ferry_flutter/lib/src/query.dart#L49

**Comment by micimize** [comment]
@vasilich6107 [`None` is the same as our `loading`](https://github.com/gql-dart/ferry/blob/0709509ea03c04f55a3da3410fdd13c02c45a3f4/ferry/lib/src/operation_response.dart#L9-L10) – but more importantly any implementation that depends on the frequency of a `build` or `builder` being called is very fragile and likely to break eventually.

Is this behavior breaking some specific code you have, or are you concerned with elegance?

**Comment by vasilich6107** [comment]
@micimize none of that.
It is more like "oh, I did not expect that behaviour. It could be a bug. I need to check)"
I'll close this issue for now.
If anyone will have similar question the answer will be waiting here
