### ISSUE TITLE
How Do I Update the Authorization header for SocketClient?

### ISSUE THREAD

**Issue by RobertoOrtis** [zino-app/graphql-flutter#727]
I have to update the Authorization header with a new access token after the app started. However, it keeps the token the app started with.

Example:

App started -> app asks user for credentials -> generated new token -> the app runs X time -> app is closed by user -> token expired -> user started the app -> app asks user for credentials -> new token is issued -> the app crashes because it's using old token instead of the new one.

I hope I am making myself clear.

**Comment by micimize** [comment]
which version are you on and what does your link declaration look like?

**Comment by RobertoOrtis** [comment]
Version ^4.0.0-alpha.4

```
Future<GraphQLClient> client() async {
    final HttpLink _httpLink = HttpLink(graphqlEndpoint);

    var jwt = await _storage.read(key: 'user_token');

    final AuthLink _authLink = AuthLink(getToken: () async => await _storage.read(key: 'user_token'));

    final SocketClientConfig _config = SocketClientConfig(
        autoReconnect: true, inactivityTimeout: null, // Duration(seconds: 2),
        initialPayload: {'Authorization': jwt}
    );

    final WebSocketLink _websocketLink = WebSocketLink(subscriptionEndpoint, config: _config);

    Link _link = _authLink.concat(_httpLink);

    _link =
        Link.split((request) => request.isSubscription, _websocketLink, _link);
    return GraphQLClient(link: _link, cache: GraphQLCache(store: HiveStore()));
  }
```

The `AuthLink` works fine. The token gets updated whenever it has to. However, the token for the socket does not.

**Comment by micimize** [comment]
So, I'd try upgrading to `4.0.0-alpha.6`, which revived/updated the old `WebSocketLink`. Then, you can make `initialPayload` an async callback like `getToken`, and when the connection fails due to auth it should auto reconnect on error, and there's a [`connectOrReconnect`](https://github.com/zino-app/graphql-flutter/blob/modularization/packages/graphql/lib/src/links/websocket_link/websocket_link.dart#L37) method you can call manually.

The issue here is that I think `gql_http_link` only sends `initialPayload` once, and doesn't have any `autoReconnect` logic. The link graph you have looks like "if request then `_websocketLink` else `_authLink.concat(_httpLink)`" so the websocket link never gets the authlink's header. it only authenticates with the `initialPayload` and then never again

**Comment by RobertoOrtis** [comment]
Could you give me an example on how I could implement it? I tried a couple of things but can't figure it out.

**Comment by micimize** [comment]
I might do it something like so (with `alpha.6`)
```dart
VoidCallback reauthenticationSideEffects;
void main() {
    Map authWebsocket() async {
        var jwt = await _storage.read(key: 'user_token');
        return {'Authorization': jwt}
    }
    final WebSocketLink _websocketLink = WebSocketLink(..., initialPayload: authWebsocket);
    reauthenticationSideEffects = _websocketLink.connectOrReconnect;
}
...
void reauthenticate(String newToken) {
  _storage.write(key: 'user_token' value: newToken);
  reauthenticationSideEffects();
}
```

**Comment by RobertoOrtis** [comment]
Great! It's now working like a charm.

How could I debug the current authorization token being used by the socket?

**Comment by micimize** [comment]
i'm not sure, because it is only sent at the initial connection time. You could log each authentication on the server, print tokens in `authWebsocket`, or maybe just call `_websocketLink.config.initialPayload` to see what's stored currently

**Comment by steebchen** [comment]
@micimize Thanks so much for the snippet above, I was searching quite long for this easy solution.

**Comment by mo-ah-dawood** [comment]
My solution is to create custom socket link

```dart

class SocketCustomLink extends Link {
  SocketCustomLink(this.url);
  final String url;
  _Connection? _connection;

  /// package : ansi_logger
  AnsiLogger logger = AnsiLogger();

  @override
  Stream<Response> request(Request request, [forward]) async* {
    /// first get the token by your own way
    /// im using package : cqrs_mediator
    String? token = await Mediator.instance.run(GetAuthTokenQuery()).resolve();

    /// check is connection is null or the token changed
    if (_connection == null || _connection!.token != token) {
      connectOrReconnect(token);
    }
    yield* _connection!.client.subscribe(request, true);
  }

  /// Connects or reconnects to the server with the specified headers.
  void connectOrReconnect(String? token) {
    _connection?.client.dispose();
    var _url = Uri.parse(url);
    if (kIsWeb) {
      /// web don't support headers in sockets
      _url = _url.replace(queryParameters: {"access_token": token});
    }
    _connection = _Connection(
      client: SocketClient(
        _url.toString(),
        // i don't know why this is visible for testing only
        // i think it might be useful to use it
        // ignore: invalid_use_of_visible_for_testing_member
        onMessage: kDebugMode ? _onMessage : null,
        config: SocketClientConfig(
          autoReconnect: true,
          headers: kIsWeb || token == null
              ? null
              : {"Authorization": " Bearer $token"},
        ),
      ),
      token: token,
    );
  }

  void _onMessage(GraphQLSocketMessage event) {
    logger.logBoxStart();
    logger.logJson(event.toJson());
    logger.logBoxEnd();
  }

  @override
  Future<void> dispose() async {
    await _connection?.client.dispose();
    _connection = null;
  }
}

class _Connection {
  SocketClient client;
  String? token;
  _Connection({
    required this.client,
    required this.token,
  });
}

```
> Note this will work every time you subscribe  using the client
> if you need to change the token after subscription just dispose it and resubscribe again

**Comment by vincenzopalazzo** [comment]
>My solution is to create custom socket link

@mo-ah-dawood I see your solution, and I like it, why not create a doc section in graphql client where to put all this code? PRs are welcome.

**Comment by mo-ah-dawood** [comment]
I added it #https://github.com/zino-hofmann/graphql-flutter/pull/1056#issue-1149958636
