### ISSUE TITLE
Is there a way to remove 'charset=utf-8' in http header?

### ISSUE THREAD

**Issue by crackerli** [zino-app/graphql-flutter#732]
As we know, 'charset=utf-8' will be added into 'Content-Type' automatically, we can not override it to remove.

But to some server, this header string will cause the rejection, we need to remove the string from the requests.

In flutter, we have a workaround as mentioned in below:
https://github.com/dart-lang/http/issues/184#issuecomment-466604977

Is it possible to do the samething in graphql-flutter?

**Comment by micimize** [comment]
In `4.0.0-beta.1` you should be able to override it with `defaultHeaders` passed to the `HttpLink` re-exported from `gql_http_link`, ([resolved here](https://github.com/gql-dart/gql/blob/04780eeba2e3e455369c69f7d85338cc1e2497f6/links/gql_http_link/lib/src/link.dart#L171-L193)). If that doesn't work, I'd PR a test+fix to `gql_http_link`, or maybe look at https://github.com/TarekkMA/gql_dio_link 

Yet another reason to switch to dio (#712)

**Comment by crackerli** [comment]
Thanks much, will upgrade to 4.0.0-beta.1, I can now override the Content-Type value.

**Comment by micimize** [comment]
@crackerli great! Comment if there's still some issue and I'll reopen
