### ISSUE TITLE
Get HTTP status code in ErrorLink

### ISSUE THREAD

**Issue by jomag** [zino-app/graphql-flutter#733]
Our GraphQL backend is built to respond with 403 on authentication error. In that case I would like the Flutter app to throw away the old API token and redirect to a sign in screen. I tried to do this with ErrorLink, and it does catch the error. But I've not found a way to extract the HTTP status code from the ErrorResponse. Is there any way to do that?

**Comment by mwawrusch** [comment]
Ran into exactly the same problem. 
Going beyond the original question, what's the best way to implement token renewal and general retry for gateway failures in graphql 3.1.0?

**Comment by mwawrusch** [comment]
To answer half of my question, https://github.com/felangel/fresh/tree/master/packages/fresh_graphql seems to work well for token renewal.

**Comment by micimize** [comment]
In `v4` you should be able to get [`HttpLinkResponseContext`](https://github.com/gql-dart/gql/blob/dfece82d5a7fbce372a6bd8fbad2b2e0c8b03863/links/gql_http_link/lib/src/link.dart#L32) from the response, which has the status code
