### ISSUE TITLE
`pollInterval:1` in lots of article usage

### ISSUE THREAD

**Issue by linbudu599** [zino-app/graphql-flutter#740]
I got a puzzle when I'm learning to combine GraphQL & Flutter, most of articles that introduce usage have a weird line of code:
```dart
options: QueryOptions(
            documentNode: gql(
              getAllToDosQuery,
            ),
            pollInterval: 1)
```
the `pollInterval` helps to make UI sync with Server, but will it make real request to GraphQL Server, or just hit cache(only use `cache: InMemoryCache()`)?
If I donot want use this to keeo UI sync with Server, how should I do?
The ideal result is to show a ProgressIndicator after each mutaion, but it seems that `result` params from Query Widget will not be changed by mutation?
see full demo [here](https://github.com/linbudu599/flutter_graphql_example)

**Comment by micimize** [comment]
It only controls re-fetches from the server. Changes to the cache from mutations (and elsewhere in v4) will always be rebroadcast to watched queries. If `pollInterval` is `0` or `null` the query won't poll.
https://github.com/zino-app/graphql-flutter/blob/eec7d2c5e8d753f7d2d62b2964cb61730caeae42/packages/graphql/lib/src/core/query_options.dart#L129-L131

The mutation doesn't change the query loading state, but if its optimistic results cause the query to rebroadcast you can use `result.loading || result.optimistic`:
https://github.com/zino-app/graphql-flutter/blob/eec7d2c5e8d753f7d2d62b2964cb61730caeae42/packages/graphql/lib/src/core/query_result.dart#L57-L59

Alternatively, your `Mutation` provider can wrap your `Query` and you can do `queryResult.loading || mutationResult.loading`
