### ISSUE TITLE
Query B requests fields that Query A already accuired, but still goes to network.

### ISSUE THREAD

**Issue by omerman** [zino-app/graphql-flutter#742]
First of all, thank you for this wonderful library and api.

**Describe the bug**

I'll describe with an example:

- Lets say I have 2 entities. Workout, and Exercise.
Workout has an array of exercises.

- Also I have 2 components, `WorkoutComp`, `ExerciseComp`.
The workout comp renders a list of `ExerciseComp`.

- I have a query for the workout comp that fetches the workout info by id, and I have another query for exercise,
it fetches exercise info by id.

Since the the workout contains exercises, I'm trying to give a better ui experience, so naturally in the Workout query, I fetch all of the exercise fields as well so that that each exercise component will not have to go to the network to bring extra fields.
```graphql
query Workout($workoutId: Int!) {
  workout(id: $workoutId) {
    id
    __typename
    exercises {
    id
    __typename
    name
    asset
     }
  }
}

query Exercise($exerciseId: Int!) {
  exercise(id: $exerciseId) {
    id
    __typename
    name
    asset
  }
}
```
**Expected behavior**
I expected that if I'm querying for the exercises info in a higher level in a previous query,
then once I need to render a specific exercise with an id that is cached and fields that are cached, the query will not need the network, but it does

**Comment by micimize** [comment]
@omerman you can get the behavior you're looking for on the beta, or just pass the child data to the child component and only query if you don't have that property.

In `v4` your nested result should be optimistically read from the cache, and you can disable the subsequent network request with a `FetchPolicy.cacheOnly` (see [the `Policies` section in the readme](https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#policies)).

There is a rub though – the client doesn't magically know what the field `exercise(id: $exerciseId)` returns, so I believe you want a custom `TypePolicy` that [reads](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-read-function) with args ([example from normalize](https://github.com/gql-dart/ferry/blob/e4f5d92ec8d935009bbb8dd7f0c8cbdb87a96923/normalize/test/field_policy/read_test.dart#L56-L59))

so after #743 gets (hopefully) released by CI, I _think_ it should be something like:
```dart
typePolicies: {
  'Query': TypePolicy(
    queryType: true,
    exercise: {
      'posts': FieldPolicy(
        read: (existing, options) => options
            .readField(
              options.field, existing ?? {'\$ref': 'Exercise:${options.id}'},
            ),
      ),
    },
  ),
},
```

@smkhalsa does that look right?

**Comment by smkhalsa** [comment]
@micimize yes, that should work. Two things though:

1. When creating the reference, you'll need to access `options.variables.id`, not `options.id`.
2. I'm not sure how FetchPolicies are implemented in `graphql_flutter`, but in `ferry`, I'd still go with FetchPolicy.CacheFirst in this case since the read function would cause the cache to return a value and the network call wouldn't be made. With FetchPolicy.CacheOnly, you'd only ever receive data for an exercise if it was returned in another query.

**Comment by omerman** [comment]
Thank you very much guys!  @micimize @smkhalsa 

The TypePolicy looks just like what I need, so i'm eager to try it!
