### ISSUE TITLE
Support for custom scalars

### ISSUE THREAD

**Issue by jomag** [zino-app/graphql-flutter#745]
It would be nice if graphql-flutter supported custom scalars. Like many others, I have a need for a date+time in my GraphQL types, and it would be great if I could add a custom scalar so that conversion between ISO8601 strings and DateTime objects was handled automatically.

**Comment by micimize** [comment]
This is a subset of the type generation problem: #26 

For now, we leave that to other libraries:
* https://pub.dev/packages/artemis
* https://pub.dev/packages/gql_build
* https://github.com/micimize/major (my lib – janky slow and maximalist)

Ferry also has built-in codegen: https://pub.dev/packages/ferry
