### ISSUE TITLE
Add android INTERNET permissions to examples so they work in release mode

### ISSUE THREAD

**Issue by crackerli** [zino-app/graphql-flutter#748]
**Describe the bug**
graphql flutter can work well in debug mode, request the data successfully, but failed in release mode.
In release mode, the returned result shows that has exception, but the detailed expception is '[]'
      if (queryResults.hasException)  {
        print('exeption: ${queryResults.exception.graphqlErrors}');
        yield ReposNotLoaded(queryResults.exception.graphqlErrors); // the graphqlErrors is '[]'
        return;
      }
Additionally, with Charles to catch the request, we can see the graphql flutter does not emit the request, it get the error locally.

**To Reproduce**
1. open the example project of graphql_flutter "flutter_bloc", build it successfully
2. open the app with debug mode, then we can see the data we want.
3. open the app with command "flutter run --release", then we can't get the requested data.

**Expected behavior**
We can get the data as in debug mode

**Smartphone :**
 - Device: [vivo NEX A, Coolpad]
 - OS: [ Android ]

**Tried on different graphql flutter versions**
3.0.0, 3.1.0, 4.0.0-beta.1
On all versions the results are the same.

**Tried on different flutter platforms**
I tried on two different flutter verions:

Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (4 months ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (3 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2

On the two different flutter versions the results are the same.

**Comment by micimize** [comment]
@crackerli  what is `exception.linkException`? Or `exception.clientException` on v3. Hard for me to imagine the issue is with the library – I'm guessing there's some `--release` based configuration that makes it not connect to the host

**Comment by crackerli** [comment]
@micimize Thanks for your attention, the exception.clientException in v3 is:  Failed to connect to https://api.github.com/graphql: Failed host lookup: 'api.github.com'

**Comment by micimize** [comment]
@crackerli https://github.com/flutter/flutter/issues/27883#issuecomment-471357931

try `<uses-permission android:name="android.permission.INTERNET" />` if you're on android. I'm guessing it's something like this – just a general network configuration issue

**Comment by crackerli** [comment]
Thank you much, it's worked
