### ISSUE TITLE
parse result data fails when 2 fields or more contain the same value

### ISSUE THREAD

**Issue by jimschmit** [zino-app/graphql-flutter#749]
Hello, here my setup:
version: 3.1
cache: OptimisticCache
defaultFetchPolicy: cacheAndNetwork

When I try to do a query to a resource (Activity) with a given id (it's an GUID) and 2 fields or more (in my case "title" and "description") contain the same value, in this case "test" as a string, when trying to access activity['description'] it returns me a List<Object> instead of a string.

I have a Activity class which has a fromJson constructor and it fails to assign the description with this error:
`Dart Unhandled Exception: type 'List<Object>' is not a subtype of type 'String'`

It seems like all properties are somehow a list of objects, but they get resolved correctly to their types.

The problem is gone away when I have unique values in the fields (database)...
![image](https://user-images.githubusercontent.com/23400669/96465730-93f1f980-1229-11eb-8b1f-a0153c2b329c.png)

**Comment by micimize** [comment]
I'm not sure what's happening here but 1. I doubt this is because of `graphql_flutter` and 2. If it is it was probably fixed by `4.0.0-beta`'s cache normalization improvements

**Comment by jimschmit** [comment]
Thank you for your feedback, I tried 4.0.0-beta3 and it now works like a charm!
