### ISSUE TITLE
How Do I Catch Server Disconnection from a subscription?

### ISSUE THREAD

**Issue by RobertoOrtis** [zino-app/graphql-flutter#750]
Hello,

Is there a way to catch the error when the connection to the server is lost when using a subscription?

**Comment by micimize** [comment]
@RobertoOrtis not sure – you might be able to use `onConnectOrReconnect` to listen for it:
https://github.com/zino-app/graphql-flutter/blob/53737b5c94e365f4648ac7ccf2f47f2187419b95/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L34

We should probably expose a way to respond to `ConnectionError`s for this:
https://github.com/zino-app/graphql-flutter/blob/53737b5c94e365f4648ac7ccf2f47f2187419b95/packages/graphql/lib/src/links/websocket_link/websocket_client.dart#L282-L283

**Comment by RobertoOrtis** [comment]
I did something like the following but nothing comes out when the connection is lost:

```
final SocketClientConfig _config = SocketClientConfig(
      autoReconnect: true,
      inactivityTimeout: null, // Duration(seconds: 2),
      onConnectOrReconnect: (socket) async {
        socket.stream.listen((event) {
         ........
        });
      },
      initialPayload: authWebsocket
    );
```

**Comment by micimize** [comment]
`listen` listens to events. you probably want `onDone`. Merging this into #655
