### ISSUE TITLE
How do I use fetchMore method in stand alone ?

### ISSUE THREAD

**Issue by freewebwithme** [zino-app/graphql-flutter#759]
I was looking for information and sample code for implementing fetchMore in stand alone version(not in builder function)
I want to do something like this.

1. Get first query for screen loading, showing limited amount of products.
```
Future<List<Product>> getProductsBySubCategoryName(
      {String categoryName, int limit}) async {
    final session = getIt<Session>();
    final result = await _client.query(
      QueryOptions(
        document: gql(productsBySubCatName),
        variables: {
          "categoryName": categoryName,
          "storeId": int.parse(session.user.profile.storeId),
          "limit": limit,
        },
      ),
    );

    if (result.hasException) {
      print("Error from getProductsBySubCategory: ${result.exception}");
      throw Backend.ServerException();
    }

    return result.data["getProductsBySubcategoryName"]
        .map((product) => Product.fromJson(product))
        .cast<Product>()
        .toList();
  }

```
2. Then when I scroll down to the bottom of screen, `fetchMore` to show more products. So I need to make a separate function like this..maybe?
```
  Future<List<Product>> fetchMoreProducts({int offset}) {
    FetchMoreOptions opts = FetchMoreOptions(
      // use same query document.
      document: gql(productsBySubCatName),
      variables: {"offset": offset},
      updateQuery: (previousResultData, fetchMoreResultData) {
        List<Product> newData =
            fetchMoreResultData["getProductsBySubcategoryName"]
                .map((product) => Product.fromJson(product))
                .cast<Product>()
                .toList();
        // merge previous result with new result and return
        List<Product> mergedResults = [...previousResultData, ...newData];

        return mergedResults;
      },
    );
      
       // Then call fetchMore method 
       // but how can I supply original options and previous result data to this function??
    _client.fetchMore(opts);
  }

```
Then call fetchMore method  but how can I supply original options and previous result data to this function??
    _client.fetchMore(opts, originalOptions: ??, previousResult: ??);

Is this correct way of using fetchMore method? or If I am missing some docs or sample code, please let me know.

**Comment by micimize** [comment]
@freewebwithme right – here's [an example](https://github.com/zino-app/graphql-flutter/blob/beta/changelog-v3-v4.md#clientfetchmore-experimental) in the migration guide where I wrap the result and options into a container class, because every call to `fetchMore` requires `originalOptions` (your `QueryOptions`) and `previousResult` (your `result`), which you also want to replace with the results of the `fetchMore`.

**Comment by freewebwithme** [comment]
@micimize Thanks your example helps a lot.
Then I am having trouble with merging previous result data and fetch more result data.
```
    return FetchMoreOptions(
      document: initialOptions.document,
      variables: {"offset": products.length},
      updateQuery: (previousResultData, fetchMoreResultData) {
        var mergedResult = [
          ...previousResultData as List<dynamic>,
          ...fetchMoreResultData as List<dynamic>
        ];
        return mergedResult;
      },
    );
```
And if I call `fetchMore`, I got an error.
`_CastError (type: _InternalLinkedHashMap<String, dynamic> is not a subtype of type 'List<dynamic>' in type cast `
I think that is merge results OperationException.

So I have checked each previousResultData and fetchMoreResultData in `updateQuery` function.
And they are both List<Product>.

So What am I missing? Is it occurred from updating a Cache? Can you give me some hints?

**Comment by freewebwithme** [comment]
I think I found a solution.
I think I need to return merged result as same format that was used previous(fetch)

```
return FetchMoreOptions(
      document: initialOptions.document,
      variables: {"offset": products.length},
      updateQuery: (previousResultData, fetchMoreResultData) {
        var mergedResult = [
          ...previousResultData["getProductsBySubcategoryName"],
          //   as List<dynamic>,
          ...fetchMoreResultData["getProductsBySubcategoryName"],
          //  as List<dynamic>
        ];
        Map<String, dynamic> newMap = {
          "getProductsBySubcategoryName": mergedResult
        };
        return newMap;
      },
    );
```
