### ISSUE TITLE
Architecture/walkthrough video

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#762]
After the `v4` stable release I intend to make a video walkthrough of the library so that that new contributors can onboard more easily.

Important issues to address: #787, #201, https://github.com/zino-app/graphql-flutter/issues/774#issuecomment-735436053, #640, #712, #643, #634, #753, #650, #212 

Will also create an [ARCHITECTURE.md](https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html) on stream

**Comment by micimize** [comment]
If a serious prospective maintainer wants this, comment and I can try and get it done sooner rather than later. We could possibly sync up for it.

**Comment by jinxac** [comment]
Hi, I have contributed to this library with ideas sometime last year. I am willing to contribute to this once I have an understanding of the codebase.

**Comment by MrCreeper1008** [comment]
I can help as well.

**Comment by hyochan** [comment]
I am also interested. We are planning to migrate our app to graphql with flutter. Previously it was graphql and react-native.

**Comment by micimize** [comment]
went ahead and created a modest [ARCHITECTURE.md](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql/ARCHITECTURE.md) today

**Comment by micimize** [comment]
I don't have the time/inclination to do this anymore, so I'm closing it. If someone ends up doing serious development work and has a question for me, feel free to @ me on the discord

**Comment by degibenz** [comment]
I am also interested.

**Comment by PritishSawant** [comment]
If anyone is looking for alternative may be this could help https://github.com/flutter/codelabs/tree/master/github-graphql-client. I have not tried this myself so proceed at your own risk
