### ISSUE TITLE
📣   maintainer update  📣

### ISSUE THREAD

**Issue by micimize** [zino-app/graphql-flutter#763]
I'm starting a full time position next week, and am focusing on some other projects* as well. As such, **while I intend to see v4 through to a [stable release][v4],** I won't be spending nearly as much time as a [proactive maintainer], and will be in the [discord] less often.

This means that development will likely slow dramatically. If we have someone else step up as core maintainer I'll close this, which hopefully #762 may help with.

Anyhow, I think with v4, `graphql / graphql_flutter` have much more stable foundations in their utilization of libraries from [gql dart]. I'm mostly creating/pinning this for the sake of transparency of the project's status.

<br/>  

\* my [twitter] & [youtube] for anyone interested
 
[v4]: https://github.com/zino-app/graphql-flutter/labels/v4
[discord]: https://discord.gg/tXTtBfC
[proactive maintainer]: https://github.com/zino-app/graphql-flutter/issues/420#issuecomment-626060686
[gql dart]: https://github.com/gql-dart/gql
[twitter]: https://twitter.com/micimize
[youtube]: https://www.youtube.com/channel/UCj39MVr1fuFtE1eDNXDGJuQ/

**Comment by MrCreeper1008** [comment]
I would very much like to help with maintaining this, however I am not very familiar with the internals of GraphQL. Are there any resources available to get me up to speed? Thank you for this great library btw!

**Comment by micimize** [comment]
@MrCreeper1008 right now other than the readmes, api docs, and code, there isn't much. #762 should help, so subscribe to that for updates

**Comment by MrCreeper1008** [comment]
a video walkthrough would be very helpful!

**Comment by joekendal** [comment]
I would GitHub Sponsor it if there's that option?

**Comment by micimize** [comment]
@joekendal I do have a [github sponsors](https://github.com/sponsors/micimize), but now that I have a full time job it probably makes more sense to donate to the [open collective](https://opencollective.com/graphql-flutter)

**Comment by micimize** [comment]
closing in favor of #894
