### ISSUE TITLE
Upgrade connectivity package

### ISSUE THREAD

**Issue by danilofuchs** [zino-app/graphql-flutter#764]
**Is your feature request related to a problem? Please describe.**
When using `graphql_flutter`, `connectivity` 0.4.4 is added. This version requires the `NSLocationWhenInUseUsageDescription` permission on iOS.
This can cause user friction. Version 2.0.0 removes some APIs and removes the requirement for the API.

**Describe the solution you'd like**
Upgrade `connectivity` to ^2.0.0. In stable and beta branches

**Describe alternatives you've considered**
Use another library? 

**Additional context**
https://pub.dev/packages/connectivity/changelog#200

**Comment by micimize** [comment]
#754 bumps `beta` to `connectivity: ^2.0.0`
