### ISSUE TITLE
Extend to use get package (https://pub.dev/packages/get)

### ISSUE THREAD

**Issue by gusdoe** [zino-app/graphql-flutter#765]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The popularity of getX package is growing rapidly and the simplicity of its usage quite appealing. Therefore I would like to use this state management tool. 

**Describe alternatives you've considered**
hasura_connect

**Additional context**
n/a

**Comment by Abhishek01039** [comment]
Hii @gusdoe 
you can use any state management technique which you want.
but are you talking about an example here?
like this repo should have an example with `get(X)` and graphql_flutter
Thanks.

**Comment by micimize** [comment]
We currently leave most of these 3rd party bindings in "userland," for instance there is a [graphql_flutter_bloc](https://github.com/artflutter/graphql_flutter_bloc) package. If you think there are some idioms that a package could make easier compared to just using `graphql/client.dart` directly, a 3rd party package is the way to go.

Really, the main thing is that we should decouple the widgets from our provider (#640)
