### ISSUE TITLE
feature request: pass BuildContext to authlink getToken

### ISSUE THREAD

**Issue by zhammer** [zino-app/graphql-flutter#770]
hey! i'm a brand new flutter developer and have very much appreciated this library as an easy transition from using apollo in react.

question: what do folks think of updating the signature of `AuthLink.getContext` to take in a `BuildContext` in graphql_flutter 4.x? here's my use case (and feel free to correct me if anything seems off here as, again, i'm just starting with flutter):
- I have an access token provider above my graphqlprovider (ie `AccessTokenProvider(GraphQLProvider(my_app))`)
- I would like to setup authlink so that `getToken` gets the access token from the `AccessTokenProvider` (eg `getToken(BuildContext context) => Provider.of<AccessToken>(context)`

i realize i could store the accesstoken in local cache state, but i may persist the GraphQLCache at some point and would prefer to persist the accesstoken using `flutter_secure_storage`, not in a potentially insecure store. **(amendment: actually in the current state this wouldn't work since getToken doesn't get passed the cache)**

happy to put up a PR for this if folks are on board! not sure how much concern there is re: breaking apis during 4.x beta. though changing `getToken() => ...` to `getToken(_) => ...` should be an easy change for devs.

https://github.com/zino-app/graphql-flutter/blob/2efce9f15e59208d86a2c4b1c9e0794cc28ea680/packages/graphql/lib/src/links/auth_link.dart#L39

**Comment by zhammer** [comment]
ah wait, i didn't realize everything in the `graphql` package is totally flutter-unaware. not sure how this could be easily done.

**Comment by micimize** [comment]
@zhammer you could define your client+links within a stateful widget (or even within a `build`), and get whatever info you need from `context` within the `getToken` definition (leveraging the presence of `context` within the closure)

**Comment by zhammer** [comment]
Ah smart! I'll try this out.
