### ISSUE TITLE
initPayload from SocketClientConfig is not accepting Json-like data

### ISSUE THREAD

**Issue by warcayac** [zino-app/graphql-flutter#780]
**Describe the bug**
I'm getting the following error message 
```
The argument type 'Map<String, Map<String,String>>' can't be assigned to the parameter type 'Future<dynamic> Function()'.
```
for `initPayload` parameter at this code:
```
static final WebSocketLink webSocketLink = WebSocketLink(
    url: 'wss://hasura.io/learn/graphql',
    config: SocketClientConfig(
      autoReconnect: true,
      inactivityTimeout: Duration(seconds: 30),
      initPayload: {'headers': {'Authorization': _token}},
    ),
  );
```

**To Reproduce**
- Following the [GraphQL Flutter Tutorial](https://hasura.io/learn/graphql/flutter-graphql/graphql-client/).
- According to [initPayload property](https://pub.dev/documentation/graphql/latest/graphql/SocketClientConfig/initPayload.html) help: `Can be null, but must be a valid json structure if provided.`
- According to [GetInitPayload typedef](https://pub.dev/documentation/graphql/latest/graphql/GetInitPayload.html) help: `typedef GetInitPayload = FutureOr<dynamic> Function();`

**Expected behavior**
No error message.

**Comment by micimize** [comment]
`initialPayload` in the v4 beta has this

**Comment by eoanodea** [comment]
Is there any update on this? I've run into the exact same issue and can't get around it

**Comment by eoanodea** [comment]
Found a workaround for this for any other poor soul that has to deal with it, update this:

```
initPayload: {
  "headers": {"Authorization": _token}
}
```
To this:
```
initPayload: () => {
  "headers": {"Authorization": _token}
}
```

**Comment by warcayac** [comment]
Yeah! I did this and it's working.
