### ISSUE TITLE
__typename was not executed because no suitable resolver could be found

### ISSUE THREAD

**Issue by noobloser** [zino-app/graphql-flutter#784]
Whenever I try to post a mutation via the library I get the error message
"**_typename was not executed because no suitable resolver could be found - this indicates a resolver or validation bug. Please let us know by filing an issue.**"

I minimized my code for a suitable test example:

<details>
  <summary>code example</summary>

```
class APIClient {
  String token = 'XXXXXX';

  GraphQLClient graphQLClient() {
    final HttpLink _httpLink = HttpLink('http://192.168.178.35:8080/graphql');
    final AuthLink _authLink = AuthLink(getToken: () async => 'Bearer $token');
    final Link _link = _authLink.concat(_httpLink);

    final Policies _policies = Policies(
      fetch: FetchPolicy.networkOnly,
    );

    return GraphQLClient(
      link: _link,
      cache: GraphQLCache(),
      defaultPolicies: DefaultPolicies(
        watchQuery: _policies,
        query: _policies,
        mutate: _policies,
      ),
    );
  }
}

const String mtAddTest = r'''
mutation addDance($input: [AddTestInput!]!) {
  addTest(input: $input) {
    test {
      name
    }
  }
}
''';

void test() async {
    final MutationOptions options = MutationOptions(
      document: gql(mtAddTest),
      variables: <String, dynamic>{
        "input": [
          {"name": "temp"}
        ]
      },
    );

    QueryResult result = await APIClient().graphQLClient().mutate(options);
    if (result.hasException) {
      print(result.exception.toString());
    }
  }
```
</details>

At first I thought the db at fault, as subscriptions were still working (not in the code example, for simplicity reasons), but then I completely started from scratch.
Here my db schema for dgraph if that matters.

```
type Test {
    name: String!
}
```

In the meantime I can execute the mutation via insomnia quite fine.
I work with the library graphql: ^4.0.0-beta.5   but also tried ^4.0.0-beta.2 for testing sake. It was all the same.
The server is run locally and accessed over the local ip address.
Also Flutter is run on the same computer using an emulator.

<details>
  <summary>flutter doctor -v</summary>

```

[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /opt/flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/owner/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /home/owner/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

```
</details>

If someone has the same issues, or has some input for me that would be great,
as I am reaching for straws.

**Comment by noobloser** [comment]
Just tried the query option.
It works when the __typename is also used in the query (like #785), otherwise the same error occurs.

**Comment by micimize** [comment]
`gql` adds  `__typename` to every selection set recursively, so I don't know how manually adding `__typename` would change things. The error is being thrown on the server side – resolvers are a server side graphql concept and the client has no real awareness of them. 

manual addition of `__typename` changing the results is very strange if you're using the `gql` helper bundled with the client.

**Comment by noobloser** [comment]
Thank you for your input, it proved to be quite helpful.
The issue with the __typename in the query resolved itself somehow, so that the __typename specification is no longer needed. ¯\_(ツ)_/¯

For the mutation the error messages comes from one __typename that is inserted by gql:
 ```
mutation addTest($input: [AddTestInput!]!) {
  __typename                 <- just this
  addTest(input: $input) {
    __typename
    test {
      __typename
      name
    }
  }
}
 ```

@micimize, you are right, as the error message is coming from the server.
My question then changes into: is the upmost __typename the intended graphql syntax, and what return value is expected for that. I am assuming 'Mutation' as that would be the type.

 ```
{
  "data": {
                   <- I assume then you'd expect to have "__typename": "Mutation" here?
    "addTest": {
      "__typename": "AddTestPayload",
      "test": [
        {
          "__typename": "Test",
          "name": "john"
        }
      ]
    }
  },
 ```

**Comment by noobloser** [comment]
As this seems to be an error on the dgraph service and I don't want to waste your time, I'll close this issue.
For everyone else having the same problem, please refer to the [dgraph issue](https://discuss.dgraph.io/t/bug-upmost-typename-in-mutation-finds-no-resolver/11989)

**Comment by noobloser** [comment]
As the dgraph service does not allow the upmost __typename, I'd like to know if there is a way to disable that in gql and if not if there is documentation to change gql myself accordingly.
thanks for your help, even though it is quite a special case

**Comment by micimize** [comment]
@noobloser that's interesting – it should be fairly easy to do. `gql` is really just:
```dart
DocumentNode gql(String document) => transform(
      parseString(document),
      [AddTypenameVisitor()],
    );
 ```
where `AddTypenameVisitor` is from `normalize`. I think the following will do what you want:
```dart
import 'package:normalize/utils.dart';

class AddNestedTypenameVisitor extends AddTypenameVisitor {
  @override
  visitOperationDefinitionNode(node) => node;
}

DocumentNode gql(String document) => transform(
      parseString(document),
      [AddNestedTypenameVisitor()],
    );
```

**Comment by micimize** [comment]
@noobloser I'm going to close this as something like the above should work, but comment if it doesn't and I'll try and help troubleshoot.

Dgraph is actually spec-noncompliant here, so I'd recommend opening an issue there:
* [Type Name Introspection] should be supported against any `Object` type
* All [Root Operation Types] are also `Object` types.

[Type Name Introspection]: https://spec.graphql.org/June2018/#sec-Type-Name-Introspection
[Root Operation Types]: https://spec.graphql.org/June2018/#sec-Root-Operation-Types
