### ISSUE TITLE
CacheMissException if __typename not in query

### ISSUE THREAD

**Issue by ninodinatale** [zino-app/graphql-flutter#785]
**Describe the issue**
Throws `CacheMissException` if `__typename` is not provided in the query:

> Round trip cache re-read failed: cache.readQuery(request) returned null

**To Reproduce**

```graphql
query changes($id: ID!) {
    task(id: $id) {
        changes {
            id
            name
        }
    }
}
```

working query:
```graphql
query changes($id: ID!) {
    task(id: $id) {
        __typename
        changes {
            __typename
            id
            name
        }
    }
}
```

**Expected behavior**
Either no need to add `__typename` to the query or a more concise error message.

**device / execution context**
localhost, iOS and android simulator

**Comment by micimize** [comment]
@ninodinatale will need a few more details here – 
* are you using the `gql` helper?
* do you know if the `result.data` from the server was `null`? Can you set a breakpoint in `_resolveQueryOnNetwork` to find out?

**Comment by ninodinatale** [comment]
@micimize sure:
* I am using [Artemis](https://github.com/comigor/artemis) for generating typed queries which uses `gql` internally, so yes, I guess?
* The `result.data` was not `null`.

**Comment by micimize** [comment]
I was referring to the `gql` helper provided by  our libraries – Artemis doesn't add `__typename` automatically. Of course this is still an issue – the cache round-trip should work regardless as long as both write and read use the same AST. Will try and take a look soon

**Comment by micimize** [comment]
@ninodinatale I still need a sample of the `data` causing the failure to be able to tell what's going wrong. What code path and preconditions are present would also help – i.e. `client.query`, using the `Query` widget, and what `FetchPolicy` you're using

**Comment by micimize** [comment]
@ninodinatale after #795, this is one of the only issues I consider blocking the release of a stable `v4`, but I really need more info to figure out what the problem is.

**Comment by micimize** [comment]
closing due to lack of response
