### ISSUE TITLE
Ensure fragment uniqueness / merge duplicate fragments

### ISSUE THREAD

**Issue by reilem** [zino-app/graphql-flutter#786]
**Is your feature request related to a problem? Please describe.**

When you have two fragments "A" and "B" in a query that re-use the same fragment "C" you now get errors saying:
```
There can be only one fragment named "C"
```

**Describe the solution you'd like**

Automatically detect and scrap duplicate fragments, just like the apollo client does.

See: https://github.com/apollographql/apollo-client/pull/913

**Describe alternatives you've considered**

Right now I have to move all fragment appending to the top level query, which sometimes gets confusing if you forget to add a fragment which is nested deeply within other fragments.

**Additional context**

Could be that I'm just doing things incorrectly. I am adding fragments by doing:
```gql(''' your_query_here ''')..definitions.addAll(fragment.definitions)```

Maybe there is a better way? I tried adding them in the query string with `'${}'` but this just gave lots more other errors.

**Comment by reilem** [comment]
As a workaround I created this extension:
```dart
extension AppDocumentNode on DocumentNode {
  List<DefinitionNode> get uniqueDefinitions => definitions
      .fold<Map<String, DefinitionNode>>({}, (acc, def) {
        acc[def.name.value] = def;
        return acc;
      })
      .values
      .toList();
}
```

I can now use fragments just like in apollo by doing the following:
```dart
gql(''' your_query_here ''')..definitions.addAll(fragment.uniqueDefinitions)
```
and I no longer get the above warning.

Still not sure if I am maybe messing something up or if this is intended behaviour but I couldn't find anything in the Docs explaining how to do this.

**Comment by micimize** [comment]
@reilem if we had a standalone module leveraging gql's [AST transformation](https://github.com/gql-dart/gql/tree/f2fe378df2340257530e576c7dd6dacee5650596/gql#visiting-graphql-ast-nodes) to provide a Transformer, we would definitely incorporate it, and it could be used elsewhere.

**Comment by reilem** [comment]
Thanks for the response! I see now that DocumentNode actually comes from the dart gql package. So is this actually more of a gql-dart issue? Because then I might trying raising an issue on their end and perhaps make a fix there. Only been using this for a couple days now so I could be wrong though.

**Comment by micimize** [comment]
Yes, we use gql tooling fairly extensively, especially in v4 with [links](https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#links) and [normalize](https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#direct-cache-access-api).

You could open it there as a feature request – it would probably belong in a standalone package within the monorepo. `gql` doesn't typically provide any specific transformers/visitors itself.

You could also PR just the deduplication feature + tests to `beta` here – that part should be much simpler than merging, which I remember being kind of difficult.

**Comment by reilem** [comment]
If I find the moment I will try make a PR here then. Would you guys be more likely to accept an AST Transformation implementation, or would the extension shown above be good enough?

**Comment by micimize** [comment]
@reilem it should be an AST transformation so we can simply include it in the `gql` helper

**Comment by reilem** [comment]
Issue is no longer relevant since
```
gql('...')..definitions.addAll(...)
```
Now results in: `Unsupported operation: Cannot add to a fixed-length list`

Does this library still support fragments in any way?

**Comment by micimize** [comment]
see https://github.com/zino-app/graphql-flutter/issues/113#issuecomment-809588718 – there is no special support for fragments

**Comment by reilem** [comment]
Yeah I see. I fixed my issue for now with a little less boiler plate code: https://github.com/zino-app/graphql-flutter/issues/113#issuecomment-817739768
