### ISSUE TITLE
how to debug requests

### ISSUE THREAD

**Issue by mobileink** [zino-app/graphql-flutter#789]
**Describe the bug**

I'm trying to make a simple query using graphql (not graphql-flutter). The query result is:

```
ClientException: Failed to connect to http://localhost:3085/graphql: Invalid response body: Must provide query string
```

 I need to see what the client is sending, but I don't see how to get that information. I managed to figure out how to use the gql pkg to print QueryOptions.documentNode (it looks fine), and I can print the QueryOptions cache, etc. But the documentation provides no clue as to how I can find out what the client sends over the wire.

This is graphql 3.0.0 on Linux.

**Comment by micimize** [comment]
@mobileink You can set a breakpoint and descend into the execution of the library, use something like [`flutter_stetho`](https://pub.dev/packages/flutter_stetho), [etc](https://stackoverflow.com/questions/57735144/how-to-inspect-network-calls-in-flutter-application), or just log requests on the server. Could be a server side issue like [this express one](https://stackoverflow.com/questions/36691554/graphql-post-body-must-provide-query-string)

**Comment by micimize** [comment]
The flutter network inspector should now have request/response bodies as well https://github.com/flutter/devtools/issues/2398
