### ISSUE TITLE
Background Push Notification

### ISSUE THREAD

**Issue by zaimanza** [zino-app/graphql-flutter#790]
I want to subscribe to a resolver to view push notification even when the app is closed so that changed data will be pushed.

For example:
   A customer add an order and close the app. The customer will receive a push notification once the restaurant update the order status to ready.

I have looked into flutter_local_notifications but have no clue on how to link to flutter graphQL subscription.

**Comment by theGlenn** [comment]
iOS and Android apps are running in a sandboxed environment with quite a few restrictions restrictions applied to them by the os; keeping a connection alive or any ind of battery draining network activity is part of them

- https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background

If you wan to send push notifications from your server, you'll have to send them appart and set them up like all apps do.
- https://firebase.google.com/docs/cloud-messaging/android/client
- https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server

**Comment by micimize** [comment]
In the v4 you can make sure you have access to the client from whatever context you manage to consume push events from, and write cache changes with the [direct cache access api](https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql#direct-cache-access-api).

A really elegant solution would be to implement a subscription link for firebase cloud messaging, automatically writing results to the cache as they occur. But yeah theGlenn is right – [you can't keep a websocket open while backgrounded](https://stackoverflow.com/a/43854461/2234013), so you'll have to find an alternative solution to push notifications compared to our default subscription stack.
