### ISSUE TITLE
cannot mix top level fields from two different graphql servers

### ISSUE THREAD

**Issue by TesfahunK** [zino-app/graphql-flutter#794]
So i was using hasura graphql engine for my backend and lately they have introduced a feature called schema stitching that combines remote graphql schemas, and i ran into a problem when i tried to mutate from the secondary stitched schema. all the queries and mutations from the primary schema work perfectly is it me or has anyone ran into this?

**Comment by micimize** [comment]
This sounds like an issue with the server configuration – from the client's perspective it should all act like a single service

**Comment by micimize** [comment]
closing as I'm fairly sure this is a server side issue. If you still think it's client side, come by `#support` in the [discord](https://discord.gg/tXTtBfC), but you're probably better off finding support on hasura itself
