### ISSUE TITLE
[QUESTION] Integration with AWS AppSync

### ISSUE THREAD

**Issue by darrinps** [zino-app/graphql-flutter#796]
Curious if this has been used to integrate with AWS AppSync. They have their own version that works with GraphQL and Flutter I believe, but I don't see any reason to require another package on top of this one just to talk GraphQL with AppSync.

Anyone?

**Comment by micimize** [comment]
Someone added [a section to the docs](https://github.com/zino-app/graphql-flutter/blob/a3e4401c09aa36f11a2f341f759a18702b32516d/packages/graphql_flutter/README.md#aws-appsync-support) on this, and there is a longer discussion linked there. I don't know of a custom graphql-enabled AppSync client

**Comment by micimize** [comment]
merging into #209
