### ISSUE TITLE
[Question]  How do you architecture your project layers?

### ISSUE THREAD

**Issue by ManuLpz4** [zino-app/graphql-flutter#800]
Hello! I hope you are doing well.

In my team we decide to migrate our networking side to GraphQL, but all the examples that I find have the UI very coupled with the networking part, which I don't like.

How it was: UI < Provider (riverpod soon I think) < FooService < HttpService (like an interceptor)

Any suggestion? Please and thank you so much :)

**Comment by micimize** [comment]
You could take a look at https://github.com/zino-app/graphql-flutter/tree/master/examples/flutter_bloc. You can really use `graphql/client.dart` however you would another non-flutter-integrated library, but you might want to look at how the `Mutation` widget does some of its callback handling.

I'm fairly interested in other architecture designs in theory, but personally found trying to work with `riverpod + flutter_hooks` (for instance) quite unintuitive and not worth the effort. If you all discover any idioms you think might be worth sharing, please do so here or in the discord! A less opinionated / more decoupled flutter api is a common request.
