### ISSUE TITLE
Please Update connectivity package to the lastest 2.0.2

### ISSUE THREAD

**Issue by kaushik-xs** [zino-app/graphql-flutter#803]
One of our apps need connectivity 2.0.2 and the latest version of graphql-flutter uses 2.0.0 of connectivity.  Because of this, we have a dependency conflict issue. 

Can this be upgraded to the latest version of connectivity ?

**Comment by micimize** [comment]
Shouldn't this not be an issue? Our version is `^2.0.0` which should be [equivalent to `>=2.0.0 <3.0.0`](https://dart.dev/tools/pub/dependencies#caret-syntax)
