### ISSUE TITLE
Cannot find any example how to use errorLink

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-app/graphql-flutter#804]
There is no example how to use Error link. The only lines of mention is: reportClientException
But there are different kind of exception like onGraphQLError, onException with complex inut and output types / streams. Befre update it was simple: 

```
final ErrorLink errorLink =
      ErrorLink(onGraphQLError: (ErrorResponse response) async {
    var isAutheError = response.exception.graphqlErrors;
....
}
```

**Comment by micimize** [comment]
`ErrorLink` is reexported from `gql_error_link` – here's [an example](https://github.com/gql-dart/gql/blob/f2fe378df2340257530e576c7dd6dacee5650596/links/gql_error_link/example/gql_error_link_example.dart#L45-L69).
