### ISSUE TITLE
Cannot find any guidlines for initPayload migration

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-app/graphql-flutter#805]
Hi, i have updated graph-flutter version to latest. I was using subscriptions and i was sending initialPayload:

```
initPayload: () {
              return authTokenService.addAuthHeader(EnvVariables.currentHost);
            })
```

in order to authorize websocket connection
I cannot find any mentions about it in migration guide.
Can anybody provide a new way of sending auth token on connect

Thanks

**Comment by mateusfsilva** [comment]
Hi,

The property was renamed from `initPayload` to `initialPayload`.

```dart
final config = SocketClientConfig(
  autoReconnect: true,
  queryAndMutationTimeout: Duration(seconds: 60),
  inactivityTimeout: Duration(minutes: 2),
  delayBetweenReconnectionAttempts: Duration(seconds: 5),
  onConnectOrReconnect: _onConnectOrReconnect,
  initialPayload: {
    'authToken': token,
  },
);

final _wsLink = WebSocketLink(_hostAddress, config: config);
```

**Comment by vytautas-pranskunas-** [comment]
It would be good to add it to docs or at least into deprecation message
