### ISSUE TITLE
post_install error on iOS simulator: undefined method `each_child'

### ISSUE THREAD

**Issue by mattdizon** [zino-app/graphql-flutter#809]
**Describe the issue**
When trying to integrate graphql-flutter into a newly created app and running it on iOS Simulator, it will throw an error at the post_install hook:

Error Message: 
`
[!] An error occurred while processing the post-install hook of the
    Podfile.

undefined method `each_child' for #<Dir:0x007fe1822364d0>
Did you mean?  each_slice
    
Error running pod install
Error launching application on iPhone Xʀ.
`

**To Reproduce**
1. Run Flutter create command
2. Add Package to newly created app
3. Try running the app in iOS 

**Expected behavior**
App to launch successfully 

**device / execution context**
iOS Xr 12.4

If you want to troubleshoot or discuss in real time, consider coming to the `support` channel in the [discord](https://discord.gg/tXTtBfC)

**Comment by micimize** [comment]
This looks like an issue with flutter's build system (cocoapods can be very finicky). Try looking at this [stackoverflow].

[stackoverflow]: https://stackoverflow.com/questions/65197799/flutter-pod-install-problem-undefined-method-each-child-for-dir0x00007fa6
