### ISSUE TITLE
Better offline support for Query widget

### ISSUE THREAD

**Issue by jamonkko** [zino-app/graphql-flutter#812]
This is for a use case where you want to show cached data even if network request fails.

Now if you use `cacheAndNetwork` with query widget, the builder is called first with data from cache (or maybe first with `.loading` and then with cached data). This is fine and works, but when network request fails and the builder is then called again with the error, then that is a problem since the last render will be with error and not with the cached data :(

I'm still using v3 so not sure if this has changed since, or if there is some error policy that would ignore the failed network request leaving last render to work with cached data?

Even if you could skip the builder call with network error, I still would like to be able to show in UI indicators if data is being reloaded from network and also if network fetch fails so user would know the data shown is cached. For that to work the query widget builder would need to provide enough metadata (like the .loading) if the network fetch is still loading, or if the network request failed. That would enable to build UI that could show some refreshing/loading indicator even if cached data is shown and also "no network / connection problem" indicator in case the loading fails. 

I guess the QueryResultSource does provide the info that the results are from cache, which indicates that the network request is still ongoing in this case, but it cannot be used to know if network request eventually fails. 

One option might be to add `onError` callback added for the query widget (just like Mutation widget has). In case of `cacheAndNetwork` is in use and `onError` callback is defined, then that callback would be called instead of the builder if request fails. So that the last call for builder would be with cached data or with valid data from network. 
Did not want to start trying to do PR for it before asking if that would be even considered to be approved?

**Comment by jamonkko** [comment]
I guess now (v4) that `refetch` has been fixed to fetch from network if using `cacheFirst` this use case is almost covered.
https://github.com/zino-app/graphql-flutter/issues/541

But what if the refetch fails, will it result in error state and empty/null data instead of having the cached data still available? So even for that scenario the callback would be handy to know that refetch failed but builder would not be called and the cached data would be still the last rendered state

**Comment by micimize** [comment]
Sounds like you're looking for the [`ErrorPolicy.all`](https://pub.dev/documentation/graphql/latest/graphql/ErrorPolicy-class.html), which surfaces data and errors. In v4 there's a fix to show cached data if none was returned.

**Comment by jamonkko** [comment]
Thanks for answer! I upgraded to v4 and its new cache improvements seem to have everything needed  🎉 

And it should be possible to achieve the functionality I want using correct errorpolicy.
