### ISSUE TITLE
PartialDataException (PartialDataException(path: __typename))

### ISSUE THREAD

**Issue by ManuLpz4** [zino-app/graphql-flutter#814]
Hi guys, hope you're doing well :)

Im facing this issue, I don't know why and I think the docs isn't clear for it. I tried a lot of things but I can't solve it.

Please and thank you so much 💙

### My client
The partialDataPolicy is for trying to solve it.
```
GraphQLClient(
  cache: GraphQLCache(partialDataPolicy: PartialDataCachePolicy.accept),
  link: _link(),
);
```

### My query and options
```
const String query = r'''
  query CheckAuthToken($email: String!, $token: String!) {
    checkAuthToken(email: $email, token: $token)
  }

''';
  final QueryOptions options = QueryOptions(
    document: gql(query),
    variables: {
      'email': email,
      'token': token,
    },
  );
```

### The playground's response
```
{
  "data": {
    "checkAuthToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJlbWFpbCI6InRlc3RAYmVsby5jYXNoIiwiYmVsb3RhZyI6InRlc3QiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2MTM1NDY3NTEsImV4cCI6MTYxNjEzODc1MSwiYXVkIjoiaHR0cHM6Ly9iZWxvLmNhc2giLCJpc3MiOiJCZWxvIiwic3ViIjoidGVzdEBiZWxvLmNhc2gifQ.iNYLBxBM8x7epSIpAxS7XhOuf0W4ld9a0qedhi28peo"
  }
}
```

### The exception on Flutter
```
PartialDataException (PartialDataException(path: __typename))
```

**Comment by micimize** [comment]
This is because your server does not comply to the GraphQL spec by responding with a top-level `__typename: Query`: https://github.com/zino-app/graphql-flutter/issues/784#issuecomment-750476097

`gql` adds `__typename` to the entire query to make normalization work automatically – you can create your own custom function for now:
```dart
import 'package:normalize/utils.dart';

class AddNestedTypenameVisitor extends AddTypenameVisitor {
  @override
  visitOperationDefinitionNode(node) => node;
}

DocumentNode gql(String document) => transform(
      parseString(document),
      [AddNestedTypenameVisitor()],
    );
```
We should indeed have a better error messag here

**Comment by ManuLpz4** [comment]
Thank you so much for the response. We are going to work on it so :)

**Comment by micimize** [comment]
@devsideal it may be outdated advice as I am no longer a maintainer but my snippet above is using the `normalize` package, which IIRC is used internally by `graphql_flutter` but not re-exported:

> `import 'package:normalize/utils.dart';`

**Comment by devsideal** [comment]
Thanks @micimize for the reply, I moved on `hasura_connect` package Its working fine.
