### ISSUE TITLE
How to get queries with async/await

### ISSUE THREAD

**Issue by alvinkonda** [zino-app/graphql-flutter#820]
Hello,

Is it possible to get query results through async/await, rather than a builder function, so that we can update the widget state more easily? I'm not seeing this on the package description. 

Thanks,
Alvin

**Comment by micimize** [comment]
If you don't want a stream of results, you can access the client directly with the [client provider](https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql_flutter#graphql-provider) and then use [`client.query`](https://github.com/zino-app/graphql-flutter/tree/beta/packages/graphql_flutter#query)

**Comment by AshishMhalankar** [comment]
Future<dynamic> query() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    print("variables query : " + variables.toString());

    GraphQLClient _client = clientToQuery(MutationHelper.link(
      prefs.getString(IConstanct.token),
    ));
    return await _client
        .query(
      QueryOptions(
        document: gql(documentNode),
        variables: variables,
        fetchPolicy: FetchPolicy.noCache,
      ),
    )
        .then((value) {
      if (value.hasException) {
        print("GQL hasException :" + value.exception.graphqlErrors.toString());
      }
      return value;
    });
  }
