### ISSUE TITLE
HttpLink is UNDEFINED

### ISSUE THREAD

**Issue by TheOutrider** [zino-app/graphql-flutter#822]
I've Upgraded the version for the plugin and found that my **HttpLink** object was throwing error.
Without that I cannot proceed further.
Also, the use of HttpLink is also available in the ReadMe, but cannot be implemented in the code

final HttpLink httpLink = HttpLink(
uri: myUrl, 
defaultHeaders : MyHeader
);

If there is any alternative for that, I would appreciate the help.

**Comment by luiq54** [comment]
Theres a [migration guide](https://github.com/zino-app/graphql-flutter/blob/beta/changelog-v3-v4.md#we-now-use-the-gql_link-system) from v3 to v4 . Read this.

**Comment by AshishMhalankar** [comment]
HttpLink("myUrl, defaultHeaders: {
  "Authorization ":"  xyz"
    })
    
    try with this

**Comment by micimize** [comment]
Please read docs and ask support questions in `#support` of the discord https://discord.gg/tXTtBfC
