### ISSUE TITLE
Google Fonts issues with uuid package

### ISSUE THREAD

**Issue by jlnrrg** [zino-app/graphql-flutter#825]
**Describe the issue**
There is not really a problem, but there are incompatibilities with the `google_fonts: ^2.0.0` library rn.
From what I analyzed this is mainly because of the use of the package `uuid_enhanced` which was not updated since 18.03.2019. Thus I'd like to encourage a change to another package (possibly [uuid](https://pub.dev/packages/uuid), but idk).

**To Reproduce**
1. Start a dummy project
2. add `google_fonts: ^2.0.0` and `graphql ^4.0.1` in your pubspec
3. profit :laughing: 

**Error Message**
```
Because uuid_enhanced 3.0.2 depends on crypto ^2.0.0 and no versions of uuid_enhanced match >3.0.2 <4.0.0, uuid_enhanced ^3.0.2 requires crypto ^2.0.0.
And because google_fonts >=2.0.0-nullsafety.0 depends on crypto ^3.0.0 and graphql >=4.0.0-alpha.4 depends on uuid_enhanced ^3.0.2, google_fonts >=2.0.0-nullsafety.0 is incompatible with graphql >=4.0.0-alpha.4.
So, because test_project depends on both google_fonts ^2.0.0 and graphql ^4.0.1, version solving failed.
```

**Comment by TolgaYld** [comment]
same issue... :/

**Comment by vasilich6107** [comment]
@jlnrrg @TolgaYld 
This is not an issue of this package.
Use `dependency_overrides` to solve the issue
https://stackoverflow.com/questions/23031384/how-to-specify-dependency-overrides-in-pubspec-yaml

**Comment by jlnrrg** [comment]
@vasilich6107 I see where you are coming from, as the other package is outdated and not graphql-flutter.
But then again the decision to incorporate this out-of-date package is not ideal. Of cause I know about dependency_override (thx for the recommendation nevertheless), but it is more ment to be used as a quick fix and just creates unnecessary issues down the line.
So in my experience it is worthwhile either bringing the existing uuid_enhanced up to date (considering the long silence might be harder) or switching packages completely

**Comment by micimize** [comment]
https://pub.dev/packages/graphql/versions/4.1.0-beta.1 is now released with this fixed
