### ISSUE TITLE
Flutter 2 Errors

### ISSUE THREAD

**Issue by ufukhawk** [zino-app/graphql-flutter#832]
**Describe the bug**
I get a graphql_flutter error when switching to Flutter 2. Anyone have any idea about the solution?

**Screenshots**
![Screen Shot 2021-03-06 at 21 25 07](https://user-images.githubusercontent.com/30172226/110233571-d5174b80-7f35-11eb-9970-a9954abeabc6.png)

 - Version 5.0.0-nullsafety.1

**Additional context**
This is happening because it is still using the old version.
https://github.com/.../packages/graphql_flutter/pubspec.yaml

Please update pubs in pubspec.yaml.

hive : ^2.0.0
path_provider : ^2.0.1
connectivity : ^3.0.2
hive : ^2.0.0
pedantic : ^1.11.0 
mockito : ^5.0.0-nullsafety.7

You must update these packages to the **nullsafety** versions.

**Comment by widiu7omo** [comment]
Currently, just remove version number of hive. It's solved my problem.
i.e
```
dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^4.0.1
  hive:
  hive_flutter:
```
I'm also running flutter 2.

**Comment by ufukhawk** [comment]
> Currently, just remove version number of hive. It's solved my problem.
> i.e
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   graphql_flutter: ^4.0.1
>   hive:
>   hive_flutter:
> ```
> 
> I'm also running flutter 2.

I do not use hive. Flutter 2 migration seems to be a huge problem for large projects for now. pubs uses different pubs in itself and different errors occur from each other.
Correcting this seems like an incredibly time-consuming task at the moment.
hopefully, by the end of this month, all pubs will get a compatible version among themselves.

**Comment by micimize** [comment]
Are you sure you're on `5.0.0-nullsafety.1`? It should be using upgraded versions already – see the nullsafety branch: https://github.com/zino-app/graphql-flutter/blob/nullsafety/packages/graphql_flutter/pubspec.yaml#L15
