### ISSUE TITLE
Packages that graphql_flutter use are not updated to new versions

### ISSUE THREAD

**Issue by selmaskopljakovic** [zino-app/graphql-flutter#834]
Hello,

I have an issue with updating projects to Flutter 2, it seems like you haven't updated all packages that are used by graphql_flutter. Etc. provider, web_socket_channel...
It makes a huge problem with a collision with dependency on other packages that I'm using for projects.  

Thank you,
Kind regards,
Selma

**Comment by seyaobey** [comment]
I'm facing the same problem. I cannot upgrade to the latest `firebase_core` and `firebase_messaging`. There is incompatibility with `graphql_flutter: ^4.0.1` because of `path_provider ^1.6.10`

**Comment by alexobviously** [comment]
Also having this problem, clashes with `path_provider`

**Comment by micimize** [comment]
[4.1.0-beta.1](https://pub.dev/packages/graphql_flutter/versions/4.1.0-beta.1) should have solved this. There is also a nullsafe prerelease at [5.0.0-nullsafety.1](https://pub.dev/packages/graphql_flutter/versions/5.0.0-nullsafety.1) – see https://github.com/zino-app/graphql-flutter/issues/797#issuecomment-792147133 for more details.

**Comment by micimize** [comment]
lmk if this is true on `beta` and what packages

**Comment by horgag** [comment]
also facing the same problems as above even with 4.1.0-beta.1

**Comment by micimize** [comment]
What packages are still behind on `4.1.0-beta.2`? `path_provider`? I don't have as much time to contribute here so I'd appreciate it if someone could PR the version bumps

Here are the pubspecs:
https://github.com/zino-app/graphql-flutter/blob/v4.1.0-beta.2/packages/graphql/pubspec.yaml
https://github.com/zino-app/graphql-flutter/blob/v4.1.0-beta.2/packages/graphql-flutter/pubspec.yaml

**Comment by selmaskopljakovic** [comment]
To me, the first pubspec.yaml seems updated.
The second one I'm not allowed to see.

2 weeks ago, the main problems were with upgrading to Flutter2 was with graphql_flutter dependencies since I use in projects many of the same packages.

I see no updates in the last two weeks, the last update was 7th March.
Should I try to upgrade again?

**Comment by horgag** [comment]
I tried updating the packages because a lot of the packages are having conflicts with firebase packages. In the end I just lowered the rev of the firebase packages.

**Comment by naim5am** [comment]
depends on **path_provider: ^1.6.10 dated Jun 2, 2020** which does not pass nullsafety. path_provider is not something easy to work around. 338 packages depend on it.

**Comment by micimize** [comment]
@naim5am I've just published `5.0.0-nullsafety.2` with `path_provider: ^2.0.1`.

Everyone – if you're still having issues please switch to `5.0.0-nullsafety.2` (or `.3` for `graphql`) as I'd like to merge nullsafety into `beta` soon

**Comment by vincenzopalazzo** [comment]
Considered Fixed
