### ISSUE TITLE
[Question] How to handle transactions?

### ISSUE THREAD

**Issue by Fintasys** [zino-app/graphql-flutter#835]
Hey !

I was wondering how to realize transaction with graphql and this package? 
Currently I'm facing the issue that two requests have to be made and if one fails both should be canceled.

Beside that amazing package, thanks for your hard work :bow:

**Comment by micimize** [comment]
idk of any work done in this area on the client. One approach in GraphQL is to have [a single mutation be wrapped by your transaction](https://graphqlme.com/2018/05/13/transactions-mutations-and-graphql/), or [execute multiple top-level mutations in a transaction](https://hasura.io/docs/latest/graphql/core/databases/postgres/mutations/multiple-mutations.html), but these are server-side solutions.

It would be either very awkward or next to impossible to do this on the client, especially without a corresponding server side solution, but you could just wait for the first mutation to return and then do the second. If you were to send both requests, and one failed, you would have a race condition between cancelling the second and it completing.

It is also possible that you're looking for an offline mutation queue (#201)

**Comment by Fintasys** [comment]
@micimize Thanks for your answer. What about the use case of doing one mutation that creates an new entry and the next mutation needs the id of the previous created entry. If first mutation succeeds and second one fails the data is corrupted. Absolute basic use case which I think seems to be impossible to cover with graphql?
