### ISSUE TITLE
[Question] Is there a possibility to set a cache duration?

### ISSUE THREAD

**Issue by Juphex** [zino-app/graphql-flutter#836]
Hey,
I'd like to cache query only for a specific time, e.g. 5 minutes. When I then query again after 5 minutes the query should not be taken from cache but from the network. Is there any convenient way?

This is what I used now, but this is not working.

```
final QueryOptions options = QueryOptions(
      document: gql(query),
      variables: variables,
      pollInterval: Duration(minutes: 5),
    );
```

**Comment by micimize** [comment]
Your issue may be that `pollInterval` only works with `watchQuery` and the `Query` widget. It is a bit of a silly historical artifact that it can be passed to `client.query`.

The immediate question is related to #340 – essentially you could provide a custom `Store`, but that's different from what you're looking for
