### ISSUE TITLE
Requesting help for graphql subscription

### ISSUE THREAD

**Issue by lotus-x** [zino-app/graphql-flutter#845]
I have implemented grpahql subscription server using https://github.com/enisdenjo/graphql-ws.

Here's my flutter code,

 ```dart
Future<void> subscribeAppointmentStart() async {
    final WebSocketLink _webSocketLink = WebSocketLink(
      Common.baseSocketUrl,
      config: SocketClientConfig(
        connect: (url, protocols) => IOWebSocketChannel.connect(
          url,
          protocols: protocols,
          headers: {'access-token': 'token'},
        ),
      ),
    );

    final GraphQLClient _client = GraphQLClient(
      cache: GraphQLCache(),
      link: _webSocketLink,
    );

    final query = gql(r'''
      subscription AppointmentStart {
        onAppointmentStart {
          id
        }
      }
    ''');

    final SubscriptionOptions options = SubscriptionOptions(
      document: query,
    );

    final subscription = _client.subscribe(options);

    subscription.listen((event) {
      print(event);
    }, onError: (error) {
      print(error);
    });
  }
```

When the above code is executed following debug log is written repeatedly,

**Connecting to websocket: ws://192.168.1.2:5000/subscription...
Connected to websocket.
Disconnected from websocket.
Scheduling to connect in 5 seconds...
Connecting to websocket: ws://192.168.1.2:5000/subscription...
Connected to websocket.
Disconnected from websocket.
Scheduling to connect in 5 seconds...**

Also server produces the following error,

**WebSocket protocol error occured. It was most likely caused due to an unsupported subprotocol "graphql-ws" requested by the client. graphql-ws implements exclusively the "graphql-transport-ws" subprotocol, please make sure that the client implements it too.**

I'm running app in a real device, not in an emulator.

**Comment by ridyio** [comment]
@lotus-x Can you share details on how you fixed this issue to make it work with `graphql-ws` server?

**Comment by lotus-x** [comment]
Actually it's about websocket link & message types supported differently by graphql-ws

You can verify those types from here https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

So you should change the `MessageTypes` in websocket link source files https://github.com/gql-dart/gql/blob/master/links/gql_websocket_link/lib/src/messages.dart

So it should be like this at the end

```dart
class MessageTypes {
  MessageTypes._();

  // client connections
  static const String connectionInit = "connection_init";
  static const String connectionTerminate = "connection_terminate";

  // server connections
  static const String connectionAck = "connection_ack";
  static const String connectionError = "connection_error";
  static const String connectionKeepAlive = "ka";

  // client operations
  static const String start = "subscribe";
  static const String stop = "complete";

  // server operations
  static const String data = "next";
  static const String error = "error";
  static const String complete = "complete";

  // default tag for use in identifying issues
  static const String unknown = "unknown";
}
```

**Comment by laurisvan** [comment]
@lotus-x When trying to implement this one, it seems that my connections were terminated because the subscription was started before a `connection_ack`. How did you overcome this problem?

**Comment by lotus-x** [comment]
> @lotus-x When trying to implement this one, it seems that my connections were terminated because the subscription was started before a `connection_ack`. How did you overcome this problem?

I didn't experience this kind of issue when I'm working with websocket link, Did you change some extra properties other than `start` & `data`? Because if the websocket link package trying to initialize the subscription before the acknowledgement, it is another kind of issue, I don't think its related to message names (if you haven't changed any non related properties)

**Comment by laurisvan** [comment]
Yep, it is not about the message names - it just appears that the existing WebSocketClient sends CONNECTED right after establishing the connection and never waits for the acknowledgdement. Our client establishes subscription immediately, and hence dies because the server refuses to accept any subscriptions before ack is sent.

**Comment by lotus-x** [comment]
Hi @laurisvan sorry for the late reply, did you solve your issue?

**Comment by laurisvan** [comment]
@lotus-x No, not really, we took the legacy graphql subscriptions back until we get this one. I checked the current implementation and felt like it needs to be reworked to support this kind of two-stage handshake. I hope to contribute that in near future, but right now we are so busy at work that cannot even think of it. :(
