### ISSUE TITLE
How to get rid on "__typename" being added to every query?

### ISSUE THREAD

**Issue by ristiisa** [zino-app/graphql-flutter#846]
How to configure the library to not automatically add "__typename" to every query?

**Comment by ygotthilf** [comment]
Hello,

The `gql` implementation is :
```
DocumentNode gql(String document) => transform(
      parseString(document),
      [AddTypenameVisitor()],
    );
```

So you can directly use the `parseString` function from the `gql/language.dart` package :

```
import 'package:gql/language.dart';

final hello = parseString('''
  query hello {
    hello {
      __typename
      id
    }
  }
  ''');
```

**Comment by micimize** [comment]
^ above is correct. You can also create a custom one as in https://github.com/zino-app/graphql-flutter/issues/814#issuecomment-782293733
