### ISSUE TITLE
how do i remove __typename for every request response from graphql ?

### ISSUE THREAD

**Issue by dunods** [zino-app/graphql-flutter#852]
how do i remove __typename for every request response from graphql ?

trying to insert addTypename property in graphql but getting confused where to insert ? any thoughts

**Comment by micimize** [comment]
This is all the `gql` helper adds over `gql/language.dart`'s `parseString`, so you can just use that if you want, or look at the source to roll your own

**Comment by AneesRazaRaise** [comment]
@dunods Did you resolve it ?

**Comment by micimize** [comment]
From https://github.com/zino-app/graphql-flutter/issues/846#issuecomment-803939789:

```dart
import 'package:gql/language.dart';

final hello = parseString('''
  query hello {
    hello {
      id
    }
  }
  ''');
```

**Comment by AneesRazaRaise** [comment]
@micimize  Thank you so much..! You literally save my life...

**Comment by harshakuruwita** [comment]
@micimize thanks for correct answer
