### ISSUE TITLE
When starting an app subscription gives last message

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [zino-app/graphql-flutter#859]
Hi,

not sure why but after killing and restarting, or reloading app, i get last received message (before restart) through subscription when subscribing to topic. 
Any ideas why it is happening and how o prevent this? 

```
 _graphQLClient
        .subscribe(SubscriptionOptions(document: notificationtSubscription, variables: {
          'userId': _userStore.id,
        }))
        .takeUntil(_unsubscriber)
        .listen((event) {
      if (event.data != null) {
        _messageHandler(event.data['notification']);
      }
    });
```

so when app is starting ```listen``` is firing with last received message but backend is not sending anything. 
I am sure it is last received emssage because ```data``` property is ```_InternalLinkedHashMap<dynamic, dynamic>``` instead of ```Map<String, dyamic>``` like it suppose to be when sent trough backend

**Comment by micimize** [comment]
Looks like this is because the default policy for subscriptions is `networkOnly`, but we still return an optimistic first result in spite of that:
https://github.com/zino-app/graphql-flutter/blob/a04d55c97d27f80be00e956fe2ab6a511a2b5ba3/packages/graphql/lib/src/core/query_manager.dart#L74-L85

We should  change this – `networkOnly` should only return results from the network and there are too many use cases for subscriptions for the default to be `cacheAndNetwork` imo. Will fix before merging `nullsafety`

**Comment by micimize** [comment]
For now you can the `defaultPolicies` on the client and use `noCache`:
https://github.com/zino-app/graphql-flutter/blob/a04d55c97d27f80be00e956fe2ab6a511a2b5ba3/packages/graphql/lib/src/core/policies.dart#L229-L245

**Comment by micimize** [comment]
`5.0.0-nullsafety.4` has a fix for this

**Comment by AlonsoHernandez99** [comment]
@vytautas-pranskunas did you resolve the bug without migrate to nullsafety?

**Comment by vytautas-pranskunas-** [comment]
@AlonsoHernandez99 hi, i am not migrating right now becaus eamny dependencies still not there. But when i do - I will post here. I have this issue in TODO of my project. Thanks

**Comment by micimize** [comment]
This is a one-line change, so you could fork, make the change, and use `dependency_overrides` as a stopgap if you can't migrate just yet:
https://github.com/zino-app/graphql-flutter/commit/8af2edd31cfaaa193388c5ac1f2fe5bb4676fed4#diff-f7363e83c21742b370cb187be7d60fcbdd781ec92d96cd6726ee5653bdb4b841L74

**Comment by vytautas-pranskunas-** [comment]
So how exactly this one line fixes an issue?
I migrated to null safety and will test it soon but if you can comment that will be easier. Because for now i did this:
```
_graphQLClient
        .subscribe(SubscriptionOptions(document: notificationtSubscription, variables: {
          'userId': _userStore.id,
        }))
        .where((event) =>
            event.data != null &&
            event.data!['notification']['data'] is Map<String,
                dynamic>) 
        .takeUntil(_unsubscriber!)
        .listen((event) {
```

**Comment by vytautas-pranskunas-** [comment]
also it is not related but can someone give me response on this: https://github.com/zino-app/graphql-flutter/issues/863
this is critical part for authentication because I rely on operation name which should be public

**Comment by vytautas-pranskunas-** [comment]
It is fixed
