### ISSUE TITLE
Web is not supported

### ISSUE THREAD

**Issue by SanjiKir** [zino-app/graphql-flutter#865]
**Describe the issue**
Web support doesn't work.

**To Reproduce**
Try to run any request.

**Expected behavior**
`Platform` access is not supported on the web. Yet, obviously internally graphql package somewhere access `Platform`. This lead to an error on `linkException`

**screenshots**
![image](https://user-images.githubusercontent.com/15332993/114464707-67220c00-9be6-11eb-814a-6887a7b9a02a.png)

**Comment by SanjiKir** [comment]
The issues was on my side. Closing the issue.

**Comment by cacianokroth** [comment]
Hello @SanjiKir,
I have the same problem, how did you solve it, which configuration did you have to change in order for it to work normally?
Regards!
