### ISSUE TITLE
is there no way to just query data in graphql-flutter (like  for log in authentication ) without  building widget.  current functions are to build widgets after query it mixes backend and frontend .

### ISSUE THREAD

**Issue by nav1101** [zino-app/graphql-flutter#87]
like query separately pass data and build widget 

Found this 
Client client = GraphqlProvider.of(context).value;
var data = await client.query(query: //YourQuery String here);
But not in  Docs ! 

IT IS WORKING FINE

**Comment by HofmannZ** [comment]
We're woking on splitting it up ;)

**Comment by Cassianokunsch** [comment]
Cool, but when do you initialize this variable?

**Comment by Cassianokunsch** [comment]
> like query separately pass data and build widget
> 
> Found this
> Client client = GraphqlProvider.of(context).value;
> var data = await client.query(query: //YourQuery String here);
> But not in Docs !
> 
> IT IS WORKING FINE

Cool, but when do you initialize this variable?

**Comment by amirkarimistr** [comment]
but i get this error `Failed assertion: line 58 pos 12: 'provider != null': is not true.`
when i try to add the below lines of code in my repository.

> Client client = GraphqlProvider.of(context).value;
> var data = await client.query(query: //YourQuery String here);

**Comment by vincenzopalazzo** [comment]
@amirkarimistr maybe because this issue is more than one year old?

If you have problem I suggest to you to open a detailed issue, thanks

**Comment by kevin4dhd** [comment]
any solution?
