### ISSUE TITLE
`writeNormalized` to cache doesn't update the `ObservableQuery`? 

### ISSUE THREAD

**Issue by D4G4** [zino-app/graphql-flutter#886]
So I am watching a query using `client.watchQuery(...).stream.listen(...)`

and later I run a mutation where I bascially add data to the list.

Since the cache isn't smart enough to update itself on its own, I am manually updating it in `update` method inside `MutationOptions` as follows:

```
MutationOptions options = MutationOptions(
    document: gql(GAllQueries.allQueries()),
    variables: variables ?? {},
    operationName: operationName,
    cacheRereadPolicy: CacheRereadPolicy.mergeOptimistic,
    fetchPolicy: FetchPolicy.cacheAndNetwork,
    update: (
      cache,
      QueryResult result,
    ) {
      if (result.hasException) {
        debugPrint(result.exception);
      } else {
        var post = (result.data[result.data.keys.last]
            as Map<String, dynamic>)['post'];

        var dataId = "${post["__typename"]}:${post["id"]}";  //Creating the exact id as cache

        (cache as GraphQLCache).writeNormalized(dataId, post); //WRITING THE DATA

        debugPrint(cache.store) //I can see the updated value in the cache!!  (yay?)

        cache.shouldBroadcast(claimExecution: true); //not really rebroadcasting :(
      }
    },
 );
```

Now, my stream, of `watchQuery`, don't really get any update! 

How do I notify my stream? 

Or is there any other way to do so?

++

Digging deep into the cache, I've realized even though I've added data into my cache, my query's result inside the cache isn't referring to that data. I'm pretty sure I shouldn't manually update it, right? 

`graphql_flutter: ^4.0.1`

Btw, [this](https://github.com/zino-app/graphql-flutter/issues/57) is outdated!

**Comment by micimize** [comment]
it isn't expected that `writeNormalized` be called directly, and it doesn't have rebroadcast awareness. There is a `broadcastRequested` flag on the cache that `writeQuery` and `writeFragment` will set – it is protected but you might be able to reference it in an extension method idk.
