### ISSUE TITLE
SanitizeVariables - Unhandled Client-Side Exception: Null check operator used on a null - ^5.0.0-nullsafety.2

### ISSUE THREAD

**Issue by nobbyharding** [zino-app/graphql-flutter#890]
It seams there is an Unhandles errored deep in the package. I have made a custom link as was all working in 4

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/1613022/118193469-a63eb980-b43f-11eb-8b71-d954b0362bb2.png">

**Comment by nobbyharding** [comment]
Could be my bad but for reference.
// TODO use more efficient traversal method in SanitizeVariables variableSanitizer(
update variables passed null from Query

**Comment by micimize** [comment]
you're using a custom sanitizeVariables? What does it look like? It can't return `null` at the top level because the api requires at least an empty map

**Comment by nobbyharding** [comment]
hey there:

options: QueryOptions(
          document: gql(query),
           variables: params
         ),

params was NULL, migration from 4 - setting params = Map<String, dynamic>();  all working. 

Happy to close it but just thought in the codebase, null variables should be set to  params = Map<String, dynamic>(); I would say to prevent the evenry client having to do such?

**Comment by micimize** [comment]
ah – yeah this should be a non-issue post-nullsafety. `const {}` is the default but that gets overridden if you pass null explicitly
