### ISSUE TITLE
Upgrade rxdart dependency to support 0.27.0

### ISSUE THREAD

**Issue by ryanheise** [zino-app/graphql-flutter#899]
**Is your feature request related to a problem? Please describe.**

Apps using 0.27.0 of rxdart either directly or transitively may now give compile errors.

**Describe the solution you'd like**

Upgrade the rxdart dependency to 0.27.0, or use a version range spec if compatible.

**Describe alternatives you've considered**

A dependency override.

**Additional context**

There will be a pana penalty soon:

> The constraint `^0.26.0` on rxdart does not support the stable version `0.27.0`, that was published 13 days ago.
> 
> When rxdart is 30 days old, this package will no longer be awarded points in this category.

**Comment by ryanheise** [comment]
That 30 day grace period has expired, and graphql is now penalised by pana on pub.dev.

**Comment by mwawrusch** [comment]
Please upgrade this - we are using a module (getstream.io) that depends on this.

**Comment by vincenzopalazzo** [comment]
Fixed with https://github.com/zino-app/graphql-flutter/pull/978

Thanks
