### ISSUE TITLE
Connectivity package has to be replaced by connectivity_plus package

### ISSUE THREAD

**Issue by samtarbury** [zino-app/graphql-flutter#910]
**Describe the issue**
The dependency with connectivity package in last versions of graphql_flutter prevents from building app.
It fails with this error **Execution failed for task ':connectivity:compileDebugJavaWithJavac'.**\
Please replace it with **connectivity_plus** package instead which works like a charm. The other one is no more recommended!

**device / execution context**
Android

**Comment by micimize** [comment]
This is already done on beta https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql_flutter/pubspec.yaml #904 – maybe there is an issue with CI. Will look later

**Comment by samtarbury** [comment]
Ok thanks could you release or pre-release this fix asap since it's a
blocking compilation issue with last Gradle/Java versions.

Thanks,

Sam

Le jeudi 3 juin 2021, Michael Joseph Rosenthal ***@***.***> a
écrit :
