### ISSUE TITLE
Upgrade RxDart to latest

### ISSUE THREAD

**Issue by Tejaswgupta** [zino-app/graphql-flutter#943]
**Describe the issue**
RxDart dependency is ```^0.26.0 ``` which is oudated and is conflicting with some other packages (`stream_chat_flutter`) which depend on the latest RxDart(`^0.27.1`).

**Solution**
Upgrade to the latest RxDart to keep in sync with other packages.

**Comment by eugene-kalaganov** [comment]
same with 
`  connectivity_plus: ^2.0.2 # https://pub.dev/packages/connectivity_plus`
looks like this graphql repo is abandoned
