### ISSUE TITLE
SocketException (SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.1.3, port = 41148)

### ISSUE THREAD

**Issue by freewebwithme** [zino-app/graphql-flutter#945]
**Describe the issue**
SocketException (SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.1.3, port = 41148)

**To Reproduce**

I have no idea how to reproduce this issue

**Expected behavior**
graphql should send a request to the server

**device / execution context**

This issue doesn't happen when I use with simulator, but it pops up when I use LG G7(I haven't test other device)

### Other useful/optional fields
SocketException (SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.1.3, port = 41148)

**Comment by Dekhnar** [comment]
same issue

**Comment by abdelrahmanelmarakby** [comment]
Reasons why this happen :
1 - maybe your connection is dead make sure you have a good stable internet connection

2 - the server you are trying to connect is down or un reachable

**Comment by freewebwithme** [comment]
This problem is not related to graphql_flutter package.
My computer has a firewall that deny all incoming connection.
