### ISSUE TITLE
Expected an argument name when passing parameters

### ISSUE THREAD

**Issue by abdelrahmanelmarakby** [zino-app/graphql-flutter#948]
**Describe the issue**
A clear and concise description of what the problem is.

**To Reproduce**

**Expected behavior**

**device / execution context**
Are you on iOS, android, web, in a simulator, running from the terminal etc? This is especially important for `localhost` connection issues.

### Other useful/optional fields

Please fill or delete these sections if you don't fill them in

<details>
  <summary>Stacktrace:</summary>

```dart
{my stacktrace here}
```

</details>

**screenshots**

**additional context**
* What backend are you trying to use?
* If you have a network issue, does your operation work with [GraphiQL](https://www.electronjs.org/apps/graphiql)?

**additional notes**
Did you struggle to understand the docs or examples, or dislike the current api? 

If you want to troubleshoot or discuss in real time, consider coming to the `support` channel in the [discord](https://discord.gg/tXTtBfC)

**Comment by vasilich6107** [comment]
Someone, close this issue, there is no relevant info here
