### ISSUE TITLE
Mutation returning __typname error

### ISSUE THREAD

**Issue by CamronLDNF** [zino-app/graphql-flutter#953]
Hi folks. We're suddenly getting a mutation error and cannot figure out what is causing it. Any ideas? 

In the Flutter app, we're using `graphql_flutter: ^4.0.1`.  
On the server side, we're using the [gqlgen](https://gqlgen.com/getting-started/) library.

### **My client**
```dart
  final policies = Policies(
    fetch: FetchPolicy.noCache,
  );

  GraphQLClient clientForAPIRequests = GraphQLClient(
    link: link,
    cache: GraphQLCache(),
    defaultPolicies: DefaultPolicies(
      query: policies,
      mutate: policies,
    )
  );
```

### **My mutation and options**
```dart
  static String createUser = r"""
    mutation(
      $userId: String
      $firstName: String!
      $lastName: String!
      $email: String!
      $deviceToken: String!
      $signupMethod: String!
      $dob: DateTime!
      $gender: String!
      $countryCode: String!
      $notifications: UserNotificationsInput
    ) {
      createUser(
        input: {
          userId: $userId
          firstName: $firstName
          lastName: $lastName
          email: $email
          deviceToken: $deviceToken
          signupMethod: $signupMethod
          dob: $dob
          gender: $gender
          countryCode: $countryCode
          notifications: $notifications
        }
      ) {
          email
      }
    }   
    """;
```
NOTE: `UserNotificationsInput` is a set of key-value pairs.

### **The error returned**
```
OperationException(linkException: ServerException(originalException: null,
parsedResponse: Response(data: null,
errors: [
  GraphQLError(message: unknownfield,
  locations: null,
  path: [
    variable,
    notifications,
    __typename
  ],
  extensions: {
    code: GRAPHQL_VALIDATION_FAILED
  })
],
context: Context({
  ResponseExtensions: Instanceof'ResponseExtensions'
}))),
graphqlErrors: [
  
])
```

I understand that it's a server validation error but it's as a result of the client automatically adding the `__typename` field to the mutation request, hence the issue raised here. Any ideas??

**Comment by vasilich6107** [comment]
Look at your error
```
GraphQLError(message: unknownfield,
  locations: null,
  path: [
    variable,
    notifications,
    __typename
  ],
```

It looks obvious that your server does not like `__typename` field in `UserNotificationsInput`

It literally says you "Hey, developer I do not like `__typename` in `variables`=>`notifications` object.

It seems that this relates you your relationships with server.

To debug further - try to execute the same request with Insomnia or Postman to ensure that this error is not related to `graphql` lib

**Comment by dishankjj** [comment]
Is the issue fixed? Any update on the issue?

**Comment by vincenzopalazzo** [comment]
>Is the issue fixed? Any update on the issue?

There are new maintainers now for version 5.x, do you discover the same error? if yes could you please open a new issue and also make a minimal example that I can reproduce?
