### ISSUE TITLE
PLEASE SHIFT TO NULL SAFETY :(

### ISSUE THREAD

**Issue by nakshatrasinghh** [zino-app/graphql-flutter#969]
It doesn't work with flutter 2.5

![Screenshot 2021-10-03 at 9 03 30 PM](https://user-images.githubusercontent.com/53419293/135761012-6d5cdab5-a703-4743-baa0-0b608e5e81e3.png)

Tried older versions as well :(
![Screenshot 2021-10-03 at 9 04 21 PM](https://user-images.githubusercontent.com/53419293/135761053-cdd290ca-9188-4af6-958b-732e048fd340.png)

**Comment by HofmannZ** [comment]
@nakshatrasinghh - try `^5.0.0`.

**Comment by nakshatrasinghh** [comment]
> @nakshatrasinghh - try `^5.0.0`.

I did try it out, I have attached screenshots as well, please have a look
