### ISSUE TITLE
Connection timeout but reconnecting fails

### ISSUE THREAD

**Issue by shaon2016** [zino-app/graphql-flutter#987]
**Describe the issue**
Sometimes it fails to connect to the remote server. After connection time out, it tries automatically to connect to server again. But every time it fails. Connection time out and reconnecting is not working perfectly. 

![Screenshot 2021-11-28 141525](https://user-images.githubusercontent.com/19825354/143734923-f703dde8-df85-4416-8345-fab98df25778.png)

See the above screenshot to understand. It fails to reconnect. 

Sometimes some API doesn't get any response. just connection timeout keep happening.

**Comment by vincenzopalazzo** [comment]
Hi @shaon2016,

can you reproduce this error with a simple curl command? or if you use curl it return the result that you will espect?

**Comment by shaon2016** [comment]
@vincenzopalazzo hi
I have no idea about curl command. We are facing this issue on our daily development. Even in our release apk the issue remain same.

**Comment by vincenzopalazzo** [comment]
Hi @shaon2016,

>We are using this version
^5.0.0

Can you upgrade to the latest beta version? https://pub.dev/packages/graphql_flutter/versions/5.0.1-beta.1

>I have no idea about curl command. We are facing this issue on our daily development. Even in our release apk the issue remain same.

The timeout usually it is not depending on the client that you are using, but on how much time the server takes to answer.
If you try to reproduce your query request with curl and add feedback here you can help to debug this issue.

The `errno` it is thrown from the system and this is a good description of it https://stackoverflow.com/a/69241858/10854225

**Comment by shaon2016** [comment]
We have tried using dio package also. issue remain same. so we come to an understand that it could be a server issue. I am closing this thread.
