### ISSUE TITLE
upgraded to alpha-1.0.0

### ISSUE THREAD

**Issue by kunaldodiya** [zino-app/graphql-flutter#99]
hello,

in previous version I was able to set apiToken 

```
final Client client = GraphqlProvider.of(context).value;
final SharedPreferences preferences = await SharedPreferences.getInstance();
const token = preferences.getString('authToken');
client.apiToken = token;
```
from authentication.dart page 

but now client.link says, its final, can't change it.
how can i set headers ??? 

Also main.dart file does not support async function so that i can't use something like:-

```
final SharedPreferences preferences = await SharedPreferences.getInstance();
const token = preferences.getString('authToken');

HttpLink link = HttpLink(
      uri: 'http://192.168.2.200:4000',
      headers: <String, String>{
        'Authorization': token,
      },
    );
```

**Comment by HofmannZ** [comment]
You can override the headers trough the context operation context, allowing dynamically calculated headers. We added an [example of it](https://github.com/zino-app/graphql-flutter/blob/86c8b7c28c8639906f99dbd3e1c39fbb1127c2e3/example/lib/main.dart#L65) in the example project, but I'll add it to the migration guide as well.

> The code snippet comes form the example project:
```dart
Query(
  options: QueryOptions(
    document: queries.readRepositories,
    pollInterval: 4,
    // you can optionally override some http options through the contexts
    context: <String, dynamic>{
      'headers': <String, String>{
        'Authorization': 'Bearer <YOUR_PERSONAL_ACCESS_TOKEN>',
      },
    },
  ),
  builder: (QueryResult result) {
    ...
  },
);
```

**Comment by kunaldodiya** [comment]
That is cool.. But now i have to specify headers in every request manually, can u make it one time process???

**Comment by filippofilip95** [comment]
@kunaldodiya Were you able to make it one time process ? I'am solving same issue as you. Thank you for your Help ! 👍

**Comment by filippofilip95** [comment]
@nayanbhana in my project i use redux. So i usually wrap Query with StoreConnector and then provide user token.
`
  Widget _buildQuery() {
    return StoreConnector<AppState, String>(
      converter: (store) => store.state.user.token,
      builder: (context, token) {
        return Query(
          options: QueryOptions(
            document: lookForMusicQuery,
            variables: {'keyword': _keyword},
            context: {
              'headers': {'Authorization': 'Bearer $token'}
            },
          ),
          builder: (QueryResult result) {
            return QueryManager(
              result: result,
              builder: (data) {
                return _buildListView(data['lookForMusic']);
              },
            );
          },
        );
      },
    );
  }
`
This approach works but i will refactor it to something like AuthorizedQuery widget.
There will be almost same logic but then i can use it anywhere without wrapping it by StoreConnector.

**Comment by liu-dongyu** [comment]
Why close ?  Is there any solution to make it one time process ?

**Comment by HofmannZ** [comment]
@liu-dongyu You can use an `AuthLink`:

```dart
final AuthLink authLink = AuthLink(
  getToken: () async => 'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
);
```

The function you provide to the `AuthLink` can be a future and can call any of you own auth logic.
